use super::super::model::*;

const fn node(
    id: SourceNodeId,
    owner: SourceOwnerId,
    symbol: &'static str,
    role: NodeRole,
    epoch: Epoch,
    boundary: Boundary,
) -> SourceNode {
    SourceNode {
        id,
        owner,
        symbol,
        role,
        ops: MAP_OPS,
        epoch,
        boundary,
        state_witness: None,
    }
}

pub(in super::super) const NODES: &[SourceNode] = &[
    node(
        SourceNodeId::AbiMapSlot,
        SourceOwnerId::SqliteVfsAbiTable,
        "xShmMap: Some(io_shm::map)",
        NodeRole::Entry,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiMapEntry,
        SourceOwnerId::AbiIoShm,
        "unsafe extern \"C\" fn map",
        NodeRole::Entry,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiMapNullOutput,
        SourceOwnerId::AbiBoundary,
        "unsafe fn write_pointer_null",
        NodeRole::AbiProjection,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiMapValidation,
        SourceOwnerId::AbiIoShm,
        "fn sqlite_bool",
        NodeRole::ManagedValidation,
        Epoch::AbiInput,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::FileStateMap,
        SourceOwnerId::AbiFileState,
        "pub(super) fn shm_map",
        NodeRole::Adapter,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::FixtureMapFault,
        SourceOwnerId::FixtureFaultFile,
        "fn shm_map",
        NodeRole::FaultWrapper,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RouteMapPreparation,
        SourceOwnerId::FixtureRouteFile,
        "fn prepare_first_main_shm_map",
        NodeRole::RoutePromotion,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RoutePlanClaim,
        SourceOwnerId::FixtureFaultPlan,
        "fn claim",
        NodeRole::RoutePromotion,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RoutePromotionDelegate,
        SourceOwnerId::RegistryTestBridge,
        "fn prepare_wal_main_shm_test_fault_script",
        NodeRole::RoutePromotion,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RouteNoPlanPromotionDelegate,
        SourceOwnerId::RegistryTestBridge,
        "fn promote_main_to_wal_for_shm",
        NodeRole::RoutePromotion,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionCallbackBegin,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_to_wal",
        NodeRole::CallbackOwner,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionProcessBegin,
        SourceOwnerId::RegistryProcessOwner,
        "fn begin_callback",
        NodeRole::CallbackOwner,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionOwnerBegin,
        SourceOwnerId::RegistryOwner,
        "fn begin_callback",
        NodeRole::CallbackOwner,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionStateBegin,
        SourceOwnerId::RegistryState,
        "fn begin_callback",
        NodeRole::CallbackOwner,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionCallbackComplete,
        SourceOwnerId::RegistryPromotion,
        "callback.complete()",
        NodeRole::CallbackOwner,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionProcessComplete,
        SourceOwnerId::RegistryProcessOwner,
        "fn complete",
        NodeRole::CallbackOwner,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionOwnerFinish,
        SourceOwnerId::RegistryOwner,
        "fn finish_callback",
        NodeRole::CallbackOwner,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionStateFinish,
        SourceOwnerId::RegistryState,
        "fn finish_callback",
        NodeRole::CallbackOwner,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryPromotionAdapter,
        SourceOwnerId::RegistryAbiFile,
        "fn promote_main_to_wal",
        NodeRole::CustodyAdapter,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryPromotionOwner,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_custody",
        NodeRole::CustodyAdapter,
        Epoch::MapRoutePreparation,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionClaimShmProcess,
        SourceOwnerId::RegistryProcessLifecycle,
        "fn claim_shm",
        NodeRole::CustodyAdapter,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionClaimShmApplyRoute,
        SourceOwnerId::RegistryProcessOwner,
        "fn apply_route<T>",
        NodeRole::CustodyAdapter,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionClaimShmOwner,
        SourceOwnerId::RegistryOwnerLifecycle,
        "fn claim_shm",
        NodeRole::CustodyAdapter,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::PromotionClaimShmState,
        SourceOwnerId::RegistryState,
        "pub(super) fn claim_shm",
        NodeRole::CustodyAdapter,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RuntimeBindMain,
        SourceOwnerId::ManagedCoordinator,
        "fn bind_main_file",
        NodeRole::Initialization,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::CoordinatorAttach,
        SourceOwnerId::ManagedCoordinator,
        "fn attach",
        NodeRole::Initialization,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryAbiFaultInstall,
        SourceOwnerId::RegistryAbiFile,
        "fn install_exact_wal_main_shm_test_fault_script",
        NodeRole::FaultController,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryFaultInstall,
        SourceOwnerId::RegistryFileFaults,
        "fn install_exact_wal_main_shm_test_fault_script",
        NodeRole::FaultController,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultInstall,
        SourceOwnerId::ManagedFaultApi,
        "fn install_shm_test_fault_script",
        NodeRole::FaultController,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultControllerInstall,
        SourceOwnerId::ManagedFaultController,
        "pub(super) fn install",
        NodeRole::FaultController,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RoutePlanRecord,
        SourceOwnerId::FixtureFaultPlan,
        "fn record_installed",
        NodeRole::RoutePromotion,
        Epoch::FirstMapBootstrap,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RouteMapDelegate,
        SourceOwnerId::FixtureRouteFile,
        "fn shm_map",
        NodeRole::Adapter,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::TestBridgeMap,
        SourceOwnerId::RegistryTestBridge,
        "fn shm_map",
        NodeRole::Adapter,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryMapAdapter,
        SourceOwnerId::RegistryAbiFile,
        "fn shm_map",
        NodeRole::Adapter,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryMapOperation,
        SourceOwnerId::RegistryOperations,
        "fn shm_map",
        NodeRole::ManagedOperation,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedConnectionMap,
        SourceOwnerId::ManagedMapping,
        "fn map",
        NodeRole::ManagedOperation,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedMapCoordinator,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        NodeRole::ManagedOperation,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedMapValidation,
        SourceOwnerId::ManagedMapping,
        "validate_region_size",
        NodeRole::ManagedValidation,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedShmPlatformModuleSelect,
        SourceOwnerId::ManagedShmRoot,
        "#[path = \"windows_sqlite_shm.rs\"]",
        NodeRole::PlatformSeam,
        Epoch::PlatformBinding,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::WindowsAllocationGranularity,
        SourceOwnerId::WindowsShm,
        "fn allocation_granularity",
        NodeRole::PlatformSeam,
        Epoch::PlatformBinding,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedFileSizeGrow,
        SourceOwnerId::ManagedNamespaceIo,
        "fn size",
        NodeRole::ManagedOperation,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedRegionLoop,
        SourceOwnerId::ManagedMapping,
        "while state",
        NodeRole::ManagedOperation,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::WindowsCreateMapping,
        SourceOwnerId::WindowsShm,
        "fn create_mapping",
        NodeRole::PlatformSeam,
        Epoch::PlatformBinding,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::WindowsMapView,
        SourceOwnerId::WindowsShm,
        "fn map_view",
        NodeRole::PlatformSeam,
        Epoch::PlatformBinding,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedMappingCleanup,
        SourceOwnerId::WindowsShm,
        "fn close_explicit",
        NodeRole::CleanupOwner,
        Epoch::WalMainSteady,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedNativeMappingCleanup,
        SourceOwnerId::WindowsShm,
        "fn close_explicit",
        NodeRole::CleanupOwner,
        Epoch::WalMainSteady,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedMappingCustodyRetain,
        SourceOwnerId::ManagedFaultMapping,
        "fn retain_test_mapping_custody",
        NodeRole::CleanupOwner,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedInlineRegionCustody,
        SourceOwnerId::ManagedMapping,
        "regions.push(ManagedSqliteShmRegionMapping",
        NodeRole::ManagedOperation,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedRegionSelect,
        SourceOwnerId::ManagedMapping,
        "REGION_CUSTODY_MISSING",
        NodeRole::ManagedOperation,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    SourceNode {
        id: SourceNodeId::WalMainColdNodeWitness,
        owner: SourceOwnerId::ManagedMapping,
        symbol: "validate_region_size",
        role: NodeRole::StateWitness,
        ops: INITIALIZING_OPS,
        epoch: Epoch::ColdNodeAcquirePrefix,
        boundary: Boundary::PendingExpansion,
        state_witness: Some(StateWitness::WalMainPromotedNodeAbsentAfterEarlyMapReturn),
    },
    node(
        SourceNodeId::RegistryMapProjection,
        SourceOwnerId::RegistryAbiFile,
        "ManagedSqliteShmMapOutcome::Mapped(pointer)",
        NodeRole::AbiProjection,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiMapProjection,
        SourceOwnerId::AbiIoShm,
        "output.write(pointer.as_ptr())",
        NodeRole::AbiProjection,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiMapFallbackProjection,
        SourceOwnerId::AbiFileState,
        "Ok(Err(_)) | Err(_) =>",
        NodeRole::AbiProjection,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiMapUnavailableCode,
        SourceOwnerId::AbiResultCodes,
        "SHM_MAP_UNAVAILABLE",
        NodeRole::AbiProjection,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
];
