CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_runtime_compatibility_verification_challenges (
  challenge_id TEXT PRIMARY KEY NOT NULL,
  challenge_schema TEXT NOT NULL CHECK(challenge_schema='compute_federation.external_pool_adapter_runtime_compatibility_verification_challenge.v1'),
  challenge_digest TEXT NOT NULL UNIQUE CHECK(length(challenge_digest)=64 AND challenge_digest NOT GLOB '*[^0-9a-f]*'),
  challenge_material_digest TEXT NOT NULL CHECK(length(challenge_material_digest)=64 AND challenge_material_digest NOT GLOB '*[^0-9a-f]*'),
  challenge_json TEXT NOT NULL CHECK(json_valid(challenge_json) AND json_type(challenge_json)='object' AND length(CAST(challenge_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  challenge_nonce_digest TEXT NOT NULL UNIQUE CHECK(length(challenge_nonce_digest)=64 AND challenge_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  issued_at TEXT NOT NULL CHECK(issued_at GLOB '????-??-??T??:??:??.?????????Z' AND length(issued_at)=30 AND julianday(issued_at) IS NOT NULL),
  expires_at TEXT NOT NULL CHECK(expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(expires_at)=30 AND julianday(expires_at) IS NOT NULL),
  registry_release_json TEXT NOT NULL CHECK(json_valid(registry_release_json) AND json_type(registry_release_json)='object' AND length(CAST(registry_release_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  registry_release_id TEXT NOT NULL,
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_material_digest TEXT NOT NULL CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  adapter_id TEXT NOT NULL,
  release_version TEXT NOT NULL,
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_kind TEXT NOT NULL CHECK(runtime_kind='server_sidecar_v1'),
  entrypoint_path TEXT NOT NULL,
  entrypoint_sha256 TEXT NOT NULL CHECK(length(entrypoint_sha256)=64 AND entrypoint_sha256 NOT GLOB '*[^0-9a-f]*'),
  entrypoint_size_bytes INTEGER NOT NULL CHECK(typeof(entrypoint_size_bytes)='integer' AND entrypoint_size_bytes>0),
  profile_id TEXT NOT NULL CHECK(profile_id='external_pool_adapter_linux_runtime_compatibility_v2'),
  profile_revision INTEGER NOT NULL CHECK(profile_revision=2),
  profile_digest TEXT NOT NULL CHECK(length(profile_digest)=64 AND profile_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_digest TEXT NOT NULL CHECK(length(supervisor_session_policy_digest)=64 AND supervisor_session_policy_digest NOT GLOB '*[^0-9a-f]*'),
  source_capsule_policy_digest TEXT NOT NULL CHECK(length(source_capsule_policy_digest)=64 AND source_capsule_policy_digest NOT GLOB '*[^0-9a-f]*'),
  runner_policy_digest TEXT NOT NULL CHECK(length(runner_policy_digest)=64 AND runner_policy_digest NOT GLOB '*[^0-9a-f]*'),
  fixture_catalog_digest TEXT NOT NULL CHECK(length(fixture_catalog_digest)=64 AND fixture_catalog_digest NOT GLOB '*[^0-9a-f]*'),
  fixture_resources_json TEXT NOT NULL CHECK(json_valid(fixture_resources_json) AND json_type(fixture_resources_json)='array' AND json_array_length(fixture_resources_json)=4),
  sandbox_verifier_key_record_id TEXT NOT NULL,
  sandbox_verifier_key_record_digest TEXT NOT NULL CHECK(length(sandbox_verifier_key_record_digest)=64 AND sandbox_verifier_key_record_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_key_id TEXT NOT NULL CHECK(length(sandbox_verifier_key_id)=64 AND sandbox_verifier_key_id NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_operator TEXT NOT NULL,
  sandbox_verifier_product TEXT NOT NULL,
  signature_algorithm TEXT NOT NULL CHECK(signature_algorithm='rsa-pkcs1v15-sha256'),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>0),
  predecessor_verification_receipt_id TEXT,
  predecessor_verification_receipt_digest TEXT,
  created_by_admin_user_id TEXT NOT NULL,
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_runtime_compatibility_challenge'),
  idempotency_scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  recorded_at TEXT NOT NULL CHECK(recorded_at=issued_at),
  CHECK(expires_at=(strftime('%Y-%m-%dT%H:%M:%S',issued_at,'+5 minutes')||substr(issued_at,20))),
  CHECK((predecessor_verification_receipt_id IS NULL)=(predecessor_verification_receipt_digest IS NULL)),
  CHECK((sequence=1)=(predecessor_verification_receipt_id IS NULL)),
  UNIQUE(challenge_id,challenge_digest),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(sandbox_verifier_key_record_id,sandbox_verifier_key_record_digest,sandbox_verifier_key_id) REFERENCES compute_external_pool_adapter_sandbox_verifier_keys(key_record_id,key_record_digest,key_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_verification_receipt_id,predecessor_verification_receipt_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_receipts(verification_receipt_id,verification_receipt_digest) ON DELETE RESTRICT
);
