CREATE INDEX IF NOT EXISTS idx_v268_challenge_release_lineage ON compute_external_pool_adapter_runtime_compatibility_verification_challenges(registry_release_id,sequence);
CREATE INDEX IF NOT EXISTS idx_v268_observation_release ON compute_external_pool_adapter_runtime_compatibility_verification_run_observations(registry_release_id,run_completed_at);
CREATE INDEX IF NOT EXISTS idx_v268_verification_release_head ON compute_external_pool_adapter_runtime_compatibility_verification_receipts(registry_release_id,sequence DESC);
CREATE INDEX IF NOT EXISTS idx_v268_verification_expiry ON compute_external_pool_adapter_runtime_compatibility_verification_receipts(expires_at);
