CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_runtime_compatibility_verification_revocations (
  revocation_receipt_id TEXT PRIMARY KEY NOT NULL,
  revocation_receipt_schema TEXT NOT NULL CHECK(revocation_receipt_schema='compute_federation.external_pool_adapter_runtime_compatibility_revocation_receipt.v1'),
  revocation_receipt_digest TEXT NOT NULL UNIQUE,
  revocation_material_digest TEXT NOT NULL,
  revocation_receipt_json TEXT NOT NULL CHECK(json_valid(revocation_receipt_json) AND json_type(revocation_receipt_json)='object' AND length(CAST(revocation_receipt_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  verification_receipt_id TEXT NOT NULL UNIQUE,
  verification_receipt_digest TEXT NOT NULL,
  registry_release_id TEXT NOT NULL,
  registry_release_digest TEXT NOT NULL,
  revoked_by_admin_user_id TEXT NOT NULL,
  reason TEXT NOT NULL CHECK(length(reason) BETWEEN 12 AND 500 AND reason=trim(reason)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_runtime_compatibility_revocation'),
  idempotency_scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  revoked_at TEXT NOT NULL CHECK(length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=revoked_at),
  revocation_status TEXT NOT NULL CHECK(revocation_status='signed_verifier_assertion_revoked_historical_only'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"process_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"session_ready":false,"upstream_probe_ready":false}'),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(verification_receipt_id,verification_receipt_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_receipts(verification_receipt_id,verification_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT
);
