CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_runtime_compatibility_verification_run_observations (
  run_observation_id TEXT PRIMARY KEY NOT NULL,
  run_observation_schema TEXT NOT NULL CHECK(run_observation_schema='compute_federation.external_pool_adapter_runtime_compatibility_server_run_observation.v1'),
  run_observation_digest TEXT NOT NULL UNIQUE CHECK(length(run_observation_digest)=64 AND run_observation_digest NOT GLOB '*[^0-9a-f]*'),
  run_observation_material_digest TEXT NOT NULL CHECK(length(run_observation_material_digest)=64 AND run_observation_material_digest NOT GLOB '*[^0-9a-f]*'),
  run_observation_json TEXT NOT NULL CHECK(json_valid(run_observation_json) AND json_type(run_observation_json)='object' AND length(CAST(run_observation_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  runner_execution_id TEXT NOT NULL UNIQUE,
  challenge_id TEXT NOT NULL UNIQUE,
  challenge_digest TEXT NOT NULL,
  challenge_nonce_digest TEXT NOT NULL,
  registry_release_id TEXT NOT NULL,
  registry_release_digest TEXT NOT NULL,
  registry_release_material_digest TEXT NOT NULL,
  installation_content_digest TEXT NOT NULL,
  profile_id TEXT NOT NULL CHECK(profile_id='external_pool_adapter_linux_runtime_compatibility_v2'),
  profile_revision INTEGER NOT NULL CHECK(profile_revision=2),
  profile_digest TEXT NOT NULL,
  runner_policy_digest TEXT NOT NULL,
  fixture_catalog_digest TEXT NOT NULL,
  source_capsule_sha256 TEXT NOT NULL,
  source_capsule_size_bytes INTEGER NOT NULL CHECK(source_capsule_size_bytes>0),
  source_capsule_policy_digest TEXT NOT NULL,
  launch_image_sha256 TEXT NOT NULL,
  launch_image_size_bytes INTEGER NOT NULL CHECK(launch_image_size_bytes>0),
  public_fixture_delivery_root TEXT NOT NULL CHECK(length(public_fixture_delivery_root)=64 AND public_fixture_delivery_root NOT GLOB '*[^0-9a-f]*'),
  fixture_resources_json TEXT NOT NULL CHECK(json_valid(fixture_resources_json) AND json_array_length(fixture_resources_json)=4),
  observations_json TEXT NOT NULL CHECK(json_valid(observations_json) AND json_array_length(observations_json)=10),
  no_work_json TEXT NOT NULL CHECK(json_valid(no_work_json) AND json_type(no_work_json)='object'),
  run_started_at TEXT NOT NULL CHECK(length(run_started_at)=30 AND julianday(run_started_at) IS NOT NULL),
  run_completed_at TEXT NOT NULL CHECK(length(run_completed_at)=30 AND julianday(run_completed_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=run_completed_at),
  child_network_attempt_count INTEGER NOT NULL CHECK(child_network_attempt_count=0),
  upstream_connect_attempt_count INTEGER NOT NULL CHECK(upstream_connect_attempt_count=0),
  write_outside_ephemeral_count INTEGER NOT NULL CHECK(write_outside_ephemeral_count=0),
  additional_process_attempt_count INTEGER NOT NULL CHECK(additional_process_attempt_count=0),
  policy_violation_count INTEGER NOT NULL CHECK(policy_violation_count=0),
  observation_status TEXT NOT NULL CHECK(observation_status='server_run_observed_no_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"process_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"session_ready":false,"upstream_probe_ready":false}'),
  UNIQUE(challenge_id,challenge_digest),
  UNIQUE(run_observation_id,run_observation_digest),
  FOREIGN KEY(challenge_id,challenge_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_challenges(challenge_id,challenge_digest) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT
);
