CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_runtime_compatibility_verification_receipts (
  verification_receipt_id TEXT PRIMARY KEY NOT NULL,
  verification_receipt_schema TEXT NOT NULL CHECK(verification_receipt_schema='compute_federation.external_pool_adapter_runtime_compatibility_verification_receipt.v1'),
  verification_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(verification_receipt_digest)=64 AND verification_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  verification_material_digest TEXT NOT NULL,
  verification_receipt_json TEXT NOT NULL CHECK(json_valid(verification_receipt_json) AND json_type(verification_receipt_json)='object' AND length(CAST(verification_receipt_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  runner_execution_id TEXT NOT NULL UNIQUE,
  challenge_id TEXT NOT NULL UNIQUE,
  challenge_digest TEXT NOT NULL,
  run_observation_id TEXT NOT NULL UNIQUE,
  run_observation_digest TEXT NOT NULL,
  run_observation_material_digest TEXT NOT NULL,
  registry_release_id TEXT NOT NULL,
  registry_release_digest TEXT NOT NULL,
  registry_release_material_digest TEXT NOT NULL,
  installation_content_digest TEXT NOT NULL,
  profile_id TEXT NOT NULL CHECK(profile_id='external_pool_adapter_linux_runtime_compatibility_v2'),
  profile_revision INTEGER NOT NULL CHECK(profile_revision=2),
  profile_digest TEXT NOT NULL,
  runner_policy_digest TEXT NOT NULL,
  fixture_catalog_digest TEXT NOT NULL,
  public_fixture_delivery_root TEXT NOT NULL,
  sandbox_verifier_key_record_id TEXT NOT NULL,
  sandbox_verifier_key_record_digest TEXT NOT NULL,
  sandbox_verifier_key_id TEXT NOT NULL,
  sandbox_verifier_operator TEXT NOT NULL,
  sandbox_verifier_product TEXT NOT NULL,
  signature_algorithm TEXT NOT NULL CHECK(signature_algorithm='rsa-pkcs1v15-sha256'),
  signature_message_digest TEXT NOT NULL,
  signature_base64 TEXT NOT NULL CHECK(length(signature_base64) BETWEEN 4 AND 1368),
  signature_digest TEXT NOT NULL UNIQUE,
  sequence INTEGER NOT NULL CHECK(sequence>0),
  predecessor_verification_receipt_id TEXT,
  predecessor_verification_receipt_digest TEXT,
  verified_by_admin_user_id TEXT NOT NULL,
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_runtime_compatibility_signature'),
  idempotency_scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  verified_at TEXT NOT NULL CHECK(length(verified_at)=30 AND julianday(verified_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=verified_at),
  expires_at TEXT NOT NULL CHECK(length(expires_at)=30 AND julianday(expires_at) IS NOT NULL),
  evidence_scope TEXT NOT NULL CHECK(evidence_scope='v237_signature_over_server_owned_controlled_public_fixture_runtime_observation_v1'),
  receipt_status TEXT NOT NULL CHECK(receipt_status='signed_verifier_assertion_over_server_run_observation_no_activation_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"process_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"session_ready":false,"upstream_probe_ready":false}'),
  CHECK((predecessor_verification_receipt_id IS NULL)=(predecessor_verification_receipt_digest IS NULL)),
  CHECK((sequence=1)=(predecessor_verification_receipt_id IS NULL)),
  CHECK(expires_at=(strftime('%Y-%m-%dT%H:%M:%S',verified_at,'+24 hours')||substr(verified_at,20))),
  UNIQUE(registry_release_id,sequence),
  UNIQUE(registry_release_id,predecessor_verification_receipt_id),
  UNIQUE(idempotency_scope,idempotency_key),
  UNIQUE(verification_receipt_id,verification_receipt_digest),
  FOREIGN KEY(challenge_id,challenge_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_challenges(challenge_id,challenge_digest) ON DELETE RESTRICT,
  FOREIGN KEY(run_observation_id,run_observation_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_run_observations(run_observation_id,run_observation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(sandbox_verifier_key_record_id,sandbox_verifier_key_record_digest,sandbox_verifier_key_id) REFERENCES compute_external_pool_adapter_sandbox_verifier_keys(key_record_id,key_record_digest,key_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_verification_receipt_id,predecessor_verification_receipt_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_receipts(verification_receipt_id,verification_receipt_digest) ON DELETE RESTRICT
);
