use crate::types::AppState;
use crate::{
    friend_api, group_ai, group_chat_retrieval_api, group_summary_api, project_api,
    project_deletion, project_join_requests, project_membership, project_runtime_permission_api,
    project_space, project_store,
};
use axum::routing::{delete, get, post};
use axum::Router;
use std::sync::Arc;

pub(super) fn routes() -> Router<Arc<AppState>> {
    Router::new()
    .route(
        "/api/me/friends",
        get(friend_api::list_friends).post(friend_api::add_friend_by_phone),
    )
    .route(
        "/api/me/friends/search",
        get(friend_api::search_friend_by_phone),
    )
    .route(
        "/api/me/friends/recommendations",
        get(friend_api::list_friend_recommendations),
    )
    .route(
        "/api/me/project-share-messages/:project_id",
        delete(friend_api::delete_project_share_messages),
    )
    .route(
        "/api/me/friends/:friend_id/messages",
        get(friend_api::list_friend_messages).post(friend_api::send_friend_message),
    )
    .route(
        "/api/me/friends/:friend_id/messages/:message_id",
        delete(friend_api::delete_friend_message),
    )
    .route(
        "/api/me/friends/:friend_id/messages/:message_id/ai-reply",
        post(friend_api::request_friend_ai_reply),
    )
    .route(
        "/api/me/groups",
        get(friend_api::list_friend_groups).post(friend_api::create_friend_group),
    )
    .route(
        "/api/me/groups/:group_id/members",
        post(friend_api::add_group_members),
    )
    .route(
        "/api/me/groups/:group_id/messages",
        get(friend_api::list_friend_group_messages).post(friend_api::send_friend_group_message),
    )
    .route(
        "/api/me/groups/:group_id/messages/search",
        post(group_chat_retrieval_api::search_group_chat_messages),
    )
    .route(
        "/api/me/groups/:group_id/messages/:message_id",
        delete(friend_api::delete_friend_group_message),
    )
    .route(
        "/api/me/groups/:group_id/messages/:message_id/ai-reply",
        post(friend_api::request_group_ai_reply),
    )
    .route(
        "/api/me/groups/:group_id/ai-docs",
        get(group_summary_api::list_group_ai_documents)
            .post(group_summary_api::update_group_ai_document),
    )
    .route(
        "/api/me/groups/:group_id/summary-posts",
        get(group_summary_api::list_group_summary_posts)
            .post(group_summary_api::create_group_summary_post),
    )
    .route(
        "/api/me/groups/:group_id/summary-posts/auto-split",
        post(group_summary_api::auto_split_group_summary_posts),
    )
    .route(
        "/api/me/groups/:group_id/summary-posts/:post_id",
        get(group_summary_api::get_group_summary_post)
            .patch(group_summary_api::update_group_summary_post),
    )
    .route("/api/me/projects", get(project_api::list_my_projects))
    .route("/api/projects", post(project_api::create_project))
    .route(
        "/api/projects/external",
        post(project_api::register_external_project),
    )
    .route("/api/projects/:id", delete(project_deletion::delete_project))
    // ── 项目商店 ─────────────────────────────────────────────────────
    .route(
        "/api/store/projects",
        get(project_store::list_store_projects),
    )
    .route(
        "/api/store/projects/:id",
        get(project_store::get_store_project),
    )
    .route(
        "/api/store/joined",
        get(project_store::list_joined_projects),
    )
    // ── 成员管理 ─────────────────────────────────────────────────────
    .route(
        "/api/projects/:id/join",
        post(project_membership::join_project),
    )
    .route(
        "/api/projects/:id/leave",
        delete(project_membership::leave_project),
    )
    .route(
        "/api/projects/:id/members",
        get(project_membership::list_members).post(project_membership::add_member),
    )
    .route(
        "/api/projects/:id/invite-links",
        get(project_membership::list_project_invite_links)
            .post(project_membership::create_project_invite_link),
    )
    .route(
        "/api/projects/:id/invite-links/:code",
        delete(project_membership::revoke_project_invite_link),
    )
    .route(
        "/api/project-invites/:code",
        get(project_membership::get_project_invite_preview),
    )
    .route(
        "/api/project-invites/:code/join",
        post(project_membership::join_project_by_invite_link),
    )
    .route(
        "/api/projects/:id/member-audit",
        get(project_membership::list_member_audit),
    )
    .route(
        "/api/projects/:id/roles",
        get(project_membership::list_project_roles).post(project_membership::create_project_role),
    )
    .route(
        "/api/projects/:id/roles/:role_id",
        axum::routing::patch(project_membership::update_project_role)
            .delete(project_membership::delete_project_role),
    )
    .route(
        "/api/projects/:id/visibility",
        axum::routing::patch(project_membership::update_visibility),
    )
    .route(
        "/api/projects/:id/runtime-permission",
        get(project_runtime_permission_api::get_runtime_permission)
            .patch(project_runtime_permission_api::update_runtime_permission),
    )
    .route(
        "/api/projects/:id/icon",
        axum::routing::patch(project_membership::update_project_icon),
    )
    .route(
        "/api/projects/:id/brand",
        axum::routing::patch(project_membership::update_project_brand),
    )
    .route(
        "/api/projects/:id/members/:user_id",
        axum::routing::patch(project_membership::update_member_role)
            .delete(project_membership::remove_member),
    )
    .route(
        "/api/projects/:id/members/:user_id/profile",
        axum::routing::patch(project_membership::update_member_profile),
    )
    .route(
        "/api/projects/:id/members/:user_id/moderation",
        axum::routing::patch(project_membership::update_member_moderation),
    )
    // ── 加入申请审批 ──────────────────────────────────────────────────
    .route(
        "/api/projects/:id/request-join",
        post(project_join_requests::request_join),
    )
    .route(
        "/api/projects/:id/join-requests",
        get(project_join_requests::list_join_requests),
    )
    .route(
        "/api/projects/:id/join-requests/:req_id",
        axum::routing::patch(project_join_requests::review_join_request),
    )
    .route(
        "/api/me/join-requests",
        get(project_join_requests::my_join_requests),
    )
    .route(
        "/api/me/join-requests/:req_id",
        axum::routing::delete(project_join_requests::cancel_my_join_request),
    )
    .route(
        "/api/me/owned-projects/pending-counts",
        get(project_join_requests::owned_projects_pending_counts),
    )
    // ── 项目空间：频道、成员协作、集体 AI 开发 ───────────────────────────
    .route(
        "/api/projects/:project_id/space",
        get(project_space::get_project_space),
    )
    .route(
        "/api/projects/:project_id/space/description",
        axum::routing::patch(project_space::update_project_description),
    )
    .route(
        "/api/projects/:project_id/space/gallery-image",
        axum::routing::patch(project_space::update_project_gallery_image),
    )
    .route(
        "/api/projects/:project_id/ai/available-nodes",
        get(group_ai::api::available_nodes),
    )
    .route(
        "/api/projects/:project_id/ai/node-authorizations",
        post(group_ai::api::upsert_node_authorization),
    )
    .route(
        "/api/projects/:project_id/ai/bots",
        get(group_ai::api::list_bots),
    )
    .route(
        "/api/projects/:project_id/ai/matters/plan",
        post(group_ai::api::create_matter_plan),
    )
    .route(
        "/api/projects/:project_id/ai/matters",
        get(group_ai::api::list_matters),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/approve",
        post(group_ai::api::approve_matter),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/start",
        post(group_ai::api::start_matter),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/run-all",
        post(group_ai::automation_api::run_matter_assignments),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/review",
        post(group_ai::automation_api::run_review_assignment),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/events",
        get(group_ai::automation_api::list_matter_events),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/governance",
        get(group_ai::governance_api::get_matter_governance),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/budget-policy",
        post(group_ai::governance_api::update_matter_budget_policy_handler),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/reviews",
        post(group_ai::governance_api::record_matter_review),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/merge-requests",
        post(group_ai::governance_api::create_merge_request),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/merge-requests/:merge_request_id",
        post(group_ai::governance_api::update_merge_request),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/merge-requests/:merge_request_id/check",
        post(group_ai::governance_api::check_merge_request),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/merge-requests/:merge_request_id/apply",
        post(group_ai::governance_api::apply_merge_request),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/request-changes",
        post(group_ai::api::request_matter_changes),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/accept",
        post(group_ai::api::accept_matter),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/cancel",
        post(group_ai::api::cancel_matter),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/assignments/:assignment_id/complete",
        post(group_ai::api::complete_assignment),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/assignments/:assignment_id/fail",
        post(group_ai::api::fail_assignment),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/assignments/:assignment_id/retry",
        post(group_ai::api::retry_assignment),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/assignments/:assignment_id/run",
        post(group_ai::api::run_assignment),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/assignments/:assignment_id/artifact",
        get(group_ai::automation_api::get_assignment_artifact),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/assignments/:assignment_id/artifacts",
        post(group_ai::governance_api::record_assignment_artifact),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id/assignments/:assignment_id/settlement",
        post(group_ai::api::record_assignment_settlement_handler),
    )
    .route(
        "/api/projects/:project_id/ai/matters/:matter_id",
        get(group_ai::api::get_matter),
    )
}
