CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_task_event_batches (
  event_batch_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(event_batch_id)) BETWEEN 1 AND 240 AND event_batch_id=trim(event_batch_id)),
  event_batch_schema TEXT NOT NULL CHECK(event_batch_schema='compute_federation.external_pool_adapter_task_event_batch.v1'),
  event_batch_digest TEXT NOT NULL UNIQUE CHECK(length(event_batch_digest)=64 AND event_batch_digest NOT GLOB '*[^0-9a-f]*'),
  event_batch_json TEXT NOT NULL CHECK(json_valid(event_batch_json) AND json_type(event_batch_json)='object' AND length(CAST(event_batch_json AS BLOB))<=524288),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  event_poll_id TEXT NOT NULL UNIQUE,
  event_poll_digest TEXT NOT NULL CHECK(length(event_poll_digest)=64 AND event_poll_digest NOT GLOB '*[^0-9a-f]*'),
  exchange_receipt_id TEXT NOT NULL,
  exchange_receipt_digest TEXT NOT NULL CHECK(length(exchange_receipt_digest)=64 AND exchange_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  predecessor_event_batch_id TEXT,
  predecessor_event_batch_digest TEXT,
  remote_execution_id TEXT NOT NULL CHECK(length(trim(remote_execution_id)) BETWEEN 1 AND 240 AND remote_execution_id=trim(remote_execution_id)),
  remote_identity_digest TEXT NOT NULL CHECK(length(remote_identity_digest)=64 AND remote_identity_digest NOT GLOB '*[^0-9a-f]*'),
  executor_binding_digest TEXT NOT NULL CHECK(length(executor_binding_digest)=64 AND executor_binding_digest NOT GLOB '*[^0-9a-f]*'),
  remote_execution_state TEXT NOT NULL CHECK(remote_execution_state IN ('committed','running','terminal_after_run')),
  authenticated_observation_sha256 TEXT NOT NULL CHECK(length(authenticated_observation_sha256)=64 AND authenticated_observation_sha256 NOT GLOB '*[^0-9a-f]*'),
  cursor_before_remote_sequence INTEGER NOT NULL CHECK(typeof(cursor_before_remote_sequence)='integer' AND cursor_before_remote_sequence BETWEEN 0 AND 9007199254740991),
  cursor_before_previous_event_root TEXT,
  cursor_before_digest TEXT NOT NULL CHECK(length(cursor_before_digest)=64 AND cursor_before_digest NOT GLOB '*[^0-9a-f]*'),
  cursor_after_remote_sequence INTEGER NOT NULL CHECK(typeof(cursor_after_remote_sequence)='integer' AND cursor_after_remote_sequence BETWEEN 0 AND 9007199254740991),
  cursor_after_previous_event_root TEXT,
  cursor_after_digest TEXT NOT NULL CHECK(length(cursor_after_digest)=64 AND cursor_after_digest NOT GLOB '*[^0-9a-f]*'),
  previous_batch_root TEXT,
  batch_root TEXT NOT NULL UNIQUE CHECK(length(batch_root)=64 AND batch_root NOT GLOB '*[^0-9a-f]*'),
  replay_classification TEXT NOT NULL CHECK((event_count=0 AND replay_classification='empty') OR (event_count>0 AND replay_classification='new')),
  event_count INTEGER NOT NULL CHECK(typeof(event_count)='integer' AND event_count BETWEEN 0 AND 256),
  event_roots_json TEXT NOT NULL CHECK(json_valid(event_roots_json) AND json_type(event_roots_json)='array' AND json_array_length(event_roots_json)=event_count AND length(CAST(event_roots_json AS BLOB))<=524288),
  event_inventory_digest TEXT NOT NULL CHECK(length(event_inventory_digest)=64 AND event_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  authenticated_at TEXT NOT NULL CHECK(authenticated_at GLOB '????-??-??T??:??:??.?????????Z' AND length(authenticated_at)=30 AND julianday(authenticated_at) IS NOT NULL),
  received_at TEXT NOT NULL CHECK(received_at GLOB '????-??-??T??:??:??.?????????Z' AND length(received_at)=30 AND julianday(received_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at GLOB '????-??-??T??:??:??.?????????Z' AND length(recorded_at)=30 AND julianday(recorded_at) IS NOT NULL),
  authority_status TEXT NOT NULL CHECK(authority_status='production_transport_evidence_no_v213_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  CHECK((predecessor_event_batch_id IS NULL)=(predecessor_event_batch_digest IS NULL)),
  CHECK((predecessor_event_batch_id IS NULL)=(previous_batch_root IS NULL)),
  CHECK((cursor_before_remote_sequence=0)=(cursor_before_previous_event_root IS NULL)),
  CHECK(cursor_before_previous_event_root IS NULL OR (length(cursor_before_previous_event_root)=64 AND cursor_before_previous_event_root NOT GLOB '*[^0-9a-f]*')),
  CHECK((cursor_after_remote_sequence=0)=(cursor_after_previous_event_root IS NULL)),
  CHECK(cursor_after_previous_event_root IS NULL OR (length(cursor_after_previous_event_root)=64 AND cursor_after_previous_event_root NOT GLOB '*[^0-9a-f]*')),
  CHECK(cursor_after_remote_sequence=cursor_before_remote_sequence+event_count),
  CHECK(authenticated_at<=received_at AND received_at<=recorded_at),
  UNIQUE(predecessor_event_batch_id),
  UNIQUE(event_batch_id,event_batch_digest),
  FOREIGN KEY(event_poll_id,event_poll_digest) REFERENCES compute_external_pool_adapter_task_event_polls(event_poll_id,event_poll_digest) ON DELETE RESTRICT,
  FOREIGN KEY(exchange_receipt_id,exchange_receipt_digest) REFERENCES compute_external_pool_adapter_task_exchange_receipts(exchange_receipt_id,exchange_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_event_batch_id,predecessor_event_batch_digest) REFERENCES compute_external_pool_adapter_task_event_batches(event_batch_id,event_batch_digest) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_task_events (
  event_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(event_id)) BETWEEN 1 AND 240 AND event_id=trim(event_id)),
  event_schema TEXT NOT NULL CHECK(event_schema='compute_federation.external_pool_adapter_task_event.v1'),
  event_digest TEXT NOT NULL UNIQUE CHECK(length(event_digest)=64 AND event_digest NOT GLOB '*[^0-9a-f]*'),
  event_json TEXT NOT NULL CHECK(json_valid(event_json) AND json_type(event_json)='object' AND length(CAST(event_json AS BLOB))<=524288),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  event_batch_id TEXT NOT NULL,
  event_batch_digest TEXT NOT NULL CHECK(length(event_batch_digest)=64 AND event_batch_digest NOT GLOB '*[^0-9a-f]*'),
  remote_identity_digest TEXT NOT NULL CHECK(length(remote_identity_digest)=64 AND remote_identity_digest NOT GLOB '*[^0-9a-f]*'),
  event_ordinal INTEGER NOT NULL CHECK(typeof(event_ordinal)='integer' AND event_ordinal BETWEEN 1 AND 256),
  remote_event_id TEXT NOT NULL CHECK(length(trim(remote_event_id)) BETWEEN 1 AND 240 AND remote_event_id=trim(remote_event_id)),
  event_type TEXT NOT NULL CHECK(length(trim(event_type)) BETWEEN 1 AND 120 AND event_type=trim(event_type)),
  remote_sequence INTEGER NOT NULL CHECK(typeof(remote_sequence)='integer' AND remote_sequence BETWEEN 1 AND 9007199254740991),
  previous_event_root TEXT,
  event_root TEXT NOT NULL UNIQUE CHECK(length(event_root)=64 AND event_root NOT GLOB '*[^0-9a-f]*'),
  canonical_event_digest TEXT NOT NULL CHECK(length(canonical_event_digest)=64 AND canonical_event_digest NOT GLOB '*[^0-9a-f]*'),
  observed_at TEXT NOT NULL CHECK(observed_at GLOB '????-??-??T??:??:??.?????????Z' AND length(observed_at)=30 AND julianday(observed_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at GLOB '????-??-??T??:??:??.?????????Z' AND length(recorded_at)=30 AND julianday(recorded_at) IS NOT NULL),
  authority_status TEXT NOT NULL CHECK(authority_status='production_transport_evidence_no_v213_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  CHECK((remote_sequence=1)=(previous_event_root IS NULL)),
  CHECK(previous_event_root IS NULL OR (length(previous_event_root)=64 AND previous_event_root NOT GLOB '*[^0-9a-f]*')),
  CHECK(observed_at<=recorded_at),
  UNIQUE(event_batch_id,event_ordinal),
  UNIQUE(event_batch_id,remote_event_id),
  UNIQUE(event_batch_id,remote_sequence),
  FOREIGN KEY(event_batch_id,event_batch_digest) REFERENCES compute_external_pool_adapter_task_event_batches(event_batch_id,event_batch_digest) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED
);
