CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_task_exchange_receipts (
  exchange_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(exchange_receipt_id)) BETWEEN 1 AND 240 AND exchange_receipt_id=trim(exchange_receipt_id)),
  exchange_receipt_schema TEXT NOT NULL CHECK(exchange_receipt_schema='compute_federation.external_pool_adapter_task_exchange_receipt.v1'),
  exchange_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(exchange_receipt_digest)=64 AND exchange_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  exchange_receipt_json TEXT NOT NULL CHECK(json_valid(exchange_receipt_json) AND json_type(exchange_receipt_json)='object' AND length(CAST(exchange_receipt_json AS BLOB))<=524288),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  exchange_attempt_id TEXT NOT NULL UNIQUE,
  exchange_attempt_digest TEXT NOT NULL CHECK(length(exchange_attempt_digest)=64 AND exchange_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  operation_kind TEXT NOT NULL CHECK(operation_kind IN ('prepare','idempotent_commit','cancel_no_start','reconcile','authenticated_events')),
  source_kind TEXT NOT NULL CHECK(source_kind IN ('start_outbox_send_attempt','reconcile_poll','event_poll')),
  source_id TEXT NOT NULL,
  source_digest TEXT NOT NULL CHECK(length(source_digest)=64 AND source_digest NOT GLOB '*[^0-9a-f]*'),
  provider_id TEXT NOT NULL,
  adapter_id TEXT NOT NULL,
  adapter_revision INTEGER NOT NULL CHECK(typeof(adapter_revision)='integer' AND adapter_revision BETWEEN 1 AND 9007199254740991),
  adapter_registry_digest TEXT NOT NULL CHECK(length(adapter_registry_digest)=64 AND adapter_registry_digest NOT GLOB '*[^0-9a-f]*'),
  adapter_implementation_digest TEXT NOT NULL CHECK(length(adapter_implementation_digest)=64 AND adapter_implementation_digest NOT GLOB '*[^0-9a-f]*'),
  command_id TEXT NOT NULL,
  command_digest TEXT NOT NULL CHECK(length(command_digest)=64 AND command_digest NOT GLOB '*[^0-9a-f]*'),
  outbox_id TEXT NOT NULL,
  outbox_digest TEXT NOT NULL CHECK(length(outbox_digest)=64 AND outbox_digest NOT GLOB '*[^0-9a-f]*'),
  send_attempt_id TEXT NOT NULL,
  send_attempt_digest TEXT NOT NULL CHECK(length(send_attempt_digest)=64 AND send_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  route_authorization_id TEXT NOT NULL,
  route_authorization_digest TEXT NOT NULL CHECK(length(route_authorization_digest)=64 AND route_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  route_credential_id TEXT NOT NULL,
  route_credential_revision INTEGER NOT NULL CHECK(typeof(route_credential_revision)='integer' AND route_credential_revision BETWEEN 1 AND 9007199254740991),
  route_credential_digest TEXT NOT NULL CHECK(length(route_credential_digest)=64 AND route_credential_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verification_receipt_id TEXT NOT NULL,
  credential_verification_receipt_digest TEXT NOT NULL CHECK(length(credential_verification_receipt_digest)=64 AND credential_verification_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_id TEXT NOT NULL,
  credential_verifier_revision INTEGER NOT NULL CHECK(typeof(credential_verifier_revision)='integer' AND credential_verifier_revision BETWEEN 1 AND 9007199254740991),
  credential_verifier_digest TEXT NOT NULL CHECK(length(credential_verifier_digest)=64 AND credential_verifier_digest NOT GLOB '*[^0-9a-f]*'),
  executor_binding_digest TEXT NOT NULL CHECK(length(executor_binding_digest)=64 AND executor_binding_digest NOT GLOB '*[^0-9a-f]*'),
  fencing_generation INTEGER NOT NULL CHECK(typeof(fencing_generation)='integer' AND fencing_generation BETWEEN 1 AND 9007199254740991),
  fence_digest TEXT NOT NULL CHECK(length(fence_digest)=64 AND fence_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_digest TEXT NOT NULL CHECK(length(supervisor_session_policy_digest)=64 AND supervisor_session_policy_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_launch_profile_digest TEXT NOT NULL CHECK(length(runtime_launch_profile_digest)=64 AND runtime_launch_profile_digest NOT GLOB '*[^0-9a-f]*'),
  task_protocol_profile_digest TEXT NOT NULL CHECK(length(task_protocol_profile_digest)=64 AND task_protocol_profile_digest NOT GLOB '*[^0-9a-f]*'),
  upstream_transport_target_id TEXT NOT NULL,
  upstream_transport_target_digest TEXT NOT NULL CHECK(length(upstream_transport_target_digest)=64 AND upstream_transport_target_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_companion_digest TEXT NOT NULL CHECK(length(supervisor_session_policy_companion_digest)=64 AND supervisor_session_policy_companion_digest NOT GLOB '*[^0-9a-f]*'),
  launch_image_sha256 TEXT NOT NULL CHECK(length(launch_image_sha256)=64 AND launch_image_sha256 NOT GLOB '*[^0-9a-f]*'),
  ephemeral_task_secret_delivery_root TEXT NOT NULL CHECK(length(ephemeral_task_secret_delivery_root)=64 AND ephemeral_task_secret_delivery_root NOT GLOB '*[^0-9a-f]*'),
  task_protocol_conformance_run_receipt_id TEXT NOT NULL,
  task_protocol_conformance_run_receipt_digest TEXT NOT NULL CHECK(length(task_protocol_conformance_run_receipt_digest)=64 AND task_protocol_conformance_run_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  session_roots_digest TEXT NOT NULL CHECK(length(session_roots_digest)=64 AND session_roots_digest NOT GLOB '*[^0-9a-f]*'),
  session_transcript_digest TEXT NOT NULL CHECK(length(session_transcript_digest)=64 AND session_transcript_digest NOT GLOB '*[^0-9a-f]*' AND session_transcript_digest=session_roots_digest),
  request_digest TEXT NOT NULL CHECK(length(request_digest)=64 AND request_digest NOT GLOB '*[^0-9a-f]*'),
  delivery_attempt_digest TEXT NOT NULL CHECK(length(delivery_attempt_digest)=64 AND delivery_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  exchange_ordinal INTEGER NOT NULL CHECK(typeof(exchange_ordinal)='integer' AND exchange_ordinal BETWEEN 1 AND 64),
  exchange_nonce_digest TEXT NOT NULL CHECK(length(exchange_nonce_digest)=64 AND exchange_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  upstream_request_bytes INTEGER NOT NULL CHECK(typeof(upstream_request_bytes)='integer' AND upstream_request_bytes BETWEEN 1 AND 65536),
  upstream_request_sha256 TEXT NOT NULL CHECK(length(upstream_request_sha256)=64 AND upstream_request_sha256 NOT GLOB '*[^0-9a-f]*'),
  upstream_response_bytes INTEGER NOT NULL CHECK(typeof(upstream_response_bytes)='integer' AND upstream_response_bytes BETWEEN 1 AND 262144),
  upstream_response_sha256 TEXT NOT NULL CHECK(length(upstream_response_sha256)=64 AND upstream_response_sha256 NOT GLOB '*[^0-9a-f]*'),
  semantic_observation_bytes INTEGER NOT NULL CHECK(typeof(semantic_observation_bytes)='integer' AND semantic_observation_bytes BETWEEN 1 AND 262144),
  semantic_observation_sha256 TEXT NOT NULL CHECK(length(semantic_observation_sha256)=64 AND semantic_observation_sha256 NOT GLOB '*[^0-9a-f]*'),
  exchange_root TEXT NOT NULL UNIQUE CHECK(length(exchange_root)=64 AND exchange_root NOT GLOB '*[^0-9a-f]*'),
  authenticated_at TEXT NOT NULL CHECK(authenticated_at GLOB '????-??-??T??:??:??.?????????Z' AND length(authenticated_at)=30 AND julianday(authenticated_at) IS NOT NULL),
  received_at TEXT NOT NULL CHECK(received_at GLOB '????-??-??T??:??:??.?????????Z' AND length(received_at)=30 AND julianday(received_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at GLOB '????-??-??T??:??:??.?????????Z' AND length(recorded_at)=30 AND julianday(recorded_at) IS NOT NULL),
  authority_status TEXT NOT NULL CHECK(authority_status='production_transport_evidence_no_v213_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  CHECK(authenticated_at<=received_at AND received_at<=recorded_at),
  UNIQUE(exchange_receipt_id,exchange_receipt_digest),
  UNIQUE(exchange_attempt_id,exchange_attempt_digest),
  FOREIGN KEY(exchange_attempt_id,exchange_attempt_digest) REFERENCES compute_external_pool_adapter_task_exchange_attempts(exchange_attempt_id,exchange_attempt_digest) ON DELETE RESTRICT
);
