CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_task_exchange_attempts (
  exchange_attempt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(exchange_attempt_id)) BETWEEN 1 AND 240 AND exchange_attempt_id=trim(exchange_attempt_id)),
  exchange_attempt_schema TEXT NOT NULL CHECK(exchange_attempt_schema='compute_federation.external_pool_adapter_task_exchange_attempt.v1'),
  exchange_attempt_digest TEXT NOT NULL UNIQUE CHECK(length(exchange_attempt_digest)=64 AND exchange_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  exchange_attempt_json TEXT NOT NULL CHECK(json_valid(exchange_attempt_json) AND json_type(exchange_attempt_json)='object' AND length(CAST(exchange_attempt_json AS BLOB))<=524288),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  operation_kind TEXT NOT NULL CHECK(operation_kind IN ('prepare','idempotent_commit','cancel_no_start','reconcile','authenticated_events')),
  source_kind TEXT NOT NULL CHECK(source_kind IN ('start_outbox_send_attempt','reconcile_poll','event_poll')),
  source_id TEXT NOT NULL CHECK(length(trim(source_id)) BETWEEN 1 AND 240 AND source_id=trim(source_id)),
  source_digest TEXT NOT NULL CHECK(length(source_digest)=64 AND source_digest NOT GLOB '*[^0-9a-f]*'),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 240 AND provider_id=trim(provider_id)),
  adapter_id TEXT NOT NULL CHECK(length(trim(adapter_id)) BETWEEN 1 AND 240 AND adapter_id=trim(adapter_id)),
  adapter_revision INTEGER NOT NULL CHECK(typeof(adapter_revision)='integer' AND adapter_revision BETWEEN 1 AND 9007199254740991),
  adapter_registry_digest TEXT NOT NULL CHECK(length(adapter_registry_digest)=64 AND adapter_registry_digest NOT GLOB '*[^0-9a-f]*'),
  adapter_implementation_digest TEXT NOT NULL CHECK(length(adapter_implementation_digest)=64 AND adapter_implementation_digest NOT GLOB '*[^0-9a-f]*'),
  command_id TEXT NOT NULL CHECK(length(trim(command_id)) BETWEEN 1 AND 240 AND command_id=trim(command_id)),
  command_digest TEXT NOT NULL CHECK(length(command_digest)=64 AND command_digest NOT GLOB '*[^0-9a-f]*'),
  outbox_id TEXT NOT NULL CHECK(length(trim(outbox_id)) BETWEEN 1 AND 240 AND outbox_id=trim(outbox_id)),
  outbox_digest TEXT NOT NULL CHECK(length(outbox_digest)=64 AND outbox_digest NOT GLOB '*[^0-9a-f]*'),
  send_attempt_id TEXT NOT NULL CHECK(length(trim(send_attempt_id)) BETWEEN 1 AND 240 AND send_attempt_id=trim(send_attempt_id)),
  send_attempt_digest TEXT NOT NULL CHECK(length(send_attempt_digest)=64 AND send_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  route_authorization_id TEXT NOT NULL CHECK(length(trim(route_authorization_id)) BETWEEN 1 AND 240 AND route_authorization_id=trim(route_authorization_id)),
  route_authorization_digest TEXT NOT NULL CHECK(length(route_authorization_digest)=64 AND route_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  route_credential_id TEXT NOT NULL CHECK(length(trim(route_credential_id)) BETWEEN 1 AND 240 AND route_credential_id=trim(route_credential_id)),
  route_credential_revision INTEGER NOT NULL CHECK(typeof(route_credential_revision)='integer' AND route_credential_revision BETWEEN 1 AND 9007199254740991),
  route_credential_digest TEXT NOT NULL CHECK(length(route_credential_digest)=64 AND route_credential_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verification_receipt_id TEXT NOT NULL CHECK(length(trim(credential_verification_receipt_id)) BETWEEN 1 AND 240 AND credential_verification_receipt_id=trim(credential_verification_receipt_id)),
  credential_verification_receipt_digest TEXT NOT NULL CHECK(length(credential_verification_receipt_digest)=64 AND credential_verification_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_id TEXT NOT NULL CHECK(length(trim(credential_verifier_id)) BETWEEN 1 AND 240 AND credential_verifier_id=trim(credential_verifier_id)),
  credential_verifier_revision INTEGER NOT NULL CHECK(typeof(credential_verifier_revision)='integer' AND credential_verifier_revision BETWEEN 1 AND 9007199254740991),
  credential_verifier_digest TEXT NOT NULL CHECK(length(credential_verifier_digest)=64 AND credential_verifier_digest NOT GLOB '*[^0-9a-f]*'),
  executor_binding_digest TEXT NOT NULL CHECK(length(executor_binding_digest)=64 AND executor_binding_digest NOT GLOB '*[^0-9a-f]*'),
  fencing_generation INTEGER NOT NULL CHECK(typeof(fencing_generation)='integer' AND fencing_generation BETWEEN 1 AND 9007199254740991),
  fence_digest TEXT NOT NULL CHECK(length(fence_digest)=64 AND fence_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_digest TEXT NOT NULL CHECK(length(supervisor_session_policy_digest)=64 AND supervisor_session_policy_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_launch_profile_digest TEXT NOT NULL CHECK(length(runtime_launch_profile_digest)=64 AND runtime_launch_profile_digest NOT GLOB '*[^0-9a-f]*'),
  task_protocol_profile_digest TEXT NOT NULL CHECK(length(task_protocol_profile_digest)=64 AND task_protocol_profile_digest NOT GLOB '*[^0-9a-f]*'),
  upstream_transport_target_id TEXT NOT NULL CHECK(length(trim(upstream_transport_target_id)) BETWEEN 1 AND 240 AND upstream_transport_target_id=trim(upstream_transport_target_id)),
  upstream_transport_target_digest TEXT NOT NULL CHECK(length(upstream_transport_target_digest)=64 AND upstream_transport_target_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_companion_digest TEXT NOT NULL CHECK(length(supervisor_session_policy_companion_digest)=64 AND supervisor_session_policy_companion_digest NOT GLOB '*[^0-9a-f]*'),
  launch_image_sha256 TEXT NOT NULL CHECK(length(launch_image_sha256)=64 AND launch_image_sha256 NOT GLOB '*[^0-9a-f]*'),
  ephemeral_task_secret_delivery_root TEXT NOT NULL CHECK(length(ephemeral_task_secret_delivery_root)=64 AND ephemeral_task_secret_delivery_root NOT GLOB '*[^0-9a-f]*'),
  task_protocol_conformance_run_receipt_id TEXT NOT NULL CHECK(length(trim(task_protocol_conformance_run_receipt_id)) BETWEEN 1 AND 240 AND task_protocol_conformance_run_receipt_id=trim(task_protocol_conformance_run_receipt_id)),
  task_protocol_conformance_run_receipt_digest TEXT NOT NULL CHECK(length(task_protocol_conformance_run_receipt_digest)=64 AND task_protocol_conformance_run_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  session_roots_digest TEXT NOT NULL CHECK(length(session_roots_digest)=64 AND session_roots_digest NOT GLOB '*[^0-9a-f]*'),
  session_transcript_digest TEXT NOT NULL CHECK(length(session_transcript_digest)=64 AND session_transcript_digest NOT GLOB '*[^0-9a-f]*' AND session_transcript_digest=session_roots_digest),
  request_digest TEXT NOT NULL CHECK(length(request_digest)=64 AND request_digest NOT GLOB '*[^0-9a-f]*'),
  delivery_attempt_digest TEXT NOT NULL UNIQUE CHECK(length(delivery_attempt_digest)=64 AND delivery_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  started_at TEXT NOT NULL CHECK(started_at GLOB '????-??-??T??:??:??.?????????Z' AND length(started_at)=30 AND julianday(started_at) IS NOT NULL),
  authority_status TEXT NOT NULL CHECK(authority_status='production_transport_evidence_no_v213_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  UNIQUE(source_kind,source_id),
  UNIQUE(exchange_attempt_id,exchange_attempt_digest),
  FOREIGN KEY(command_id) REFERENCES compute_attempt_dispatch_commands(command_id) ON DELETE RESTRICT,
  FOREIGN KEY(outbox_id) REFERENCES compute_attempt_start_outbox(outbox_id) ON DELETE RESTRICT,
  FOREIGN KEY(send_attempt_id) REFERENCES compute_attempt_start_send_attempts(send_attempt_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_authorization_id) REFERENCES compute_route_authorization_receipts(route_authorization_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_credential_id,route_credential_revision) REFERENCES compute_route_credential_versions(credential_id,credential_revision) ON DELETE RESTRICT,
  FOREIGN KEY(credential_verification_receipt_id) REFERENCES compute_external_pool_adapter_credential_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT,
  FOREIGN KEY(upstream_transport_target_id,upstream_transport_target_digest) REFERENCES compute_external_pool_adapter_upstream_transport_targets(target_id,target_digest) ON DELETE RESTRICT,
  FOREIGN KEY(task_protocol_conformance_run_receipt_id,task_protocol_conformance_run_receipt_digest) REFERENCES compute_external_pool_adapter_task_protocol_conformance_run_receipts(run_receipt_id,run_receipt_digest) ON DELETE RESTRICT
);
