CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_task_reconcile_polls (
  reconcile_poll_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(reconcile_poll_id)) BETWEEN 1 AND 240 AND reconcile_poll_id=trim(reconcile_poll_id)),
  reconcile_poll_schema TEXT NOT NULL CHECK(reconcile_poll_schema='compute_federation.external_pool_adapter_task_reconcile_poll.v1'),
  reconcile_poll_digest TEXT NOT NULL UNIQUE CHECK(length(reconcile_poll_digest)=64 AND reconcile_poll_digest NOT GLOB '*[^0-9a-f]*'),
  reconcile_poll_json TEXT NOT NULL CHECK(json_valid(reconcile_poll_json) AND json_type(reconcile_poll_json)='object' AND length(CAST(reconcile_poll_json AS BLOB))<=524288),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  predecessor_reconcile_poll_id TEXT,
  predecessor_reconcile_poll_digest TEXT,
  poll_ordinal INTEGER NOT NULL CHECK(typeof(poll_ordinal)='integer' AND poll_ordinal BETWEEN 1 AND 9007199254740991),
  uncertain_exchange_attempt_id TEXT NOT NULL,
  uncertain_exchange_attempt_digest TEXT NOT NULL CHECK(length(uncertain_exchange_attempt_digest)=64 AND uncertain_exchange_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  command_id TEXT NOT NULL,
  command_digest TEXT NOT NULL CHECK(length(command_digest)=64 AND command_digest NOT GLOB '*[^0-9a-f]*'),
  outbox_id TEXT NOT NULL,
  outbox_digest TEXT NOT NULL CHECK(length(outbox_digest)=64 AND outbox_digest NOT GLOB '*[^0-9a-f]*'),
  send_attempt_id TEXT NOT NULL,
  send_attempt_digest TEXT NOT NULL CHECK(length(send_attempt_digest)=64 AND send_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  route_authorization_id TEXT NOT NULL,
  route_authorization_digest TEXT NOT NULL CHECK(length(route_authorization_digest)=64 AND route_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  executor_binding_digest TEXT NOT NULL CHECK(length(executor_binding_digest)=64 AND executor_binding_digest NOT GLOB '*[^0-9a-f]*'),
  fencing_generation INTEGER NOT NULL CHECK(typeof(fencing_generation)='integer' AND fencing_generation BETWEEN 1 AND 9007199254740991),
  fence_digest TEXT NOT NULL CHECK(length(fence_digest)=64 AND fence_digest NOT GLOB '*[^0-9a-f]*'),
  remote_execution_id TEXT CHECK(remote_execution_id IS NULL OR (length(trim(remote_execution_id)) BETWEEN 1 AND 240 AND remote_execution_id=trim(remote_execution_id))),
  remote_identity_digest TEXT NOT NULL CHECK(length(remote_identity_digest)=64 AND remote_identity_digest NOT GLOB '*[^0-9a-f]*'),
  remote_execution_state TEXT NOT NULL CHECK(remote_execution_state IN ('absent','prepared','committed','running','terminal_no_start','terminal_after_run','unknown','rejected')),
  authenticated_subject_sha256 TEXT CHECK(authenticated_subject_sha256 IS NULL OR (length(authenticated_subject_sha256)=64 AND authenticated_subject_sha256 NOT GLOB '*[^0-9a-f]*')),
  request_digest TEXT NOT NULL CHECK(length(request_digest)=64 AND request_digest NOT GLOB '*[^0-9a-f]*'),
  not_before TEXT NOT NULL CHECK(not_before GLOB '????-??-??T??:??:??.?????????Z' AND length(not_before)=30 AND julianday(not_before) IS NOT NULL),
  not_after TEXT NOT NULL CHECK(not_after GLOB '????-??-??T??:??:??.?????????Z' AND length(not_after)=30 AND julianday(not_after) IS NOT NULL),
  created_at TEXT NOT NULL CHECK(created_at GLOB '????-??-??T??:??:??.?????????Z' AND length(created_at)=30 AND julianday(created_at) IS NOT NULL),
  authority_status TEXT NOT NULL CHECK(authority_status='production_transport_evidence_no_v213_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  claim_status TEXT NOT NULL CHECK(claim_status IN ('pending','claimed','in_flight_unknown','delivery_observed','quarantined')),
  claim_revision INTEGER NOT NULL CHECK(typeof(claim_revision)='integer' AND claim_revision BETWEEN 1 AND 9007199254740991),
  claim_generation INTEGER NOT NULL CHECK(typeof(claim_generation)='integer' AND claim_generation BETWEEN 0 AND 9007199254740991),
  claim_owner_id TEXT,
  claim_token_digest TEXT,
  claim_expires_at TEXT,
  CHECK((predecessor_reconcile_poll_id IS NULL)=(predecessor_reconcile_poll_digest IS NULL)),
  CHECK((poll_ordinal=1)=(predecessor_reconcile_poll_id IS NULL)),
  CHECK(authenticated_subject_sha256 IS NOT NULL OR (remote_execution_id IS NULL AND remote_execution_state='unknown')),
  CHECK(not_before<=created_at AND created_at<=not_after AND not_before<not_after),
  CHECK((claim_status='claimed' AND claim_owner_id IS NOT NULL AND claim_token_digest IS NOT NULL AND claim_expires_at IS NOT NULL AND claim_generation>0 AND length(trim(claim_owner_id)) BETWEEN 1 AND 240 AND length(claim_token_digest)=64 AND claim_token_digest NOT GLOB '*[^0-9a-f]*' AND claim_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(claim_expires_at)=30 AND julianday(claim_expires_at) IS NOT NULL) OR (claim_status<>'claimed' AND claim_owner_id IS NULL AND claim_token_digest IS NULL AND claim_expires_at IS NULL)),
  UNIQUE(uncertain_exchange_attempt_id,poll_ordinal),
  UNIQUE(predecessor_reconcile_poll_id),
  UNIQUE(reconcile_poll_id,reconcile_poll_digest),
  FOREIGN KEY(predecessor_reconcile_poll_id,predecessor_reconcile_poll_digest) REFERENCES compute_external_pool_adapter_task_reconcile_polls(reconcile_poll_id,reconcile_poll_digest) ON DELETE RESTRICT,
  FOREIGN KEY(uncertain_exchange_attempt_id,uncertain_exchange_attempt_digest) REFERENCES compute_external_pool_adapter_task_exchange_attempts(exchange_attempt_id,exchange_attempt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(command_id) REFERENCES compute_attempt_dispatch_commands(command_id) ON DELETE RESTRICT,
  FOREIGN KEY(outbox_id) REFERENCES compute_attempt_start_outbox(outbox_id) ON DELETE RESTRICT,
  FOREIGN KEY(send_attempt_id) REFERENCES compute_attempt_start_send_attempts(send_attempt_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_authorization_id) REFERENCES compute_route_authorization_receipts(route_authorization_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_task_event_polls (
  event_poll_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(event_poll_id)) BETWEEN 1 AND 240 AND event_poll_id=trim(event_poll_id)),
  event_poll_schema TEXT NOT NULL CHECK(event_poll_schema='compute_federation.external_pool_adapter_task_event_poll.v1'),
  event_poll_digest TEXT NOT NULL UNIQUE CHECK(length(event_poll_digest)=64 AND event_poll_digest NOT GLOB '*[^0-9a-f]*'),
  event_poll_json TEXT NOT NULL CHECK(json_valid(event_poll_json) AND json_type(event_poll_json)='object' AND length(CAST(event_poll_json AS BLOB))<=524288),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  predecessor_event_poll_id TEXT,
  predecessor_event_poll_digest TEXT,
  poll_ordinal INTEGER NOT NULL CHECK(typeof(poll_ordinal)='integer' AND poll_ordinal BETWEEN 1 AND 9007199254740991),
  source_exchange_receipt_id TEXT NOT NULL,
  source_exchange_receipt_digest TEXT NOT NULL CHECK(length(source_exchange_receipt_digest)=64 AND source_exchange_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  command_id TEXT NOT NULL,
  command_digest TEXT NOT NULL CHECK(length(command_digest)=64 AND command_digest NOT GLOB '*[^0-9a-f]*'),
  outbox_id TEXT NOT NULL,
  outbox_digest TEXT NOT NULL CHECK(length(outbox_digest)=64 AND outbox_digest NOT GLOB '*[^0-9a-f]*'),
  send_attempt_id TEXT NOT NULL,
  send_attempt_digest TEXT NOT NULL CHECK(length(send_attempt_digest)=64 AND send_attempt_digest NOT GLOB '*[^0-9a-f]*'),
  route_authorization_id TEXT NOT NULL,
  route_authorization_digest TEXT NOT NULL CHECK(length(route_authorization_digest)=64 AND route_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  executor_binding_digest TEXT NOT NULL CHECK(length(executor_binding_digest)=64 AND executor_binding_digest NOT GLOB '*[^0-9a-f]*'),
  fencing_generation INTEGER NOT NULL CHECK(typeof(fencing_generation)='integer' AND fencing_generation BETWEEN 1 AND 9007199254740991),
  fence_digest TEXT NOT NULL CHECK(length(fence_digest)=64 AND fence_digest NOT GLOB '*[^0-9a-f]*'),
  remote_execution_id TEXT NOT NULL CHECK(length(trim(remote_execution_id)) BETWEEN 1 AND 240 AND remote_execution_id=trim(remote_execution_id)),
  remote_identity_digest TEXT NOT NULL CHECK(length(remote_identity_digest)=64 AND remote_identity_digest NOT GLOB '*[^0-9a-f]*'),
  remote_execution_state TEXT NOT NULL CHECK(remote_execution_state IN ('committed','running')),
  authenticated_subject_sha256 TEXT NOT NULL CHECK(length(authenticated_subject_sha256)=64 AND authenticated_subject_sha256 NOT GLOB '*[^0-9a-f]*'),
  requested_remote_sequence INTEGER NOT NULL CHECK(typeof(requested_remote_sequence)='integer' AND requested_remote_sequence BETWEEN 0 AND 9007199254740991),
  requested_previous_event_root TEXT,
  requested_cursor_digest TEXT NOT NULL CHECK(length(requested_cursor_digest)=64 AND requested_cursor_digest NOT GLOB '*[^0-9a-f]*'),
  request_digest TEXT NOT NULL CHECK(length(request_digest)=64 AND request_digest NOT GLOB '*[^0-9a-f]*'),
  not_before TEXT NOT NULL CHECK(not_before GLOB '????-??-??T??:??:??.?????????Z' AND length(not_before)=30 AND julianday(not_before) IS NOT NULL),
  not_after TEXT NOT NULL CHECK(not_after GLOB '????-??-??T??:??:??.?????????Z' AND length(not_after)=30 AND julianday(not_after) IS NOT NULL),
  created_at TEXT NOT NULL CHECK(created_at GLOB '????-??-??T??:??:??.?????????Z' AND length(created_at)=30 AND julianday(created_at) IS NOT NULL),
  authority_status TEXT NOT NULL CHECK(authority_status='production_transport_evidence_no_v213_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  claim_status TEXT NOT NULL CHECK(claim_status IN ('pending','claimed','in_flight_unknown','delivery_observed','quarantined')),
  claim_revision INTEGER NOT NULL CHECK(typeof(claim_revision)='integer' AND claim_revision BETWEEN 1 AND 9007199254740991),
  claim_generation INTEGER NOT NULL CHECK(typeof(claim_generation)='integer' AND claim_generation BETWEEN 0 AND 9007199254740991),
  claim_owner_id TEXT,
  claim_token_digest TEXT,
  claim_expires_at TEXT,
  CHECK((predecessor_event_poll_id IS NULL)=(predecessor_event_poll_digest IS NULL)),
  CHECK((poll_ordinal=1)=(predecessor_event_poll_id IS NULL)),
  CHECK((requested_remote_sequence=0)=(requested_previous_event_root IS NULL)),
  CHECK(requested_previous_event_root IS NULL OR (length(requested_previous_event_root)=64 AND requested_previous_event_root NOT GLOB '*[^0-9a-f]*')),
  CHECK(not_before<=created_at AND created_at<=not_after AND not_before<not_after),
  CHECK((claim_status='claimed' AND claim_owner_id IS NOT NULL AND claim_token_digest IS NOT NULL AND claim_expires_at IS NOT NULL AND claim_generation>0 AND length(trim(claim_owner_id)) BETWEEN 1 AND 240 AND length(claim_token_digest)=64 AND claim_token_digest NOT GLOB '*[^0-9a-f]*' AND claim_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(claim_expires_at)=30 AND julianday(claim_expires_at) IS NOT NULL) OR (claim_status<>'claimed' AND claim_owner_id IS NULL AND claim_token_digest IS NULL AND claim_expires_at IS NULL)),
  UNIQUE(remote_identity_digest,requested_cursor_digest,poll_ordinal),
  UNIQUE(predecessor_event_poll_id),
  UNIQUE(event_poll_id,event_poll_digest),
  FOREIGN KEY(predecessor_event_poll_id,predecessor_event_poll_digest) REFERENCES compute_external_pool_adapter_task_event_polls(event_poll_id,event_poll_digest) ON DELETE RESTRICT,
  FOREIGN KEY(source_exchange_receipt_id,source_exchange_receipt_digest) REFERENCES compute_external_pool_adapter_task_exchange_receipts(exchange_receipt_id,exchange_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(command_id) REFERENCES compute_attempt_dispatch_commands(command_id) ON DELETE RESTRICT,
  FOREIGN KEY(outbox_id) REFERENCES compute_attempt_start_outbox(outbox_id) ON DELETE RESTRICT,
  FOREIGN KEY(send_attempt_id) REFERENCES compute_attempt_start_send_attempts(send_attempt_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_authorization_id) REFERENCES compute_route_authorization_receipts(route_authorization_id) ON DELETE RESTRICT
);
