use super::super::super::model::{
    EdgeKind, Epoch, Reachability, SourceEdge, SourceEffect, SourceNodeId, ALL_OPS,
};
use super::require_edge_shape;

pub(super) fn validate(edges: &[SourceEdge]) -> Result<(), &'static str> {
    for (id, from, to, kind, reachability, effect) in [
        (
            "fault.begin.observe",
            SourceNodeId::ManagedFaultBegin,
            SourceNodeId::ManagedFaultObserve,
            EdgeKind::Call,
            Reachability::Required,
            SourceEffect::None,
        ),
        (
            "fault.observe.controller-observe",
            SourceNodeId::ManagedFaultObserve,
            SourceNodeId::ManagedFaultControllerObserve,
            EdgeKind::Call,
            Reachability::Conditional,
            SourceEffect::None,
        ),
        (
            "fault.controller-observe.trigger-before",
            SourceNodeId::ManagedFaultControllerObserve,
            SourceNodeId::ManagedFaultTriggerBefore,
            EdgeKind::ConditionalCall,
            Reachability::Conditional,
            SourceEffect::None,
        ),
        (
            "fault.trigger-before.activate",
            SourceNodeId::ManagedFaultTriggerBefore,
            SourceNodeId::ManagedFaultActivateBefore,
            EdgeKind::Call,
            Reachability::Conditional,
            SourceEffect::None,
        ),
        (
            "fault.before.terminal",
            SourceNodeId::ManagedFaultActivateBefore,
            SourceNodeId::ManagedFaultTerminalize,
            EdgeKind::TerminalReturn,
            Reachability::Conditional,
            SourceEffect::Poison,
        ),
        (
            "fault.finish.trigger-after",
            SourceNodeId::ManagedFaultFinish,
            SourceNodeId::ManagedFaultTriggerAfter,
            EdgeKind::ConditionalCall,
            Reachability::Conditional,
            SourceEffect::None,
        ),
        (
            "fault.trigger-after.activate",
            SourceNodeId::ManagedFaultTriggerAfter,
            SourceNodeId::ManagedFaultActivateAfter,
            EdgeKind::Call,
            Reachability::Conditional,
            SourceEffect::None,
        ),
        (
            "fault.after.terminal",
            SourceNodeId::ManagedFaultActivateAfter,
            SourceNodeId::ManagedFaultTerminalize,
            EdgeKind::TerminalReturn,
            Reachability::Required,
            SourceEffect::Poison,
        ),
        (
            "fault.terminal.poison",
            SourceNodeId::ManagedFaultTerminalize,
            SourceNodeId::ManagedPoison,
            EdgeKind::MutationBeforeContinuation,
            Reachability::Required,
            SourceEffect::Poison,
        ),
    ] {
        require_edge_shape(
            edges,
            id,
            from,
            to,
            kind,
            ALL_OPS,
            Epoch::WalMainSteady,
            reachability,
            effect,
        )?;
    }
    Ok(())
}
