package com.elon.app.chatgptweb

internal object ChatGptWebUiSemantics {
    const val GENERIC_ACTION = "action"
    const val DICTATION = "dictation"
    const val WEB_SEARCH = "web_search"

    val KNOWN = setOf(
        "navigation",
        "title",
        "profile",
        "new_conversation",
        "temporary_chat",
        "attachment",
        "model",
        WEB_SEARCH,
        DICTATION,
        "voice_mode",
        "send",
        "stop",
        "suggestion",
        "copy",
        "regenerate",
        "edit",
        "share",
        "feedback",
        "read_aloud",
        "previous_response",
        "next_response",
        "open_media",
        "reasoning_details",
        "branch",
        "delete",
        "close",
        "confirm",
        "conversation",
        "conversation_options",
        "conversation_group",
        "home",
        "pinned",
        "download_app",
        "personalization",
        "help",
        "logout",
        "plan",
        "search",
        "text_input",
        "selection",
        "toggle",
        "slider",
        "images",
        "library",
        "apps",
        "tasks",
        "project",
        "save_to_project",
        "gpts",
        "settings",
        "health",
        "finances",
        "work",
        "create_asset",
        "sources",
        "conversation_files",
        "rename",
        "pin",
        "archive",
        "more",
        "timestamp",
        GENERIC_ACTION,
    )
}
