package com.elon.app.chatgptweb

internal object ChatGptWebAdapterAssets {
    val names: List<String> get() = ADAPTER_ASSETS

    private val ADAPTER_ASSETS = listOf(
        "chatgpt_web_adapter_bootstrap.js",
        "chatgpt_web_private_runtime_bindings.js",
        "chatgpt_web_committed_owner_path.js",
        "chatgpt_web_new_chat_confirmation.js",
        "chatgpt_web_private_new_conversation.js",
        "chatgpt_web_adapter_authentication_policy.js",
        "chatgpt_web_private_directory_pages.js",
        "chatgpt_web_private_directory_browser.js",
        "chatgpt_web_directory_page_requests.js",
    "chatgpt_web_private_directory_refresh.js",
        "chatgpt_web_private_conversation_directory.js",
        "chatgpt_web_adapter_conversation_directory_requests.js",
        "chatgpt_web_adapter_project_policy.js",
        "chatgpt_web_adapter_project_hints.js",
        "chatgpt_web_adapter_context_menu_policy.js",
        "chatgpt_web_adapter_control_labels.js",
        "chatgpt_web_adapter_project_choice_reveal.js",
        "chatgpt_web_adapter_conversation_history.js",
        "chatgpt_web_adapter_conversations.js",
        "chatgpt_web_adapter_message_action_policy.js",
        "chatgpt_web_adapter_message_portal_policy.js",
        "chatgpt_web_private_content_source.js", "chatgpt_web_image_assets.js",
        "chatgpt_web_private_image_pointer.js",
        "chatgpt_web_private_image_gallery.js",
        "chatgpt_web_adapter_messages.js",
        "chatgpt_web_adapter_model_label_policy.js",
        "chatgpt_web_private_model_contract.js",
        "chatgpt_web_private_model_catalog.js",
        "chatgpt_web_private_model_state.js",
        "chatgpt_web_adapter_composer_option_policy.js",
        "chatgpt_web_adapter_composer_submenu.js",
        "chatgpt_web_adapter_composer_tool_state_policy.js",
        "chatgpt_web_private_composer_tool_context.js",
        "chatgpt_web_adapter_composer_tool_selection.js",
        "chatgpt_web_adapter_action_target_policy.js",
        "chatgpt_web_adapter_composer_dismiss_policy.js",
        "chatgpt_web_adapter_attachment_policy.js",
        "chatgpt_web_dictation_runtime.js",
        "chatgpt_web_adapter_dictation_session_policy.js",
        "chatgpt_web_adapter_dictation_actions.js",
        "chatgpt_web_adapter_composer.js",
        "chatgpt_web_adapter_navigation_policy.js",
        "chatgpt_web_adapter_sidebar_control_policy.js",
        "chatgpt_web_adapter_navigation.js",
        "chatgpt_web_adapter_page_semantic_policy.js",
        "chatgpt_web_private_temporary_chat.js",
        "chatgpt_web_adapter_temporary_chat.js",
        "chatgpt_web_adapter_form_controls.js",
        "chatgpt_web_adapter_control_ownership_policy.js",
        "chatgpt_web_adapter_overlay_policy.js",
        "chatgpt_web_adapter_form_commands.js",
        "chatgpt_web_adapter_disclosure_controls.js",
        "chatgpt_web_adapter_snapshot_scheduler.js",
        "chatgpt_web_adapter_streaming_policy.js",
        "chatgpt_web_stream_watchdog_probe.js",
        "chatgpt_web_stream_watchdog_acceptance.js",
        "chatgpt_web_adapter_skin.js",
        "chatgpt_web_adapter_realtime_voice_policy.js",
        "chatgpt_web_adapter_layout.js",
        "chatgpt_web_private_protocol_evidence.js",
        "chatgpt_web_private_research_probe.js",
        "chatgpt_web_private_voice_relay.js",
        "chatgpt_web_realtime_data_channel_research.js",
        "chatgpt_web_realtime_voice_research.js",
        "chatgpt_web_private_transport_policy.js",
        "chatgpt_web_private_file_citation.js",
        "chatgpt_web_private_history_projection.js",
        "chatgpt_web_private_transport.js",
        "chatgpt_web_private_library_download.js", "chatgpt_web_private_file_download.js",
        "chatgpt_web_private_mounted_library_attachment.js",
        "chatgpt_web_private_library_attachment_policy.js",
        "chatgpt_web_private_library_attachment.js",
        "chatgpt_web_private_library_catalog.js", "chatgpt_web_private_library_mutations.js",
        "chatgpt_web_private_attachment_protocol.js",
        "chatgpt_web_private_attachment_bytes.js",
        "chatgpt_web_private_attachment_reservation.js",
        "chatgpt_web_private_attachment_library.js",
        "chatgpt_web_private_attachment_transport.js",
        "chatgpt_web_native_attachment_source.js",
        "chatgpt_web_private_attachment_project.js",
        "chatgpt_web_private_attachment_composer.js",
        "chatgpt_web_private_attachment_image.js",
        "chatgpt_web_private_attachment_selection.js",
        "chatgpt_web_private_attachment_send.js",
        "chatgpt_web_private_conversation_mutation.js",
        "chatgpt_web_private_conversation_delete.js",
        "chatgpt_web_private_conversation_share_contract.js", "chatgpt_web_private_shared_links.js",
        "chatgpt_web_private_project_conversation_share.js",
        "chatgpt_web_private_conversation_share.js",
        "chatgpt_web_private_read_aloud_transport.js",
        "chatgpt_web_private_read_aloud_adapter.js",
        "chatgpt_web_private_dictation_transport.js",
        "chatgpt_web_private_dictation_orchestrator.js",
        "chatgpt_web_private_text_transaction_policy.js",
        "chatgpt_web_private_text_transaction_relay.js",
        "chatgpt_web_private_delta_document.js", "chatgpt_web_private_stream_policy.js",
        "chatgpt_web_private_stream_transport.js",
        "chatgpt_web_private_send_observer.js", "chatgpt_web_private_text_runtime_submit.js",
        "chatgpt_web_runtime_generation_state.js",
        "chatgpt_web_private_regenerate_contract.js", "chatgpt_web_private_regenerate_runtime.js",
        "chatgpt_web_private_stop_runtime.js", "chatgpt_web_text_transaction_orchestrator.js",
        "chatgpt_web_attachment_transport_observer.js",
        "chatgpt_web_adapter.js",
    )
}
