package com.elon.app.chatgptweb

internal object ChatGptWebNativeAttachmentPolicy {
    private val imageTypes = setOf("image/jpeg", "image/png", "image/webp")
    private val documentTypes = setOf(
        "text/plain", "application/pdf", "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.ms-powerpoint",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "application/vnd.ms-excel",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "application/vnd.oasis.opendocument.text", "application/rtf", "text/rtf",
        "text/csv", "text/tab-separated-values", "text/markdown", "application/json",
        "application/xml", "text/xml", "text/html",
        "application/javascript",
        "application/toml",
        "application/vnd.apple.keynote",
        "application/vnd.apple.pages",
        "application/x-powershell",
        "application/x-rust",
        "application/x-scala",
        "application/x-sql",
        "application/x-yaml",
        "message/rfc822",
        "text/calendar",
        "text/css",
        "text/javascript",
        "text/jsx",
        "text/tsx",
        "text/vbscript",
        "text/x-asm",
        "text/x-astro",
        "text/x-c",
        "text/x-c++",
        "text/x-clojure",
        "text/x-csharp",
        "text/x-dart",
        "text/x-diff",
        "text/x-ejs",
        "text/x-elixir",
        "text/x-erb",
        "text/x-erlang",
        "text/x-go",
        "text/x-groovy",
        "text/x-handlebars",
        "text/x-haskell",
        "text/x-jade",
        "text/x-java",
        "text/x-jinja2",
        "text/x-julia",
        "text/x-kotlin",
        "text/x-liquid",
        "text/x-lisp",
        "text/x-lua",
        "text/x-makefile",
        "text/x-mustache",
        "text/x-objectivec",
        "text/x-objectivec++",
        "text/x-perl",
        "text/x-php",
        "text/x-pug",
        "text/x-python",
        "text/x-r",
        "text/x-rst",
        "text/x-ruby",
        "text/x-rust",
        "text/x-scala",
        "text/x-script.python",
        "text/x-sh",
        "text/x-shellscript",
        "text/x-swift",
        "text/x-tex",
        "text/x-tmpl",
        "text/x-twig",
        "text/x-typescript",
        "text/x-vcard",
        "application/haansofthwp",
        "application/haansofthwpx",
        "application/hwp+zip",
        "application/vnd.hancom.hwpx",
        "application/x-hwp",
        "application/x-hwp+zip",
        "application/x-hwp-v5",
    )

    fun supports(mimeType: String, size: Long, width: Int?, height: Int?): Boolean {
        if (size !in 1L..ChatGptWebNativeAttachmentReader.MAX_BYTES.toLong()) return false
        if (mimeType in documentTypes) return true
        // The production photo picker already decodes and normalizes to this pixel budget.
        return mimeType in imageTypes && width != null && height != null &&
            width in 1..16_384 && height in 1..16_384 && width.toLong() * height <= 4_000_000L
    }
}
