use anyhow::Result;
use rusqlite::{named_params, Transaction};

use crate::compute_federation::external_pool_adapter_provider_runtime_readiness::*;

pub(super) fn insert_readiness(
    tx: &Transaction<'_>,
    receipt: &ExternalPoolAdapterProviderRuntimeReadinessReceipt,
) -> Result<()> {
    let r = &receipt.readiness;
    tx.execute(
        "INSERT INTO compute_external_pool_adapter_provider_runtime_readiness_receipts(
          readiness_receipt_id,readiness_receipt_schema,readiness_receipt_digest,
          readiness_material_digest,readiness_receipt_json,canonicalization,digest_algorithm,
          policy_id,policy_revision,policy_digest,provider_binding_id,provider_binding_digest,
          registry_release_id,registry_release_digest,registry_release_material_digest,
          installation_receipt_id,installation_receipt_digest,installation_content_digest,
          candidate_id,candidate_digest,delegation_id,delegation_digest,profile_id,profile_digest,
          target_id,target_digest,companion_id,companion_digest,provider_id,provider_policy_revision,
          provider_digest,provider_status,vulnerability_reattestation_receipt_id,
          vulnerability_reattestation_receipt_digest,sandbox_reattestation_receipt_id,
          sandbox_reattestation_receipt_digest,credential_reattestation_receipt_id,
          credential_reattestation_receipt_digest,runtime_compatibility_verification_receipt_id,
          runtime_compatibility_verification_receipt_digest,launch_policy_digest,target_policy_digest,
          entrypoint_capsule_policy_digest,supervisor_session_policy_digest,source_capsule_sha256,
          source_capsule_size_bytes,launch_image_sha256,launch_image_size_bytes,
          runtime_custody_epoch_digest,runtime_bundle_identity_commitment,
          post_cleanup_observation_commitment,probe_execution_id,request_bytes,response_bytes,
          probe_checked_at,cleanup_completed_at,checked_at,expires_at,sequence,
          predecessor_readiness_receipt_id,predecessor_readiness_receipt_digest,
          recorded_by_actor_kind,recorded_by_actor_user_id,recorded_at,idempotency_scope,
          idempotency_key,confirmation,evidence_scope,receipt_status,effects_json,
          observed_readiness_json
        ) VALUES (
          :id,:schema,:digest,:material,:json,:canonicalization,:algorithm,:policy_id,
          :policy_revision,:policy_digest,:binding_id,:binding_digest,:release_id,:release_digest,
          :release_material,:installation_id,:installation_digest,:content_digest,:candidate_id,
          :candidate_digest,:delegation_id,:delegation_digest,:profile_id,:profile_digest,
          :target_id,:target_digest,:companion_id,:companion_digest,:provider_id,
          :provider_revision,:provider_digest,:provider_status,:vulnerability_id,
          :vulnerability_digest,:sandbox_id,:sandbox_digest,:credential_id,:credential_digest,
          :verification_id,:verification_digest,:launch_policy,:target_policy,:capsule_policy,
          :session_policy,:source_sha,:source_size,:launch_sha,:launch_size,:epoch_digest,
          :bundle_commitment,:observation_commitment,:execution_id,:request_bytes,:response_bytes,
          :probe_at,:cleanup_at,:checked_at,:expires_at,:sequence,:predecessor_id,
          :predecessor_digest,:actor_kind,:actor_id,:recorded_at,:scope,:key,:confirmation,
          :evidence_scope,:status,:effects,:readiness)",
        named_params! {
            ":id": receipt.readiness_receipt_id,
            ":schema": receipt.schema,
            ":digest": receipt.readiness_receipt_digest,
            ":material": receipt.readiness_material_digest,
            ":json": canonical_provider_runtime_readiness_receipt_json_and_digest(receipt)?.0,
            ":canonicalization": receipt.canonicalization,
            ":algorithm": receipt.digest_algorithm,
            ":policy_id": r.policy_id,
            ":policy_revision": i64::try_from(r.policy_revision)?,
            ":policy_digest": r.policy_digest,
            ":binding_id": r.provider_binding_id,
            ":binding_digest": r.provider_binding_digest,
            ":release_id": r.registry_release_id,
            ":release_digest": r.registry_release_digest,
            ":release_material": r.registry_release_material_digest,
            ":installation_id": r.installation_receipt_id,
            ":installation_digest": r.installation_receipt_digest,
            ":content_digest": r.installation_content_digest,
            ":candidate_id": r.candidate_id,
            ":candidate_digest": r.candidate_digest,
            ":delegation_id": r.delegation_id,
            ":delegation_digest": r.delegation_digest,
            ":profile_id": r.profile_id,
            ":profile_digest": r.profile_digest,
            ":target_id": r.target_id,
            ":target_digest": r.target_digest,
            ":companion_id": r.companion_id,
            ":companion_digest": r.companion_digest,
            ":provider_id": r.provider_id,
            ":provider_revision": r.provider_policy_revision,
            ":provider_digest": r.provider_digest,
            ":provider_status": r.provider_status,
            ":vulnerability_id": r.vulnerability_reattestation_receipt_id,
            ":vulnerability_digest": r.vulnerability_reattestation_receipt_digest,
            ":sandbox_id": r.sandbox_reattestation_receipt_id,
            ":sandbox_digest": r.sandbox_reattestation_receipt_digest,
            ":credential_id": r.credential_reattestation_receipt_id,
            ":credential_digest": r.credential_reattestation_receipt_digest,
            ":verification_id": r.runtime_compatibility_verification_receipt_id,
            ":verification_digest": r.runtime_compatibility_verification_receipt_digest,
            ":launch_policy": r.launch_policy_digest,
            ":target_policy": r.target_policy_digest,
            ":capsule_policy": r.entrypoint_capsule_policy_digest,
            ":session_policy": r.supervisor_session_policy_digest,
            ":source_sha": r.source_capsule_sha256,
            ":source_size": i64::try_from(r.source_capsule_size_bytes)?,
            ":launch_sha": r.launch_image_sha256,
            ":launch_size": i64::try_from(r.launch_image_size_bytes)?,
            ":epoch_digest": r.sealed_bindings.runtime_custody_epoch_digest,
            ":bundle_commitment": r.sealed_bindings.runtime_bundle_identity_commitment,
            ":observation_commitment": r.sealed_bindings.post_cleanup_observation_commitment,
            ":execution_id": r.probe_execution_id,
            ":request_bytes": i64::try_from(r.request_bytes)?,
            ":response_bytes": i64::try_from(r.response_bytes)?,
            ":probe_at": r.probe_checked_at,
            ":cleanup_at": r.cleanup_completed_at,
            ":checked_at": r.checked_at,
            ":expires_at": r.expires_at,
            ":sequence": i64::try_from(r.sequence)?,
            ":predecessor_id": r.predecessor_readiness_receipt_id,
            ":predecessor_digest": r.predecessor_readiness_receipt_digest,
            ":actor_kind": r.recorded_by_actor_kind,
            ":actor_id": r.recorded_by_actor_user_id,
            ":recorded_at": r.recorded_at,
            ":scope": r.idempotency_scope,
            ":key": r.idempotency_key,
            ":confirmation": r.confirmation,
            ":evidence_scope": r.evidence_scope,
            ":status": r.receipt_status,
            ":effects": canonical_json(&r.effects)?,
            ":readiness": canonical_json(&r.observed_readiness)?,
        },
    )?;
    Ok(())
}

pub(super) fn insert_revocation(
    tx: &Transaction<'_>,
    receipt: &ExternalPoolAdapterProviderRuntimeReadinessRevocationReceipt,
) -> Result<()> {
    let r = &receipt.revocation;
    tx.execute(
        "INSERT INTO compute_external_pool_adapter_provider_runtime_readiness_revocations(
          revocation_receipt_id,revocation_receipt_schema,revocation_receipt_digest,
          revocation_material_digest,revocation_receipt_json,canonicalization,digest_algorithm,
          readiness_receipt_id,readiness_receipt_digest,provider_binding_id,
          provider_binding_digest,candidate_id,candidate_digest,profile_id,profile_digest,
          target_id,target_digest,companion_id,companion_digest,provider_id,
          revoked_by_actor_kind,revoked_by_actor_user_id,reason,revoked_at,recorded_at,
          idempotency_scope,idempotency_key,confirmation,revocation_status,effects_json,
          readiness_json
        ) VALUES (
          :id,:schema,:digest,:material,:json,:canonicalization,:algorithm,:readiness_id,
          :readiness_digest,:binding_id,:binding_digest,:candidate_id,:candidate_digest,
          :profile_id,:profile_digest,:target_id,:target_digest,:companion_id,:companion_digest,
          :provider_id,:actor_kind,:actor_id,:reason,:revoked_at,:recorded_at,:scope,:key,
          :confirmation,:status,:effects,:readiness)",
        named_params! {
            ":id": receipt.revocation_receipt_id,
            ":schema": receipt.schema,
            ":digest": receipt.revocation_receipt_digest,
            ":material": receipt.revocation_material_digest,
            ":json": canonical_provider_runtime_readiness_revocation_json_and_digest(receipt)?.0,
            ":canonicalization": receipt.canonicalization,
            ":algorithm": receipt.digest_algorithm,
            ":readiness_id": r.readiness_receipt_id,
            ":readiness_digest": r.readiness_receipt_digest,
            ":binding_id": r.provider_binding_id,
            ":binding_digest": r.provider_binding_digest,
            ":candidate_id": r.candidate_id,
            ":candidate_digest": r.candidate_digest,
            ":profile_id": r.profile_id,
            ":profile_digest": r.profile_digest,
            ":target_id": r.target_id,
            ":target_digest": r.target_digest,
            ":companion_id": r.companion_id,
            ":companion_digest": r.companion_digest,
            ":provider_id": r.provider_id,
            ":actor_kind": r.revoked_by_actor_kind,
            ":actor_id": r.revoked_by_actor_user_id,
            ":reason": r.reason,
            ":revoked_at": r.revoked_at,
            ":recorded_at": r.recorded_at,
            ":scope": r.idempotency_scope,
            ":key": r.idempotency_key,
            ":confirmation": r.confirmation,
            ":status": r.revocation_status,
            ":effects": canonical_json(&r.effects)?,
            ":readiness": canonical_json(&r.readiness)?,
        },
    )?;
    Ok(())
}

fn canonical_json<T: serde::Serialize>(value: &T) -> Result<String> {
    Ok(
        crate::compute_plugin_sharing_directive::canonical_compute_plugin_ijson_and_sha256(
            value,
            PROVIDER_RUNTIME_READINESS_MAX_RECEIPT_JSON_BYTES,
        )?
        .0,
    )
}
