use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ExternalPoolAdapterProviderActiveSuccessorStructuralInput {
    pub provider_id: String,
    pub provider_owner_account_id: String,
    pub provider_binding_id: String,
    pub provider_binding_digest: String,
    pub registry_release_id: String,
    pub registry_release_digest: String,
    pub registry_release_material_digest: String,
    pub installation_receipt_id: String,
    pub installation_receipt_digest: String,
    pub installation_content_digest: String,
    pub candidate_id: String,
    pub candidate_digest: String,
    pub delegation_id: String,
    pub delegation_digest: String,
    pub service_actor_id: String,
    pub logical_adapter_id: String,
    pub logical_adapter_binding_digest: String,
    pub logical_projection_compatibility_digest: String,
    pub route_adapter_projection_id: String,
    pub profile_id: String,
    pub profile_digest: String,
    pub launch_policy_digest: String,
    pub target_id: String,
    pub target_digest: String,
    pub target_policy_digest: String,
    pub companion_id: String,
    pub companion_digest: String,
    pub supervisor_session_policy_digest: String,
    pub entrypoint_capsule_policy_digest: String,
    pub launch_image_sha256: String,
    pub task_protocol_profile_digest: String,
    pub lane_subject_digest: String,
    pub task_production_carrier_policy_digest: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ExternalPoolAdapterProviderActiveSuccessorActivationRootEnvelope {
    pub provider_id: String,
    pub provider_owner_account_id: String,
    pub source_registering_provider_id: String,
    pub source_registering_provider_policy_revision: i64,
    pub source_registering_provider_json: String,
    pub source_registering_provider_digest: String,
    pub initial_active_provider_id: String,
    pub initial_active_provider_policy_revision: i64,
    pub initial_active_provider_json: String,
    pub initial_active_provider_digest: String,
    pub provider_binding_id: String,
    pub provider_binding_digest: String,
    pub registry_release_id: String,
    pub registry_release_digest: String,
    pub registry_release_material_digest: String,
    pub installation_receipt_id: String,
    pub installation_receipt_digest: String,
    pub installation_content_digest: String,
    pub candidate_id: String,
    pub candidate_digest: String,
    pub delegation_id: String,
    pub delegation_digest: String,
    pub service_actor_id: String,
    pub logical_adapter_id: String,
    pub logical_adapter_binding_digest: String,
    pub logical_projection_compatibility_digest: String,
    pub route_adapter_projection_id: String,
    pub profile_id: String,
    pub profile_digest: String,
    pub launch_policy_digest: String,
    pub target_id: String,
    pub target_digest: String,
    pub target_policy_digest: String,
    pub companion_id: String,
    pub companion_digest: String,
    pub supervisor_session_policy_digest: String,
    pub entrypoint_capsule_policy_digest: String,
    pub launch_image_sha256: String,
    pub task_protocol_profile_digest: String,
    pub lane_subject_digest: String,
    pub task_production_carrier_policy_digest: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ExternalPoolAdapterProviderActiveSuccessorActivationRoot {
    pub schema: String,
    pub canonicalization: String,
    pub digest_algorithm: String,
    pub activation_root_digest: String,
    pub activation_root: ExternalPoolAdapterProviderActiveSuccessorActivationRootEnvelope,
}
