use super::super::super::model::*;

const fn edge(
    id: &'static str,
    from: SourceNodeId,
    to: SourceNodeId,
    kind: EdgeKind,
    ops: &'static [PathOp],
    epoch: Epoch,
    reachability: Reachability,
    effect: SourceEffect,
) -> SourceEdge {
    SourceEdge {
        id,
        from,
        to,
        kind,
        ops,
        epoch,
        reachability,
        effect,
    }
}

pub(in super::super::super) const EDGES: &[SourceEdge] = &[
    edge(
        "lock.slot.entry",
        SourceNodeId::AbiLockSlot,
        SourceNodeId::AbiLockEntry,
        EdgeKind::Call,
        LOCK_OPS,
        Epoch::AbiInput,
        Reachability::Required,
        SourceEffect::None,
    ),
    edge(
        "lock.entry.validate",
        SourceNodeId::AbiLockEntry,
        SourceNodeId::AbiLockValidation,
        EdgeKind::Call,
        LOCK_OPS,
        Epoch::AbiInput,
        Reachability::Required,
        SourceEffect::None,
    ),
    edge(
        "lock.validate.raw",
        SourceNodeId::AbiLockValidation,
        SourceNodeId::AbiRawRun,
        EdgeKind::ConditionalCall,
        LOCK_OPS,
        Epoch::AbiInput,
        Reachability::Conditional,
        SourceEffect::None,
    ),
    edge(
        "lock.raw.dispatch",
        SourceNodeId::AbiLockRawGate,
        SourceNodeId::FileStateLock,
        EdgeKind::Continuation,
        LOCK_OPS,
        Epoch::AbiInput,
        Reachability::Conditional,
        SourceEffect::None,
    ),
    edge(
        "lock.dispatch.fixture-fault",
        SourceNodeId::FileStateLock,
        SourceNodeId::FixtureLockFault,
        EdgeKind::Call,
        LOCK_OPS,
        Epoch::AbiInput,
        Reachability::Required,
        SourceEffect::None,
    ),
    edge(
        "lock.fixture.controller",
        SourceNodeId::FixtureLockFault,
        SourceNodeId::FixtureFaultController,
        EdgeKind::Call,
        LOCK_OPS,
        Epoch::AbiInput,
        Reachability::Required,
        SourceEffect::None,
    ),
    edge(
        "lock.fixture.route",
        SourceNodeId::FixtureFaultController,
        SourceNodeId::RouteLockDelegate,
        EdgeKind::ConditionalCall,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Reachability::Conditional,
        SourceEffect::None,
    ),
    edge(
        "lock.route.test-bridge",
        SourceNodeId::RouteLockDelegate,
        SourceNodeId::TestBridgeLock,
        EdgeKind::Call,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Reachability::Required,
        SourceEffect::None,
    ),
    edge(
        "lock.test-bridge.adapter",
        SourceNodeId::TestBridgeLock,
        SourceNodeId::RegistryLockAdapter,
        EdgeKind::Call,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Reachability::Required,
        SourceEffect::None,
    ),
    edge(
        "lock.adapter.request",
        SourceNodeId::RegistryLockAdapter,
        SourceNodeId::ManagedLockRequest,
        EdgeKind::Call,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Reachability::Required,
        SourceEffect::None,
    ),
    edge(
        "lock.request.operation",
        SourceNodeId::ManagedLockRequest,
        SourceNodeId::RegistryLockOperation,
        EdgeKind::ConditionalCall,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Reachability::Conditional,
        SourceEffect::None,
    ),
    edge(
        "lock.operation.callback",
        SourceNodeId::RegistryLockOperation,
        SourceNodeId::RegistryCallbackBegin,
        EdgeKind::Call,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Reachability::Required,
        SourceEffect::CallbackLease,
    ),
    edge(
        "lock.custody.connection",
        SourceNodeId::RegistryShmCustodyGate,
        SourceNodeId::ManagedConnectionLock,
        EdgeKind::ConditionalCall,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Reachability::Conditional,
        SourceEffect::None,
    ),
];
