import type { UiTunerDocument, UiTunerElement, UiTunerElementKind } from './types'

const now = () => new Date().toISOString()

function element(
  id: string,
  name: string,
  kind: UiTunerElementKind,
  overrides: Partial<UiTunerElement>,
): UiTunerElement {
  return {
    id,
    name,
    kind,
    x: 24,
    y: 24,
    width: 160,
    height: 48,
    text: name,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: 600,
    letterSpacing: 0,
    paddingX: 12,
    paddingY: 10,
    borderRadius: 6,
    borderWidth: 1,
    color: '#f5f5f5',
    background: '#1f2023',
    borderColor: '#34363b',
    opacity: 1,
    ...overrides,
  }
}

export function createInitialTunerDocument(): UiTunerDocument {
  return {
    version: 1,
    updatedAt: now(),
    canvas: {
      name: '移动端首页板块',
      width: 390,
      height: 844,
      background: '#111317',
    },
    elements: [
      element('hero.kicker', '顶部标签', 'text', {
        x: 24,
        y: 34,
        width: 134,
        height: 30,
        text: '设计稿微调',
        fontSize: 13,
        lineHeight: 18,
        fontWeight: 700,
        paddingX: 12,
        paddingY: 6,
        borderRadius: 15,
        color: '#dff6e8',
        background: '#173a23',
        borderColor: '#2f7042',
      }),
      element('hero.title', '主标题', 'text', {
        x: 24,
        y: 86,
        width: 336,
        height: 92,
        text: '用鼠标把页面板块调到你觉得刚刚好',
        fontSize: 29,
        lineHeight: 37,
        fontWeight: 800,
        paddingX: 0,
        paddingY: 0,
        borderWidth: 0,
        color: '#f7f7f7',
        background: '#111317',
        borderColor: '#111317',
      }),
      element('hero.copy', '说明文字', 'text', {
        x: 24,
        y: 188,
        width: 330,
        height: 56,
        text: '选中任意板块后拖动位置，或在右侧面板微调字号、行高、内边距和圆角。',
        fontSize: 14,
        lineHeight: 22,
        fontWeight: 500,
        paddingX: 0,
        paddingY: 0,
        borderWidth: 0,
        color: '#b8b8b8',
        background: '#111317',
        borderColor: '#111317',
      }),
      element('hero.cta', '主按钮', 'button', {
        x: 24,
        y: 270,
        width: 164,
        height: 44,
        text: '保存这组尺寸',
        fontSize: 14,
        lineHeight: 20,
        fontWeight: 800,
        paddingX: 18,
        paddingY: 11,
        borderRadius: 6,
        color: '#000000',
        background: '#f5f5f5',
        borderColor: '#f5f5f5',
      }),
      element('metric.font', '字体卡片', 'card', {
        x: 24,
        y: 350,
        width: 158,
        height: 116,
        text: '标题字号\n29px / 37px',
        fontSize: 16,
        lineHeight: 24,
        fontWeight: 800,
        paddingX: 16,
        paddingY: 18,
        borderRadius: 8,
        color: '#f7f7f7',
        background: '#1d2228',
        borderColor: '#33404a',
      }),
      element('metric.gap', '间距卡片', 'card', {
        x: 208,
        y: 350,
        width: 158,
        height: 116,
        text: '模块间距\n24px 起',
        fontSize: 16,
        lineHeight: 24,
        fontWeight: 800,
        paddingX: 16,
        paddingY: 18,
        borderRadius: 8,
        color: '#fff6d6',
        background: '#2b2616',
        borderColor: '#5d4d1f',
      }),
      element('feature.panel', '功能板块', 'card', {
        x: 24,
        y: 504,
        width: 342,
        height: 148,
        text: '后续我会把你导出的 JSON 转成真实 CSS / Tailwind class / design token。',
        fontSize: 16,
        lineHeight: 25,
        fontWeight: 700,
        paddingX: 20,
        paddingY: 20,
        borderRadius: 8,
        color: '#ededed',
        background: '#202124',
        borderColor: '#34363b',
      }),
      element('footer.note', '底部提示', 'card', {
        x: 24,
        y: 690,
        width: 342,
        height: 92,
        text: '调完后点“复制参数”，我就能按你的手动微调结果落代码。',
        fontSize: 14,
        lineHeight: 22,
        fontWeight: 600,
        paddingX: 18,
        paddingY: 16,
        borderRadius: 8,
        color: '#d9d9d9',
        background: '#17191d',
        borderColor: '#2f3339',
      }),
    ],
  }
}

export function createBlankElement(kind: UiTunerElementKind, index: number): UiTunerElement {
  const baseName = kind === 'text' ? '文字' : kind === 'button' ? '按钮' : kind === 'media' ? '图片占位' : '卡片'
  return element(`custom.${kind}.${Date.now()}`, `${baseName} ${index}`, kind, {
    x: 36 + (index % 3) * 16,
    y: 36 + (index % 5) * 20,
    width: kind === 'text' ? 220 : 180,
    height: kind === 'text' ? 48 : kind === 'button' ? 42 : 112,
    text: kind === 'media' ? '图片/截图' : `${baseName} ${index}`,
    fontSize: kind === 'button' ? 14 : 16,
    lineHeight: kind === 'button' ? 20 : 24,
    fontWeight: kind === 'text' ? 700 : 600,
    paddingX: kind === 'text' ? 0 : 14,
    paddingY: kind === 'text' ? 0 : 12,
    borderWidth: kind === 'text' ? 0 : 1,
    color: kind === 'button' ? '#000000' : '#f5f5f5',
    background: kind === 'button' ? '#f5f5f5' : kind === 'text' ? '#111317' : '#202124',
    borderColor: kind === 'button' ? '#f5f5f5' : '#34363b',
  })
}
