use rusqlite::{Result, Row};

pub(super) struct StoredWorkAdmissionRow {
    pub work_admission_id: String,
    pub installation_id_digest: String,
    pub clock_epoch_digest: String,
    pub plugin_id: String,
    pub slot_ref: String,
    pub release_json: String,
    pub install_receipt_id: String,
    pub install_receipt_digest: String,
    pub promotion_receipt_id: String,
    pub promotion_receipt_digest: String,
    pub source_digest: String,
    pub plan_action: String,
    pub plan_id: String,
    pub plan_digest: String,
    pub signed_plan_envelope_digest: String,
    pub signed_manifest_set_digest: String,
    pub application_request_digest: String,
    pub application_receipt_digest: String,
    pub admission_bindings_digest: String,
    pub application_inventory_revision: i64,
    pub policy_revision: i64,
    pub sharing_authorization_ref: String,
    pub sharing_authorization_revision: i64,
    pub sharing_authorization_digest: String,
    pub policy_binding_receipt_digest: String,
    pub policy_revocation_receipt_digest: String,
    pub node_profile_digest: String,
    pub manifest_catalog_revision: i64,
    pub manifest_catalog_digest: String,
    pub manifest_catalog_binding_receipt_digest: String,
    pub keyring_bundle_revision: i64,
    pub publisher_keyring_revision: i64,
    pub publisher_keyring_digest: String,
    pub control_keyring_revision: i64,
    pub control_keyring_digest: String,
    pub plugin_version: String,
    pub publisher_id: String,
    pub manifest_digest: String,
    pub signed_manifest_envelope_digest: String,
    pub target_id: String,
    pub target_json: String,
    pub task_kinds_json: String,
    pub host_api_protocol_id: String,
    pub host_api_revision: i64,
    pub entrypoint_kind: String,
    pub entrypoint_relative_path: String,
    pub entrypoint_arguments_json: String,
    pub entrypoint_arguments_digest: String,
    pub health_check_json: String,
    pub runner_relative_path: String,
    pub runner_file_digest: String,
    pub runner_file_size_bytes: i64,
    pub runner_file_executable: bool,
    pub grant_ref: String,
    pub permission_grant_digest: String,
    pub granted_permissions_json: String,
    pub authorized_max_cpu_millicores: i64,
    pub authorized_max_memory_bytes: i64,
    pub authorized_max_vram_bytes: i64,
    pub authorized_max_disk_bytes: i64,
    pub authorized_max_processes: i64,
    pub authorized_max_sidecar_uptime_seconds: i64,
    pub install_generation: i64,
    pub activation_generation: i64,
    pub runtime_generation: i64,
    pub work_admission_generation_before: i64,
    pub work_admission_generation_after: i64,
    pub previous_work_admission_id: Option<String>,
    pub previous_work_admission_receipt_digest: Option<String>,
    pub desired_presence: String,
    pub desired_activation: String,
    pub slot_phase: String,
    pub admission: String,
    pub runtime_phase: String,
    pub candidate_slot_present: bool,
    pub runtime_slot_present: bool,
    pub runtime_runner_digest_present: bool,
    pub health_present: bool,
    pub active_attempts: i64,
    pub authority_state_revision_before: i64,
    pub authority_state_revision_after: i64,
    pub inventory_revision_before: i64,
    pub inventory_revision_after: i64,
    pub inventory_digest_before: String,
    pub inventory_digest_after: String,
    pub authority_epoch_before: i64,
    pub authority_epoch_after: i64,
    pub process_owner_epoch: i64,
    pub trusted_time_before_ms: i64,
    pub authority_updated_at_ms_before: i64,
    pub admitted_at_ms: i64,
    pub source_json: String,
    pub receipt_json: String,
    pub receipt_digest: String,
}

impl StoredWorkAdmissionRow {
    pub(super) fn read(row: &Row<'_>) -> Result<Self> {
        Ok(Self {
            work_admission_id: row.get(0)?,
            installation_id_digest: row.get(1)?,
            clock_epoch_digest: row.get(2)?,
            plugin_id: row.get(3)?,
            slot_ref: row.get(4)?,
            release_json: row.get(5)?,
            install_receipt_id: row.get(6)?,
            install_receipt_digest: row.get(7)?,
            promotion_receipt_id: row.get(8)?,
            promotion_receipt_digest: row.get(9)?,
            source_digest: row.get(10)?,
            plan_action: row.get(11)?,
            plan_id: row.get(12)?,
            plan_digest: row.get(13)?,
            signed_plan_envelope_digest: row.get(14)?,
            signed_manifest_set_digest: row.get(15)?,
            application_request_digest: row.get(16)?,
            application_receipt_digest: row.get(17)?,
            admission_bindings_digest: row.get(18)?,
            application_inventory_revision: row.get(19)?,
            policy_revision: row.get(20)?,
            sharing_authorization_ref: row.get(21)?,
            sharing_authorization_revision: row.get(22)?,
            sharing_authorization_digest: row.get(23)?,
            policy_binding_receipt_digest: row.get(24)?,
            policy_revocation_receipt_digest: row.get(25)?,
            node_profile_digest: row.get(26)?,
            manifest_catalog_revision: row.get(27)?,
            manifest_catalog_digest: row.get(28)?,
            manifest_catalog_binding_receipt_digest: row.get(29)?,
            keyring_bundle_revision: row.get(30)?,
            publisher_keyring_revision: row.get(31)?,
            publisher_keyring_digest: row.get(32)?,
            control_keyring_revision: row.get(33)?,
            control_keyring_digest: row.get(34)?,
            plugin_version: row.get(35)?,
            publisher_id: row.get(36)?,
            manifest_digest: row.get(37)?,
            signed_manifest_envelope_digest: row.get(38)?,
            target_id: row.get(39)?,
            target_json: row.get(40)?,
            task_kinds_json: row.get(41)?,
            host_api_protocol_id: row.get(42)?,
            host_api_revision: row.get(43)?,
            entrypoint_kind: row.get(44)?,
            entrypoint_relative_path: row.get(45)?,
            entrypoint_arguments_json: row.get(46)?,
            entrypoint_arguments_digest: row.get(47)?,
            health_check_json: row.get(48)?,
            runner_relative_path: row.get(49)?,
            runner_file_digest: row.get(50)?,
            runner_file_size_bytes: row.get(51)?,
            runner_file_executable: row.get(52)?,
            grant_ref: row.get(53)?,
            permission_grant_digest: row.get(54)?,
            granted_permissions_json: row.get(55)?,
            authorized_max_cpu_millicores: row.get(56)?,
            authorized_max_memory_bytes: row.get(57)?,
            authorized_max_vram_bytes: row.get(58)?,
            authorized_max_disk_bytes: row.get(59)?,
            authorized_max_processes: row.get(60)?,
            authorized_max_sidecar_uptime_seconds: row.get(61)?,
            install_generation: row.get(62)?,
            activation_generation: row.get(63)?,
            runtime_generation: row.get(64)?,
            work_admission_generation_before: row.get(65)?,
            work_admission_generation_after: row.get(66)?,
            previous_work_admission_id: row.get(67)?,
            previous_work_admission_receipt_digest: row.get(68)?,
            desired_presence: row.get(69)?,
            desired_activation: row.get(70)?,
            slot_phase: row.get(71)?,
            admission: row.get(72)?,
            runtime_phase: row.get(73)?,
            candidate_slot_present: row.get(74)?,
            runtime_slot_present: row.get(75)?,
            runtime_runner_digest_present: row.get(76)?,
            health_present: row.get(77)?,
            active_attempts: row.get(78)?,
            authority_state_revision_before: row.get(79)?,
            authority_state_revision_after: row.get(80)?,
            inventory_revision_before: row.get(81)?,
            inventory_revision_after: row.get(82)?,
            inventory_digest_before: row.get(83)?,
            inventory_digest_after: row.get(84)?,
            authority_epoch_before: row.get(85)?,
            authority_epoch_after: row.get(86)?,
            process_owner_epoch: row.get(87)?,
            trusted_time_before_ms: row.get(88)?,
            authority_updated_at_ms_before: row.get(89)?,
            admitted_at_ms: row.get(90)?,
            source_json: row.get(91)?,
            receipt_json: row.get(92)?,
            receipt_digest: row.get(93)?,
        })
    }
}
