CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_registry_releases (
  registry_release_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 200),
  registry_release_schema TEXT NOT NULL CHECK(registry_release_schema='compute_federation.external_pool_adapter_registry_release_receipt.v1'),
  registry_release_digest TEXT NOT NULL UNIQUE CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json) AND json_type(receipt_json)='object' AND length(CAST(receipt_json AS BLOB))<=1048576),
  registry_release_material_digest TEXT NOT NULL UNIQUE CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  admission_id TEXT NOT NULL,
  admission_digest TEXT NOT NULL CHECK(length(admission_digest)=64 AND admission_digest NOT GLOB '*[^0-9a-f]*'),
  package_receipt_id TEXT NOT NULL,
  package_receipt_digest TEXT NOT NULL CHECK(length(package_receipt_digest)=64 AND package_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  package_material_digest TEXT NOT NULL CHECK(length(package_material_digest)=64 AND package_material_digest NOT GLOB '*[^0-9a-f]*'),
  source_receipt_id TEXT NOT NULL,
  source_receipt_digest TEXT NOT NULL CHECK(length(source_receipt_digest)=64 AND source_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  adapter_id TEXT NOT NULL CHECK(length(trim(adapter_id)) BETWEEN 1 AND 200),
  release_version TEXT NOT NULL CHECK(length(trim(release_version)) BETWEEN 1 AND 200),
  route_kind TEXT NOT NULL CHECK(route_kind='server_adapter'),
  supported_provider_kinds_json TEXT NOT NULL CHECK(supported_provider_kinds_json='["external_pool"]'),
  implementation_digest TEXT NOT NULL CHECK(length(implementation_digest)=64 AND implementation_digest NOT GLOB '*[^0-9a-f]*'),
  declared_implementation_sha256 TEXT NOT NULL CHECK(length(declared_implementation_sha256)=64 AND declared_implementation_sha256 NOT GLOB '*[^0-9a-f]*'),
  supported_capabilities_json TEXT NOT NULL CHECK(json_valid(supported_capabilities_json) AND json_type(supported_capabilities_json)='array' AND json_array_length(supported_capabilities_json)=6 AND length(CAST(supported_capabilities_json AS BLOB))<=65536),
  capability_set_digest TEXT NOT NULL CHECK(length(capability_set_digest)=64 AND capability_set_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_json TEXT NOT NULL CHECK(json_valid(credential_verifier_json) AND json_type(credential_verifier_json)='object' AND length(CAST(credential_verifier_json AS BLOB))<=65536),
  credential_verifier_digest TEXT NOT NULL CHECK(length(credential_verifier_digest)=64 AND credential_verifier_digest NOT GLOB '*[^0-9a-f]*'),
  archive_sha256 TEXT NOT NULL CHECK(length(archive_sha256)=64 AND archive_sha256 NOT GLOB '*[^0-9a-f]*'),
  archive_size_bytes INTEGER NOT NULL CHECK(typeof(archive_size_bytes)='integer' AND archive_size_bytes BETWEEN 1 AND 33554432),
  manifest_canonical_json TEXT NOT NULL CHECK(json_valid(manifest_canonical_json) AND json_type(manifest_canonical_json)='object' AND length(CAST(manifest_canonical_json AS BLOB))<=65536),
  manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'),
  entry_inventory_digest TEXT NOT NULL CHECK(length(entry_inventory_digest)=64 AND entry_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  entry_count INTEGER NOT NULL CHECK(typeof(entry_count)='integer' AND entry_count BETWEEN 1 AND 128),
  total_uncompressed_bytes INTEGER NOT NULL CHECK(typeof(total_uncompressed_bytes)='integer' AND total_uncompressed_bytes BETWEEN 1 AND 67108864),
  registered_at TEXT NOT NULL CHECK(registered_at GLOB '????-??-??T??:??:??.?????????Z' AND length(registered_at)=30 AND julianday(registered_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=registered_at),
  registry_effect TEXT NOT NULL CHECK(registry_effect='provider_neutral_release_registered'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  CHECK(implementation_digest=declared_implementation_sha256 AND implementation_digest=archive_sha256),
  UNIQUE(adapter_id,release_version),
  FOREIGN KEY(admission_id) REFERENCES compute_external_pool_adapter_release_admissions(admission_id) ON DELETE RESTRICT,
  FOREIGN KEY(package_receipt_id) REFERENCES compute_external_pool_adapter_artifact_package_receipts(package_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(source_receipt_id) REFERENCES compute_external_pool_adapter_artifact_source_receipts(source_receipt_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_registry_provider_bindings (
  provider_binding_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 200),
  provider_binding_schema TEXT NOT NULL CHECK(provider_binding_schema='compute_federation.external_pool_adapter_registry_provider_binding_receipt.v1'),
  provider_binding_digest TEXT NOT NULL UNIQUE CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json) AND json_type(receipt_json)='object' AND length(CAST(receipt_json AS BLOB))<=1048576),
  provider_binding_material_digest TEXT NOT NULL UNIQUE CHECK(length(provider_binding_material_digest)=64 AND provider_binding_material_digest NOT GLOB '*[^0-9a-f]*'),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  registry_release_id TEXT NOT NULL,
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL UNIQUE CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 200),
  installation_receipt_id TEXT NOT NULL UNIQUE,
  installation_receipt_digest TEXT NOT NULL CHECK(length(installation_receipt_digest)=64 AND installation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  installation_material_digest TEXT NOT NULL CHECK(length(installation_material_digest)=64 AND installation_material_digest NOT GLOB '*[^0-9a-f]*'),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  application_id TEXT NOT NULL,
  application_digest TEXT NOT NULL CHECK(length(application_digest)=64 AND application_digest NOT GLOB '*[^0-9a-f]*'),
  adoption_receipt_id TEXT NOT NULL,
  adoption_receipt_digest TEXT NOT NULL CHECK(length(adoption_receipt_digest)=64 AND adoption_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  adoption_material_digest TEXT NOT NULL CHECK(length(adoption_material_digest)=64 AND adoption_material_digest NOT GLOB '*[^0-9a-f]*'),
  provider_id TEXT NOT NULL,
  provider_owner_account_id TEXT NOT NULL,
  provider_policy_revision INTEGER NOT NULL CHECK(typeof(provider_policy_revision)='integer' AND provider_policy_revision>0),
  provider_digest TEXT NOT NULL CHECK(length(provider_digest)=64 AND provider_digest NOT GLOB '*[^0-9a-f]*'),
  adapter_id TEXT NOT NULL,
  release_version TEXT NOT NULL,
  adapter_config_revision INTEGER NOT NULL CHECK(typeof(adapter_config_revision)='integer' AND adapter_config_revision>0),
  adapter_config_digest TEXT NOT NULL CHECK(length(trim(adapter_config_digest)) BETWEEN 1 AND 512),
  admission_id TEXT NOT NULL,
  admission_digest TEXT NOT NULL CHECK(length(admission_digest)=64 AND admission_digest NOT GLOB '*[^0-9a-f]*'),
  package_receipt_id TEXT NOT NULL,
  package_receipt_digest TEXT NOT NULL CHECK(length(package_receipt_digest)=64 AND package_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  package_material_digest TEXT NOT NULL CHECK(length(package_material_digest)=64 AND package_material_digest NOT GLOB '*[^0-9a-f]*'),
  source_receipt_id TEXT NOT NULL,
  source_receipt_digest TEXT NOT NULL CHECK(length(source_receipt_digest)=64 AND source_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_conformance_receipt_id TEXT NOT NULL,
  sandbox_conformance_receipt_digest TEXT NOT NULL CHECK(length(sandbox_conformance_receipt_digest)=64 AND sandbox_conformance_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verification_receipt_id TEXT NOT NULL,
  credential_verification_receipt_digest TEXT NOT NULL CHECK(length(credential_verification_receipt_digest)=64 AND credential_verification_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  credential_locator_commitment TEXT NOT NULL CHECK(length(credential_locator_commitment)=64 AND credential_locator_commitment NOT GLOB '*[^0-9a-f]*'),
  bound_by_admin_user_id TEXT NOT NULL CHECK(length(trim(bound_by_admin_user_id)) BETWEEN 1 AND 200),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_registry_binding'),
  checked_at TEXT NOT NULL CHECK(checked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(checked_at)=30 AND julianday(checked_at) IS NOT NULL),
  bound_at TEXT NOT NULL CHECK(bound_at=checked_at),
  recorded_at TEXT NOT NULL CHECK(recorded_at=checked_at),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240),
  registry_effect TEXT NOT NULL CHECK(registry_effect='installed_instance_companion_recorded'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  UNIQUE(registry_release_id,provider_id),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(installation_receipt_id) REFERENCES compute_external_pool_adapter_installation_receipts(installation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(adoption_receipt_id) REFERENCES compute_external_pool_adapter_adoption_receipts(adoption_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(application_id) REFERENCES compute_external_pool_onboarding_applications(application_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT,
  FOREIGN KEY(package_receipt_id) REFERENCES compute_external_pool_adapter_artifact_package_receipts(package_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(source_receipt_id) REFERENCES compute_external_pool_adapter_artifact_source_receipts(source_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(sandbox_conformance_receipt_id) REFERENCES compute_external_pool_adapter_sandbox_conformance_reports(sandbox_conformance_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(credential_verification_receipt_id) REFERENCES compute_external_pool_adapter_credential_verification_receipts(credential_verification_receipt_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_registry_release_time ON compute_external_pool_adapter_registry_releases(registered_at DESC,registry_release_id);
CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_registry_binding_provider ON compute_external_pool_adapter_registry_provider_bindings(provider_id,bound_at DESC,provider_binding_id);
