//! Typed, source-only recursive request and resolution plans before the first wave dispatch.
//!
//! These values contain only immutable plan material and typed ordinal references. They never own
//! a namespace grant, directory handle, candidate or content lease. Real owners remain in the
//! accumulated custody graph and can be reached only by a future consuming advancer.

use std::convert::Infallible;

use super::super::super::{WindowsLoaderModuleNode, WindowsPostLeaseModuleEdgeLocator};
use super::super::{WindowsPostLeaseSystemImageParseReceipt, WindowsRecursiveImageOwnerRef};

#[derive(PartialEq, Eq)]
pub(super) enum WindowsRecursiveRequestImportKind {
    Normal,
    Delay,
    Forwarder,
}

/// One parser-authenticated edge in canonical source-frontier/local-edge order.
pub(super) struct WindowsRecursiveParsedEdgeRequest {
    pub(super) module_request_ordinal: usize,
    pub(super) global_import_edge_ordinal: usize,
    pub(super) source_parse_receipt_ordinal: usize,
    pub(super) importer_parsed_image_ordinal: usize,
    pub(super) importer: WindowsLoaderModuleNode,
    pub(super) importer_graph_edge_ordinal: usize,
    pub(super) edge_locator: WindowsPostLeaseModuleEdgeLocator,
    pub(super) import_kind: WindowsRecursiveRequestImportKind,
    pub(super) normalized_requested_name: String,
    pub(super) imported_symbol_name: Option<String>,
    pub(super) imported_symbol_ordinal: Option<u16>,
    pub(super) ordered_search_step_ordinals: Vec<usize>,
    pub(super) edge_request_binding_digest: String,
}

/// Direct typed evidence for one source-frontier parse receipt. Keeping only its ordinal would let
/// an otherwise well-shaped request plan splice a receipt from another wave, owner or parser.
pub(super) struct WindowsRecursiveSourceFrontierPlanEntry {
    pub(super) parse_receipt_ordinal: usize,
    pub(super) receipt_digest: String,
    pub(super) wave_ordinal: usize,
    pub(super) producer_acquisition_receipt_ordinal: usize,
    pub(super) producer_module_request_ordinal: usize,
    pub(super) parsed_image_ordinal: usize,
    pub(super) node: WindowsLoaderModuleNode,
    pub(super) source_owner: WindowsRecursiveImageOwnerRef,
    pub(super) source_owner_binding_digest: String,
    pub(super) image_material_identity_digest: String,
    pub(super) parser_policy_digest: String,
    pub(super) import_table_digest: String,
    pub(super) normal_import_count: usize,
    pub(super) delay_import_count: usize,
    pub(super) forwarder_count: usize,
}

/// Exact wave-zero parsed-image/package-file cross-binding retained by the whole custody graph.
/// Parsed-image and package-file ordinals are deliberately separate coordinates.
pub(super) struct WindowsRecursiveBaseParsedImageOwnerPlanEntry {
    pub(super) prelease_parsed_image_ordinal: usize,
    pub(super) package_file_ordinal: usize,
    pub(super) file_identity_digest: String,
    pub(super) postlease_parsed_image_ordinal: usize,
    pub(super) postlease_image_material_identity_digest: String,
    pub(super) lease_generation_digest: String,
    pub(super) source_owner_binding_digest: String,
}

#[derive(PartialEq, Eq)]
pub(super) struct WindowsRecursiveForwarderSymbolRef {
    pub(super) name: Option<String>,
    pub(super) ordinal: Option<u16>,
}

#[derive(PartialEq, Eq)]
pub(super) struct WindowsRecursiveForwarderTargetRef {
    pub(super) node: WindowsLoaderModuleNode,
    pub(super) symbol: WindowsRecursiveForwarderSymbolRef,
}

/// Exact cumulative state of one direct-import-rooted forwarder chain before this producer wave.
/// The root target is the first visited entry, so `next_hop_ordinal + 1 == visited_targets.len()`.
pub(super) struct WindowsRecursiveRetainedForwarderChainPlanEntry {
    pub(super) source_import_edge_ordinal: usize,
    pub(super) next_hop_ordinal: usize,
    pub(super) current_target: WindowsRecursiveForwarderTargetRef,
    pub(super) visited_targets: Vec<WindowsRecursiveForwarderTargetRef>,
    pub(super) chain_binding_digest: String,
}

/// Canonical request range generated by one already-parsed recursive producer frontier.
///
/// `A0` continues to use the existing typed GrantReady plan. This plan therefore starts at
/// producer wave one and cannot be used to manufacture a second wave-zero path.
#[must_use = "recursive request plan must remain in its whole-wave custody"]
pub(in crate::node_agent_compute_plugin_host::runtime_loader_load_set) struct WindowsRecursiveWaveRequestPlan
{
    pub(super) producer_wave_ordinal: usize,
    pub(super) previous_acquisition_receipt_digest: String,
    pub(super) input_custody_digest: String,
    pub(super) authenticated_recursive_policy_digest: String,
    pub(super) source_frontier: Vec<WindowsRecursiveSourceFrontierPlanEntry>,
    pub(super) first_module_request_ordinal: usize,
    pub(super) module_requests: Vec<WindowsRecursiveParsedEdgeRequest>,
    pub(super) first_searched_name_ordinal: usize,
    pub(super) first_system_image_request_ordinal: usize,
    pub(super) parser_policy_digest: String,
    pub(super) source_request_plan_digest: String,
    pub(super) _canonical_request_plan_producer_unavailable: Infallible,
}

#[derive(PartialEq, Eq)]
pub(super) enum WindowsRecursiveFilesystemUseRoute {
    OrdinaryFilesystem,
    SideBySide,
}

/// Exact ultimate owner route. API-set is deliberately not a variant: it is a one-hop terminal
/// indirection to one of the system-owner variants below, so nested API-set resolution is
/// unrepresentable. Side-by-side remains an acquisition route for a filesystem owner, not a fifth
/// kind of immutable owner.
#[derive(PartialEq, Eq)]
pub(super) enum WindowsRecursiveRouteOwnerRef {
    PackageContentLease {
        package_file_ordinal: usize,
    },
    AuthenticatedPreloadedModule {
        preloaded_module_ordinal: usize,
    },
    KnownDllSection {
        known_dll_authority_record_ordinal: usize,
    },
    ResolvedFilesystemSystemImage {
        resolution_request_ordinal: usize,
        route: WindowsRecursiveFilesystemUseRoute,
    },
}

impl WindowsRecursiveRouteOwnerRef {
    pub(super) fn matches_image_owner(&self, owner: &WindowsRecursiveImageOwnerRef) -> bool {
        match (self, owner) {
            (
                Self::PackageContentLease {
                    package_file_ordinal: left,
                },
                WindowsRecursiveImageOwnerRef::PackageContentLease {
                    package_file_ordinal: right,
                },
            ) => left == right,
            (
                Self::AuthenticatedPreloadedModule {
                    preloaded_module_ordinal: left,
                },
                WindowsRecursiveImageOwnerRef::AuthenticatedPreloadedModule {
                    preloaded_module_ordinal: right,
                },
            ) => left == right,
            (
                Self::KnownDllSection {
                    known_dll_authority_record_ordinal: left,
                },
                WindowsRecursiveImageOwnerRef::KnownDllSection {
                    known_dll_authority_record_ordinal: right,
                },
            ) => left == right,
            (
                Self::ResolvedFilesystemSystemImage {
                    resolution_request_ordinal: left,
                    ..
                },
                WindowsRecursiveImageOwnerRef::ResolvedFilesystemSystemImage {
                    resolution_request_ordinal: right,
                },
            ) => left == right,
            _ => false,
        }
    }
}

/// API-set hosts cannot be package files and cannot recursively be API-set contracts.
#[derive(PartialEq, Eq)]
pub(super) enum WindowsRecursiveApiSetHostOwnerRef {
    AuthenticatedPreloadedModule {
        preloaded_module_ordinal: usize,
    },
    KnownDllSection {
        known_dll_authority_record_ordinal: usize,
    },
    ResolvedFilesystemSystemImage {
        resolution_request_ordinal: usize,
        route: WindowsRecursiveFilesystemUseRoute,
    },
}

#[derive(PartialEq, Eq)]
pub(super) enum WindowsRecursiveModuleTerminalRef {
    Direct {
        owner: WindowsRecursiveRouteOwnerRef,
    },
    ApiSetHost {
        normalized_contract_name: String,
        normalized_host_module_cache_key: String,
        host_component_identity_digest: String,
        host_owner: WindowsRecursiveApiSetHostOwnerRef,
        os_build_identity_digest: String,
        schema_identity_digest: String,
        contract_host_binding_set_digest: String,
        resolution_binding_digest: String,
    },
}

pub(super) struct WindowsRecursiveModuleResolutionPlanEntry {
    pub(super) module_request_ordinal: usize,
    pub(super) searched_name_ordinals: Vec<usize>,
    pub(super) terminal: WindowsRecursiveModuleTerminalRef,
    pub(super) resolution_binding_digest: String,
}

/// Positive Shadow is absent by construction. Earlier successful names do not mint a second
/// positive grant or a detached alias authority in policy V1.
#[derive(PartialEq, Eq)]
pub(super) enum WindowsRecursiveSearchedNameDisposition {
    MustRemainAbsent,
    Terminal {
        terminal: WindowsRecursiveModuleTerminalRef,
    },
}

pub(super) struct WindowsRecursiveSearchedNamePlanEntry {
    pub(super) searched_name_ordinal: usize,
    pub(super) module_request_ordinal: usize,
    pub(super) step_position: usize,
    pub(super) search_directory_ordinal: usize,
    pub(super) normalized_name: String,
    pub(super) search_directory_authority_binding_digest: String,
    pub(super) disposition: WindowsRecursiveSearchedNameDisposition,
    pub(super) grant_request_digest: String,
    pub(super) disposition_binding_digest: String,
}

pub(super) struct WindowsRecursiveFilesystemImageUse {
    pub(super) module_request_ordinal: usize,
    pub(super) searched_name_ordinal: usize,
    pub(super) search_directory_ordinal: usize,
    pub(super) normalized_name: String,
    pub(super) search_directory_authority_binding_digest: String,
    pub(super) route: WindowsRecursiveFilesystemUseRoute,
}

/// Exact pre-candidate filesystem acquisition request. A retained candidate is intentionally not
/// present; it may first appear only after every planned searched-name grant has succeeded.
pub(super) struct WindowsRecursiveFilesystemImageRequestPlanEntry {
    pub(super) resolution_request_ordinal: usize,
    pub(super) canonical_dedupe_ordinal: usize,
    pub(super) primary_use_ordinal: usize,
    pub(super) normalized_name: String,
    pub(super) search_directory_authority_binding_digest: String,
    pub(super) resolved_component_identity_digest: String,
    pub(super) expected_file_identity_digest: String,
    pub(super) concrete_servicing_generation_digest: String,
    pub(super) code_integrity_evidence_digest: String,
    pub(super) servicing_resolution_receipt_digest: String,
    pub(super) namespace_alias_currentness_receipt_digest: String,
    pub(super) candidate_binding_digest: String,
    pub(super) uses: Vec<WindowsRecursiveFilesystemImageUse>,
    pub(super) lease_request_digest: String,
}

#[derive(PartialEq, Eq)]
pub(super) enum WindowsRecursiveTargetParseDisposition {
    AlreadyParsed {
        parsed_image_ordinal: usize,
    },
    NextFrontier {
        parse_receipt_ordinal: usize,
        target_parse_wave_ordinal: usize,
    },
}

/// Canonical unique target/owner queue, ordered by its earliest producer request.
pub(super) struct WindowsRecursiveRouteOwnerPlanEntry {
    pub(super) route_owner_ordinal: usize,
    pub(super) earliest_producer_module_request_ordinal: usize,
    pub(super) target: WindowsLoaderModuleNode,
    pub(super) resolved_module_cache_key: String,
    pub(super) owner: WindowsRecursiveRouteOwnerRef,
    pub(super) expected_source_owner_binding_digest: String,
    pub(super) expected_image_material_identity_digest: String,
    pub(super) parse_disposition: WindowsRecursiveTargetParseDisposition,
    pub(super) route_owner_binding_digest: String,
}

/// Scalar borrow keys for retained search-directory owners in the accumulated graph. These are
/// not handles and cannot substitute for the root custody that owns those directories.
pub(super) struct WindowsRecursiveRetainedSearchDirectoryAuthorityRef {
    pub(super) search_directory_ordinal: usize,
    pub(super) directory_identity_digest: String,
    pub(super) authority_binding_digest: String,
}

/// Authenticated terminal/disposition plan for exactly one recursive producer request range.
#[must_use = "resolved recursive plan must move with all grants and route-specific owners"]
pub(in crate::node_agent_compute_plugin_host::runtime_loader_load_set) struct AuthenticatedWindowsRecursiveWaveResolutionPlan
{
    pub(super) producer_wave_ordinal: usize,
    pub(super) authenticated_recursive_policy_digest: String,
    pub(super) parser_policy_digest: String,
    pub(super) source_request_plan_digest: String,
    pub(super) module_resolutions: Vec<WindowsRecursiveModuleResolutionPlanEntry>,
    pub(super) searched_name_dispositions: Vec<WindowsRecursiveSearchedNamePlanEntry>,
    pub(super) filesystem_image_requests: Vec<WindowsRecursiveFilesystemImageRequestPlanEntry>,
    pub(super) route_owners: Vec<WindowsRecursiveRouteOwnerPlanEntry>,
    pub(super) terminal_resolution_set_digest: String,
    pub(super) searched_name_disposition_set_digest: String,
    pub(super) filesystem_request_set_digest: String,
    pub(super) route_owner_set_digest: String,
    pub(super) resolved_plan_digest: String,
    pub(super) _authenticated_wave_resolver_unavailable: Infallible,
}

pub(super) struct WindowsRecursiveWaveDispatchPlanEvidence {
    pub(super) producer_wave_ordinal: usize,
    pub(super) previous_acquisition_receipt_digest: String,
    pub(super) input_custody_digest: String,
    pub(super) authenticated_recursive_policy_digest: String,
    pub(super) parser_policy_digest: String,
    pub(super) source_frontier: Vec<WindowsRecursiveSourceFrontierPlanEntry>,
    pub(super) first_module_request_ordinal: usize,
    pub(super) module_requests: Vec<WindowsRecursiveParsedEdgeRequest>,
    pub(super) first_searched_name_ordinal: usize,
    pub(super) first_system_image_request_ordinal: usize,
    pub(super) module_resolutions: Vec<WindowsRecursiveModuleResolutionPlanEntry>,
    pub(super) searched_name_dispositions: Vec<WindowsRecursiveSearchedNamePlanEntry>,
    pub(super) filesystem_image_requests: Vec<WindowsRecursiveFilesystemImageRequestPlanEntry>,
    pub(super) route_owners: Vec<WindowsRecursiveRouteOwnerPlanEntry>,
    pub(super) request_plan_digest: String,
    pub(super) terminal_resolution_set_digest: String,
    pub(super) searched_name_disposition_set_digest: String,
    pub(super) filesystem_request_set_digest: String,
    pub(super) route_owner_set_digest: String,
    pub(super) resolved_plan_digest: String,
    pub(super) validated_plan_evidence_digest: String,
}

impl WindowsRecursiveSourceFrontierPlanEntry {
    pub(super) fn matches_receipt(
        &self,
        receipt: &WindowsPostLeaseSystemImageParseReceipt,
    ) -> bool {
        self.parse_receipt_ordinal == receipt.parse_receipt_ordinal
            && self.receipt_digest == receipt.receipt_digest
            && self.wave_ordinal == receipt.wave_ordinal
            && self.producer_acquisition_receipt_ordinal
                == receipt.producer_acquisition_receipt_ordinal
            && self.producer_module_request_ordinal == receipt.producer_module_request_ordinal
            && self.parsed_image_ordinal == receipt.parsed_image_ordinal
            && self.node == receipt.node
            && self.source_owner == receipt.source_owner
            && self.source_owner_binding_digest == receipt.source_owner_binding_digest
            && self.image_material_identity_digest == receipt.image_material_identity_digest
            && self.parser_policy_digest == receipt.parser_policy_digest
            && self.import_table_digest == receipt.import_table_digest
            && self.normal_import_count == receipt.normal_import_count
            && self.delay_import_count == receipt.delay_import_count
            && self.forwarder_count == receipt.forwarder_count
    }
}
