use super::super::model::*;

const fn node(
    id: SourceNodeId,
    owner: SourceOwnerId,
    symbol: &'static str,
    role: NodeRole,
    ops: &'static [PathOp],
    epoch: Epoch,
    boundary: Boundary,
) -> SourceNode {
    SourceNode {
        id,
        owner,
        symbol,
        role,
        ops,
        epoch,
        boundary,
        state_witness: None,
    }
}

pub(in super::super) const NODES: &[SourceNode] = &[
    node(
        SourceNodeId::AbiLockSlot,
        SourceOwnerId::SqliteVfsAbiTable,
        "xShmLock: Some(io_shm::lock)",
        NodeRole::Entry,
        LOCK_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiLockEntry,
        SourceOwnerId::AbiIoShm,
        "unsafe extern \"C\" fn lock",
        NodeRole::Entry,
        LOCK_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiLockValidation,
        SourceOwnerId::AbiIoShm,
        "fn shm_lock_action",
        NodeRole::ManagedValidation,
        LOCK_OPS,
        Epoch::AbiInput,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::FileStateLock,
        SourceOwnerId::AbiFileState,
        "pub(super) fn shm_lock",
        NodeRole::Adapter,
        LOCK_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::FixtureLockFault,
        SourceOwnerId::FixtureFaultFile,
        "fn shm_lock",
        NodeRole::FaultWrapper,
        LOCK_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RouteLockDelegate,
        SourceOwnerId::FixtureRouteFile,
        "fn shm_lock",
        NodeRole::Adapter,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::TestBridgeLock,
        SourceOwnerId::RegistryTestBridge,
        "fn shm_lock",
        NodeRole::Adapter,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryLockAdapter,
        SourceOwnerId::RegistryAbiFile,
        "fn shm_lock",
        NodeRole::Adapter,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedLockRequest,
        SourceOwnerId::ManagedTypes,
        "fn new",
        NodeRole::ManagedValidation,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::RegistryLockOperation,
        SourceOwnerId::RegistryOperations,
        "fn shm_lock",
        NodeRole::ManagedOperation,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedConnectionLock,
        SourceOwnerId::ManagedLocking,
        "pub(crate) fn lock",
        NodeRole::ManagedOperation,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedPlatformModuleSelect,
        SourceOwnerId::ManagedFsRoot,
        "#[path = \"node_agent_managed_fs/windows.rs\"]",
        NodeRole::PlatformSeam,
        ALL_OPS,
        Epoch::PlatformBinding,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedWindowsLockingExport,
        SourceOwnerId::ManagedWindowsPlatform,
        "mod sqlite_locking",
        NodeRole::PlatformSeam,
        ALL_OPS,
        Epoch::PlatformBinding,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedLockCoordinator,
        SourceOwnerId::ManagedLocking,
        "fn lock_connection",
        NodeRole::ManagedOperation,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockLocalGate,
        SourceOwnerId::ManagedLocking,
        "fn sibling_masks",
        NodeRole::ManagedValidation,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockAcquireGate,
        SourceOwnerId::ManagedLocking,
        "fn require_unlocked",
        NodeRole::ManagedValidation,
        ACQUIRE_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockSharedReleaseGate,
        SourceOwnerId::ManagedLocking,
        "ManagedSqliteShmLockAction::UnlockShared =>",
        NodeRole::ManagedValidation,
        UNLOCK_SHARED_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockExclusiveReleaseGate,
        SourceOwnerId::ManagedLocking,
        "ManagedSqliteShmLockAction::UnlockExclusive =>",
        NodeRole::ManagedValidation,
        UNLOCK_EXCLUSIVE_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockAcquire,
        SourceOwnerId::ManagedLocking,
        "fn try_os_lock",
        NodeRole::ManagedOperation,
        ACQUIRE_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockRelease,
        SourceOwnerId::ManagedLocking,
        "fn unlock_os_range",
        NodeRole::ManagedOperation,
        UNLOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockLocalSharedMasks,
        SourceOwnerId::ManagedLocking,
        "held.shared_mask",
        NodeRole::ManagedOperation,
        SHARED_LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockPlatformSharedMasks,
        SourceOwnerId::ManagedLocking,
        "held.shared_mask",
        NodeRole::ManagedOperation,
        SHARED_LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockPlatformExclusiveMasks,
        SourceOwnerId::ManagedLocking,
        "held.exclusive_mask",
        NodeRole::ManagedOperation,
        EXCLUSIVE_LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedLockExclusiveRanges,
        SourceOwnerId::ManagedLocking,
        "held.exclusive_ranges",
        NodeRole::ManagedOperation,
        EXCLUSIVE_LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::RegistryLockProjection,
        SourceOwnerId::RegistryAbiFile,
        "ManagedSqliteShmLockAttempt::Acquired",
        NodeRole::AbiProjection,
        LOCK_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryLockBusyProjection,
        SourceOwnerId::RegistryAbiFile,
        "ManagedSqliteShmLockAttempt::Contended",
        NodeRole::AbiProjection,
        ACQUIRE_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiLockProjection,
        SourceOwnerId::AbiIoShm,
        "HandleBoundSqliteAbiAttempt::Acquired",
        NodeRole::AbiProjection,
        LOCK_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiLockBusyProjection,
        SourceOwnerId::AbiIoShm,
        "HandleBoundSqliteAbiAttempt::Busy",
        NodeRole::AbiProjection,
        ACQUIRE_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiLockFallbackProjection,
        SourceOwnerId::AbiFileState,
        "Ok(Err(_)) | Err(_) =>",
        NodeRole::AbiProjection,
        LOCK_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiLockUnavailableCode,
        SourceOwnerId::AbiResultCodes,
        "SHM_LOCK_UNAVAILABLE",
        NodeRole::AbiProjection,
        LOCK_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
];
