use super::super::super::model::{Epoch, SourceEffect, SourceOwnerId};
use super::super::model::*;

const fn terminal(
    cause: MapPhase,
    terminal: MapPhase,
    timing: MapTiming,
    exit: MapExit,
    retention: MapRetention,
) -> MapStepKind {
    MapStepKind::Terminal(MapTerminalTemplate {
        cause,
        returned_terminal: terminal,
        stored_poison: MapPhaseProjection::NotWritten,
        route_marker: MapPhaseProjection::NotWritten,
        timing,
        exit,
        retention,
        multiplicity: MapMultiplicity::OncePerMapCall,
    })
}

const fn pending(
    cause: MapPhase,
    terminal_phase: MapPhase,
    retention: MapRetention,
    reason: MapPendingReason,
) -> MapStepKind {
    MapStepKind::Pending {
        terminal: Some(MapTerminalTemplate {
            cause,
            returned_terminal: terminal_phase,
            stored_poison: MapPhaseProjection::Pending,
            route_marker: MapPhaseProjection::Pending,
            timing: MapTiming::LocalDeterministic,
            exit: MapExit::AbiUnavailableNull,
            retention,
            multiplicity: MapMultiplicity::OncePerMapCall,
        }),
        reason,
    }
}

pub(in super::super) const STEPS: &[MapSourceStep] = &[
    with_value_flow(
        step(
            MapSourceStepId::AbiNullFirst,
            MapSiteId::AbiInput,
            SourceOwnerId::AbiBoundary,
            "unsafe fn write_pointer_null",
            "if !output.is_null()",
            1,
            MAP_BOTH,
            Epoch::AbiInput,
            SourceEffect::OutputNull,
            MapStepKind::Continuation,
        ),
        MapValueFlow::AbiNullWriteConditional,
    ),
    step(
        MapSourceStepId::AbiInputRejected,
        MapSiteId::AbiInput,
        SourceOwnerId::AbiIoShm,
        "unsafe extern \"C\" fn map",
        "return result_codes::SHM_MAP_UNAVAILABLE;",
        1,
        MAP_BOTH,
        Epoch::AbiInput,
        SourceEffect::None,
        MapStepKind::StructuralJoin,
    ),
    with_value_flow(
        step(
            MapSourceStepId::AbiNullOutputRejected,
            MapSiteId::AbiInput,
            SourceOwnerId::AbiIoShm,
            "unsafe extern \"C\" fn map",
            "if output.is_null()",
            1,
            MAP_BOTH,
            Epoch::AbiInput,
            SourceEffect::None,
            terminal(
                MapPhase::AbiValidation,
                MapPhase::AbiValidation,
                MapTiming::Validation,
                MapExit::AbiUnavailableNoSlot,
                MapRetention::None,
            ),
        ),
        MapValueFlow::OutputSlotAbsent,
    ),
    step(
        MapSourceStepId::AbiRawDispatch,
        MapSiteId::RawState,
        SourceOwnerId::AbiIoShm,
        "unsafe extern \"C\" fn map",
        "file_state::run_code(",
        1,
        MAP_BOTH,
        Epoch::AbiInput,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::OuterFaultControllerRejected,
        MapSiteId::OuterFault,
        SourceOwnerId::FixtureFaultFile,
        "fn shm_map",
        "if self.begin(ManagedTestCallbackFaultOperation::ShmMap)?",
        1,
        MAP_BOTH,
        Epoch::AbiInput,
        SourceEffect::None,
        MapStepKind::Pending {
            terminal: Some(MapTerminalTemplate {
                cause: MapPhase::OuterCallbackFault,
                returned_terminal: MapPhase::OuterCallbackFault,
                stored_poison: MapPhaseProjection::NotWritten,
                route_marker: MapPhaseProjection::NotWritten,
                timing: MapTiming::LocalDeterministic,
                exit: MapExit::AbiUnavailableNull,
                retention: MapRetention::ExistingCustody,
                multiplicity: MapMultiplicity::LifetimeCallbackOccurrence,
            }),
            reason: MapPendingReason::CallbackLifetimeOccurrence,
        },
    ),
    step(
        MapSourceStepId::OuterFaultSelected,
        MapSiteId::OuterFault,
        SourceOwnerId::FixtureFaultFile,
        "fn shm_map",
        "return Err(());",
        1,
        MAP_BOTH,
        Epoch::AbiInput,
        SourceEffect::None,
        MapStepKind::Pending {
            terminal: Some(MapTerminalTemplate {
                cause: MapPhase::OuterCallbackFault,
                returned_terminal: MapPhase::OuterCallbackFault,
                stored_poison: MapPhaseProjection::NotWritten,
                route_marker: MapPhaseProjection::NotWritten,
                timing: MapTiming::BeforeCall,
                exit: MapExit::AbiUnavailableNull,
                retention: MapRetention::ExistingCustody,
                multiplicity: MapMultiplicity::LifetimeCallbackOccurrence,
            }),
            reason: MapPendingReason::CallbackLifetimeOccurrence,
        },
    ),
    step(
        MapSourceStepId::OuterFaultPass,
        MapSiteId::OuterFault,
        SourceOwnerId::FixtureFaultFile,
        "fn shm_map",
        "self.inner()?.shm_map(region, region_size, extend)",
        1,
        MAP_BOTH,
        Epoch::AbiInput,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::OuterInnerMissing,
        MapSiteId::OuterFault,
        SourceOwnerId::FixtureFaultFile,
        "fn inner",
        "self.inner.as_mut().ok_or(())",
        1,
        MAP_BOTH,
        Epoch::AbiInput,
        SourceEffect::None,
        pending(
            MapPhase::OuterCallbackFault,
            MapPhase::OuterCallbackFault,
            MapRetention::ExistingCustody,
            MapPendingReason::RouteOrPlanPrecondition,
        ),
    ),
    step(
        MapSourceStepId::AdapterNotPresent,
        MapSiteId::AbiProjection,
        SourceOwnerId::RegistryAbiFile,
        "fn shm_map",
        "ManagedSqliteShmMapOutcome::NotPresent =>",
        1,
        MAP_OBSERVE,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    with_value_flow(
        step(
            MapSourceStepId::AdapterMapped,
            MapSiteId::AbiProjection,
            SourceOwnerId::RegistryAbiFile,
            "fn shm_map",
            "ManagedSqliteShmMapOutcome::Mapped(pointer) =>",
            1,
            MAP_BOTH,
            Epoch::WalMainSteady,
            SourceEffect::None,
            MapStepKind::Continuation,
        ),
        MapValueFlow::TypedPointerCarried,
    ),
    step(
        MapSourceStepId::AdapterRegionMismatch,
        MapSiteId::AbiProjection,
        SourceOwnerId::RegistryAbiFile,
        "fn shm_map",
        "pointer.region() != region",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending(
            MapPhase::AbiProjection,
            MapPhase::AbiProjection,
            MapRetention::ExistingCustody,
            MapPendingReason::PrefixMutationSplit,
        ),
    ),
    step(
        MapSourceStepId::AdapterLengthMismatch,
        MapSiteId::AbiProjection,
        SourceOwnerId::RegistryAbiFile,
        "fn shm_map",
        "pointer.length() != region_size.get() as usize",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::DefensiveCorruption),
    ),
    step(
        MapSourceStepId::AdapterNullPointer,
        MapSiteId::AbiProjection,
        SourceOwnerId::RegistryAbiFile,
        "fn shm_map",
        "NonNull::new(unsafe { pointer.as_mut_ptr() }.cast()).ok_or(())?",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::DefensiveCorruption),
    ),
    step(
        MapSourceStepId::AbiFailureProjection,
        MapSiteId::AbiProjection,
        SourceOwnerId::AbiIoShm,
        "unsafe extern \"C\" fn map",
        "Err(()) => result_codes::SHM_MAP_UNAVAILABLE",
        1,
        MAP_BOTH,
        Epoch::AbiInput,
        SourceEffect::None,
        MapStepKind::StructuralJoin,
    ),
    step(
        MapSourceStepId::AbiNotPresentProjection,
        MapSiteId::AbiProjection,
        SourceOwnerId::AbiIoShm,
        "unsafe extern \"C\" fn map",
        "Ok(HandleBoundSqliteAbiShmMap::NotPresent) => ffi::SQLITE_OK",
        1,
        MAP_OBSERVE,
        Epoch::AbiInput,
        SourceEffect::None,
        terminal(
            MapPhase::Success,
            MapPhase::Success,
            MapTiming::Succeeded,
            MapExit::AbiOkNotPresent,
            MapRetention::NodeCustody,
        ),
    ),
    with_value_flow(
        step(
            MapSourceStepId::AbiMappedProjection,
            MapSiteId::AbiProjection,
            SourceOwnerId::AbiIoShm,
            "unsafe extern \"C\" fn map",
            "output.write(pointer.as_ptr())",
            1,
            MAP_BOTH,
            Epoch::AbiInput,
            SourceEffect::OutputPointer,
            terminal(
                MapPhase::Success,
                MapPhase::Success,
                MapTiming::Succeeded,
                MapExit::AbiOkMapped,
                MapRetention::ViewAndMappingCustody,
            ),
        ),
        MapValueFlow::AbiPointerWritten,
    ),
];
