use super::super::super::model::{Epoch, SourceEffect, SourceOwnerId};
use super::super::model::*;

const fn rewrite(
    cause: MapPhase,
    terminal: MapPhase,
    stored_poison: MapPhaseProjection,
    retention: MapRetention,
    multiplicity: MapMultiplicity,
) -> MapStepKind {
    MapStepKind::CleanupRewrite(MapTerminalTemplate {
        cause,
        returned_terminal: terminal,
        stored_poison,
        route_marker: MapPhaseProjection::Returned,
        timing: MapTiming::Cleanup,
        exit: MapExit::AbiUnavailableNull,
        retention,
        multiplicity,
    })
}

const fn terminal(
    cause: MapPhase,
    retention: MapRetention,
    multiplicity: MapMultiplicity,
) -> MapStepKind {
    MapStepKind::Terminal(MapTerminalTemplate {
        cause,
        returned_terminal: cause,
        stored_poison: MapPhaseProjection::Pending,
        route_marker: MapPhaseProjection::Pending,
        timing: MapTiming::Cleanup,
        exit: MapExit::AbiUnavailableNull,
        retention,
        multiplicity,
    })
}

pub(in super::super) const STEPS: &[MapSourceStep] = &[
    step(
        MapSourceStepId::ExactOpenCleanupSucceeded,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedFailureCustody,
        "fn consume_open_failure",
        "ManagedSqliteShmFailurePhase::ExactSiblingOpen",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Cleanup,
        terminal(
            MapPhase::ExactSiblingOpen,
            MapRetention::None,
            MapMultiplicity::OncePerMapCall,
        ),
    ),
    step(
        MapSourceStepId::ExactOpenCloseRewrite,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedFailureCustody,
        "fn consume_open_failure",
        "ManagedSqliteShmFailurePhase::FileClose",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::RetainCustody,
        rewrite(
            MapPhase::ExactSiblingOpen,
            MapPhase::FileClose,
            MapPhaseProjection::Pending,
            MapRetention::FileCloseCustody,
            MapMultiplicity::OncePerMapCall,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsExclusiveFaultBeforeCloseSucceeded,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedInitialization,
            "fn close_failed_open_file",
            "Ok(_) => original",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Cleanup,
            terminal(
                MapPhase::DmsExclusiveAcquire,
                MapRetention::None,
                MapMultiplicity::OncePerMapCall,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "Err(failure) => return Err(self.close_failed_open_file(state, file, failure))",
            1,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsExclusiveFaultBeforeCloseRewrite,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedInitialization,
            "fn close_failed_open_file",
            "Err(close_failure) =>",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::RetainCustody,
            rewrite(
                MapPhase::DmsExclusiveAcquire,
                MapPhase::FileClose,
                MapPhaseProjection::Pending,
                MapRetention::FileCloseCustody,
                MapMultiplicity::OncePerMapCall,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "Err(failure) => return Err(self.close_failed_open_file(state, file, failure))",
            1,
        ),
    ),
    step(
        MapSourceStepId::DmsTruncateFaultBeforeReleaseOk,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "return Err(self.close_failed_open_file(state, file, failure));",
        2,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Cleanup,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::DmsTruncateFaultBeforeReleaseFailed,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmDmsCustody::ExclusiveOutcomeUncertain",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::RetainCustody,
        rewrite(
            MapPhase::DmsTruncate,
            MapPhase::DmsExclusiveRelease,
            MapPhaseProjection::Returned,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsTruncateCloseSucceeded,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedInitialization,
            "fn close_failed_open_file",
            "Ok(_) => original",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Cleanup,
            terminal(
                MapPhase::DmsTruncate,
                MapRetention::None,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "return Err(self.close_failed_open_file(state, file, failure));",
            2,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsTruncateCloseRewrite,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedInitialization,
            "fn close_failed_open_file",
            "Err(close_failure) =>",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::RetainCustody,
            rewrite(
                MapPhase::DmsTruncate,
                MapPhase::FileClose,
                MapPhaseProjection::Cause,
                MapRetention::FileCloseCustody,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "return Err(self.close_failed_open_file(state, file, failure));",
            2,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsSharedFaultBeforeCloseSucceeded,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedInitialization,
            "fn close_failed_open_file",
            "Ok(_) => original",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Cleanup,
            terminal(
                MapPhase::DmsSharedAcquire,
                MapRetention::None,
                MapMultiplicity::OncePerMapCall,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "Err(failure) => return Err(self.close_failed_open_file(state, file, failure))",
            2,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsSharedFaultBeforeCloseRewrite,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedInitialization,
            "fn close_failed_open_file",
            "Err(close_failure) =>",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::RetainCustody,
            rewrite(
                MapPhase::DmsSharedAcquire,
                MapPhase::FileClose,
                MapPhaseProjection::Pending,
                MapRetention::FileCloseCustody,
                MapMultiplicity::OncePerMapCall,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "Err(failure) => return Err(self.close_failed_open_file(state, file, failure))",
            2,
        ),
    ),
    step(
        MapSourceStepId::ViewMapFaultBeforeCleanupOk,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "return Err(failure);",
        5,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::Cleanup,
        terminal(
            MapPhase::ViewMap,
            MapRetention::ExistingCustody,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::ViewMapFaultBeforeCleanupFailed,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailurePhase::MappingClose",
        2,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::RetainCustody,
        rewrite(
            MapPhase::ViewMap,
            MapPhase::MappingClose,
            MapPhaseProjection::Cause,
            MapRetention::MappingCustody,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::ViewMapNativeCleanupOk,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailurePhase::ViewMap",
        2,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::Cleanup,
        terminal(
            MapPhase::ViewMap,
            MapRetention::ExistingCustody,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::ViewMapNativeCleanupFailed,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailurePhase::MappingClose",
        4,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::RetainCustody,
        rewrite(
            MapPhase::ViewMap,
            MapPhase::MappingClose,
            MapPhaseProjection::Returned,
            MapRetention::MappingCustody,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
];
