use super::super::super::model::{Epoch, SourceEffect, SourceOwnerId};
use super::super::model::*;

mod finalization;

pub(in super::super) const FINALIZATION_STEPS: &[MapSourceStep] = finalization::STEPS;

const fn unavailable(
    cause: MapPhase,
    terminal: MapPhase,
    timing: MapTiming,
    retention: MapRetention,
    multiplicity: MapMultiplicity,
) -> MapStepKind {
    MapStepKind::Terminal(MapTerminalTemplate {
        cause,
        returned_terminal: terminal,
        stored_poison: MapPhaseProjection::Pending,
        route_marker: MapPhaseProjection::Pending,
        timing,
        exit: MapExit::AbiUnavailableNull,
        retention,
        multiplicity,
    })
}

pub(in super::super) const STEPS: &[MapSourceStep] = &[
    step(
        MapSourceStepId::ExactOpenFaultBefore,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmFailurePhase::ExactSiblingOpen",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        unavailable(
            MapPhase::ExactSiblingOpen,
            MapPhase::ExactSiblingOpen,
            MapTiming::BeforeCall,
            MapRetention::None,
            MapMultiplicity::SymbolicPhaseOccurrence,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::ExactOpenFaultAfterKnown,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_KNOWN_MUTATION",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Poison,
            unavailable(
                MapPhase::ExactSiblingOpen,
                MapPhase::ExactSiblingOpen,
                MapTiming::AfterSuccessKnown,
                MapRetention::NodeCustody,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "ManagedSqliteShmFailurePhase::ExactSiblingOpen",
            1,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::ExactOpenFaultAfterUncertain,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_OUTCOME_UNCERTAIN",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Poison,
            unavailable(
                MapPhase::ExactSiblingOpen,
                MapPhase::ExactSiblingOpen,
                MapTiming::AfterSuccessUncertain,
                MapRetention::NodeCustody,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "ManagedSqliteShmFailurePhase::ExactSiblingOpen",
            1,
        ),
    ),
    step(
        MapSourceStepId::ExactOpenNativeFailure,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "Err(failure) => return Err(self.consume_open_failure(state, failure))",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::DmsExclusiveFaultBefore,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmFailurePhase::DmsExclusiveAcquire",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::DmsExclusiveFaultAfterKnown,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmDmsCustody::ExclusiveKnown",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Poison,
        unavailable(
            MapPhase::DmsExclusiveAcquire,
            MapPhase::DmsExclusiveAcquire,
            MapTiming::AfterSuccessKnown,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsExclusiveFaultAfterUncertain,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_OUTCOME_UNCERTAIN",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Poison,
            unavailable(
                MapPhase::DmsExclusiveAcquire,
                MapPhase::DmsExclusiveAcquire,
                MapTiming::AfterSuccessUncertain,
                MapRetention::NodeCustody,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "ManagedSqliteShmFailurePhase::DmsExclusiveAcquire",
            1,
        ),
    ),
    step(
        MapSourceStepId::DmsExclusiveContended,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "Ok(PlatformManagedSqliteLockAttempt::Contended) => false",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::DmsExclusiveNativeFailure,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmFailurePhase::DmsExclusiveAcquire",
        2,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::DmsTruncateNativeReleaseOk,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmFailurePhase::DmsTruncate",
        2,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Poison,
        unavailable(
            MapPhase::DmsTruncate,
            MapPhase::DmsTruncate,
            MapTiming::NativeResult,
            MapRetention::NodeCustody,
            MapMultiplicity::OncePerMapCall,
        ),
    ),
    step(
        MapSourceStepId::DmsTruncateNativeReleaseFailed,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmDmsCustody::ExclusiveOutcomeUncertain",
        2,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Poison,
        MapStepKind::CleanupRewrite(MapTerminalTemplate {
            cause: MapPhase::DmsTruncate,
            returned_terminal: MapPhase::DmsExclusiveRelease,
            stored_poison: MapPhaseProjection::Returned,
            route_marker: MapPhaseProjection::Returned,
            timing: MapTiming::Cleanup,
            exit: MapExit::AbiUnavailableNull,
            retention: MapRetention::NodeCustody,
            multiplicity: MapMultiplicity::OncePerMapCall,
        }),
    ),
    step(
        MapSourceStepId::DmsTruncateFaultAfterKnown,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "return Err(self.activate_after_test_fault(state, fault, true));",
        3,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Poison,
        unavailable(
            MapPhase::DmsTruncate,
            MapPhase::DmsTruncate,
            MapTiming::AfterSuccessKnown,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsTruncateFaultAfterUncertain,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_OUTCOME_UNCERTAIN",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Poison,
            unavailable(
                MapPhase::DmsTruncate,
                MapPhase::DmsTruncate,
                MapTiming::AfterSuccessUncertain,
                MapRetention::NodeCustody,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "ManagedSqliteShmFailurePhase::DmsTruncate",
            1,
        ),
    ),
    step(
        MapSourceStepId::DmsExclusiveReleaseFaultBefore,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "let exclusive_release_fault = match self.begin_test_fault(",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Poison,
        unavailable(
            MapPhase::DmsExclusiveRelease,
            MapPhase::DmsExclusiveRelease,
            MapTiming::BeforeCall,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
        ),
    ),
    step(
        MapSourceStepId::DmsExclusiveReleaseNativeFailure,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "if let Err(error) = platform::unlock_sqlite_byte_range",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Poison,
        unavailable(
            MapPhase::DmsExclusiveRelease,
            MapPhase::DmsExclusiveRelease,
            MapTiming::NativeResult,
            MapRetention::NodeCustody,
            MapMultiplicity::OncePerMapCall,
        ),
    ),
    step(
        MapSourceStepId::DmsExclusiveReleaseFaultAfterKnown,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmDmsCustody::Released",
        3,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Poison,
        unavailable(
            MapPhase::DmsExclusiveRelease,
            MapPhase::DmsExclusiveRelease,
            MapTiming::AfterSuccessKnown,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsExclusiveReleaseFaultAfterUncertain,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_OUTCOME_UNCERTAIN",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Poison,
            unavailable(
                MapPhase::DmsExclusiveRelease,
                MapPhase::DmsExclusiveRelease,
                MapTiming::AfterSuccessUncertain,
                MapRetention::NodeCustody,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "if let Some(fault) = exclusive_release_fault",
            1,
        ),
    ),
    step(
        MapSourceStepId::DmsSharedFaultBefore,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmFailurePhase::DmsSharedAcquire",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::DmsSharedNativeBusy,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "NODE_MANAGED_SQLITE_SHM_DMS_BUSY",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::DmsSharedNativeFailure,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "ManagedSqliteShmFailurePhase::DmsSharedAcquire",
        3,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::DmsSharedFaultAfterKnown,
        MapSiteId::NodeInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        "return Err(self.activate_after_test_fault(state, fault, true));",
        5,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::Poison,
        unavailable(
            MapPhase::DmsSharedAcquire,
            MapPhase::DmsSharedAcquire,
            MapTiming::AfterSuccessKnown,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::DmsSharedFaultAfterUncertain,
            MapSiteId::NodeInitialization,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_OUTCOME_UNCERTAIN",
            1,
            MAP_BOTH,
            Epoch::FirstMapBootstrap,
            SourceEffect::Poison,
            unavailable(
                MapPhase::DmsSharedAcquire,
                MapPhase::DmsSharedAcquire,
                MapTiming::AfterSuccessUncertain,
                MapRetention::NodeCustody,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedInitialization,
            "fn open_node",
            "ManagedSqliteShmFailurePhase::DmsSharedAcquire",
            1,
        ),
    ),
];
