use super::super::super::model::{Epoch, SourceEffect, SourceOwnerId};
use super::super::model::*;

const fn unavailable(
    cause: MapPhase,
    timing: MapTiming,
    retention: MapRetention,
    multiplicity: MapMultiplicity,
) -> MapStepKind {
    MapStepKind::Terminal(MapTerminalTemplate {
        cause,
        returned_terminal: cause,
        stored_poison: MapPhaseProjection::Pending,
        route_marker: MapPhaseProjection::Pending,
        timing,
        exit: MapExit::AbiUnavailableNull,
        retention,
        multiplicity,
    })
}

const fn pending(
    cause: MapPhase,
    timing: MapTiming,
    retention: MapRetention,
    multiplicity: MapMultiplicity,
    reason: MapPendingReason,
) -> MapStepKind {
    MapStepKind::Pending {
        terminal: Some(MapTerminalTemplate {
            cause,
            returned_terminal: cause,
            stored_poison: MapPhaseProjection::Pending,
            route_marker: MapPhaseProjection::Pending,
            timing,
            exit: MapExit::AbiUnavailableNull,
            retention,
            multiplicity,
        }),
        reason,
    }
}

pub(in super::super) const STEPS: &[MapSourceStep] = &[
    step(
        MapSourceStepId::FileSizeFaultBefore,
        MapSiteId::FileSize,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailurePhase::FileSize",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending(
            MapPhase::FileSize,
            MapTiming::BeforeCall,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
            MapPendingReason::PrefixMutationSplit,
        ),
    ),
    step(
        MapSourceStepId::FileSizeAfterSelectorRejected,
        MapSiteId::FileSize,
        SourceOwnerId::ManagedFaultController,
        "fn supports_after_success",
        "phase != ManagedSqliteShmFailurePhase::FileSize",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::RejectedByControlFlow),
    ),
    step(
        MapSourceStepId::FileSizeNativeFailure,
        MapSiteId::FileSize,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailurePhase::FileSize",
        2,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending(
            MapPhase::FileSize,
            MapTiming::NativeResult,
            MapRetention::NodeCustody,
            MapMultiplicity::OncePerMapCall,
            MapPendingReason::PrefixMutationSplit,
        ),
    ),
    step(
        MapSourceStepId::ObserveNotPresent,
        MapSiteId::FileSize,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "return Ok(ManagedSqliteShmMapOutcome::NotPresent);",
        1,
        MAP_OBSERVE,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::FileGrowFaultBefore,
        MapSiteId::FileGrow,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailurePhase::FileGrow",
        1,
        MAP_EXTEND,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending(
            MapPhase::FileGrow,
            MapTiming::BeforeCall,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
            MapPendingReason::PrefixMutationSplit,
        ),
    ),
    step(
        MapSourceStepId::FileGrowNativeFailure,
        MapSiteId::FileGrow,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailure::poisoned(",
        1,
        MAP_EXTEND,
        Epoch::WalMainSteady,
        SourceEffect::Poison,
        unavailable(
            MapPhase::FileGrow,
            MapTiming::NativeResult,
            MapRetention::NodeCustody,
            MapMultiplicity::OncePerMapCall,
        ),
    ),
    step(
        MapSourceStepId::FileGrowFaultAfterKnown,
        MapSiteId::FileGrow,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "self.finish_test_fault(&mut state, file_grow_fault, true)",
        1,
        MAP_EXTEND,
        Epoch::WalMainSteady,
        SourceEffect::Poison,
        unavailable(
            MapPhase::FileGrow,
            MapTiming::AfterSuccessKnown,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicPhaseOccurrence,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::FileGrowFaultAfterUncertain,
            MapSiteId::FileGrow,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_OUTCOME_UNCERTAIN",
            1,
            MAP_EXTEND,
            Epoch::WalMainSteady,
            SourceEffect::Poison,
            unavailable(
                MapPhase::FileGrow,
                MapTiming::AfterSuccessUncertain,
                MapRetention::NodeCustody,
                MapMultiplicity::SymbolicPhaseOccurrence,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedMapping,
            "fn map_connection",
            "self.finish_test_fault(&mut state, file_grow_fault, true)",
            1,
        ),
    ),
    step(
        MapSourceStepId::MappingCreateFaultBefore,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailurePhase::MappingCreate",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending(
            MapPhase::MappingCreate,
            MapTiming::BeforeCall,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicRegionLoop,
            MapPendingReason::PrefixMutationSplit,
        ),
    ),
    step(
        MapSourceStepId::MappingCreateNativeFailure,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "ManagedSqliteShmFailurePhase::MappingCreate",
        2,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::None,
        pending(
            MapPhase::MappingCreate,
            MapTiming::NativeResult,
            MapRetention::NodeCustody,
            MapMultiplicity::SymbolicRegionLoop,
            MapPendingReason::PlatformTypedOutcome,
        ),
    ),
    step(
        MapSourceStepId::MappingCreateAttempt,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "let mut mapping = {",
        1,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::MappingCreateRetained,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "self.retain_test_mapping_custody(",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::RetainCustody,
        MapStepKind::Continuation,
    ),
    with_call_context(
        step(
            MapSourceStepId::MappingCreateFaultAfterKnown,
            MapSiteId::MappingCreate,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_KNOWN_MUTATION",
            1,
            MAP_BOTH,
            Epoch::WalMainSteady,
            SourceEffect::Poison,
            unavailable(
                MapPhase::MappingCreate,
                MapTiming::AfterSuccessKnown,
                MapRetention::MappingCustody,
                MapMultiplicity::SymbolicRegionLoop,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedMapping,
            "fn map_connection",
            "self.finish_test_fault(&mut state, mapping_fault, true)",
            1,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::MappingCreateFaultAfterUncertain,
            MapSiteId::MappingCreate,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_OUTCOME_UNCERTAIN",
            1,
            MAP_BOTH,
            Epoch::WalMainSteady,
            SourceEffect::Poison,
            unavailable(
                MapPhase::MappingCreate,
                MapTiming::AfterSuccessUncertain,
                MapRetention::MappingCustody,
                MapMultiplicity::SymbolicRegionLoop,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedMapping,
            "fn map_connection",
            "self.finish_test_fault(&mut state, mapping_fault, true)",
            1,
        ),
    ),
    step(
        MapSourceStepId::MappingCreateAfterMatchLostExcluded,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_MATCH_LOST",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::Poison,
        MapStepKind::Excluded(MapExclusionReason::RejectedByControlFlow),
    ),
    step(
        MapSourceStepId::ViewMapFaultBeforeUncertain,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "== ManagedSqliteShmFailureClass::OutcomeUncertainPoisoned",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::RetainCustody,
        pending(
            MapPhase::ViewMap,
            MapTiming::BeforeCall,
            MapRetention::MappingCustody,
            MapMultiplicity::SymbolicRegionLoop,
            MapPendingReason::ControllerInternalFailure,
        ),
    ),
    step(
        MapSourceStepId::ViewMapNullCustodyRetained,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "view: Some(view)",
        1,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::RetainCustody,
        MapStepKind::Excluded(MapExclusionReason::DefensiveCorruption),
    ),
    step(
        MapSourceStepId::ViewMapNullPoisoned,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_VIEW_RETURNED_NULL",
        1,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::Poison,
        MapStepKind::Excluded(MapExclusionReason::DefensiveCorruption),
    ),
    step(
        MapSourceStepId::ViewMapFaultAfterKnown,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "self.finish_test_fault(&mut state, view_fault, true)",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::Poison,
        unavailable(
            MapPhase::ViewMap,
            MapTiming::AfterSuccessKnown,
            MapRetention::ViewAndMappingCustody,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    with_call_context(
        step(
            MapSourceStepId::ViewMapFaultAfterUncertain,
            MapSiteId::ViewMap,
            SourceOwnerId::ManagedFaultController,
            "fn into_after_failure",
            "NODE_MANAGED_SQLITE_SHM_TEST_FAULT_AFTER_OUTCOME_UNCERTAIN",
            1,
            MAP_BOTH,
            Epoch::WalMainSteady,
            SourceEffect::Poison,
            unavailable(
                MapPhase::ViewMap,
                MapTiming::AfterSuccessUncertain,
                MapRetention::ViewAndMappingCustody,
                MapMultiplicity::SymbolicRegionLoop,
            ),
        ),
        source_anchor(
            SourceOwnerId::ManagedMapping,
            "fn map_connection",
            "self.finish_test_fault(&mut state, view_fault, true)",
            1,
        ),
    ),
    step(
        MapSourceStepId::ViewMapSucceeded,
        MapSiteId::ViewMap,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "Ok(view) => view",
        1,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::RegionRecorded,
        MapSiteId::RegionSelection,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "logical_pointer: Some(logical_pointer)",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::CustodyMutation,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::RegionLoopContinues,
        MapSiteId::RegionSelection,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "while state",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::RegionReuseCandidate,
        MapSiteId::RegionSelection,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "let selected = node.regions.get(region as usize)",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Pending {
            terminal: None,
            reason: MapPendingReason::SuccessPrestatePartition,
        },
    ),
    step(
        MapSourceStepId::RegionCustodyMissing,
        MapSiteId::RegionSelection,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_REGION_CUSTODY_MISSING",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::Poison,
        pending(
            MapPhase::ViewMap,
            MapTiming::Validation,
            MapRetention::PrefixDependent,
            MapMultiplicity::SymbolicRegionLoop,
            MapPendingReason::ManagedStateInvariant,
        ),
    ),
    with_value_flow(
        step(
            MapSourceStepId::ManagedMapped,
            MapSiteId::RegionSelection,
            SourceOwnerId::ManagedMapping,
            "fn map_connection",
            "Ok(ManagedSqliteShmMapOutcome::Mapped(",
            1,
            MAP_BOTH,
            Epoch::WalMainSteady,
            SourceEffect::None,
            MapStepKind::Continuation,
        ),
        MapValueFlow::TypedPointerCreated,
    ),
];
