use super::super::super::model::{Epoch, SourceEffect, SourceOwnerId};
use super::super::model::*;

const fn unavailable(
    cause: MapPhase,
    terminal: MapPhase,
    timing: MapTiming,
    retention: MapRetention,
) -> MapStepKind {
    MapStepKind::Terminal(MapTerminalTemplate {
        cause,
        returned_terminal: terminal,
        stored_poison: MapPhaseProjection::Pending,
        route_marker: MapPhaseProjection::Pending,
        timing,
        exit: MapExit::AbiUnavailableNull,
        retention,
        multiplicity: MapMultiplicity::OncePerMapCall,
    })
}

const fn pending_unavailable(
    cause: MapPhase,
    terminal: MapPhase,
    retention: MapRetention,
    reason: MapPendingReason,
) -> MapStepKind {
    MapStepKind::Pending {
        terminal: Some(MapTerminalTemplate {
            cause,
            returned_terminal: terminal,
            stored_poison: MapPhaseProjection::Pending,
            route_marker: MapPhaseProjection::Pending,
            timing: MapTiming::LocalDeterministic,
            exit: MapExit::AbiUnavailableNull,
            retention,
            multiplicity: MapMultiplicity::OncePerMapCall,
        }),
        reason,
    }
}

pub(in super::super) const STEPS: &[MapSourceStep] = &[
    step(
        MapSourceStepId::RouteNonMainBypass,
        MapSiteId::RoutePlan,
        SourceOwnerId::FixtureRouteFile,
        "fn prepare_first_main_shm_map",
        "if self.shm_faults.role() != ManagedSqliteLogicalFileRole::Main",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::ExactFixtureInvariant),
    ),
    step(
        MapSourceStepId::RoutePlanClaimRejected,
        MapSiteId::RoutePlan,
        SourceOwnerId::FixtureRouteFile,
        "fn prepare_first_main_shm_map",
        "let _ = self.inner.retain_test_fault_bridge_failure(code);",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::RetainCustody,
        pending_unavailable(
            MapPhase::RoutePreparation,
            MapPhase::RoutePreparation,
            MapRetention::RegistryMarkerBeforeCompletion,
            MapPendingReason::RouteOrPlanPrecondition,
        ),
    ),
    step(
        MapSourceStepId::RoutePlanned,
        MapSiteId::RoutePlan,
        SourceOwnerId::FixtureRouteFile,
        "fn prepare_first_main_shm_map",
        "Some(plan) =>",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::RouteNoPlan,
        MapSiteId::RoutePlan,
        SourceOwnerId::FixtureRouteFile,
        "fn prepare_first_main_shm_map",
        "let observer = self.inner.promote_main_to_wal_for_shm()?;",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::PromotionAdmissionRejected,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_to_wal",
        ".begin_callback(self.route, ManagedSqliteRegistryCallbackKind::Shm)",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::None,
        pending_unavailable(
            MapPhase::PromotionCallbackAdmission,
            MapPhase::PromotionCallbackAdmission,
            MapRetention::ExistingCustody,
            MapPendingReason::CallbackOwnerVariant,
        ),
    ),
    step(
        MapSourceStepId::PromotionAlreadyWalLive,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_custody",
        "if file.shm_mut().is_some()",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::None,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::PromotionWalDetached,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_custody",
        "ManagedSqliteRegistryPinnedFileOperationRejection::ShmDetached",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::ExactFixtureInvariant),
    ),
    step(
        MapSourceStepId::PromotionSidecar,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_custody",
        "ManagedSqliteRegistryPinnedFileCustody::Sidecar",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::ExactFixtureInvariant),
    ),
    step(
        MapSourceStepId::PromotionClaimShmRejected,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_custody",
        "Err(rejection) =>",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::None,
        pending_unavailable(
            MapPhase::PromotionCustody,
            MapPhase::PromotionCustody,
            MapRetention::ExistingCustody,
            MapPendingReason::PromotionCustodyVariant,
        ),
    ),
    step(
        MapSourceStepId::PromotionBindSucceeded,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_custody",
        "ManagedSqliteRegistryPinnedFileCustody::WalMain",
        2,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::CustodyMutation,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::PromotionBindFailedRetained,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_custody",
        "Ok(()) => Err(ManagedSqliteRegistryPinnedFileOperationRejection::Shm",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::RetainCustody,
        pending_unavailable(
            MapPhase::PromotionCustody,
            MapPhase::PromotionCustody,
            MapRetention::RegistryMarkerBeforeCompletion,
            MapPendingReason::PromotionCustodyVariant,
        ),
    ),
    step(
        MapSourceStepId::PromotionBindRetentionFailed,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_custody",
        "Err(rejection) => Err(",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::RetainCustody,
        pending_unavailable(
            MapPhase::PromotionCustody,
            MapPhase::PromotionCustody,
            MapRetention::RegistryMarkerBeforeCompletion,
            MapPendingReason::CallbackOwnerVariant,
        ),
    ),
    step(
        MapSourceStepId::PromotionOperationErrorWins,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_to_wal",
        "(Err(rejection), _) => Err(rejection)",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::None,
        MapStepKind::StructuralJoin,
    ),
    step(
        MapSourceStepId::PromotionCompletionRejected,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_to_wal",
        "(Ok(()), Err(rejection)) => Err(",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::CallbackLease,
        pending_unavailable(
            MapPhase::PromotionCallbackCompletion,
            MapPhase::PromotionCallbackCompletion,
            MapRetention::ExistingCustody,
            MapPendingReason::CallbackOwnerVariant,
        ),
    ),
    step(
        MapSourceStepId::PromotionCompleted,
        MapSiteId::Promotion,
        SourceOwnerId::RegistryPromotion,
        "fn promote_main_to_wal",
        "(Ok(()), Ok(())) => Ok(())",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::CallbackLease,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::FaultInstallRejected,
        MapSiteId::FaultInstall,
        SourceOwnerId::RegistryFileFaults,
        "fn install_exact_wal_main_shm_test_fault_script",
        "if let Err(rejection) = result.as_ref()",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::RetainCustody,
        pending_unavailable(
            MapPhase::FaultScriptInstall,
            MapPhase::FaultScriptInstall,
            MapRetention::RegistryMarkerBeforeCompletion,
            MapPendingReason::RouteOrPlanPrecondition,
        ),
    ),
    step(
        MapSourceStepId::FaultProbeRecordRejected,
        MapSiteId::FaultInstall,
        SourceOwnerId::FixtureRouteFile,
        "fn prepare_first_main_shm_map",
        "if let Err(code) = self.shm_faults.record_installed(probe)",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::RetainCustody,
        pending_unavailable(
            MapPhase::FaultScriptInstall,
            MapPhase::FaultScriptInstall,
            MapRetention::RegistryMarkerBeforeCompletion,
            MapPendingReason::RouteOrPlanPrecondition,
        ),
    ),
    step(
        MapSourceStepId::FaultProbeRecorded,
        MapSiteId::FaultInstall,
        SourceOwnerId::FixtureFaultPlan,
        "fn record_installed",
        "ManagedTestShmFaultPlanState::Installed(probe)",
        1,
        MAP_BOTH,
        Epoch::FirstMapBootstrap,
        SourceEffect::CustodyMutation,
        MapStepKind::Continuation,
    ),
    step(
        MapSourceStepId::FaultObserverRecordRejected,
        MapSiteId::RoutePlan,
        SourceOwnerId::FixtureRouteFile,
        "fn prepare_first_main_shm_map",
        "if let Err(code) = self.shm_faults.record_promoted(observer)",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::RetainCustody,
        pending_unavailable(
            MapPhase::RoutePreparation,
            MapPhase::RoutePreparation,
            MapRetention::RegistryMarkerBeforeCompletion,
            MapPendingReason::RouteOrPlanPrecondition,
        ),
    ),
    step(
        MapSourceStepId::FaultObserverRecorded,
        MapSiteId::RoutePlan,
        SourceOwnerId::FixtureFaultPlan,
        "fn record_promoted",
        "ManagedTestShmFaultPlanState::Promoted(observer)",
        1,
        MAP_BOTH,
        Epoch::MapRoutePreparation,
        SourceEffect::CustodyMutation,
        MapStepKind::Continuation,
    ),
];
