use super::super::model::*;

pub(super) const CANDIDATES: &[MapSuccessFamilyRecord] = &[
    MapSuccessFamilyRecord {
        family: MapSuccessFamily::ExtendColdCreate,
        ops: MAP_EXTEND,
        witnesses: &[
            MapSourceStepId::FirstProcessInitialized,
            MapSourceStepId::SharedDmsInitialized,
            MapSourceStepId::MappingCreateAttempt,
            MapSourceStepId::ViewMapSucceeded,
            MapSourceStepId::RegionRecorded,
            MapSourceStepId::ManagedMapped,
            MapSourceStepId::AdapterMapped,
            MapSourceStepId::AbiMappedProjection,
        ],
        exit: MapExit::AbiOkMapped,
        unresolved_multiplicity: Some(MapMultiplicity::SymbolicRegionLoop),
        prestate_partition_pending: true,
    },
    MapSuccessFamilyRecord {
        family: MapSuccessFamily::ExtendWarmCreate,
        ops: MAP_EXTEND,
        witnesses: &[
            MapSourceStepId::MappingCreateAttempt,
            MapSourceStepId::ViewMapSucceeded,
            MapSourceStepId::RegionRecorded,
            MapSourceStepId::ManagedMapped,
            MapSourceStepId::AdapterMapped,
            MapSourceStepId::AbiMappedProjection,
        ],
        exit: MapExit::AbiOkMapped,
        unresolved_multiplicity: Some(MapMultiplicity::SymbolicRegionLoop),
        prestate_partition_pending: true,
    },
    MapSuccessFamilyRecord {
        family: MapSuccessFamily::ExtendReuse,
        ops: MAP_EXTEND,
        witnesses: &[
            MapSourceStepId::RegionReuseCandidate,
            MapSourceStepId::ManagedMapped,
            MapSourceStepId::AdapterMapped,
            MapSourceStepId::AbiMappedProjection,
        ],
        exit: MapExit::AbiOkMapped,
        unresolved_multiplicity: None,
        prestate_partition_pending: true,
    },
    MapSuccessFamilyRecord {
        family: MapSuccessFamily::ObserveWarmCreate,
        ops: MAP_OBSERVE,
        witnesses: &[
            MapSourceStepId::MappingCreateAttempt,
            MapSourceStepId::ViewMapSucceeded,
            MapSourceStepId::RegionRecorded,
            MapSourceStepId::ManagedMapped,
            MapSourceStepId::AdapterMapped,
            MapSourceStepId::AbiMappedProjection,
        ],
        exit: MapExit::AbiOkMapped,
        unresolved_multiplicity: Some(MapMultiplicity::SymbolicRegionLoop),
        prestate_partition_pending: true,
    },
    MapSuccessFamilyRecord {
        family: MapSuccessFamily::ObserveReuse,
        ops: MAP_OBSERVE,
        witnesses: &[
            MapSourceStepId::RegionReuseCandidate,
            MapSourceStepId::ManagedMapped,
            MapSourceStepId::AdapterMapped,
            MapSourceStepId::AbiMappedProjection,
        ],
        exit: MapExit::AbiOkMapped,
        unresolved_multiplicity: None,
        prestate_partition_pending: true,
    },
    MapSuccessFamilyRecord {
        family: MapSuccessFamily::ObserveNotPresent,
        ops: MAP_OBSERVE,
        witnesses: &[
            MapSourceStepId::ObserveNotPresent,
            MapSourceStepId::AdapterNotPresent,
            MapSourceStepId::AbiNotPresentProjection,
        ],
        exit: MapExit::AbiOkNotPresent,
        unresolved_multiplicity: None,
        prestate_partition_pending: true,
    },
];
