use super::super::super::model::{Epoch, SourceEffect, SourceOwnerId};
use super::super::model::*;

const fn unavailable(cause: MapPhase, reason: MapPendingReason) -> MapStepKind {
    MapStepKind::Pending {
        terminal: Some(MapTerminalTemplate {
            cause,
            returned_terminal: cause,
            stored_poison: MapPhaseProjection::Pending,
            route_marker: MapPhaseProjection::Pending,
            timing: MapTiming::Validation,
            exit: MapExit::AbiUnavailableNull,
            retention: MapRetention::ExistingCustody,
            multiplicity: MapMultiplicity::OncePerMapCall,
        }),
        reason,
    }
}

const fn protocol(cause: MapPhase) -> MapStepKind {
    MapStepKind::Terminal(MapTerminalTemplate {
        cause,
        returned_terminal: cause,
        stored_poison: MapPhaseProjection::NotWritten,
        route_marker: MapPhaseProjection::Pending,
        timing: MapTiming::Validation,
        exit: MapExit::AbiUnavailableNull,
        retention: MapRetention::ExistingCustody,
        multiplicity: MapMultiplicity::OncePerMapCall,
    })
}

const fn pending_prefix(
    cause: MapPhase,
    reason: MapPendingReason,
    multiplicity: MapMultiplicity,
) -> MapStepKind {
    MapStepKind::Pending {
        terminal: Some(MapTerminalTemplate {
            cause,
            returned_terminal: cause,
            stored_poison: MapPhaseProjection::Pending,
            route_marker: MapPhaseProjection::Pending,
            timing: MapTiming::Validation,
            exit: MapExit::AbiUnavailableNull,
            retention: MapRetention::PrefixDependent,
            multiplicity,
        }),
        reason,
    }
}

pub(in super::super) const STEPS: &[MapSourceStep] = &[
    step(
        MapSourceStepId::ManagedInactive,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedMapping,
        "pub(crate) fn map(",
        "NODE_MANAGED_SQLITE_SHM_CONNECTION_INACTIVE",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::ExactFixtureInvariant),
    ),
    step(
        MapSourceStepId::RegionSizeBudgetRejected,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedTypes,
        "fn validate_region_size",
        "NODE_MANAGED_SQLITE_SHM_REGION_SIZE_BUDGET",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        protocol(MapPhase::RequestValidation),
    ),
    step(
        MapSourceStepId::RegionCountBudgetRejected,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedTypes,
        "fn validate_logical_end",
        "NODE_MANAGED_SQLITE_SHM_REGION_COUNT_BUDGET",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        protocol(MapPhase::RequestValidation),
    ),
    step(
        MapSourceStepId::LogicalEndOverflowRejected,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedTypes,
        "fn validate_logical_end",
        "NODE_MANAGED_SQLITE_SHM_LOGICAL_END_OVERFLOW",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::RejectedByControlFlow),
    ),
    step(
        MapSourceStepId::LogicalEndBudgetRejected,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedTypes,
        "fn validate_logical_end",
        "NODE_MANAGED_SQLITE_SHM_LOGICAL_SIZE_BUDGET",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        protocol(MapPhase::RequestValidation),
    ),
    step(
        MapSourceStepId::AllocationGranularityFailure,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "platform_shm::allocation_granularity().map_err",
        1,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::None,
        unavailable(
            MapPhase::RequestValidation,
            MapPendingReason::PlatformTypedOutcome,
        ),
    ),
    step(
        MapSourceStepId::AllocationGranularityZero,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_ALLOCATION_GRANULARITY_ZERO",
        1,
        MAP_BOTH,
        Epoch::PlatformBinding,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::DefensiveCorruption),
    ),
    step(
        MapSourceStepId::CoordinatorMutexPoisoned,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "self.state.lock().map_err(|_| self.poisoned_failure())?",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::Poison,
        MapStepKind::Excluded(MapExclusionReason::ExactFixtureInvariant),
    ),
    step(
        MapSourceStepId::ConnectionMissing,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_CONNECTION_NOT_ATTACHED",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::ExactFixtureInvariant),
    ),
    step(
        MapSourceStepId::DomainAlreadyPoisoned,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "return Err(poison.failure());",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        MapStepKind::Excluded(MapExclusionReason::ExactFixtureInvariant),
    ),
    step(
        MapSourceStepId::RegionSizeChanged,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_REGION_SIZE_CHANGED",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        protocol(MapPhase::RequestValidation),
    ),
    step(
        MapSourceStepId::ExistingSizeBudgetRejected,
        MapSiteId::ManagedValidation,
        SourceOwnerId::ManagedTypes,
        "fn validate_existing_size",
        "NODE_MANAGED_SQLITE_SHM_EXISTING_SIZE_BUDGET",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending_prefix(
            MapPhase::RequestValidation,
            MapPendingReason::PrefixMutationSplit,
            MapMultiplicity::OncePerMapCall,
        ),
    ),
    step(
        MapSourceStepId::MappingArithmeticRejected,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_REGION_INDEX_OVERFLOW",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending_prefix(
            MapPhase::RequestValidation,
            MapPendingReason::SymbolicLoopOrOccurrence,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::RegionOffsetOverflowRejected,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_REGION_OFFSET_OVERFLOW",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending_prefix(
            MapPhase::RequestValidation,
            MapPendingReason::PlatformCfgScope,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::ViewShiftOverflowRejected,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_VIEW_SHIFT_OVERFLOW",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending_prefix(
            MapPhase::RequestValidation,
            MapPendingReason::PlatformCfgScope,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::RegionLengthOverflowRejected,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_REGION_LENGTH_OVERFLOW",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending_prefix(
            MapPhase::RequestValidation,
            MapPendingReason::PlatformCfgScope,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::ViewLengthOverflowRejected,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_VIEW_LENGTH_OVERFLOW",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending_prefix(
            MapPhase::RequestValidation,
            MapPendingReason::PlatformCfgScope,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::MappedTotalOverflowRejected,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedMapping,
        "fn map_connection",
        "NODE_MANAGED_SQLITE_SHM_MAPPED_TOTAL_OVERFLOW",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending_prefix(
            MapPhase::RequestValidation,
            MapPendingReason::SymbolicLoopOrOccurrence,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
    step(
        MapSourceStepId::MappingBudgetRejected,
        MapSiteId::MappingCreate,
        SourceOwnerId::ManagedTypes,
        "fn validate_mapped_total",
        "NODE_MANAGED_SQLITE_SHM_MAPPED_SIZE_BUDGET",
        1,
        MAP_BOTH,
        Epoch::WalMainSteady,
        SourceEffect::None,
        pending_prefix(
            MapPhase::RequestValidation,
            MapPendingReason::SymbolicLoopOrOccurrence,
            MapMultiplicity::SymbolicRegionLoop,
        ),
    ),
];
