CREATE UNIQUE INDEX IF NOT EXISTS idx_v270_provider_runtime_readiness_genesis
  ON compute_external_pool_adapter_provider_runtime_readiness_receipts(provider_binding_id)
  WHERE predecessor_readiness_receipt_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_v270_provider_runtime_readiness_binding_head
  ON compute_external_pool_adapter_provider_runtime_readiness_receipts(provider_binding_id,sequence DESC,readiness_receipt_id);
CREATE INDEX IF NOT EXISTS idx_v270_provider_runtime_readiness_expiry
  ON compute_external_pool_adapter_provider_runtime_readiness_receipts(expires_at);
CREATE INDEX IF NOT EXISTS idx_v270_provider_runtime_readiness_v268
  ON compute_external_pool_adapter_provider_runtime_readiness_receipts(runtime_compatibility_verification_receipt_id,runtime_compatibility_verification_receipt_digest);
