CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_provider_runtime_readiness_receipts (
  readiness_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(readiness_receipt_id)) BETWEEN 1 AND 240 AND readiness_receipt_id=trim(readiness_receipt_id)),
  readiness_receipt_schema TEXT NOT NULL CHECK(readiness_receipt_schema='compute_federation.external_pool_adapter_provider_runtime_readiness_receipt.v1'),
  readiness_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(readiness_receipt_digest)=64 AND readiness_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  readiness_material_digest TEXT NOT NULL CHECK(length(readiness_material_digest)=64 AND readiness_material_digest NOT GLOB '*[^0-9a-f]*'),
  readiness_receipt_json TEXT NOT NULL CHECK(json_valid(readiness_receipt_json) AND json_type(readiness_receipt_json)='object' AND length(CAST(readiness_receipt_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  policy_id TEXT NOT NULL CHECK(policy_id='external_pool_adapter_provider_runtime_readiness_policy_v1'),
  policy_revision INTEGER NOT NULL CHECK(policy_revision=1),
  policy_digest TEXT NOT NULL CHECK(policy_digest=__POLICY_DIGEST_SQL__),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 240 AND registry_release_id=trim(registry_release_id)),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_material_digest TEXT NOT NULL CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  installation_receipt_id TEXT NOT NULL CHECK(length(trim(installation_receipt_id)) BETWEEN 1 AND 240 AND installation_receipt_id=trim(installation_receipt_id)),
  installation_receipt_digest TEXT NOT NULL CHECK(length(installation_receipt_digest)=64 AND installation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  candidate_id TEXT NOT NULL CHECK(length(trim(candidate_id)) BETWEEN 1 AND 240 AND candidate_id=trim(candidate_id)),
  candidate_digest TEXT NOT NULL CHECK(length(candidate_digest)=64 AND candidate_digest NOT GLOB '*[^0-9a-f]*'),
  delegation_id TEXT NOT NULL CHECK(length(trim(delegation_id)) BETWEEN 1 AND 240 AND delegation_id=trim(delegation_id)),
  delegation_digest TEXT NOT NULL CHECK(length(delegation_digest)=64 AND delegation_digest NOT GLOB '*[^0-9a-f]*'),
  profile_id TEXT NOT NULL CHECK(length(trim(profile_id)) BETWEEN 1 AND 240 AND profile_id=trim(profile_id)),
  profile_digest TEXT NOT NULL CHECK(length(profile_digest)=64 AND profile_digest NOT GLOB '*[^0-9a-f]*'),
  target_id TEXT NOT NULL CHECK(length(trim(target_id)) BETWEEN 1 AND 240 AND target_id=trim(target_id)),
  target_digest TEXT NOT NULL CHECK(length(target_digest)=64 AND target_digest NOT GLOB '*[^0-9a-f]*'),
  companion_id TEXT NOT NULL CHECK(length(trim(companion_id)) BETWEEN 1 AND 240 AND companion_id=trim(companion_id)),
  companion_digest TEXT NOT NULL CHECK(length(companion_digest)=64 AND companion_digest NOT GLOB '*[^0-9a-f]*'),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 240 AND provider_id=trim(provider_id)),
  provider_policy_revision INTEGER NOT NULL CHECK(typeof(provider_policy_revision)='integer' AND provider_policy_revision BETWEEN 1 AND 9007199254740991),
  provider_digest TEXT NOT NULL CHECK(length(provider_digest)=64 AND provider_digest NOT GLOB '*[^0-9a-f]*'),
  provider_status TEXT NOT NULL CHECK(provider_status='registering'),
  vulnerability_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(vulnerability_reattestation_receipt_id)) BETWEEN 1 AND 240 AND vulnerability_reattestation_receipt_id=trim(vulnerability_reattestation_receipt_id)),
  vulnerability_reattestation_receipt_digest TEXT NOT NULL CHECK(length(vulnerability_reattestation_receipt_digest)=64 AND vulnerability_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(sandbox_reattestation_receipt_id)) BETWEEN 1 AND 240 AND sandbox_reattestation_receipt_id=trim(sandbox_reattestation_receipt_id)),
  sandbox_reattestation_receipt_digest TEXT NOT NULL CHECK(length(sandbox_reattestation_receipt_digest)=64 AND sandbox_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  credential_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(credential_reattestation_receipt_id)) BETWEEN 1 AND 240 AND credential_reattestation_receipt_id=trim(credential_reattestation_receipt_id)),
  credential_reattestation_receipt_digest TEXT NOT NULL CHECK(length(credential_reattestation_receipt_digest)=64 AND credential_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_compatibility_verification_receipt_id TEXT NOT NULL CHECK(length(trim(runtime_compatibility_verification_receipt_id)) BETWEEN 1 AND 240 AND runtime_compatibility_verification_receipt_id=trim(runtime_compatibility_verification_receipt_id)),
  runtime_compatibility_verification_receipt_digest TEXT NOT NULL CHECK(length(runtime_compatibility_verification_receipt_digest)=64 AND runtime_compatibility_verification_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  launch_policy_digest TEXT NOT NULL CHECK(length(launch_policy_digest)=64 AND launch_policy_digest NOT GLOB '*[^0-9a-f]*'),
  target_policy_digest TEXT NOT NULL CHECK(length(target_policy_digest)=64 AND target_policy_digest NOT GLOB '*[^0-9a-f]*'),
  entrypoint_capsule_policy_digest TEXT NOT NULL CHECK(length(entrypoint_capsule_policy_digest)=64 AND entrypoint_capsule_policy_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_digest TEXT NOT NULL CHECK(length(supervisor_session_policy_digest)=64 AND supervisor_session_policy_digest NOT GLOB '*[^0-9a-f]*'),
  source_capsule_sha256 TEXT NOT NULL CHECK(length(source_capsule_sha256)=64 AND source_capsule_sha256 NOT GLOB '*[^0-9a-f]*'),
  source_capsule_size_bytes INTEGER NOT NULL CHECK(typeof(source_capsule_size_bytes)='integer' AND source_capsule_size_bytes BETWEEN 1 AND 9007199254740991),
  launch_image_sha256 TEXT NOT NULL CHECK(length(launch_image_sha256)=64 AND launch_image_sha256 NOT GLOB '*[^0-9a-f]*'),
  launch_image_size_bytes INTEGER NOT NULL CHECK(typeof(launch_image_size_bytes)='integer' AND launch_image_size_bytes BETWEEN 1 AND 9007199254740991),
  runtime_custody_epoch_digest TEXT NOT NULL CHECK(length(runtime_custody_epoch_digest)=64 AND runtime_custody_epoch_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_bundle_identity_commitment TEXT NOT NULL CHECK(length(runtime_bundle_identity_commitment)=64 AND runtime_bundle_identity_commitment NOT GLOB '*[^0-9a-f]*'),
  post_cleanup_observation_commitment TEXT NOT NULL CHECK(length(post_cleanup_observation_commitment)=64 AND post_cleanup_observation_commitment NOT GLOB '*[^0-9a-f]*'),
  probe_execution_id TEXT NOT NULL UNIQUE CHECK(length(trim(probe_execution_id)) BETWEEN 1 AND 240 AND probe_execution_id=trim(probe_execution_id)),
  request_bytes INTEGER NOT NULL CHECK(typeof(request_bytes)='integer' AND request_bytes BETWEEN 1 AND 16384),
  response_bytes INTEGER NOT NULL CHECK(typeof(response_bytes)='integer' AND response_bytes BETWEEN 1 AND 65536),
  probe_checked_at TEXT NOT NULL CHECK(probe_checked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(probe_checked_at)=30 AND julianday(probe_checked_at) IS NOT NULL),
  cleanup_completed_at TEXT NOT NULL CHECK(cleanup_completed_at GLOB '????-??-??T??:??:??.?????????Z' AND length(cleanup_completed_at)=30 AND julianday(cleanup_completed_at) IS NOT NULL),
  checked_at TEXT NOT NULL CHECK(checked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(checked_at)=30 AND julianday(checked_at) IS NOT NULL),
  expires_at TEXT NOT NULL CHECK(expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(expires_at)=30 AND julianday(expires_at) IS NOT NULL),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence BETWEEN 1 AND 9007199254740991),
  predecessor_readiness_receipt_id TEXT CHECK(predecessor_readiness_receipt_id IS NULL OR (length(trim(predecessor_readiness_receipt_id)) BETWEEN 1 AND 240 AND predecessor_readiness_receipt_id=trim(predecessor_readiness_receipt_id))),
  predecessor_readiness_receipt_digest TEXT CHECK(predecessor_readiness_receipt_digest IS NULL OR (length(predecessor_readiness_receipt_digest)=64 AND predecessor_readiness_receipt_digest NOT GLOB '*[^0-9a-f]*')),
  recorded_by_actor_kind TEXT NOT NULL CHECK(recorded_by_actor_kind='platform_admin'),
  recorded_by_actor_user_id TEXT NOT NULL CHECK(length(trim(recorded_by_actor_user_id)) BETWEEN 1 AND 240 AND recorded_by_actor_user_id=trim(recorded_by_actor_user_id)),
  recorded_at TEXT NOT NULL CHECK(recorded_at=checked_at),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_provider_runtime_readiness'),
  evidence_scope TEXT NOT NULL CHECK(evidence_scope='v270_server_owned_provider_specific_authenticated_no_work_post_cleanup_observation_v1'),
  receipt_status TEXT NOT NULL CHECK(receipt_status='post_cleanup_runtime_readiness_recorded_no_activation_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  observed_readiness_json TEXT NOT NULL CHECK(observed_readiness_json='{"activation_ready":false,"broker_connect_ready":true,"ipc_session_ready":true,"process_spawn_ready":true,"runtime_launch_ready":true,"secret_delivery_ready":true,"upstream_probe_observed":true}'),
  CHECK((predecessor_readiness_receipt_id IS NULL)=(predecessor_readiness_receipt_digest IS NULL)),
  CHECK((sequence=1)=(predecessor_readiness_receipt_id IS NULL)),
  CHECK(probe_checked_at<=cleanup_completed_at AND cleanup_completed_at<=checked_at AND checked_at<expires_at),
  CHECK(runtime_custody_epoch_digest<>runtime_bundle_identity_commitment AND runtime_custody_epoch_digest<>post_cleanup_observation_commitment AND runtime_bundle_identity_commitment<>post_cleanup_observation_commitment),
  CHECK(source_capsule_sha256<>launch_image_sha256),
  UNIQUE(provider_binding_id,sequence),
  UNIQUE(predecessor_readiness_receipt_id),
  UNIQUE(idempotency_scope,idempotency_key),
  UNIQUE(readiness_receipt_id,readiness_receipt_digest),
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(installation_receipt_id) REFERENCES compute_external_pool_adapter_installation_receipts(installation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(candidate_id,candidate_digest) REFERENCES compute_external_pool_provider_activation_candidates(candidate_id,candidate_digest) ON DELETE RESTRICT,
  FOREIGN KEY(delegation_id,delegation_digest) REFERENCES compute_external_pool_provider_activation_delegations(delegation_id,delegation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(profile_id,profile_digest) REFERENCES compute_external_pool_adapter_runtime_launch_profiles(profile_id,profile_digest) ON DELETE RESTRICT,
  FOREIGN KEY(target_id,target_digest) REFERENCES compute_external_pool_adapter_upstream_transport_targets(target_id,target_digest) ON DELETE RESTRICT,
  FOREIGN KEY(companion_id,companion_digest) REFERENCES compute_external_pool_adapter_supervisor_session_policy_companions(companion_id,companion_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT,
  FOREIGN KEY(vulnerability_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_vulnerability_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(sandbox_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_sandbox_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(credential_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_credential_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(runtime_compatibility_verification_receipt_id,runtime_compatibility_verification_receipt_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_receipts(verification_receipt_id,verification_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_readiness_receipt_id,predecessor_readiness_receipt_digest) REFERENCES compute_external_pool_adapter_provider_runtime_readiness_receipts(readiness_receipt_id,readiness_receipt_digest) ON DELETE RESTRICT
);
