CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_provider_runtime_readiness_revocations (
  revocation_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(revocation_receipt_id)) BETWEEN 1 AND 240 AND revocation_receipt_id=trim(revocation_receipt_id)),
  revocation_receipt_schema TEXT NOT NULL CHECK(revocation_receipt_schema='compute_federation.external_pool_adapter_provider_runtime_readiness_revocation_receipt.v1'),
  revocation_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_receipt_digest)=64 AND revocation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_material_digest TEXT NOT NULL CHECK(length(revocation_material_digest)=64 AND revocation_material_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_receipt_json TEXT NOT NULL CHECK(json_valid(revocation_receipt_json) AND json_type(revocation_receipt_json)='object' AND length(CAST(revocation_receipt_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  readiness_receipt_id TEXT NOT NULL UNIQUE CHECK(length(trim(readiness_receipt_id)) BETWEEN 1 AND 240 AND readiness_receipt_id=trim(readiness_receipt_id)),
  readiness_receipt_digest TEXT NOT NULL CHECK(length(readiness_receipt_digest)=64 AND readiness_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  candidate_id TEXT NOT NULL CHECK(length(trim(candidate_id)) BETWEEN 1 AND 240 AND candidate_id=trim(candidate_id)),
  candidate_digest TEXT NOT NULL CHECK(length(candidate_digest)=64 AND candidate_digest NOT GLOB '*[^0-9a-f]*'),
  profile_id TEXT NOT NULL CHECK(length(trim(profile_id)) BETWEEN 1 AND 240 AND profile_id=trim(profile_id)),
  profile_digest TEXT NOT NULL CHECK(length(profile_digest)=64 AND profile_digest NOT GLOB '*[^0-9a-f]*'),
  target_id TEXT NOT NULL CHECK(length(trim(target_id)) BETWEEN 1 AND 240 AND target_id=trim(target_id)),
  target_digest TEXT NOT NULL CHECK(length(target_digest)=64 AND target_digest NOT GLOB '*[^0-9a-f]*'),
  companion_id TEXT NOT NULL CHECK(length(trim(companion_id)) BETWEEN 1 AND 240 AND companion_id=trim(companion_id)),
  companion_digest TEXT NOT NULL CHECK(length(companion_digest)=64 AND companion_digest NOT GLOB '*[^0-9a-f]*'),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 240 AND provider_id=trim(provider_id)),
  revoked_by_actor_kind TEXT NOT NULL CHECK(revoked_by_actor_kind IN ('provider_owner','platform_admin')),
  revoked_by_actor_user_id TEXT NOT NULL CHECK(length(trim(revoked_by_actor_user_id)) BETWEEN 1 AND 240 AND revoked_by_actor_user_id=trim(revoked_by_actor_user_id)),
  reason TEXT NOT NULL CHECK(length(reason) BETWEEN 12 AND 500 AND reason=trim(reason)),
  revoked_at TEXT NOT NULL CHECK(revoked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=revoked_at),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_provider_runtime_readiness_revocation'),
  revocation_status TEXT NOT NULL CHECK(revocation_status='provider_runtime_readiness_revoked_historical_only'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_observed":false}'),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(readiness_receipt_id,readiness_receipt_digest) REFERENCES compute_external_pool_adapter_provider_runtime_readiness_receipts(readiness_receipt_id,readiness_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(candidate_id,candidate_digest) REFERENCES compute_external_pool_provider_activation_candidates(candidate_id,candidate_digest) ON DELETE RESTRICT,
  FOREIGN KEY(profile_id,profile_digest) REFERENCES compute_external_pool_adapter_runtime_launch_profiles(profile_id,profile_digest) ON DELETE RESTRICT,
  FOREIGN KEY(target_id,target_digest) REFERENCES compute_external_pool_adapter_upstream_transport_targets(target_id,target_digest) ON DELETE RESTRICT,
  FOREIGN KEY(companion_id,companion_digest) REFERENCES compute_external_pool_adapter_supervisor_session_policy_companions(companion_id,companion_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT
);
