use homecli_proto::{
    ModelCapability, NodeDevRuntimeProfile, NodeHardwareProfile, NodeLifecycleReport,
    NodeStorageProfile,
};
use serde::Serialize;

#[derive(Serialize)]
pub(super) struct PublicNodeResponse {
    pub agent_id: String,
    pub node_id: String,
    pub owner_user_id: String,
    pub device_name: Option<String>,
    pub hardware: Option<NodeHardwareProfile>,
    pub hardware_summary: String,
    pub storage: Option<NodeStorageProfile>,
    pub dev_runtime: Option<NodeDevRuntimeProfile>,
    pub lifecycle: Option<NodeLifecycleReport>,
    pub storage_ready: bool,
    pub storage_repo_url_configured: bool,
    pub display_name: String,
    pub short_id: String,
    pub models: Vec<ModelCapability>,
    pub allowed_clis: Vec<String>,
    pub cli_project_ready: bool,
    pub workspace_provision_ready: bool,
    pub ai_cli_ready: bool,
    pub route_a_ready: bool,
    pub api_runtime_ready: bool,
    pub server_runtime_ready: bool,
    pub project_count: i64,
    pub project_limit: i64,
    pub project_slots_remaining: i64,
    pub disk_free_bytes: Option<u64>,
    pub can_accept_project: bool,
    pub capacity_label: String,
    pub capacity_tone: String,
    pub capacity_warnings: Vec<String>,
    pub tts_worker_url: Option<String>,
    pub connected_at: u64,
    pub online: bool,
}

#[derive(Serialize)]
pub(super) struct MyNodeResponse {
    pub agent_id: String,
    pub node_id: String,
    pub owner_user_id: String,
    pub label: String,
    pub device_name: Option<String>,
    pub hardware: Option<NodeHardwareProfile>,
    pub hardware_summary: String,
    pub storage: Option<NodeStorageProfile>,
    pub dev_runtime: Option<NodeDevRuntimeProfile>,
    pub lifecycle: Option<NodeLifecycleReport>,
    pub storage_ready: bool,
    pub storage_repo_url_configured: bool,
    pub display_name: String,
    pub short_id: String,
    pub models: Vec<ModelCapability>,
    pub allowed_clis: Vec<String>,
    pub allowed_cwds: Vec<String>,
    pub cli_project_ready: bool,
    pub workspace_provision_ready: bool,
    pub ai_cli_ready: bool,
    pub route_a_ready: bool,
    pub api_runtime_ready: bool,
    pub server_runtime_ready: bool,
    pub project_count: i64,
    pub project_limit: i64,
    pub project_slots_remaining: i64,
    pub disk_free_bytes: Option<u64>,
    pub can_accept_project: bool,
    pub capacity_label: String,
    pub capacity_tone: String,
    pub capacity_warnings: Vec<String>,
    pub connected_at: u64,
    pub created_at: String,
    pub online: bool,
    pub registry_online: bool,
    pub cli_connected: bool,
}
