CREATE TABLE IF NOT EXISTS compute_external_pool_provider_activation_delegations (
  delegation_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(delegation_id)) BETWEEN 1 AND 200),
  delegation_schema TEXT NOT NULL CHECK(delegation_schema='compute_federation.external_pool_provider_activation_delegation.v1'),
  delegation_digest TEXT NOT NULL UNIQUE CHECK(length(delegation_digest)=64 AND delegation_digest NOT GLOB '*[^0-9a-f]*'),
  delegation_material_digest TEXT NOT NULL CHECK(length(delegation_material_digest)=64 AND delegation_material_digest NOT GLOB '*[^0-9a-f]*'),
  delegation_json TEXT NOT NULL CHECK(json_valid(delegation_json) AND json_type(delegation_json)='object' AND length(CAST(delegation_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 200),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 200),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 200),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 200),
  provider_owner_account_id TEXT NOT NULL CHECK(length(trim(provider_owner_account_id)) BETWEEN 1 AND 200),
  provider_policy_revision INTEGER NOT NULL CHECK(typeof(provider_policy_revision)='integer' AND provider_policy_revision BETWEEN 1 AND 9007199254740991),
  provider_digest TEXT NOT NULL CHECK(length(provider_digest)=64 AND provider_digest NOT GLOB '*[^0-9a-f]*'),
  provider_status TEXT NOT NULL CHECK(provider_status='registering'),
  logical_adapter_id TEXT NOT NULL CHECK(length(trim(logical_adapter_id)) BETWEEN 1 AND 200),
  release_version TEXT NOT NULL CHECK(length(trim(release_version)) BETWEEN 1 AND 200),
  adapter_config_revision INTEGER NOT NULL CHECK(typeof(adapter_config_revision)='integer' AND adapter_config_revision BETWEEN 1 AND 9007199254740991),
  adapter_config_digest TEXT NOT NULL CHECK(length(trim(adapter_config_digest)) BETWEEN 1 AND 512 AND adapter_config_digest=trim(adapter_config_digest)),
  service_actor_id TEXT NOT NULL CHECK(length(service_actor_id)=104 AND service_actor_id GLOB 'external_pool_platform_dispatch_service_[0-9a-f]*' AND substr(service_actor_id,41) NOT GLOB '*[^0-9a-f]*'),
  service_actor_kind TEXT NOT NULL CHECK(service_actor_kind='platform_dispatch_service'),
  allowed_route_kinds_json TEXT NOT NULL CHECK(json_valid(allowed_route_kinds_json) AND json_type(allowed_route_kinds_json)='array' AND json_array_length(allowed_route_kinds_json)=1 AND json_extract(allowed_route_kinds_json,'$[0]')='server_adapter'),
  allowed_actor_phases_json TEXT NOT NULL CHECK(json_valid(allowed_actor_phases_json) AND json_type(allowed_actor_phases_json)='array' AND json_array_length(allowed_actor_phases_json)=2 AND json_extract(allowed_actor_phases_json,'$[0]')='application' AND json_extract(allowed_actor_phases_json,'$[1]')='dispatch'),
  issued_by_owner_user_id TEXT NOT NULL CHECK(length(trim(issued_by_owner_user_id)) BETWEEN 1 AND 200),
  issued_at TEXT NOT NULL CHECK(issued_at GLOB '????-??-??T??:??:??.?????????Z' AND length(issued_at)=30 AND julianday(issued_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=issued_at),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence BETWEEN 1 AND 9007199254740991),
  predecessor_delegation_id TEXT CHECK(predecessor_delegation_id IS NULL OR length(trim(predecessor_delegation_id)) BETWEEN 1 AND 200),
  predecessor_delegation_digest TEXT CHECK(predecessor_delegation_digest IS NULL OR (length(predecessor_delegation_digest)=64 AND predecessor_delegation_digest NOT GLOB '*[^0-9a-f]*')),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_provider_activation_candidate'),
  delegation_effect TEXT NOT NULL CHECK(delegation_effect='owner_delegation_recorded'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='candidate_only'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  market_effect TEXT NOT NULL CHECK(market_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  CHECK((predecessor_delegation_id IS NULL)=(predecessor_delegation_digest IS NULL)),
  UNIQUE(delegation_id,delegation_digest),
  UNIQUE(provider_binding_id,sequence),
  UNIQUE(idempotency_scope,idempotency_key),
  UNIQUE(predecessor_delegation_id),
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_delegation_id,predecessor_delegation_digest) REFERENCES compute_external_pool_provider_activation_delegations(delegation_id,delegation_digest) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_provider_activation_candidates (
  candidate_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(candidate_id)) BETWEEN 1 AND 200),
  candidate_schema TEXT NOT NULL CHECK(candidate_schema='compute_federation.external_pool_provider_activation_candidate.v1'),
  candidate_digest TEXT NOT NULL UNIQUE CHECK(length(candidate_digest)=64 AND candidate_digest NOT GLOB '*[^0-9a-f]*'),
  candidate_material_digest TEXT NOT NULL CHECK(length(candidate_material_digest)=64 AND candidate_material_digest NOT GLOB '*[^0-9a-f]*'),
  candidate_json TEXT NOT NULL CHECK(json_valid(candidate_json) AND json_type(candidate_json)='object' AND length(CAST(candidate_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  delegation_id TEXT NOT NULL CHECK(length(trim(delegation_id)) BETWEEN 1 AND 200),
  delegation_digest TEXT NOT NULL CHECK(length(delegation_digest)=64 AND delegation_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 200),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 200),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  installation_receipt_id TEXT NOT NULL CHECK(length(trim(installation_receipt_id)) BETWEEN 1 AND 200),
  installation_receipt_digest TEXT NOT NULL CHECK(length(installation_receipt_digest)=64 AND installation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 200),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 200),
  provider_owner_account_id TEXT NOT NULL CHECK(length(trim(provider_owner_account_id)) BETWEEN 1 AND 200),
  provider_policy_revision INTEGER NOT NULL CHECK(typeof(provider_policy_revision)='integer' AND provider_policy_revision BETWEEN 1 AND 9007199254740991),
  provider_digest TEXT NOT NULL CHECK(length(provider_digest)=64 AND provider_digest NOT GLOB '*[^0-9a-f]*'),
  provider_status TEXT NOT NULL CHECK(provider_status='registering'),
  logical_adapter_id TEXT NOT NULL CHECK(length(trim(logical_adapter_id)) BETWEEN 1 AND 200),
  release_version TEXT NOT NULL CHECK(length(trim(release_version)) BETWEEN 1 AND 200),
  adapter_config_revision INTEGER NOT NULL CHECK(typeof(adapter_config_revision)='integer' AND adapter_config_revision BETWEEN 1 AND 9007199254740991),
  adapter_config_digest TEXT NOT NULL CHECK(length(trim(adapter_config_digest)) BETWEEN 1 AND 512 AND adapter_config_digest=trim(adapter_config_digest)),
  implementation_digest TEXT NOT NULL CHECK(length(implementation_digest)=64 AND implementation_digest NOT GLOB '*[^0-9a-f]*'),
  capability_set_digest TEXT NOT NULL CHECK(length(capability_set_digest)=64 AND capability_set_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_digest TEXT NOT NULL CHECK(length(credential_verifier_digest)=64 AND credential_verifier_digest NOT GLOB '*[^0-9a-f]*'),
  logical_adapter_binding_digest TEXT NOT NULL CHECK(length(logical_adapter_binding_digest)=64 AND logical_adapter_binding_digest NOT GLOB '*[^0-9a-f]*'),
  logical_projection_compatibility_digest TEXT NOT NULL CHECK(length(logical_projection_compatibility_digest)=64 AND logical_projection_compatibility_digest NOT GLOB '*[^0-9a-f]*'),
  service_actor_id TEXT NOT NULL CHECK(length(service_actor_id)=104 AND service_actor_id GLOB 'external_pool_platform_dispatch_service_[0-9a-f]*' AND substr(service_actor_id,41) NOT GLOB '*[^0-9a-f]*'),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence BETWEEN 1 AND 9007199254740991),
  predecessor_candidate_id TEXT CHECK(predecessor_candidate_id IS NULL OR length(trim(predecessor_candidate_id)) BETWEEN 1 AND 200),
  predecessor_candidate_digest TEXT CHECK(predecessor_candidate_digest IS NULL OR (length(predecessor_candidate_digest)=64 AND predecessor_candidate_digest NOT GLOB '*[^0-9a-f]*')),
  checked_at TEXT NOT NULL CHECK(checked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(checked_at)=30 AND julianday(checked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=checked_at),
  candidate_status TEXT NOT NULL CHECK(candidate_status='candidate_current_not_activation_ready'),
  activation_closure_status TEXT NOT NULL CHECK(activation_closure_status='activation_closure_not_implemented'),
  candidate_effect TEXT NOT NULL CHECK(candidate_effect='activation_candidate_recorded'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='candidate_only'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  market_effect TEXT NOT NULL CHECK(market_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  CHECK((predecessor_candidate_id IS NULL)=(predecessor_candidate_digest IS NULL)),
  UNIQUE(candidate_id,candidate_digest),
  UNIQUE(provider_binding_id,sequence),
  UNIQUE(delegation_id),
  UNIQUE(predecessor_candidate_id),
  FOREIGN KEY(delegation_id,delegation_digest) REFERENCES compute_external_pool_provider_activation_delegations(delegation_id,delegation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(installation_receipt_id) REFERENCES compute_external_pool_adapter_installation_receipts(installation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_candidate_id,predecessor_candidate_digest) REFERENCES compute_external_pool_provider_activation_candidates(candidate_id,candidate_digest) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_provider_activation_delegation_revocations (
  revocation_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(revocation_id)) BETWEEN 1 AND 200),
  revocation_schema TEXT NOT NULL CHECK(revocation_schema='compute_federation.external_pool_provider_activation_delegation_revocation.v1'),
  revocation_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_digest)=64 AND revocation_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_material_digest TEXT NOT NULL CHECK(length(revocation_material_digest)=64 AND revocation_material_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_json TEXT NOT NULL CHECK(json_valid(revocation_json) AND json_type(revocation_json)='object' AND length(CAST(revocation_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  delegation_id TEXT NOT NULL CHECK(length(trim(delegation_id)) BETWEEN 1 AND 200),
  delegation_digest TEXT NOT NULL CHECK(length(delegation_digest)=64 AND delegation_digest NOT GLOB '*[^0-9a-f]*'),
  candidate_id TEXT NOT NULL CHECK(length(trim(candidate_id)) BETWEEN 1 AND 200),
  candidate_digest TEXT NOT NULL CHECK(length(candidate_digest)=64 AND candidate_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 200),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 200),
  revoked_by_owner_user_id TEXT NOT NULL CHECK(length(trim(revoked_by_owner_user_id)) BETWEEN 1 AND 200),
  reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 1 AND 500 AND reason=trim(reason)),
  revoked_at TEXT NOT NULL CHECK(revoked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=revoked_at),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_provider_activation_delegation_revocation'),
  revocation_effect TEXT NOT NULL CHECK(revocation_effect='owner_delegation_revoked'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  market_effect TEXT NOT NULL CHECK(market_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  UNIQUE(revocation_id,revocation_digest),
  UNIQUE(delegation_id),
  UNIQUE(candidate_id),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(delegation_id,delegation_digest) REFERENCES compute_external_pool_provider_activation_delegations(delegation_id,delegation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(candidate_id,candidate_digest) REFERENCES compute_external_pool_provider_activation_candidates(candidate_id,candidate_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_external_pool_provider_activation_delegation_binding
  ON compute_external_pool_provider_activation_delegations(provider_binding_id,sequence DESC,delegation_id);
CREATE INDEX IF NOT EXISTS idx_external_pool_provider_activation_candidate_provider
  ON compute_external_pool_provider_activation_candidates(provider_id,checked_at DESC,candidate_id);
CREATE INDEX IF NOT EXISTS idx_external_pool_provider_activation_revocation_provider
  ON compute_external_pool_provider_activation_delegation_revocations(provider_id,revoked_at DESC,revocation_id);
