CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_provider_active_successor_receipts (
  active_successor_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(active_successor_receipt_id)) BETWEEN 1 AND 240 AND active_successor_receipt_id=trim(active_successor_receipt_id)),
  active_successor_receipt_schema TEXT NOT NULL CHECK(active_successor_receipt_schema='compute_federation.external_pool_adapter_provider_active_successor_receipt.v1'),
  receipt_digest TEXT NOT NULL UNIQUE CHECK(length(receipt_digest)=64 AND receipt_digest NOT GLOB '*[^0-9a-f]*'),
  receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json) AND json_type(receipt_json)='object' AND length(CAST(receipt_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  activation_root_digest TEXT NOT NULL CHECK(length(activation_root_digest)=64 AND activation_root_digest NOT GLOB '*[^0-9a-f]*'),
  successor_sequence INTEGER NOT NULL CHECK(typeof(successor_sequence)='integer' AND successor_sequence BETWEEN 1 AND 9007199254740991),
  predecessor_active_successor_receipt_id TEXT CHECK(predecessor_active_successor_receipt_id IS NULL OR (length(trim(predecessor_active_successor_receipt_id)) BETWEEN 1 AND 240 AND predecessor_active_successor_receipt_id=trim(predecessor_active_successor_receipt_id))),
  predecessor_active_successor_receipt_digest TEXT CHECK(predecessor_active_successor_receipt_digest IS NULL OR (length(predecessor_active_successor_receipt_digest)=64 AND predecessor_active_successor_receipt_digest NOT GLOB '*[^0-9a-f]*')),
  activation_root_json TEXT NOT NULL CHECK(json_valid(activation_root_json) AND json_type(activation_root_json)='object' AND length(CAST(activation_root_json AS BLOB))<=1048576),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 240 AND provider_id=trim(provider_id)),
  provider_owner_account_id TEXT NOT NULL CHECK(length(trim(provider_owner_account_id)) BETWEEN 1 AND 240 AND provider_owner_account_id=trim(provider_owner_account_id)),
  source_registering_provider_id TEXT NOT NULL CHECK(length(trim(source_registering_provider_id)) BETWEEN 1 AND 240 AND source_registering_provider_id=trim(source_registering_provider_id)),
  source_registering_provider_policy_revision INTEGER NOT NULL CHECK(typeof(source_registering_provider_policy_revision)='integer' AND source_registering_provider_policy_revision BETWEEN 1 AND 9007199254740991),
  source_registering_provider_json TEXT NOT NULL CHECK(json_valid(source_registering_provider_json) AND json_type(source_registering_provider_json)='object' AND length(CAST(source_registering_provider_json AS BLOB))<=1048576),
  source_registering_provider_digest TEXT NOT NULL CHECK(length(source_registering_provider_digest)=64 AND source_registering_provider_digest NOT GLOB '*[^0-9a-f]*'),
  initial_active_provider_id TEXT NOT NULL CHECK(length(trim(initial_active_provider_id)) BETWEEN 1 AND 240 AND initial_active_provider_id=trim(initial_active_provider_id)),
  initial_active_provider_policy_revision INTEGER NOT NULL CHECK(typeof(initial_active_provider_policy_revision)='integer' AND initial_active_provider_policy_revision BETWEEN 1 AND 9007199254740991),
  initial_active_provider_json TEXT NOT NULL CHECK(json_valid(initial_active_provider_json) AND json_type(initial_active_provider_json)='object' AND length(CAST(initial_active_provider_json AS BLOB))<=1048576),
  initial_active_provider_digest TEXT NOT NULL CHECK(length(initial_active_provider_digest)=64 AND initial_active_provider_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 240 AND registry_release_id=trim(registry_release_id)),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_material_digest TEXT NOT NULL CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  installation_receipt_id TEXT NOT NULL CHECK(length(trim(installation_receipt_id)) BETWEEN 1 AND 240 AND installation_receipt_id=trim(installation_receipt_id)),
  installation_receipt_digest TEXT NOT NULL CHECK(length(installation_receipt_digest)=64 AND installation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  candidate_id TEXT NOT NULL CHECK(length(trim(candidate_id)) BETWEEN 1 AND 240 AND candidate_id=trim(candidate_id)),
  candidate_digest TEXT NOT NULL CHECK(length(candidate_digest)=64 AND candidate_digest NOT GLOB '*[^0-9a-f]*'),
  delegation_id TEXT NOT NULL CHECK(length(trim(delegation_id)) BETWEEN 1 AND 240 AND delegation_id=trim(delegation_id)),
  delegation_digest TEXT NOT NULL CHECK(length(delegation_digest)=64 AND delegation_digest NOT GLOB '*[^0-9a-f]*'),
  service_actor_id TEXT NOT NULL CHECK(length(trim(service_actor_id)) BETWEEN 1 AND 240 AND service_actor_id=trim(service_actor_id)),
  logical_adapter_id TEXT NOT NULL CHECK(length(trim(logical_adapter_id)) BETWEEN 1 AND 240 AND logical_adapter_id=trim(logical_adapter_id)),
  logical_adapter_binding_digest TEXT NOT NULL CHECK(length(logical_adapter_binding_digest)=64 AND logical_adapter_binding_digest NOT GLOB '*[^0-9a-f]*'),
  logical_projection_compatibility_digest TEXT NOT NULL CHECK(length(logical_projection_compatibility_digest)=64 AND logical_projection_compatibility_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 240 AND route_adapter_projection_id=trim(route_adapter_projection_id)),
  profile_id TEXT NOT NULL CHECK(length(trim(profile_id)) BETWEEN 1 AND 240 AND profile_id=trim(profile_id)),
  profile_digest TEXT NOT NULL CHECK(length(profile_digest)=64 AND profile_digest NOT GLOB '*[^0-9a-f]*'),
  launch_policy_digest TEXT NOT NULL CHECK(length(launch_policy_digest)=64 AND launch_policy_digest NOT GLOB '*[^0-9a-f]*'),
  target_id TEXT NOT NULL CHECK(length(trim(target_id)) BETWEEN 1 AND 240 AND target_id=trim(target_id)),
  target_digest TEXT NOT NULL CHECK(length(target_digest)=64 AND target_digest NOT GLOB '*[^0-9a-f]*'),
  target_policy_digest TEXT NOT NULL CHECK(length(target_policy_digest)=64 AND target_policy_digest NOT GLOB '*[^0-9a-f]*'),
  companion_id TEXT NOT NULL CHECK(length(trim(companion_id)) BETWEEN 1 AND 240 AND companion_id=trim(companion_id)),
  companion_digest TEXT NOT NULL CHECK(length(companion_digest)=64 AND companion_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_digest TEXT NOT NULL CHECK(length(supervisor_session_policy_digest)=64 AND supervisor_session_policy_digest NOT GLOB '*[^0-9a-f]*'),
  entrypoint_capsule_policy_digest TEXT NOT NULL CHECK(length(entrypoint_capsule_policy_digest)=64 AND entrypoint_capsule_policy_digest NOT GLOB '*[^0-9a-f]*'),
  launch_image_sha256 TEXT NOT NULL CHECK(length(launch_image_sha256)=64 AND launch_image_sha256 NOT GLOB '*[^0-9a-f]*'),
  task_protocol_profile_digest TEXT NOT NULL CHECK(length(task_protocol_profile_digest)=64 AND task_protocol_profile_digest NOT GLOB '*[^0-9a-f]*'),
  lane_subject_digest TEXT NOT NULL CHECK(length(lane_subject_digest)=64 AND lane_subject_digest NOT GLOB '*[^0-9a-f]*'),
  task_production_carrier_policy_digest TEXT NOT NULL CHECK(task_production_carrier_policy_digest='0e2f1ee192d4701c09327a94a0a30de8fe9714c049231f8a89eeb0d4c896645b'),
  evidence_provider_id TEXT NOT NULL CHECK(length(trim(evidence_provider_id)) BETWEEN 1 AND 240 AND evidence_provider_id=trim(evidence_provider_id)),
  evidence_provider_policy_revision INTEGER NOT NULL CHECK(typeof(evidence_provider_policy_revision)='integer' AND evidence_provider_policy_revision BETWEEN 1 AND 9007199254740991),
  evidence_provider_json TEXT NOT NULL CHECK(json_valid(evidence_provider_json) AND json_type(evidence_provider_json)='object' AND length(CAST(evidence_provider_json AS BLOB))<=1048576),
  evidence_provider_digest TEXT NOT NULL CHECK(length(evidence_provider_digest)=64 AND evidence_provider_digest NOT GLOB '*[^0-9a-f]*'),
  reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(reattestation_receipt_id)) BETWEEN 1 AND 240 AND reattestation_receipt_id=trim(reattestation_receipt_id)),
  reattestation_receipt_digest TEXT NOT NULL CHECK(length(reattestation_receipt_digest)=64 AND reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  credential_observed_provider_id TEXT NOT NULL CHECK(length(trim(credential_observed_provider_id)) BETWEEN 1 AND 240 AND credential_observed_provider_id=trim(credential_observed_provider_id)),
  credential_observed_provider_policy_revision INTEGER NOT NULL CHECK(typeof(credential_observed_provider_policy_revision)='integer' AND credential_observed_provider_policy_revision BETWEEN 1 AND 9007199254740991),
  credential_observed_provider_json TEXT NOT NULL CHECK(json_valid(credential_observed_provider_json) AND json_type(credential_observed_provider_json)='object' AND length(CAST(credential_observed_provider_json AS BLOB))<=1048576),
  credential_observed_provider_digest TEXT NOT NULL CHECK(length(credential_observed_provider_digest)=64 AND credential_observed_provider_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_observation_id TEXT NOT NULL UNIQUE CHECK(length(trim(runtime_observation_id)) BETWEEN 1 AND 240 AND runtime_observation_id=trim(runtime_observation_id)),
  runtime_observation_digest TEXT NOT NULL UNIQUE CHECK(length(runtime_observation_digest)=64 AND runtime_observation_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_observed_provider_id TEXT NOT NULL CHECK(length(trim(runtime_observed_provider_id)) BETWEEN 1 AND 240 AND runtime_observed_provider_id=trim(runtime_observed_provider_id)),
  runtime_observed_provider_policy_revision INTEGER NOT NULL CHECK(typeof(runtime_observed_provider_policy_revision)='integer' AND runtime_observed_provider_policy_revision BETWEEN 1 AND 9007199254740991),
  runtime_observed_provider_json TEXT NOT NULL CHECK(json_valid(runtime_observed_provider_json) AND json_type(runtime_observed_provider_json)='object' AND length(CAST(runtime_observed_provider_json AS BLOB))<=1048576),
  runtime_observed_provider_digest TEXT NOT NULL CHECK(length(runtime_observed_provider_digest)=64 AND runtime_observed_provider_digest NOT GLOB '*[^0-9a-f]*'),
  observation_started_at TEXT NOT NULL CHECK(observation_started_at GLOB '????-??-??T??:??:??.?????????Z' AND length(observation_started_at)=30 AND julianday(observation_started_at) IS NOT NULL),
  observation_completed_at TEXT NOT NULL CHECK(observation_completed_at GLOB '????-??-??T??:??:??.?????????Z' AND length(observation_completed_at)=30 AND julianday(observation_completed_at) IS NOT NULL),
  observation_expires_at TEXT NOT NULL CHECK(observation_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(observation_expires_at)=30 AND julianday(observation_expires_at) IS NOT NULL),
  task_protocol_conformance_run_receipt_id TEXT NOT NULL CHECK(length(trim(task_protocol_conformance_run_receipt_id)) BETWEEN 1 AND 240 AND task_protocol_conformance_run_receipt_id=trim(task_protocol_conformance_run_receipt_id)),
  task_protocol_conformance_run_receipt_digest TEXT NOT NULL CHECK(length(task_protocol_conformance_run_receipt_digest)=64 AND task_protocol_conformance_run_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  task_protocol_conformance_expires_at TEXT NOT NULL CHECK(task_protocol_conformance_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(task_protocol_conformance_expires_at)=30 AND julianday(task_protocol_conformance_expires_at) IS NOT NULL),
  process_custody_epoch_digest TEXT NOT NULL CHECK(length(process_custody_epoch_digest)=64 AND process_custody_epoch_digest NOT GLOB '*[^0-9a-f]*'),
  process_custody_nonce_digest TEXT NOT NULL UNIQUE CHECK(length(process_custody_nonce_digest)=64 AND process_custody_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  process_custody_seal_digest TEXT NOT NULL UNIQUE CHECK(length(process_custody_seal_digest)=64 AND process_custody_seal_digest NOT GLOB '*[^0-9a-f]*'),
  activation_witness_id TEXT NOT NULL CHECK(length(trim(activation_witness_id)) BETWEEN 1 AND 240 AND activation_witness_id=trim(activation_witness_id)),
  activation_witness_digest TEXT NOT NULL CHECK(length(activation_witness_digest)=64 AND activation_witness_digest NOT GLOB '*[^0-9a-f]*'),
  checked_at TEXT NOT NULL CHECK(checked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(checked_at)=30 AND julianday(checked_at) IS NOT NULL),
  created_at TEXT NOT NULL CHECK(created_at=checked_at),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  receipt_integrity_digest TEXT NOT NULL UNIQUE CHECK(length(receipt_integrity_digest)=64 AND receipt_integrity_digest NOT GLOB '*[^0-9a-f]*'),
  CHECK((predecessor_active_successor_receipt_id IS NULL)=(predecessor_active_successor_receipt_digest IS NULL)),
  CHECK((successor_sequence=1)=(predecessor_active_successor_receipt_id IS NULL)),
  CHECK(provider_id=source_registering_provider_id AND provider_id=initial_active_provider_id AND provider_id=evidence_provider_id AND provider_id=credential_observed_provider_id AND provider_id=runtime_observed_provider_id),
  CHECK(initial_active_provider_policy_revision=source_registering_provider_policy_revision+1),
  CHECK(successor_sequence<>1 OR (evidence_provider_policy_revision=initial_active_provider_policy_revision AND evidence_provider_json=initial_active_provider_json AND evidence_provider_digest=initial_active_provider_digest)),
  CHECK(successor_sequence<>1 OR json_extract(evidence_provider_json,'$.updated_at')=checked_at),
  CHECK(observation_started_at<=observation_completed_at AND observation_completed_at<=checked_at AND checked_at<observation_expires_at AND observation_expires_at<=task_protocol_conformance_expires_at),
  CHECK((julianday(observation_expires_at)-julianday(observation_completed_at))*86400.0<=15.000001),
  CHECK(process_custody_epoch_digest<>process_custody_nonce_digest AND process_custody_epoch_digest<>process_custody_seal_digest AND process_custody_epoch_digest<>receipt_integrity_digest AND process_custody_nonce_digest<>process_custody_seal_digest AND process_custody_nonce_digest<>receipt_integrity_digest AND process_custody_seal_digest<>receipt_integrity_digest),
  UNIQUE(provider_binding_id,activation_root_digest,successor_sequence),
  UNIQUE(predecessor_active_successor_receipt_id),
  UNIQUE(active_successor_receipt_id,receipt_digest),
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(installation_receipt_id) REFERENCES compute_external_pool_adapter_installation_receipts(installation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(candidate_id,candidate_digest) REFERENCES compute_external_pool_provider_activation_candidates(candidate_id,candidate_digest) ON DELETE RESTRICT,
  FOREIGN KEY(delegation_id,delegation_digest) REFERENCES compute_external_pool_provider_activation_delegations(delegation_id,delegation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(profile_id,profile_digest) REFERENCES compute_external_pool_adapter_runtime_launch_profiles(profile_id,profile_digest) ON DELETE RESTRICT,
  FOREIGN KEY(target_id,target_digest) REFERENCES compute_external_pool_adapter_upstream_transport_targets(target_id,target_digest) ON DELETE RESTRICT,
  FOREIGN KEY(companion_id,companion_digest) REFERENCES compute_external_pool_adapter_supervisor_session_policy_companions(companion_id,companion_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT,
  FOREIGN KEY(reattestation_receipt_id) REFERENCES compute_external_pool_adapter_credential_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(task_protocol_conformance_run_receipt_id,task_protocol_conformance_run_receipt_digest) REFERENCES compute_external_pool_adapter_task_protocol_conformance_run_receipts(run_receipt_id,run_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_active_successor_receipt_id,predecessor_active_successor_receipt_digest) REFERENCES compute_external_pool_adapter_provider_active_successor_receipts(active_successor_receipt_id,receipt_digest) ON DELETE RESTRICT
);
