CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_provider_active_successor_revocations (
  active_successor_revocation_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(active_successor_revocation_id)) BETWEEN 1 AND 240 AND active_successor_revocation_id=trim(active_successor_revocation_id)),
  active_successor_revocation_schema TEXT NOT NULL CHECK(active_successor_revocation_schema='compute_federation.external_pool_adapter_provider_active_successor_revocation.v1'),
  revocation_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_digest)=64 AND revocation_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_json TEXT NOT NULL CHECK(json_valid(revocation_json) AND json_type(revocation_json)='object' AND length(CAST(revocation_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  target_active_successor_receipt_id TEXT NOT NULL UNIQUE CHECK(length(trim(target_active_successor_receipt_id)) BETWEEN 1 AND 240 AND target_active_successor_receipt_id=trim(target_active_successor_receipt_id)),
  target_active_successor_receipt_digest TEXT NOT NULL CHECK(length(target_active_successor_receipt_digest)=64 AND target_active_successor_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  activation_root_digest TEXT NOT NULL CHECK(length(activation_root_digest)=64 AND activation_root_digest NOT GLOB '*[^0-9a-f]*'),
  revoked_by_actor_kind TEXT NOT NULL CHECK(revoked_by_actor_kind='platform_admin'),
  revoked_by_actor_user_id TEXT NOT NULL CHECK(length(trim(revoked_by_actor_user_id)) BETWEEN 1 AND 240 AND revoked_by_actor_user_id=trim(revoked_by_actor_user_id)),
  reason_code TEXT NOT NULL CHECK(length(reason_code) BETWEEN 3 AND 120 AND reason_code=trim(reason_code) AND reason_code NOT GLOB '*[^a-z0-9_]*'),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  idempotency_digest TEXT NOT NULL UNIQUE CHECK(length(idempotency_digest)=64 AND idempotency_digest NOT GLOB '*[^0-9a-f]*'),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_provider_active_successor_revocation'),
  confirmation_digest TEXT NOT NULL CHECK(length(confirmation_digest)=64 AND confirmation_digest NOT GLOB '*[^0-9a-f]*'),
  revoked_at TEXT NOT NULL CHECK(revoked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  process_custody_epoch_digest TEXT NOT NULL CHECK(length(process_custody_epoch_digest)=64 AND process_custody_epoch_digest NOT GLOB '*[^0-9a-f]*'),
  process_custody_nonce_digest TEXT NOT NULL UNIQUE CHECK(length(process_custody_nonce_digest)=64 AND process_custody_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  process_custody_seal_digest TEXT NOT NULL UNIQUE CHECK(length(process_custody_seal_digest)=64 AND process_custody_seal_digest NOT GLOB '*[^0-9a-f]*'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  receipt_integrity_digest TEXT NOT NULL UNIQUE CHECK(length(receipt_integrity_digest)=64 AND receipt_integrity_digest NOT GLOB '*[^0-9a-f]*'),
  CHECK(process_custody_epoch_digest<>process_custody_nonce_digest AND process_custody_epoch_digest<>process_custody_seal_digest AND process_custody_epoch_digest<>receipt_integrity_digest AND process_custody_nonce_digest<>process_custody_seal_digest AND process_custody_nonce_digest<>receipt_integrity_digest AND process_custody_seal_digest<>receipt_integrity_digest),
  UNIQUE(active_successor_revocation_id,revocation_digest),
  FOREIGN KEY(target_active_successor_receipt_id,target_active_successor_receipt_digest) REFERENCES compute_external_pool_adapter_provider_active_successor_receipts(active_successor_receipt_id,receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(revoked_by_actor_user_id) REFERENCES users(id) ON DELETE RESTRICT
);
