// Reviewed text transaction modules shared by personal and group ChatGPT sessions.
const ASSETS: &[(&str, &str)] = &[
    (
        "chatgpt_web_private_runtime_bindings.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_private_runtime_bindings.js"
        ),
    ),
    (
        "chatgpt_web_committed_owner_path.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_committed_owner_path.js"),
    ),
    (
        "chatgpt_web_committed_composer_owner.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_committed_composer_owner.js"
        ),
    ),
    (
        "chatgpt_web_private_auth_context.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_private_auth_context.js"),
    ),
    (
        "chatgpt_web_private_model_contract.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_private_model_contract.js"
        ),
    ),
    (
        "chatgpt_web_private_model_catalog.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_private_model_catalog.js"
        ),
    ),
    (
        "chatgpt_web_private_model_state.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_private_model_state.js"),
    ),
    (
        "chatgpt_web_rspack_runtime.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_rspack_runtime.js"),
    ),
    (
        "chatgpt_web_rspack_context.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_rspack_context.js"),
    ),
    (
        "chatgpt_web_rspack_submit.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_rspack_submit.js"),
    ),
    (
        "chatgpt_web_private_text_runtime_submit.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_private_text_runtime_submit.js"
        ),
    ),
    (
        "chatgpt_web_runtime_generation_state.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_runtime_generation_state.js"
        ),
    ),
    (
        "chatgpt_web_private_regenerate_contract.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_private_regenerate_contract.js"
        ),
    ),
    (
        "chatgpt_web_private_regenerate_runtime.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_private_regenerate_runtime.js"
        ),
    ),
    (
        "chatgpt_web_private_stop_runtime.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_private_stop_runtime.js"),
    ),
    (
        "chatgpt_web_fresh_text_attachments.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_fresh_text_attachments.js"
        ),
    ),
    (
        "chatgpt_web_fresh_text_attachment_identity.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_fresh_text_attachment_identity.js"
        ),
    ),
    (
        "chatgpt_web_fresh_text_request.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_fresh_text_request.js"),
    ),
    (
        "chatgpt_web_fresh_text_context.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_fresh_text_context.js"),
    ),
    (
        "chatgpt_web_private_text_input.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_private_text_input.js"),
    ),
    (
        "chatgpt_web_fresh_text_user_identity.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_fresh_text_user_identity.js"
        ),
    ),
    (
        "chatgpt_web_fresh_regenerate_context.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_fresh_regenerate_context.js"
        ),
    ),
    (
        "chatgpt_web_fresh_text_reconcile.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_fresh_text_reconcile.js"),
    ),
    (
        "chatgpt_web_fresh_text_stop.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_fresh_text_stop.js"),
    ),
    (
        "chatgpt_web_fresh_text_recovery.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_fresh_text_recovery.js"),
    ),
    (
        "chatgpt_web_fresh_text_stream.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_fresh_text_stream.js"),
    ),
    (
        "chatgpt_web_fresh_text_journal_store.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_fresh_text_journal_store.js"
        ),
    ),
    (
        "chatgpt_web_fresh_text_journal.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_fresh_text_journal.js"),
    ),
    (
        "chatgpt_web_fresh_text_recovery_context.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_fresh_text_recovery_context.js"
        ),
    ),
    (
        "chatgpt_web_fresh_text_recovery_session.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_fresh_text_recovery_session.js"
        ),
    ),
    (
        "chatgpt_web_fresh_text_receipts.js",
        include_str!("../../../../android/app/src/main/assets/chatgpt_web_fresh_text_receipts.js"),
    ),
    (
        "chatgpt_web_fresh_text_transaction.js",
        include_str!(
            "../../../../android/app/src/main/assets/chatgpt_web_fresh_text_transaction.js"
        ),
    ),
];

pub(super) fn initialization_script() -> String {
    ASSETS
        .iter()
        .map(|(name, source)| format!("window.__elonChatGptBootstrapStage = '{name}';\n{source}"))
        .collect::<Vec<_>>()
        .join("\n")
}
