CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_route_renewal_receipts (
  route_renewal_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(route_renewal_receipt_id)) BETWEEN 1 AND 160),
  route_renewal_receipt_schema TEXT NOT NULL CHECK(route_renewal_receipt_schema='compute_federation.external_pool_adapter_route_renewal.v1'),
  route_renewal_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(route_renewal_receipt_digest)=64 AND route_renewal_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  route_renewal_receipt_json TEXT NOT NULL CHECK(json_valid(route_renewal_receipt_json) AND json_type(route_renewal_receipt_json)='object' AND length(CAST(route_renewal_receipt_json AS BLOB))<=2097152),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  activation_root_digest TEXT NOT NULL CHECK(length(activation_root_digest)=64 AND activation_root_digest NOT GLOB '*[^0-9a-f]*'),
  renewal_sequence INTEGER NOT NULL CHECK(typeof(renewal_sequence)='integer' AND renewal_sequence BETWEEN 1 AND 9007199254740991),
  predecessor_route_renewal_receipt_id TEXT CHECK(predecessor_route_renewal_receipt_id IS NULL OR length(trim(predecessor_route_renewal_receipt_id)) BETWEEN 1 AND 160),
  predecessor_route_renewal_receipt_digest TEXT CHECK(predecessor_route_renewal_receipt_digest IS NULL OR (length(predecessor_route_renewal_receipt_digest)=64 AND predecessor_route_renewal_receipt_digest NOT GLOB '*[^0-9a-f]*')),
  activation_receipt_id TEXT NOT NULL CHECK(length(trim(activation_receipt_id)) BETWEEN 1 AND 240),
  activation_receipt_digest TEXT NOT NULL CHECK(length(activation_receipt_digest)=64 AND activation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  active_provider_id TEXT NOT NULL CHECK(length(trim(active_provider_id)) BETWEEN 1 AND 240),
  active_provider_policy_revision INTEGER NOT NULL CHECK(typeof(active_provider_policy_revision)='integer' AND active_provider_policy_revision BETWEEN 1 AND 9007199254740991),
  active_provider_digest TEXT NOT NULL CHECK(length(active_provider_digest)=64 AND active_provider_digest NOT GLOB '*[^0-9a-f]*'),
  executor_id TEXT NOT NULL CHECK(length(trim(executor_id)) BETWEEN 1 AND 240),
  stable_executor_binding_digest TEXT NOT NULL CHECK(length(stable_executor_binding_digest)=64 AND stable_executor_binding_digest NOT GLOB '*[^0-9a-f]*'),
  projected_v211_adapter_binding_digest TEXT NOT NULL CHECK(length(projected_v211_adapter_binding_digest)=64 AND projected_v211_adapter_binding_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 240),
  route_adapter_revision INTEGER NOT NULL CHECK(typeof(route_adapter_revision)='integer' AND route_adapter_revision BETWEEN 1 AND 9007199254740991),
  route_adapter_digest TEXT NOT NULL CHECK(length(route_adapter_digest)=64 AND route_adapter_digest NOT GLOB '*[^0-9a-f]*'),
  predecessor_service_actor_authorization_id TEXT NOT NULL CHECK(length(trim(predecessor_service_actor_authorization_id)) BETWEEN 1 AND 160),
  predecessor_service_actor_authorization_digest TEXT NOT NULL CHECK(length(predecessor_service_actor_authorization_digest)=64 AND predecessor_service_actor_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  predecessor_route_credential_id TEXT NOT NULL CHECK(length(trim(predecessor_route_credential_id)) BETWEEN 1 AND 160),
  predecessor_route_credential_revision INTEGER NOT NULL CHECK(typeof(predecessor_route_credential_revision)='integer' AND predecessor_route_credential_revision BETWEEN 1 AND 9007199254740991),
  predecessor_route_credential_digest TEXT NOT NULL CHECK(length(predecessor_route_credential_digest)=64 AND predecessor_route_credential_digest NOT GLOB '*[^0-9a-f]*'),
  predecessor_route_authorization_id TEXT NOT NULL CHECK(length(trim(predecessor_route_authorization_id)) BETWEEN 1 AND 160),
  predecessor_route_authorization_revision INTEGER NOT NULL CHECK(typeof(predecessor_route_authorization_revision)='integer' AND predecessor_route_authorization_revision BETWEEN 1 AND 9007199254740991),
  predecessor_route_authorization_digest TEXT NOT NULL CHECK(length(predecessor_route_authorization_digest)=64 AND predecessor_route_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  predecessor_route_seal_id TEXT NOT NULL CHECK(length(trim(predecessor_route_seal_id)) BETWEEN 1 AND 160),
  predecessor_route_seal_digest TEXT NOT NULL CHECK(length(predecessor_route_seal_digest)=64 AND predecessor_route_seal_digest NOT GLOB '*[^0-9a-f]*'),
  activation_genesis_successor_receipt_id TEXT NOT NULL CHECK(length(trim(activation_genesis_successor_receipt_id)) BETWEEN 1 AND 240),
  activation_genesis_successor_receipt_digest TEXT NOT NULL CHECK(length(activation_genesis_successor_receipt_digest)=64 AND activation_genesis_successor_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  credential_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(credential_reattestation_receipt_id)) BETWEEN 1 AND 240),
  credential_reattestation_receipt_digest TEXT NOT NULL CHECK(length(credential_reattestation_receipt_digest)=64 AND credential_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  service_actor_id TEXT NOT NULL CHECK(length(trim(service_actor_id)) BETWEEN 1 AND 160),
  service_actor_authorization_id TEXT NOT NULL CHECK(length(trim(service_actor_authorization_id)) BETWEEN 1 AND 160),
  service_actor_authorization_revision INTEGER NOT NULL CHECK(typeof(service_actor_authorization_revision)='integer' AND service_actor_authorization_revision BETWEEN 1 AND 9007199254740991),
  service_actor_authorization_digest TEXT NOT NULL CHECK(length(service_actor_authorization_digest)=64 AND service_actor_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  route_credential_id TEXT NOT NULL CHECK(length(trim(route_credential_id)) BETWEEN 1 AND 160),
  route_credential_revision INTEGER NOT NULL CHECK(typeof(route_credential_revision)='integer' AND route_credential_revision BETWEEN 1 AND 9007199254740991),
  route_credential_digest TEXT NOT NULL CHECK(length(route_credential_digest)=64 AND route_credential_digest NOT GLOB '*[^0-9a-f]*'),
  route_authorization_id TEXT NOT NULL CHECK(length(trim(route_authorization_id)) BETWEEN 1 AND 160),
  route_authorization_revision INTEGER NOT NULL CHECK(typeof(route_authorization_revision)='integer' AND route_authorization_revision BETWEEN 1 AND 9007199254740991),
  route_authorization_digest TEXT NOT NULL CHECK(length(route_authorization_digest)=64 AND route_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  route_capabilities_json TEXT NOT NULL CHECK(json_valid(route_capabilities_json) AND json_type(route_capabilities_json)='array' AND json_array_length(route_capabilities_json)=6),
  route_capability_count INTEGER NOT NULL CHECK(route_capability_count=6),
  route_capability_set_digest TEXT NOT NULL CHECK(length(route_capability_set_digest)=64 AND route_capability_set_digest NOT GLOB '*[^0-9a-f]*'),
  route_capability_0_id TEXT NOT NULL CHECK(length(trim(route_capability_0_id)) BETWEEN 1 AND 160),
  route_capability_0_revision INTEGER NOT NULL CHECK(route_capability_0_revision>0),
  route_capability_1_id TEXT NOT NULL CHECK(length(trim(route_capability_1_id)) BETWEEN 1 AND 160),
  route_capability_1_revision INTEGER NOT NULL CHECK(route_capability_1_revision>0),
  route_capability_2_id TEXT NOT NULL CHECK(length(trim(route_capability_2_id)) BETWEEN 1 AND 160),
  route_capability_2_revision INTEGER NOT NULL CHECK(route_capability_2_revision>0),
  route_capability_3_id TEXT NOT NULL CHECK(length(trim(route_capability_3_id)) BETWEEN 1 AND 160),
  route_capability_3_revision INTEGER NOT NULL CHECK(route_capability_3_revision>0),
  route_capability_4_id TEXT NOT NULL CHECK(length(trim(route_capability_4_id)) BETWEEN 1 AND 160),
  route_capability_4_revision INTEGER NOT NULL CHECK(route_capability_4_revision>0),
  route_capability_5_id TEXT NOT NULL CHECK(length(trim(route_capability_5_id)) BETWEEN 1 AND 160),
  route_capability_5_revision INTEGER NOT NULL CHECK(route_capability_5_revision>0),
  route_seal_id TEXT NOT NULL CHECK(length(trim(route_seal_id)) BETWEEN 1 AND 160),
  route_seal_digest TEXT NOT NULL CHECK(length(route_seal_digest)=64 AND route_seal_digest NOT GLOB '*[^0-9a-f]*'),
  authenticated_at TEXT NOT NULL CHECK(length(authenticated_at)=30 AND julianday(authenticated_at) IS NOT NULL),
  authorized_at TEXT NOT NULL CHECK(length(authorized_at)=30 AND julianday(authorized_at) IS NOT NULL),
  expires_at TEXT NOT NULL CHECK(length(expires_at)=30 AND julianday(expires_at) IS NOT NULL),
  cleanup_expires_at TEXT NOT NULL CHECK(length(cleanup_expires_at)=30 AND julianday(cleanup_expires_at) IS NOT NULL),
  evidence_checked_at TEXT NOT NULL CHECK(length(evidence_checked_at)=30 AND julianday(evidence_checked_at) IS NOT NULL),
  created_at TEXT NOT NULL CHECK(created_at=evidence_checked_at),
  delegation_id TEXT NOT NULL CHECK(length(trim(delegation_id)) BETWEEN 1 AND 240),
  delegation_digest TEXT NOT NULL CHECK(length(delegation_digest)=64 AND delegation_digest NOT GLOB '*[^0-9a-f]*'),
  renewal_policy_digest TEXT NOT NULL CHECK(length(renewal_policy_digest)=64 AND renewal_policy_digest NOT GLOB '*[^0-9a-f]*'),
  renewed_by_actor_kind TEXT NOT NULL CHECK(renewed_by_actor_kind='platform_dispatch_service'),
  renewed_by_service_actor_id TEXT NOT NULL CHECK(length(trim(renewed_by_service_actor_id)) BETWEEN 1 AND 160),
  idempotency_material_json TEXT NOT NULL CHECK(json_valid(idempotency_material_json) AND json_type(idempotency_material_json)='object'),
  idempotency_digest TEXT NOT NULL UNIQUE CHECK(length(idempotency_digest)=64 AND idempotency_digest NOT GLOB '*[^0-9a-f]*'),
  CHECK((predecessor_route_renewal_receipt_id IS NULL)=(predecessor_route_renewal_receipt_digest IS NULL)),
  CHECK((renewal_sequence=1)=(predecessor_route_renewal_receipt_id IS NULL)),
  CHECK(authenticated_at=evidence_checked_at AND authorized_at=evidence_checked_at AND evidence_checked_at<expires_at AND expires_at<cleanup_expires_at),
  CHECK(service_actor_id=renewed_by_service_actor_id),
  CHECK(route_capability_0_id='authenticated_ack' AND route_capability_1_id='authenticated_events' AND route_capability_2_id='cancel_no_start' AND route_capability_3_id='idempotent_commit' AND route_capability_4_id='prepare' AND route_capability_5_id='reconcile'),
  UNIQUE(provider_binding_id,activation_root_digest,renewal_sequence),
  UNIQUE(predecessor_route_renewal_receipt_id),
  UNIQUE(route_renewal_receipt_id,route_renewal_receipt_digest),
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(activation_receipt_id,activation_receipt_digest,activation_root_digest) REFERENCES compute_external_pool_adapter_atomic_activation_receipts(activation_receipt_id,activation_receipt_digest,activation_root_digest) ON DELETE RESTRICT,
  FOREIGN KEY(active_provider_id,active_provider_policy_revision) REFERENCES compute_provider_versions(provider_id,policy_revision) ON DELETE RESTRICT,
  FOREIGN KEY(route_adapter_projection_id,route_adapter_revision) REFERENCES compute_route_adapter_versions(adapter_id,adapter_revision) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_service_actor_authorization_id) REFERENCES compute_service_actor_authorizations(actor_authorization_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_route_credential_id,predecessor_route_credential_revision) REFERENCES compute_route_credential_versions(credential_id,credential_revision) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_route_authorization_id) REFERENCES compute_route_authorization_receipts(route_authorization_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_route_seal_id) REFERENCES compute_route_authorization_seals(seal_id) ON DELETE RESTRICT,
  FOREIGN KEY(activation_genesis_successor_receipt_id,activation_genesis_successor_receipt_digest) REFERENCES compute_external_pool_adapter_provider_active_successor_receipts(active_successor_receipt_id,receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(credential_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_credential_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(service_actor_authorization_id) REFERENCES compute_service_actor_authorizations(actor_authorization_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_credential_id,route_credential_revision) REFERENCES compute_route_credential_versions(credential_id,credential_revision) ON DELETE RESTRICT,
  FOREIGN KEY(route_authorization_id) REFERENCES compute_route_authorization_receipts(route_authorization_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_seal_id) REFERENCES compute_route_authorization_seals(seal_id) ON DELETE RESTRICT,
  FOREIGN KEY(delegation_id,delegation_digest) REFERENCES compute_external_pool_provider_activation_delegations(delegation_id,delegation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_route_renewal_receipt_id,predecessor_route_renewal_receipt_digest) REFERENCES compute_external_pool_adapter_route_renewal_receipts(route_renewal_receipt_id,route_renewal_receipt_digest) ON DELETE RESTRICT
);
