//! Production-Windows rooted Map/Lock static denominator.
//!
//! This contract deliberately excludes test-harness control flow. Each count is generated by
//! replacing every continuation in one rooted decision graph with its downstream leaves; local
//! fragment widths are never added together.

mod dynamic_quotient;
mod initialization;
mod invariants;
mod lock;
mod map;
mod model;
mod poison;
mod source;
mod source_leaf_authority;
mod terminal_descriptor;

pub(crate) use terminal_descriptor::CapabilityGapV1;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum DynamicQuotientCandidateGateErrorV1 {
    RunnerCapabilityMissing {
        count: u64,
        gap: CapabilityGapV1,
    },
    ProgramInventoryIncomplete {
        missing_member_count: u64,
        missing_group_count: u64,
    },
    DescriptorBindingCommitmentDrift {
        expected_sha256: String,
        actual_sha256: String,
    },
    Unexpected(String),
}

/// A non-authorizing pre-manifest inventory summary. Its counts are program-planning facts, not
/// `Qmap`, dynamic member coverage, a quotient manifest, or Windows execution evidence.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ExecutionProgramInventoryGateReceiptV1 {
    pub(crate) member_count: u64,
    pub(crate) program_group_count: u64,
    pub(crate) source_present_member_count: u64,
    pub(crate) source_present_group_count: u64,
    pub(crate) planned_missing_member_count: u64,
    pub(crate) planned_missing_group_count: u64,
    pub(crate) inventory_sha256: String,
}

pub(super) fn validate_map() -> Result<usize, String> {
    validate_source_owner_authority()?;
    let graph = map::graph();
    validate_root_graph(&graph, source_leaf_authority::validate_map_graph)
}

pub(super) fn validate_lock() -> Result<usize, String> {
    validate_source_owner_authority()?;
    let graph = lock::graph();
    validate_root_graph(&graph, source_leaf_authority::validate_lock_graph)
}

pub(super) fn validate_all() -> Result<(usize, usize), String> {
    validate_source_owner_authority()?;
    let map_graph = map::graph();
    let lock_graph = lock::graph();
    let map_graph_count = invariants::validate_graph(&map_graph)?;
    let lock_graph_count = invariants::validate_graph(&lock_graph)?;
    invariants::validate_cross_contract(&map_graph, &lock_graph)?;
    let map = source_leaf_authority::validate_map_graph(&map_graph)?;
    let lock = source_leaf_authority::validate_lock_graph(&lock_graph)?;
    require_same_count("Map", map_graph_count, map)?;
    require_same_count("Lock", lock_graph_count, lock)?;
    Ok((map, lock))
}

pub(super) fn validate_map_dynamic_quotient_candidate_gate(
) -> Result<(), DynamicQuotientCandidateGateErrorV1> {
    dynamic_quotient::build_map_dynamic_candidate_v1(&map::graph())
        .map(|_| ())
        .map_err(classify_dynamic_candidate_error)
}

pub(super) fn validate_lock_dynamic_quotient_candidate_gate(
) -> Result<(), DynamicQuotientCandidateGateErrorV1> {
    dynamic_quotient::build_lock_dynamic_candidate_v1(&lock::graph())
        .map(|_| ())
        .map_err(classify_dynamic_candidate_error)
}

pub(super) fn inspect_map_execution_program_inventory_gate(
) -> Result<ExecutionProgramInventoryGateReceiptV1, String> {
    let inventory = dynamic_quotient::inspect_map_execution_program_inventory_v1(&map::graph())?;
    Ok(ExecutionProgramInventoryGateReceiptV1 {
        member_count: inventory.member_count,
        program_group_count: inventory.program_group_count,
        source_present_member_count: inventory.source_present_member_count,
        source_present_group_count: inventory.source_present_group_count,
        planned_missing_member_count: inventory.planned_missing_member_count,
        planned_missing_group_count: inventory.planned_missing_group_count,
        inventory_sha256: inventory.inventory_sha256,
    })
}

fn classify_dynamic_candidate_error(
    error: dynamic_quotient::DynamicCandidateErrorV1,
) -> DynamicQuotientCandidateGateErrorV1 {
    match error {
        dynamic_quotient::DynamicCandidateErrorV1::Catalog(
            dynamic_quotient::CatalogErrorV1::RunnerCapabilityMissing { count, gap, .. },
        ) => DynamicQuotientCandidateGateErrorV1::RunnerCapabilityMissing { count, gap },
        dynamic_quotient::DynamicCandidateErrorV1::ProgramCatalogAdmission(
            dynamic_quotient::ProgramCatalogAdmissionErrorV1::PlannedProgramsMissing {
                member_count,
                group_count,
                ..
            },
        ) => DynamicQuotientCandidateGateErrorV1::ProgramInventoryIncomplete {
            missing_member_count: member_count,
            missing_group_count: group_count,
        },
        dynamic_quotient::DynamicCandidateErrorV1::Catalog(
            dynamic_quotient::CatalogErrorV1::DescriptorBindingCommitmentDrift { expected, actual },
        ) => DynamicQuotientCandidateGateErrorV1::DescriptorBindingCommitmentDrift {
            expected_sha256: expected.to_lower_hex(),
            actual_sha256: actual.to_lower_hex(),
        },
        other => DynamicQuotientCandidateGateErrorV1::Unexpected(format!("{other:?}")),
    }
}

pub(super) fn validate_source_owner_authority() -> Result<(), String> {
    super::source_owner_graph::validate_source_owner_graph().map_err(str::to_owned)
}

fn validate_root_graph(
    graph: &model::ContractGraph,
    validate_frozen: fn(&model::ContractGraph) -> Result<usize, String>,
) -> Result<usize, String> {
    let graph_count = invariants::validate_graph(graph)?;
    let frozen_count = validate_frozen(graph)?;
    let root = match graph.root_operation {
        model::RootOperation::Map => "Map",
        model::RootOperation::Lock => "Lock",
    };
    require_same_count(root, graph_count, frozen_count)?;
    Ok(frozen_count)
}

fn require_same_count(root: &str, graph: usize, frozen: usize) -> Result<(), String> {
    if graph == frozen {
        Ok(())
    } else {
        Err(format!(
            "{root} graph invariant count {graph} differs from frozen authority count {frozen}"
        ))
    }
}
