CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_runtime_launch_profiles (
  profile_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(profile_id)) BETWEEN 1 AND 240 AND profile_id=trim(profile_id)),
  profile_schema TEXT NOT NULL CHECK(profile_schema='compute_federation.external_pool_adapter_runtime_launch_profile.v1'),
  profile_digest TEXT NOT NULL UNIQUE CHECK(length(profile_digest)=64 AND profile_digest NOT GLOB '*[^0-9a-f]*'),
  profile_material_digest TEXT NOT NULL CHECK(length(profile_material_digest)=64 AND profile_material_digest NOT GLOB '*[^0-9a-f]*'),
  profile_json TEXT NOT NULL CHECK(json_valid(profile_json) AND json_type(profile_json)='object' AND length(CAST(profile_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  candidate_id TEXT NOT NULL CHECK(length(trim(candidate_id)) BETWEEN 1 AND 240 AND candidate_id=trim(candidate_id)),
  candidate_digest TEXT NOT NULL CHECK(length(candidate_digest)=64 AND candidate_digest NOT GLOB '*[^0-9a-f]*'),
  delegation_id TEXT NOT NULL CHECK(length(trim(delegation_id)) BETWEEN 1 AND 240 AND delegation_id=trim(delegation_id)),
  delegation_digest TEXT NOT NULL CHECK(length(delegation_digest)=64 AND delegation_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 240 AND registry_release_id=trim(registry_release_id)),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  installation_receipt_id TEXT NOT NULL CHECK(length(trim(installation_receipt_id)) BETWEEN 1 AND 240 AND installation_receipt_id=trim(installation_receipt_id)),
  installation_receipt_digest TEXT NOT NULL CHECK(length(installation_receipt_digest)=64 AND installation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 240 AND route_adapter_projection_id=trim(route_adapter_projection_id)),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 240 AND provider_id=trim(provider_id)),
  provider_owner_account_id TEXT NOT NULL CHECK(length(trim(provider_owner_account_id)) BETWEEN 1 AND 240 AND provider_owner_account_id=trim(provider_owner_account_id)),
  provider_policy_revision INTEGER NOT NULL CHECK(typeof(provider_policy_revision)='integer' AND provider_policy_revision BETWEEN 1 AND 9007199254740991),
  provider_digest TEXT NOT NULL CHECK(length(provider_digest)=64 AND provider_digest NOT GLOB '*[^0-9a-f]*'),
  provider_status TEXT NOT NULL CHECK(provider_status='registering'),
  logical_adapter_id TEXT NOT NULL CHECK(length(trim(logical_adapter_id)) BETWEEN 1 AND 240 AND logical_adapter_id=trim(logical_adapter_id)),
  release_version TEXT NOT NULL CHECK(length(trim(release_version)) BETWEEN 1 AND 240 AND release_version=trim(release_version)),
  adapter_config_revision INTEGER NOT NULL CHECK(typeof(adapter_config_revision)='integer' AND adapter_config_revision BETWEEN 1 AND 9007199254740991),
  adapter_config_digest TEXT NOT NULL CHECK(length(trim(adapter_config_digest)) BETWEEN 1 AND 512 AND adapter_config_digest=trim(adapter_config_digest)),
  implementation_digest TEXT NOT NULL CHECK(length(implementation_digest)=64 AND implementation_digest NOT GLOB '*[^0-9a-f]*'),
  capability_set_digest TEXT NOT NULL CHECK(length(capability_set_digest)=64 AND capability_set_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_digest TEXT NOT NULL CHECK(length(credential_verifier_digest)=64 AND credential_verifier_digest NOT GLOB '*[^0-9a-f]*'),
  credential_ref_scheme TEXT NOT NULL CHECK(credential_ref_scheme='vault_ref'),
  credential_locator_commitment TEXT NOT NULL CHECK(length(credential_locator_commitment)=64 AND credential_locator_commitment NOT GLOB '*[^0-9a-f]*'),
  service_actor_id TEXT NOT NULL CHECK(length(trim(service_actor_id)) BETWEEN 1 AND 240 AND service_actor_id=trim(service_actor_id)),
  entrypoint_relative_path TEXT NOT NULL CHECK(length(entrypoint_relative_path) BETWEEN 1 AND 160 AND entrypoint_relative_path=trim(entrypoint_relative_path)),
  entrypoint_path_digest TEXT NOT NULL CHECK(length(entrypoint_path_digest)=64 AND entrypoint_path_digest NOT GLOB '*[^0-9a-f]*'),
  entrypoint_sha256 TEXT NOT NULL CHECK(length(entrypoint_sha256)=64 AND entrypoint_sha256 NOT GLOB '*[^0-9a-f]*'),
  entrypoint_size_bytes INTEGER NOT NULL CHECK(typeof(entrypoint_size_bytes)='integer' AND entrypoint_size_bytes BETWEEN 1 AND 9007199254740991),
  entry_inventory_digest TEXT NOT NULL CHECK(length(entry_inventory_digest)=64 AND entry_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  installed_file_count INTEGER NOT NULL CHECK(typeof(installed_file_count)='integer' AND installed_file_count BETWEEN 1 AND 9007199254740991),
  installed_total_bytes INTEGER NOT NULL CHECK(typeof(installed_total_bytes)='integer' AND installed_total_bytes BETWEEN 1 AND 9007199254740991),
  launch_policy_digest TEXT NOT NULL CHECK(length(launch_policy_digest)=64 AND launch_policy_digest NOT GLOB '*[^0-9a-f]*'),
  launch_policy_json TEXT NOT NULL CHECK(json_valid(launch_policy_json) AND json_type(launch_policy_json)='object' AND length(CAST(launch_policy_json AS BLOB))<=1048576),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence BETWEEN 1 AND 9007199254740991),
  predecessor_profile_id TEXT CHECK(predecessor_profile_id IS NULL OR (length(trim(predecessor_profile_id)) BETWEEN 1 AND 240 AND predecessor_profile_id=trim(predecessor_profile_id))),
  predecessor_profile_digest TEXT CHECK(predecessor_profile_digest IS NULL OR (length(predecessor_profile_digest)=64 AND predecessor_profile_digest NOT GLOB '*[^0-9a-f]*')),
  recorded_by_actor_kind TEXT NOT NULL CHECK(recorded_by_actor_kind IN ('provider_owner','platform_admin')),
  recorded_by_actor_user_id TEXT NOT NULL CHECK(length(trim(recorded_by_actor_user_id)) BETWEEN 1 AND 240 AND recorded_by_actor_user_id=trim(recorded_by_actor_user_id)),
  recorded_at TEXT NOT NULL CHECK(recorded_at GLOB '????-??-??T??:??:??.?????????Z' AND length(recorded_at)=30 AND julianday(recorded_at) IS NOT NULL),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_runtime_launch_profile'),
  profile_status TEXT NOT NULL CHECK(profile_status='launch_profile_current_inert'),
  profile_effect TEXT NOT NULL CHECK(profile_effect='runtime_launch_profile_recorded_inert'),
  adapter_effect TEXT NOT NULL CHECK(adapter_effect='none'),
  runtime_effect TEXT NOT NULL CHECK(runtime_effect='none'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  usage_effect TEXT NOT NULL CHECK(usage_effect='none'),
  market_effect TEXT NOT NULL CHECK(market_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  CHECK((predecessor_profile_id IS NULL)=(predecessor_profile_digest IS NULL)),
  UNIQUE(profile_id,profile_digest), UNIQUE(provider_binding_id,sequence),
  UNIQUE(predecessor_profile_id), UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(candidate_id,candidate_digest) REFERENCES compute_external_pool_provider_activation_candidates(candidate_id,candidate_digest) ON DELETE RESTRICT,
  FOREIGN KEY(delegation_id,delegation_digest) REFERENCES compute_external_pool_provider_activation_delegations(delegation_id,delegation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(installation_receipt_id) REFERENCES compute_external_pool_adapter_installation_receipts(installation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_profile_id,predecessor_profile_digest) REFERENCES compute_external_pool_adapter_runtime_launch_profiles(profile_id,profile_digest) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_runtime_launch_profile_revocations (
  revocation_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(revocation_id)) BETWEEN 1 AND 240 AND revocation_id=trim(revocation_id)),
  revocation_schema TEXT NOT NULL CHECK(revocation_schema='compute_federation.external_pool_adapter_runtime_launch_profile_revocation.v1'),
  revocation_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_digest)=64 AND revocation_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_material_digest TEXT NOT NULL CHECK(length(revocation_material_digest)=64 AND revocation_material_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_json TEXT NOT NULL CHECK(json_valid(revocation_json) AND json_type(revocation_json)='object' AND length(CAST(revocation_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  profile_id TEXT NOT NULL UNIQUE CHECK(length(trim(profile_id)) BETWEEN 1 AND 240 AND profile_id=trim(profile_id)),
  profile_digest TEXT NOT NULL CHECK(length(profile_digest)=64 AND profile_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  candidate_id TEXT NOT NULL CHECK(length(trim(candidate_id)) BETWEEN 1 AND 240 AND candidate_id=trim(candidate_id)),
  candidate_digest TEXT NOT NULL CHECK(length(candidate_digest)=64 AND candidate_digest NOT GLOB '*[^0-9a-f]*'),
  revoked_by_actor_kind TEXT NOT NULL CHECK(revoked_by_actor_kind IN ('provider_owner','platform_admin')),
  revoked_by_actor_user_id TEXT NOT NULL CHECK(length(trim(revoked_by_actor_user_id)) BETWEEN 1 AND 240 AND revoked_by_actor_user_id=trim(revoked_by_actor_user_id)),
  reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 12 AND 500 AND reason=trim(reason)),
  revoked_at TEXT NOT NULL CHECK(revoked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=revoked_at),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_runtime_launch_profile_revocation'),
  revocation_effect TEXT NOT NULL CHECK(revocation_effect='runtime_launch_profile_revoked'),
  adapter_effect TEXT NOT NULL CHECK(adapter_effect='none'),
  runtime_effect TEXT NOT NULL CHECK(runtime_effect='none'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  usage_effect TEXT NOT NULL CHECK(usage_effect='none'),
  market_effect TEXT NOT NULL CHECK(market_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(profile_id,profile_digest) REFERENCES compute_external_pool_adapter_runtime_launch_profiles(profile_id,profile_digest) ON DELETE RESTRICT,
  FOREIGN KEY(candidate_id,candidate_digest) REFERENCES compute_external_pool_provider_activation_candidates(candidate_id,candidate_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_external_pool_adapter_runtime_launch_profile_genesis
  ON compute_external_pool_adapter_runtime_launch_profiles(provider_binding_id)
  WHERE predecessor_profile_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_runtime_launch_profile_head
  ON compute_external_pool_adapter_runtime_launch_profiles(provider_binding_id,sequence DESC,profile_id);
CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_runtime_launch_profile_candidate
  ON compute_external_pool_adapter_runtime_launch_profiles(candidate_id,recorded_at DESC,profile_id);
