//! Public contract for external app tool quality reports.

use serde_json::{json, Value};

pub(crate) fn public_tool_quality_report_guidance(app_id: &str) -> Option<Value> {
    match app_id {
        "fb2" => Some(json!({
            "app_id": "fb2",
            "schema": "fb2.tool_quality_report.v1",
            "status": "available",
            "endpoint": {
                "method": "GET",
                "path": "/api/external/apps/fb2/tool-executions",
                "auth": {
                    "accepted_headers": [
                        "X-Elon-External-App-Token",
                        "Authorization: Bearer <external-app-service-token>"
                    ],
                    "scope": "own_app_only",
                    "service_token_env": [
                        "ELON_EXTERNAL_APP_FB2_TOKEN",
                        "ELON_EXTERNAL_APP_TOKEN"
                    ]
                }
            },
            "query": {
                "days": {
                    "type": "integer",
                    "default": 7,
                    "range": [1, 365],
                    "meaning": "统计最近多少天的 fb2 工具执行质量。"
                },
                "limit": {
                    "type": "integer",
                    "default": 50,
                    "range": [1, 500],
                    "meaning": "返回 recent_executions 的最大条数。"
                },
                "external_group_id": {
                    "type": "string",
                    "optional": true,
                    "meaning": "只看某个 fb2 群的工具执行记录。"
                },
                "status": {
                    "type": "string",
                    "optional": true,
                    "values": ["ready", "partial", "skipped", "unavailable", "not_configured"],
                    "meaning": "只看某类主项目执行状态。"
                }
            },
            "response_shape": {
                "schema": "external_app.tool_execution_report.v1",
                "summary": {
                    "total_executions": "integer",
                    "ready_executions": "integer",
                    "partial_executions": "integer",
                    "unavailable_executions": "integer",
                    "grounding_rate": "number",
                    "weak_rate": "number",
                    "unsafe_rate": "number",
                    "source_id_count": "integer",
                    "avg_duration_ms": "number"
                },
                "recent_executions": "array of metadata rows, newest first",
                "recommendations": "array of structured next actions generated by the main project",
                "privacy": {
                    "raw_payloads_exposed": false,
                    "raw_payloads_retained_in_table": "external_app_tool_executions"
                }
            },
            "recommendation_catalog": recommendation_catalog(),
            "agent_workflow": [
                "fb2 每次改动 /api/main-project/tools/execute 后，调用本报告观察最近 1-7 天 grounding/source/latency 趋势。",
                "如果 unsafe_result_count 大于 0，先修 visibility、permission 和 source_ids，再扩大 AI 自动采纳范围。",
                "如果 grounding_rate 偏低，优先让比赛、订单、群观点工具返回稳定 source ids。",
                "如果 avg_duration_ms 偏高，fb2 先加索引、缓存或收紧返回字段；主项目保持短超时和部分结果降级。",
                "该接口面向接入质量评估，不替代用户侧 AI 回复，也不对 ASR/TTS 或 context 拉取计费。"
            ]
        })),
        _ => None,
    }
}

fn recommendation_catalog() -> Value {
    json!([
        {
            "code": "no_tool_execution_data",
            "severity": "info",
            "meaning": "筛选范围内没有工具执行记录。",
            "fb2_action": "先触发一次比赛、订单或群观点类 AI 问答，再看报告。"
        },
        {
            "code": "unsafe_tool_results_present",
            "severity": "critical",
            "meaning": "存在主项目不能用于事实回答的工具结果。",
            "fb2_action": "检查 visibility、permission、source_ids 和用户权限裁剪。"
        },
        {
            "code": "tool_runtime_unavailable",
            "severity": "warning",
            "meaning": "工具执行因为配置、服务或鉴权不可用而失败。",
            "fb2_action": "检查 base url、shared token、/api/main-project/tools/execute 健康状态。"
        },
        {
            "code": "low_grounding_rate",
            "severity": "warning",
            "meaning": "可用结果中 grounded 强证据比例偏低。",
            "fb2_action": "为比赛、订单、群观点补齐可追溯 source ids。"
        },
        {
            "code": "low_source_id_coverage",
            "severity": "warning",
            "meaning": "工具结果来源 ID 覆盖不足。",
            "fb2_action": "稳定返回 match_id、order_id、ticket_id、message_id、context_audit_id。"
        },
        {
            "code": "weak_result_rate_high",
            "severity": "info",
            "meaning": "弱证据结果占比较高。",
            "fb2_action": "补充数据新鲜度、截断状态、聚合口径和字段来源。"
        },
        {
            "code": "partial_executions_dominate",
            "severity": "info",
            "meaning": "部分成功多于完全成功。",
            "fb2_action": "按 recent_executions 抽样复盘高频失败工具。"
        },
        {
            "code": "tool_latency_high",
            "severity": "warning",
            "meaning": "fb2 工具平均执行耗时偏高。",
            "fb2_action": "给高频查询加索引、缓存或参数裁剪。"
        },
        {
            "code": "tool_quality_healthy",
            "severity": "info",
            "meaning": "当前筛选范围内没有明显工具质量告警。",
            "fb2_action": "继续观察趋势，并接入自动评测或运营面板。"
        }
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exposes_fb2_tool_quality_report_contract() {
        let contract = public_tool_quality_report_guidance("fb2").unwrap();
        assert_eq!(contract["schema"], "fb2.tool_quality_report.v1");
        assert_eq!(
            contract["endpoint"]["path"],
            "/api/external/apps/fb2/tool-executions"
        );
        assert_eq!(
            contract["response_shape"]["privacy"]["raw_payloads_exposed"],
            false
        );
        assert!(contract["recommendation_catalog"]
            .as_array()
            .unwrap()
            .iter()
            .any(|item| item["code"] == "low_grounding_rate"));
    }

    #[test]
    fn unknown_app_has_no_tool_quality_report_contract() {
        assert!(public_tool_quality_report_guidance("unknown").is_none());
    }
}
