//! Tool execution contract for external app context lookups.

use serde_json::{json, Value};

const FB2_TOOL_EXECUTE_PATH: &str = "/api/main-project/tools/execute";

pub(crate) const FB2_ALLOWED_TOOLS: &[&str] = &[
    "search_matches",
    "get_match_detail",
    "search_user_orders",
    "get_order_detail",
    "search_group_opinions",
    "group_opinion_summary",
    "match_analysis_brief",
    "opinion_memories",
    "list_opinion_adoptions",
    "opinion_adoption_summary",
    "opinion_result_reviews",
    "opinion_result_review_summary",
    "platform_orders",
    "get_context_audit",
    "context_audit_summary",
];

pub(crate) const BB64A_ALLOWED_TOOLS: &[&str] = &[
    "bb64a_doctor",
    "get_status",
    "get_config",
    "get_system_proxy_status",
    "detect_conflicts",
    "test_google",
    "test_tcp",
    "test_http_proxy",
    "test_socks5_proxy",
    "get_process_tcp",
    "get_logs",
    "get_logs_filtered",
    "force_close_proxy",
    "close_all_proxies",
    "set_system_proxy",
    "disable_system_proxy",
    "set_proxy_mode",
    "proxy_yield",
    "proxy_reclaim",
    "auto_select_best",
    "exit_app",
];

pub(crate) fn public_tool_execution_guidance(app_id: &str) -> Option<Value> {
    match app_id {
        "fb2" => Some(json!({
            "app_id": "fb2",
            "schema": "fb2.tool_execution.v1",
            "execution_status": "contract_ready",
            "transport": {
                "method": "POST",
                "path": FB2_TOOL_EXECUTE_PATH,
                "auth_header": "X-FB2-AI-CENTER-TOKEN",
                "timeout_ms": 6000,
                "idempotency": "request_id"
            },
            "allowed_tools": FB2_ALLOWED_TOOLS,
            "request_shape": {
                "request_id": "string, main-project generated id for tracing and retry dedupe",
                "tool_name": "one of allowed_tools",
                "group_id": "fb2 external group id, required for group_context tools",
                "external_user_id": "fb2 user id, required for current_user_only tools",
                "context_audit_id": "optional audit id from the current context_pack",
                "arguments": "tool-specific object, ids and filters only",
                "reason": "short natural-language reason why AI needs the tool",
                "limits": {
                    "max_items": "optional integer, fb2 may clamp",
                    "max_chars": "optional integer, fb2 may clamp"
                }
            },
            "response_shape": {
                "success": "boolean",
                "request_id": "echo request_id when possible; main project uses it for tracing",
                "data": "tool-specific object or array; must include source ids when possible",
                "error": "string when success=false",
                "generated_at": "ISO-8601 timestamp",
                "source_ids": ["match_id", "order_id", "ticket_id", "message_id", "context_audit_id"],
                "visibility": "group_context | current_user_only | single_group_lightweight_memory | match_focused_brief | single_group_persistent_opinion_index | answer_opinion_adoption_samples | answer_opinion_adoption_metrics | single_group_opinion_result_review_samples | single_group_opinion_result_review_metrics | privileged_summary | audit_metadata_only | audit_metrics_only",
                "metrics": {
                    "latency_ms": "optional integer",
                    "result_count": "optional integer",
                    "truncated": "optional boolean"
                }
            },
            "main_project_execution_result": {
                "schema": "external_app.executed_tools.v1",
                "execution_id": "fb2_exec_* generated by main project",
                "status": "ready | partial | skipped | unavailable | not_configured",
                "plan": {
                    "schema": "external_app.tool_plan.v1",
                    "strategy": "deterministic_fb2_chat_v1",
                    "planned_tools": "array with tool name, trigger, confidence and evidence",
                    "domain_scenario_selection": "fb2.domain_scenario_selection.v1; selected fb2 user scenarios with primary_tools, required_citations, permission_scope and forbidden_outputs",
                    "skipped_reasons": "why main project did not plan a tool when applicable"
                },
                "results": {
                    "description": "array of normalized per-tool results",
                    "fact_grounding_rule": "only status=ready, success=true and grounding.status=grounded may be used as strong facts",
                    "grounding": {
                        "schema": "external_app.tool_result_grounding.v1",
                        "status": "grounded | weak | unsafe | unavailable",
                        "warnings": ["missing_source_ids", "missing_visibility", "visibility_mismatch"],
                        "facts_allowed": "boolean; false for unsafe/unavailable",
                        "requires_caveat": "boolean; true for weak results"
                    }
                },
                "audit": {
                    "schema": "external_app.tool_execution_audit.v1",
                    "planned_count": "number of tools main project planned",
                    "ready_count": "number of successful tool results",
                    "source_id_count": "number of returned source ids available for answer citations",
                    "grounded_result_count": "number of ready results with grounding.status=grounded",
                    "weak_result_count": "number of ready results needing caveats",
                    "unsafe_result_count": "number of results main project must not use as facts",
                    "duration_ms": "main-project side elapsed time"
                },
                "persistence": {
                    "owner": "main_project",
                    "table": "external_app_tool_executions",
                    "purpose": "long-term evaluation of fb2 tool latency, grounding quality, source coverage and planner quality",
                    "non_blocking": true
                }
            },
            "permission_rules": [
                "current_user_only 工具必须带 external_user_id，fb2 只能返回该用户自己的订单/票据。",
                "group_context 工具必须带 group_id，fb2 只能返回该群可见的比赛和群友观点。",
                "single_group_lightweight_memory 工具必须带 group_id，只能返回本群轻量群观点摘要，不能当作比赛事实。",
                "match_focused_brief 工具必须带 group_id；有 external_user_id 时只能混入当前用户自己的订单，否则只能返回比赛和群观点。",
                "single_group_persistent_opinion_index 工具必须带 group_id，只能返回该群可见的长期观点记忆，不能当作赛果事实。",
                "answer_opinion_adoption_* 工具必须带 group_id，只能返回本群 AI 回答采纳过哪些群观点的样本或汇总。",
                "single_group_opinion_result_review_* 工具必须带 group_id，只能返回本群历史观点赛后复盘，不能用于承诺未来命中。",
                "privileged_summary 工具默认禁用；平台订单摘要必须双端开关和 platform_order_summary scope 同时允许，且只能返回匿名聚合。",
                "audit 工具只能返回来源数量、耗时、裁剪和预算指标，不返回其他用户明细。",
                "主项目不得把未执行工具的预测结果当作事实。"
            ],
            "result_grounding_rules": [
                "比赛结果必须尽量带 match_id 和 odds_updated_at。",
                "订单/票据结果必须尽量带 order_id 或 ticket_id。",
                "群友观点结果必须带 message_id。",
                "群观点摘要必须尽量带 source_message_ids；比赛分析简报必须尽量带 match_id、message_id 或当前用户 order_id。",
                "长期观点记忆结果必须带 opinion_memory_id 或 source_message_id，并标记为群友观点证据。",
                "观点采纳样本和赛后复盘样本必须尽量带 opinion_memory_id；汇总指标可以不带 source_ids，但只能作为统计口径使用。",
                "返回被截断时必须设置 metrics.truncated=true，并提示可继续按 id 查详情。"
            ]
        })),
        "bb64a" => Some(json!({
            "app_id": "bb64a",
            "schema": "bb64a.tool_execution.v1",
            "execution_status": "local_mcp_ready",
            "transport": {
                "kind": "local_mcp_via_pc_node_agent",
                "default_mcp_url": "http://127.0.0.1:17899/mcp",
                "doctor_http_url": "http://127.0.0.1:17899/debug/doctor",
                "note": "The cloud server cannot call a user's loopback address directly. Execution must be relayed by the installed local CLI/node agent or by Codex on the same PC."
            },
            "allowed_tools": BB64A_ALLOWED_TOOLS,
            "request_shape": {
                "request_id": "string, main-project generated id for tracing and retry dedupe",
                "tool_name": "one of allowed_tools",
                "external_user_id": "bb64a user id when available",
                "device_id": "Windows device id or node-agent id when available",
                "arguments": "MCP tool arguments",
                "reason": "short natural-language reason why AI needs the tool",
                "dangerous": "boolean; true for local runtime control tools such as force_close_proxy or close_all_proxies"
            },
            "response_shape": {
                "success": "boolean",
                "schema": "bb64a.doctor.v1 for bb64a_doctor snapshots",
                "data": "tool-specific object",
                "error": "string when success=false",
                "generated_at": "ISO-8601 timestamp or generated_at_unix_ms",
                "source_ids": ["local_mcp_endpoint", "device_id", "context_audit_id"],
                "visibility": "current_device_only | sanitized_support_bundle | source_node_bugfix"
            },
            "permission_rules": [
                "Read-only diagnostic tools may run after the user opens the AI troubleshooting panel.",
                "Dangerous runtime tools are intentionally allowed in the first version and must remain discoverable.",
                "The client or local node agent should record user consent and audit metadata before dangerous local changes.",
                "Raw subscription URLs, access tokens and unrelated local file contents must not be uploaded unless the user explicitly enables the sensitive diagnostic option.",
                "Source-code fixes run on BB64A source nodes, not on the end user's PC."
            ],
            "result_grounding_rules": [
                "bb64a_doctor output is the primary grounded support bundle.",
                "Use get_status and detect_conflicts as live follow-up checks after any repair action.",
                "Only treat a product bug as likely when multiple diagnostics or logs point at the BB64A runtime rather than local configuration.",
                "When escalating to source-node repair, include sanitized environment traits and exact tool outputs, not private tokens."
            ]
        })),
        _ => None,
    }
}

#[cfg(test)]
#[path = "external_app_context_tool_execution_tests.rs"]
mod tests;
