//! Vendor-neutral MCP tool contracts for the V1 open-commerce network.

use serde_json::{json, Value};

pub(crate) fn definitions() -> Vec<Value> {
    vec![
        tool(
            "open_commerce_get_overview",
            "读取当前项目的商户节点、能力、授权、最近调用、计量与审计总览。先用它了解现状；不会修改数据。",
            json!({"type":"object","properties":{},"additionalProperties":false}),
            true,
            true,
        ),
        tool(
            "open_commerce_get_development_context",
            "生成供开发代理使用的商户能力、数据来源和同步健康度上下文。不会返回平台密钥、处理器配置或原始经营数据。",
            json!({"type":"object","properties":{},"additionalProperties":false}),
            true,
            true,
        ),
        tool(
            "open_commerce_search_merchants",
            "按名称、描述或能力键搜索已发布商户节点。只返回公开资料和公开能力契约，不返回处理器配置。",
            json!({
                "type":"object",
                "properties":{
                    "query":{"type":"string","maxLength":120},
                    "capability":{"type":"string","maxLength":80},
                    "limit":{"type":"integer","minimum":1,"maximum":100,"default":20}
                },
                "additionalProperties":false
            }),
            true,
            true,
        ),
        tool(
            "open_commerce_get_merchant",
            "读取一个已发布商户节点及其当前有效能力契约；不返回处理器私有配置。",
            json!({
                "type":"object",
                "required":["merchant_id"],
                "properties":{"merchant_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            true,
            true,
        ),
        tool(
            "open_commerce_list_consumer_relationships",
            "读取当前用户在本项目持有的消费者关系凭证。只返回匿名关系标识、范围、期限和状态，不返回其他用户的凭证。",
            json!({"type":"object","properties":{},"additionalProperties":false}),
            true,
            true,
        ),
        tool(
            "open_commerce_list_merchant_relationships",
            "读取当前项目指定商户收到的消费者关系凭证。消费者身份和消费者项目始终脱敏。",
            json!({
                "type":"object",
                "required":["merchant_id"],
                "properties":{"merchant_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            true,
            true,
        ),
        tool(
            "open_commerce_list_consumer_data_requests",
            "读取当前用户在本项目发起的数据删除请求及商户履约声明。响应不包含其他消费者身份。",
            json!({"type":"object","properties":{},"additionalProperties":false}),
            true,
            true,
        ),
        tool(
            "open_commerce_list_consumer_portability_exports",
            "读取当前用户在本项目生成的可携带数据包摘要。V3 包含关系、内部续期链、数据删除请求、本人低敏偏好、历史披露和账户级调用凭证计数；不包含原始调用输入、商户数据库完整订单、联系方式、真实支付或消费者账号。",
            json!({"type":"object","properties":{},"additionalProperties":false}),
            true,
            true,
        ),
        tool(
            "open_commerce_get_consumer_portability_export",
            "读取并校验当前用户拥有的一个可携带数据包。V3 还包含本人账户级、逐条可验证的终态调用凭证和商户返回结果，不允许读取其他用户的数据包，也不把结果冒充为完整订单或支付证明。",
            json!({
                "type":"object",
                "required":["export_id"],
                "properties":{"export_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            true,
            true,
        ),
        tool(
            "open_commerce_list_merchant_data_requests",
            "读取指定商户收到的匿名消费者数据删除请求。只返回关系别名和状态，不披露消费者账号或项目。",
            json!({
                "type":"object",
                "required":["merchant_id"],
                "properties":{"merchant_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            true,
            true,
        ),
        tool(
            "open_commerce_create_merchant",
            "在当前项目创建商户节点。需要项目编辑权限；默认由平台托管，但数据仍归当前项目控制。",
            json!({
                "type":"object",
                "required":["display_name"],
                "properties":{
                    "display_name":{"type":"string","minLength":1,"maxLength":120},
                    "slug":{"type":"string","minLength":3,"maxLength":64},
                    "description":{"type":"string","maxLength":2000},
                    "node_mode":{"type":"string","enum":["platform_hosted","self_hosted","third_party_hosted"],"default":"platform_hosted"},
                    "public_profile":{"type":"object","default":{}}
                },
                "additionalProperties":false
            }),
            false,
            false,
        ),
        tool(
            "open_commerce_publish_capability",
            "为当前项目的商户发布可被 AI 发现和调用的能力。merchant_runtime 只引用当前商户经过平台验证的受控运行绑定，不接受 URL 或密钥配置。",
            json!({
                "type":"object",
                "required":["merchant_id","capability_key","display_name","handler_type"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "capability_key":{"type":"string","minLength":2,"maxLength":80},
                    "display_name":{"type":"string","minLength":1,"maxLength":120},
                    "description":{"type":"string","maxLength":2000},
                    "kind":{"type":"string","maxLength":80,"default":"information"},
                    "access_level":{"type":"string","enum":["public","authorized","owner_only"],"default":"public"},
                    "input_schema":{"type":"object","default":{}},
                    "output_schema":{"type":"object","default":{}},
                    "handler_type":{"type":"string","enum":["merchant_profile","static_json","merchant_runtime"]},
                    "handler_config":{"type":"object"},
                    "unit_price_micros":{"type":"integer","minimum":0,"default":0},
                    "currency":{"type":"string","minLength":3,"maxLength":8,"default":"CNY"},
                    "freshness_seconds":{"type":"integer","minimum":0,"default":0}
                },
                "additionalProperties":false
            }),
            false,
            false,
        ),
        tool(
            "open_commerce_set_directory_publication",
            "显式发布或撤回当前项目商户的开放目录条目。只有 published 状态才允许跨项目发现；公开响应不包含项目、所有者、运行地址、密钥或处理器配置。",
            json!({
                "type":"object",
                "required":["merchant_id","published"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "published":{"type":"boolean"}
                },
                "additionalProperties":false
            }),
            false,
            false,
        ),
        tool(
            "open_commerce_create_consumer_relationship",
            "为当前用户和已发布商户建立限时关系凭证。只授权商户关联用户主动提供的偏好或会员标识，不上传偏好原文、联系方式或订单数据。",
            json!({
                "type":"object",
                "required":["merchant_id","scopes","purpose","expires_at"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "scopes":{
                        "type":"array","minItems":1,"maxItems":2,"uniqueItems":true,
                        "items":{"type":"string","enum":["preference.remember","membership.link"]}
                    },
                    "purpose":{"type":"string","minLength":1,"maxLength":500},
                    "expires_at":{"type":"string","format":"date-time"}
                },
                "additionalProperties":false
            }),
            false,
            false,
        ),
        tool(
            "open_commerce_revoke_consumer_relationship",
            "撤销当前用户持有的一项消费者关系凭证。重复撤销保持同一结果；商户历史只能继续看到已撤销的匿名凭证。",
            json!({
                "type":"object",
                "required":["relationship_id"],
                "properties":{"relationship_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_renew_consumer_relationship",
            "为当前用户持有的一项消费者关系凭证安全续期。续期会撤销旧凭证、轮换匿名标识并继承原授权范围和用途；对同一旧凭证重复调用返回同一续期结果。",
            json!({
                "type":"object",
                "required":["relationship_id","expires_at"],
                "properties":{
                    "relationship_id":{"type":"string","minLength":1,"maxLength":120},
                    "expires_at":{"type":"string","format":"date-time"}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_create_consumer_data_erasure_request",
            "针对当前用户持有的匿名商户关系发起关联数据删除请求，并原子撤销该关系。平台只创建请求回执，不声称已删除商户外部系统数据。",
            json!({
                "type":"object",
                "required":["relationship_id"],
                "properties":{"relationship_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_create_consumer_portability_export",
            "为当前用户生成不可变的消费者可携带数据快照，并返回可验证的 SHA-256 摘要。同一幂等键始终返回原快照；新键才生成新快照。V3 包含本人低敏偏好、历史披露及账户级调用凭证；不包含原始输入、商户数据库完整订单、联系方式、真实支付或消费者账号，也不执行跨运营方导入。",
            json!({
                "type":"object",
                "required":["idempotency_key"],
                "properties":{
                    "idempotency_key":{
                        "type":"string","minLength":8,"maxLength":120,
                        "pattern":"^[A-Za-z0-9_.:-]+$"
                    }
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_withdraw_consumer_data_request",
            "在商户接单前撤回当前用户的数据删除请求。撤回不会恢复此前已撤销的关系。",
            json!({
                "type":"object",
                "required":["request_id"],
                "properties":{"request_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_decide_consumer_data_request",
            "由商户项目编辑者接受、完成或拒绝匿名数据删除请求。completed 只是商户可审计声明，不是平台验证的删除证明。",
            json!({
                "type":"object",
                "required":["merchant_id","request_id","action"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "request_id":{"type":"string","minLength":1,"maxLength":120},
                    "action":{"type":"string","enum":["accept","complete","reject"]},
                    "note":{"type":"string","maxLength":500}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_upsert_runtime",
            "为当前项目商户配置受控运行绑定。地址必须通过平台主机白名单，credential_ref 只引用服务端环境变量，不能提交明文密钥。配置后仍需单独验证。",
            json!({
                "type":"object",
                "required":["merchant_id","endpoint_base_url","credential_ref"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "endpoint_base_url":{"type":"string","format":"uri","maxLength":500},
                    "credential_ref":{"type":"string","pattern":"^OPEN_COMMERCE_RUNTIME_SECRET_[A-Z0-9_]+$","maxLength":128},
                    "manifest_sha256":{"type":"string","pattern":"^[a-f0-9]{64}$"},
                    "timeout_ms":{"type":"integer","minimum":500,"maximum":15000,"default":5000}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_verify_runtime",
            "向商户运行时发起带平台签名的健康请求，核对商户身份和能力清单摘要；验证成功后真实能力才可调用。",
            json!({
                "type":"object",
                "required":["merchant_id"],
                "properties":{"merchant_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_create_grant",
            "授权指定 AI 应用调用某个商户的一个或多个能力。可设置总调用次数或总计量金额预算；授权可随时撤销。",
            json!({
                "type":"object",
                "required":["merchant_id","grantee_app_id","scopes","purpose"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "grantee_app_id":{"type":"string","minLength":2,"maxLength":80},
                    "scopes":{"type":"array","minItems":1,"maxItems":64,"items":{"type":"string","minLength":2,"maxLength":80}},
                    "purpose":{"type":"string","minLength":1,"maxLength":500},
                    "expires_at":{"type":"string","format":"date-time"},
                    "max_invocations":{"type":"integer","minimum":1},
                    "max_amount_micros":{"type":"integer","minimum":1},
                    "budget_currency":{"type":"string","minLength":3,"maxLength":3,"default":"CNY"}
                },
                "additionalProperties":false
            }),
            false,
            false,
        ),
        tool(
            "open_commerce_upsert_rate_limit",
            "为当前项目商户的指定能力设置固定时间窗调用配额。可限定一个 App；留空则对每个外部调用主体分别执行。幂等重放和项目编辑者调试不占额度。",
            json!({
                "type":"object",
                "required":["merchant_id","capability_key","window_seconds","max_requests"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "capability_key":{"type":"string","minLength":3,"maxLength":96},
                    "requester_app_id":{"type":"string","minLength":2,"maxLength":96},
                    "window_seconds":{"type":"integer","minimum":1,"maximum":86400},
                    "max_requests":{"type":"integer","minimum":1,"maximum":1000000},
                    "enabled":{"type":"boolean","default":true}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_set_rate_limit_enabled",
            "停用或重新启用一项商户调用配额。停用指定 App 策略后，仍可能命中该能力的全部 App 策略。",
            json!({
                "type":"object",
                "required":["policy_id","enabled"],
                "properties":{
                    "policy_id":{"type":"string","minLength":1,"maxLength":120},
                    "enabled":{"type":"boolean"}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_list_app_blocks",
            "读取当前商户项目的开发者 App 封禁记录。包含已解除记录，便于审计；不会修改数据。",
            json!({"type":"object","properties":{},"additionalProperties":false}),
            true,
            true,
        ),
        tool(
            "open_commerce_block_app",
            "手动封禁一个已注册开发者 App。该操作会原子撤销此商户授予该 App 的有效授权并取消待审批申请；重复封禁保持同一记录。",
            json!({
                "type":"object",
                "required":["merchant_id","requester_app_id","reason_code"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "requester_app_id":{"type":"string","minLength":2,"maxLength":96},
                    "reason_code":{"type":"string","enum":[
                        "abusive_traffic","policy_violation","security_incident",
                        "merchant_request","other"
                    ]},
                    "reason_note":{"type":"string","maxLength":500,"default":""}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_unblock_app",
            "解除一项商户 App 封禁。旧授权不会恢复，调用方必须重新申请授权。重复解除保持已解除状态。",
            json!({
                "type":"object",
                "required":["block_id"],
                "properties":{"block_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_create_integration",
            "登记一个商户自有数据源的接入方式、授权范围和数据域。这里只登记连接事实，不接收也不保存访问令牌。",
            json!({
                "type":"object",
                "required":[
                    "merchant_id","integration_key","provider_key",
                    "display_name","connection_mode"
                ],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "integration_key":{"type":"string","minLength":3,"maxLength":96},
                    "provider_key":{"type":"string","minLength":2,"maxLength":64},
                    "display_name":{"type":"string","minLength":2,"maxLength":80},
                    "connection_mode":{
                        "type":"string",
                        "enum":["official_api","merchant_export","local_adapter","manual_import"]
                    },
                    "scopes":{
                        "type":"array","maxItems":32,
                        "items":{"type":"string","minLength":1,"maxLength":64}
                    },
                    "data_domains":{
                        "type":"array","maxItems":32,
                        "items":{"type":"string","minLength":1,"maxLength":64}
                    }
                },
                "additionalProperties":false
            }),
            false,
            false,
        ),
        tool(
            "open_commerce_set_integration_enabled",
            "停用或重新启用一个商户数据接入。重新启用只恢复为已配置状态，不能伪造连接成功。",
            json!({
                "type":"object",
                "required":["integration_id","enabled"],
                "properties":{
                    "integration_id":{"type":"string","minLength":1,"maxLength":120},
                    "enabled":{"type":"boolean"}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_record_sync_receipt",
            "由受信任适配器记录一次有界同步或健康检查结果。回执只含数量、摘要和错误码，不接收原始订单、客户或财务数据。",
            json!({
                "type":"object",
                "required":[
                    "integration_id","receipt_key","sync_kind","status",
                    "started_at","completed_at"
                ],
                "properties":{
                    "integration_id":{"type":"string","minLength":1,"maxLength":120},
                    "receipt_key":{"type":"string","minLength":3,"maxLength":128},
                    "sync_kind":{"type":"string","enum":["full","incremental","health_check"]},
                    "status":{"type":"string","enum":["succeeded","partial","failed"]},
                    "records_seen":{"type":"integer","minimum":0,"default":0},
                    "records_changed":{"type":"integer","minimum":0,"default":0},
                    "cursor_digest":{"type":"string","maxLength":128},
                    "error_code":{"type":"string","maxLength":96},
                    "started_at":{"type":"string","format":"date-time"},
                    "completed_at":{"type":"string","format":"date-time"}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_revoke_grant",
            "撤销当前项目的一项商业能力授权。重复撤销保持同一结果。",
            json!({
                "type":"object",
                "required":["grant_id"],
                "properties":{"grant_id":{"type":"string","minLength":1,"maxLength":120}},
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_prepare_action_confirmation",
            "为动作类商户能力准备一份服务端短时确认。确认绑定当前用户、App、商户、能力、授权、幂等键和输入摘要；只准备，不执行。查询能力不需要调用此工具。",
            json!({
                "type":"object",
                "required":["merchant_id","capability_key","idempotency_key"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "capability_key":{"type":"string","minLength":2,"maxLength":80},
                    "grant_id":{"type":"string","maxLength":120},
                    "idempotency_key":{"type":"string","minLength":8,"maxLength":120},
                    "input":{"type":"object","default":{}}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_confirm_action_confirmation",
            "仅在当前用户已明确同意执行准备结果所指向的经营操作后确认。确认不会执行能力；随后 open_commerce_invoke 仍须携带 confirmation_id。",
            json!({
                "type":"object",
                "required":["confirmation_id","confirmation_phrase"],
                "properties":{
                    "confirmation_id":{"type":"string","minLength":1,"maxLength":120},
                    "confirmation_phrase":{"const":"CONFIRM_ACTION"}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_invoke",
            "调用一个商户能力。调用方身份来自当前 MCP 入口，不能冒充其他应用；必须提供幂等键。动作能力还必须携带已经明确确认、与同一输入绑定的一次性 confirmation_id。返回结果、计量金额和 recorded_not_charged 状态，V1 不真实扣款。",
            json!({
                "type":"object",
                "required":["merchant_id","capability_key","idempotency_key"],
                "properties":{
                    "merchant_id":{"type":"string","minLength":1,"maxLength":120},
                    "capability_key":{"type":"string","minLength":2,"maxLength":80},
                    "grant_id":{"type":"string","maxLength":120},
                    "idempotency_key":{"type":"string","minLength":8,"maxLength":120},
                    "action_confirmation_id":{"type":"string","maxLength":120},
                    "input":{"type":"object","default":{}}
                },
                "additionalProperties":false
            }),
            false,
            true,
        ),
        tool(
            "open_commerce_list_audit",
            "读取当前项目最近的商户、能力、授权和调用审计事件。审计只保存字段形状和摘要，不保存调用原始值。",
            json!({
                "type":"object",
                "properties":{"limit":{"type":"integer","minimum":1,"maximum":200,"default":50}},
                "additionalProperties":false
            }),
            true,
            true,
        ),
    ]
}

fn tool(
    name: &str,
    description: &str,
    input_schema: Value,
    read_only: bool,
    idempotent: bool,
) -> Value {
    json!({
        "name": name,
        "description": description,
        "inputSchema": input_schema,
        "annotations": {
            "readOnlyHint": read_only,
            "destructiveHint": matches!(
                name,
                "open_commerce_revoke_grant"
                    | "open_commerce_confirm_action_confirmation"
                    | "open_commerce_block_app"
                    | "open_commerce_revoke_consumer_relationship"
                    | "open_commerce_renew_consumer_relationship"
                    | "open_commerce_create_consumer_data_erasure_request"
                    | "open_commerce_withdraw_consumer_data_request"
                    | "open_commerce_decide_consumer_data_request"
            ),
            "idempotentHint": idempotent,
            "openWorldHint": name == "open_commerce_search_merchants"
                || name == "open_commerce_get_merchant"
                || name == "open_commerce_invoke"
        }
    })
}
