//! Small fallback maps for projects that have not curated graph nodes yet.

use crate::project_document_knowledge_graph_model::{
    ProjectKnowledgeEdgeConfig, ProjectKnowledgeGraphConfig, ProjectKnowledgeNodeConfig,
};

pub(crate) fn template_graph(profile: &str) -> ProjectKnowledgeGraphConfig {
    if profile == "software-platform" {
        software_platform_graph()
    } else {
        generic_graph(profile)
    }
}

fn software_platform_graph() -> ProjectKnowledgeGraphConfig {
    let mut nodes = vec![
        node(
            "cap-collaboration",
            "capabilities",
            "domain",
            "项目协作",
            "项目、频道、任务与 Git 交付",
            "",
            10,
            "#9A74E8",
            &["project", "channel", "git", "协作", "任务"],
        ),
        node(
            "cap-knowledge",
            "capabilities",
            "domain",
            "项目知识库",
            "Markdown、权威治理、AI 整理与图谱",
            "",
            20,
            "#58A8DF",
            &["document", "markdown", "knowledge", "文档", "知识"],
        ),
        node(
            "cap-ai-runtime",
            "capabilities",
            "domain",
            "AI 运行平台",
            "模型路由、上下文、工具与多代理运行",
            "",
            30,
            "#B582DD",
            &["ai", "agent", "model", "rag", "context", "mcp"],
        ),
        node(
            "cap-clients",
            "capabilities",
            "domain",
            "多端客户端",
            "PC、Windows 节点与 Android 客户端",
            "",
            40,
            "#5FBC88",
            &["pc", "windows", "android", "client", "客户端"],
        ),
        node(
            "cap-operations",
            "capabilities",
            "domain",
            "发布与运行保障",
            "构建、发布、升级、安全与恢复",
            "",
            50,
            "#D0A34F",
            &["deploy", "release", "upgrade", "security", "发布", "运维"],
        ),
        node(
            "cap-incubation",
            "capabilities",
            "domain",
            "孵化与子项目",
            "具有独立边界的实验和子项目",
            "",
            60,
            "#57A6C7",
            &["subproject", "experiment", "子项目", "实验"],
        ),
        node(
            "cap-project-space",
            "capabilities",
            "capability",
            "项目与频道",
            "项目空间、频道、成员与权限",
            "cap-collaboration",
            10,
            "#A884ED",
            &["project", "channel", "member", "项目", "频道"],
        ),
        node(
            "cap-ai-tasks",
            "capabilities",
            "capability",
            "AI 对话与任务",
            "从讨论、规划到隔离执行和验收",
            "cap-collaboration",
            20,
            "#A884ED",
            &["conversation", "task", "matter", "对话", "任务"],
        ),
        node(
            "cap-doc-editor",
            "capabilities",
            "capability",
            "Markdown 编辑阅读",
            "OneNote 式浏览、编辑和预览",
            "cap-knowledge",
            10,
            "#69B5D0",
            &["markdown", "editor", "preview", "编辑", "预览"],
        ),
        node(
            "cap-doc-governance",
            "capabilities",
            "capability",
            "权威性与 AI 整理",
            "低 token 分类、建议、Git 保护与恢复",
            "cap-knowledge",
            20,
            "#69B5D0",
            &["authority", "governance", "organization", "权威", "整理"],
        ),
        node(
            "cap-context",
            "capabilities",
            "capability",
            "项目理解与检索",
            "repo map、符号索引、RAG 和上下文包",
            "cap-ai-runtime",
            10,
            "#C291E4",
            &["context", "rag", "symbol", "repo_map", "检索"],
        ),
        node(
            "cap-provider-routing",
            "capabilities",
            "capability",
            "多供应商运行",
            "Codex、Copilot、Claude、Gemini 和 API 路由",
            "cap-ai-runtime",
            20,
            "#C291E4",
            &["codex", "copilot", "claude", "gemini", "route"],
        ),
        node(
            "cap-pc",
            "capabilities",
            "client",
            "PC 工作台",
            "React/Vite 项目协作工作台",
            "cap-clients",
            10,
            "#70B9D3",
            &["pc-frontend", "pc", "workbench"],
        ),
        node(
            "cap-node",
            "capabilities",
            "client",
            "Windows 节点",
            "本地项目、CLI 与设备执行节点",
            "cap-clients",
            20,
            "#65A8C8",
            &["node-agent", "windows", "node"],
        ),
        node(
            "cap-android",
            "capabilities",
            "client",
            "Android 客户端",
            "移动对话、项目入口和更新",
            "cap-clients",
            30,
            "#70B985",
            &["android", "apk", "compose"],
        ),
        node(
            "cap-release",
            "capabilities",
            "workflow",
            "构建与发布",
            "服务端、节点和 APK 发布闭环",
            "cap-operations",
            10,
            "#D7AF59",
            &["build", "publish", "release", "构建", "发布"],
        ),
        node(
            "cap-recovery",
            "capabilities",
            "capability",
            "安全、观测与恢复",
            "权限、任务可观测、版本恢复和故障处理",
            "cap-operations",
            20,
            "#D98675",
            &["security", "observability", "recovery", "安全", "恢复"],
        ),
        node(
            "arch-clients",
            "architecture",
            "system",
            "客户端层",
            "PC Web 与 Android 面向用户的交互入口",
            "",
            10,
            "#5FBC88",
            &["pc-frontend", "android", "client"],
        ),
        node(
            "arch-server",
            "architecture",
            "service",
            "Rust 云端服务",
            "鉴权、项目、会话、任务调度与公共 API",
            "",
            20,
            "#4FA9B8",
            &["server/src", "api", "router"],
        ),
        node(
            "arch-node",
            "architecture",
            "service",
            "Windows 节点",
            "本地 CLI、文件、Git、构建和设备能力",
            "",
            30,
            "#65A8C8",
            &["node_agent", "pc-dev-runtime"],
        ),
        node(
            "arch-workspace",
            "architecture",
            "component",
            "项目工作区与 Git",
            "隔离 worktree、版本、验证和交付事实",
            "",
            40,
            "#D18B62",
            &["workspace", "git", "worktree"],
        ),
        node(
            "arch-context",
            "architecture",
            "component",
            "上下文与知识层",
            "规则、文档图谱、repo map、符号与 RAG",
            "",
            50,
            "#B582DD",
            &["context_compiler", "project_document", "rag"],
        ),
        node(
            "arch-release",
            "architecture",
            "workflow",
            "构建发布流水线",
            "验证、打包、上传、部署和线上校验",
            "",
            60,
            "#D0A34F",
            &["scripts/publish", "release", "build"],
        ),
    ];
    for node in &mut nodes {
        node.color = node.color.to_ascii_uppercase();
    }
    ProjectKnowledgeGraphConfig {
        nodes,
        edges: vec![
            edge(
                "arch-client-server",
                "arch-clients",
                "arch-server",
                "calls",
                "HTTPS / WebSocket",
            ),
            edge(
                "arch-server-node",
                "arch-server",
                "arch-node",
                "dispatches",
                "节点协议",
            ),
            edge(
                "arch-node-workspace",
                "arch-node",
                "arch-workspace",
                "operates",
                "本地执行",
            ),
            edge(
                "arch-context-workspace",
                "arch-context",
                "arch-workspace",
                "indexes",
                "元数据与符号",
            ),
            edge(
                "arch-workspace-release",
                "arch-workspace",
                "arch-release",
                "feeds",
                "已验证提交",
            ),
        ],
    }
}

fn generic_graph(profile: &str) -> ProjectKnowledgeGraphConfig {
    let label = match profile {
        "software-api" => "API / SDK 能力",
        "product" => "产品能力",
        "research" => "研究能力",
        "operations" => "服务运行能力",
        _ => "核心能力",
    };
    ProjectKnowledgeGraphConfig {
        nodes: vec![
            node(
                "cap-core",
                "capabilities",
                "domain",
                label,
                "项目对外提供的核心价值与工作流",
                "",
                10,
                "#9A74E8",
                &["overview", "requirement", "readme"],
            ),
            node(
                "cap-knowledge",
                "capabilities",
                "domain",
                "知识与决策",
                "当前事实、指南、决策和证据",
                "",
                20,
                "#58A8DF",
                &["architecture", "guide", "decision", "evidence"],
            ),
            node(
                "cap-operations",
                "capabilities",
                "domain",
                "交付与维护",
                "验证、发布、维护和恢复",
                "",
                30,
                "#D0A34F",
                &["test", "release", "runbook"],
            ),
            node(
                "arch-entry",
                "architecture",
                "system",
                "交互入口",
                "用户、调用方或数据入口",
                "",
                10,
                "#5FBC88",
                &["client", "api", "input"],
            ),
            node(
                "arch-core",
                "architecture",
                "component",
                "核心系统",
                "主要业务逻辑与领域模型",
                "",
                20,
                "#4FA9B8",
                &["architecture", "src", "core"],
            ),
            node(
                "arch-data",
                "architecture",
                "datastore",
                "数据与外部依赖",
                "持久化、外部服务和集成边界",
                "",
                30,
                "#D18B62",
                &["data", "database", "integration"],
            ),
        ],
        edges: vec![
            edge(
                "arch-entry-core",
                "arch-entry",
                "arch-core",
                "calls",
                "请求 / 输入",
            ),
            edge(
                "arch-core-data",
                "arch-core",
                "arch-data",
                "uses",
                "数据 / 集成",
            ),
        ],
    }
}

fn node(
    id: &str,
    view: &str,
    kind: &str,
    label: &str,
    detail: &str,
    parent_id: &str,
    order: i32,
    color: &str,
    tags: &[&str],
) -> ProjectKnowledgeNodeConfig {
    ProjectKnowledgeNodeConfig {
        id: id.to_string(),
        view: view.to_string(),
        kind: kind.to_string(),
        label: label.to_string(),
        detail: detail.to_string(),
        parent_id: parent_id.to_string(),
        order,
        color: color.to_string(),
        tags: tags.iter().map(|value| value.to_string()).collect(),
        ..Default::default()
    }
}

fn edge(
    id: &str,
    source: &str,
    target: &str,
    relation: &str,
    label: &str,
) -> ProjectKnowledgeEdgeConfig {
    ProjectKnowledgeEdgeConfig {
        id: id.to_string(),
        source: source.to_string(),
        target: target.to_string(),
        relation: relation.to_string(),
        label: label.to_string(),
    }
}
