"""Generate/check Android semantic resources from the shared versioned V2 source."""
import argparse
import json
from pathlib import Path


def outputs(root):
    data = json.loads((root / "docs/design/mobile-tokens-v2.json").read_text(encoding="utf-8"))
    for mode, folder in (("light", "values"), ("dark", "values-night")):
        lines = ['<?xml version="1.0" encoding="utf-8"?>',
                 '<!-- Generated by scripts/generate-mobile-tokens.py; edit mobile-tokens-v2.json. -->',
                 '<resources>']
        lines += [f'    <color name="mobile_{name}">{value}</color>' for name, value in data[mode].items()]
        lines += [f'    <bool name="mobile_light_system_bars">{str(mode == "light").lower()}</bool>', '</resources>', '']
        yield root / f"android/app/src/main/res/{folder}/mobile_design.xml", '\n'.join(lines)
    template = root / "scripts/templates/mobile-design-v2.css"
    if template.is_file():
        def css_tokens(mode, selector):
            body = '\n'.join(f'  --mobile-{name.replace("_", "-")}: {value};'
                             for name, value in data[mode].items())
            return f'{selector} {{\n  color-scheme: {mode};\n{body}\n}}\n'
        css = '/* Generated Mobile Design V2; legacy asset URL retained for compatibility. */\n'
        css += css_tokens("light", ":root")
        css += '@media (prefers-color-scheme: dark) {\n'
        css += css_tokens("dark", ':root:not([data-theme="light"])') + '}\n'
        css += css_tokens("dark", ':root[data-theme="dark"]')
        css += template.read_text(encoding="utf-8")
        yield root / "server/src/assets/orbital_mobile_theme.css", css


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    stale = []
    for path, content in outputs(root):
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(root)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Stale mobile resources: " + ", ".join(stale))
    print("Mobile semantic resources: " + ("current" if args.check else "generated"))


if __name__ == "__main__":
    main()
