CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_supervisor_session_policy_companions (
  companion_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(companion_id)) BETWEEN 1 AND 240 AND companion_id=trim(companion_id)),
  companion_schema TEXT NOT NULL CHECK(companion_schema='compute_federation.external_pool_adapter_supervisor_session_policy_companion.v1'),
  companion_digest TEXT NOT NULL UNIQUE CHECK(length(companion_digest)=64 AND companion_digest NOT GLOB '*[^0-9a-f]*'),
  companion_material_digest TEXT NOT NULL CHECK(length(companion_material_digest)=64 AND companion_material_digest NOT GLOB '*[^0-9a-f]*'),
  companion_json TEXT NOT NULL CHECK(json_valid(companion_json) AND json_type(companion_json)='object' AND length(CAST(companion_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  profile_id TEXT NOT NULL CHECK(length(trim(profile_id)) BETWEEN 1 AND 240 AND profile_id=trim(profile_id)),
  profile_digest TEXT NOT NULL CHECK(length(profile_digest)=64 AND profile_digest NOT GLOB '*[^0-9a-f]*'),
  candidate_id TEXT NOT NULL CHECK(length(trim(candidate_id)) BETWEEN 1 AND 240 AND candidate_id=trim(candidate_id)),
  candidate_digest TEXT NOT NULL CHECK(length(candidate_digest)=64 AND candidate_digest NOT GLOB '*[^0-9a-f]*'),
  delegation_id TEXT NOT NULL CHECK(length(trim(delegation_id)) BETWEEN 1 AND 240 AND delegation_id=trim(delegation_id)),
  delegation_digest TEXT NOT NULL CHECK(length(delegation_digest)=64 AND delegation_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 240 AND registry_release_id=trim(registry_release_id)),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  installation_receipt_id TEXT NOT NULL CHECK(length(trim(installation_receipt_id)) BETWEEN 1 AND 240 AND installation_receipt_id=trim(installation_receipt_id)),
  installation_receipt_digest TEXT NOT NULL CHECK(length(installation_receipt_digest)=64 AND installation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 240 AND route_adapter_projection_id=trim(route_adapter_projection_id)),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 240 AND provider_id=trim(provider_id)),
  provider_owner_account_id TEXT NOT NULL CHECK(length(trim(provider_owner_account_id)) BETWEEN 1 AND 240 AND provider_owner_account_id=trim(provider_owner_account_id)),
  provider_policy_revision INTEGER NOT NULL CHECK(typeof(provider_policy_revision)='integer' AND provider_policy_revision BETWEEN 1 AND 9007199254740991),
  provider_digest TEXT NOT NULL CHECK(length(provider_digest)=64 AND provider_digest NOT GLOB '*[^0-9a-f]*'),
  provider_status TEXT NOT NULL CHECK(provider_status='registering'),
  logical_adapter_id TEXT NOT NULL CHECK(length(trim(logical_adapter_id)) BETWEEN 1 AND 240 AND logical_adapter_id=trim(logical_adapter_id)),
  release_version TEXT NOT NULL CHECK(length(trim(release_version)) BETWEEN 1 AND 240 AND release_version=trim(release_version)),
  adapter_config_revision INTEGER NOT NULL CHECK(typeof(adapter_config_revision)='integer' AND adapter_config_revision BETWEEN 1 AND 9007199254740991),
  adapter_config_digest TEXT NOT NULL CHECK(length(trim(adapter_config_digest)) BETWEEN 1 AND 512 AND adapter_config_digest=trim(adapter_config_digest)),
  implementation_digest TEXT NOT NULL CHECK(length(implementation_digest)=64 AND implementation_digest NOT GLOB '*[^0-9a-f]*'),
  capability_set_digest TEXT NOT NULL CHECK(length(capability_set_digest)=64 AND capability_set_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_digest TEXT NOT NULL CHECK(length(credential_verifier_digest)=64 AND credential_verifier_digest NOT GLOB '*[^0-9a-f]*'),
  service_actor_id TEXT NOT NULL CHECK(length(trim(service_actor_id)) BETWEEN 1 AND 240 AND service_actor_id=trim(service_actor_id)),
  launch_policy_digest TEXT NOT NULL CHECK(length(launch_policy_digest)=64 AND launch_policy_digest NOT GLOB '*[^0-9a-f]*'),
  process_isolation_policy_id TEXT NOT NULL CHECK(length(trim(process_isolation_policy_id)) BETWEEN 1 AND 240 AND process_isolation_policy_id=trim(process_isolation_policy_id)),
  process_isolation_policy_revision INTEGER NOT NULL CHECK(typeof(process_isolation_policy_revision)='integer' AND process_isolation_policy_revision BETWEEN 1 AND 9007199254740991),
  process_isolation_policy_digest TEXT NOT NULL CHECK(length(process_isolation_policy_digest)=64 AND process_isolation_policy_digest NOT GLOB '*[^0-9a-f]*'),
  resource_policy_id TEXT NOT NULL CHECK(length(trim(resource_policy_id)) BETWEEN 1 AND 240 AND resource_policy_id=trim(resource_policy_id)),
  resource_policy_revision INTEGER NOT NULL CHECK(typeof(resource_policy_revision)='integer' AND resource_policy_revision BETWEEN 1 AND 9007199254740991),
  resource_policy_digest TEXT NOT NULL CHECK(length(resource_policy_digest)=64 AND resource_policy_digest NOT GLOB '*[^0-9a-f]*'),
  network_egress_policy_id TEXT NOT NULL CHECK(length(trim(network_egress_policy_id)) BETWEEN 1 AND 240 AND network_egress_policy_id=trim(network_egress_policy_id)),
  network_egress_policy_revision INTEGER NOT NULL CHECK(typeof(network_egress_policy_revision)='integer' AND network_egress_policy_revision BETWEEN 1 AND 9007199254740991),
  network_egress_policy_digest TEXT NOT NULL CHECK(length(network_egress_policy_digest)=64 AND network_egress_policy_digest NOT GLOB '*[^0-9a-f]*'),
  entrypoint_capsule_policy_id TEXT NOT NULL CHECK(entrypoint_capsule_policy_id='external_pool_adapter_entrypoint_capsule_policy_v1'),
  entrypoint_capsule_policy_revision INTEGER NOT NULL CHECK(typeof(entrypoint_capsule_policy_revision)='integer' AND entrypoint_capsule_policy_revision=1),
  entrypoint_capsule_policy_digest TEXT NOT NULL CHECK(entrypoint_capsule_policy_digest='710decef25b4d19b33f086239f55f809a513508eb5ba431967971ff89249604f'),
  target_id TEXT NOT NULL CHECK(length(trim(target_id)) BETWEEN 1 AND 240 AND target_id=trim(target_id)),
  target_digest TEXT NOT NULL CHECK(length(target_digest)=64 AND target_digest NOT GLOB '*[^0-9a-f]*'),
  target_policy_digest TEXT NOT NULL CHECK(length(target_policy_digest)=64 AND target_policy_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_digest TEXT NOT NULL CHECK(length(supervisor_session_policy_digest)=64 AND supervisor_session_policy_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_json TEXT NOT NULL CHECK(json_valid(supervisor_session_policy_json) AND json_type(supervisor_session_policy_json)='object' AND length(CAST(supervisor_session_policy_json AS BLOB))<=1048576),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence BETWEEN 1 AND 9007199254740991),
  predecessor_companion_id TEXT CHECK(predecessor_companion_id IS NULL OR (length(trim(predecessor_companion_id)) BETWEEN 1 AND 240 AND predecessor_companion_id=trim(predecessor_companion_id))),
  predecessor_companion_digest TEXT CHECK(predecessor_companion_digest IS NULL OR (length(predecessor_companion_digest)=64 AND predecessor_companion_digest NOT GLOB '*[^0-9a-f]*')),
  recorded_by_actor_kind TEXT NOT NULL CHECK(recorded_by_actor_kind IN ('provider_owner','platform_admin')),
  recorded_by_actor_user_id TEXT NOT NULL CHECK(length(trim(recorded_by_actor_user_id)) BETWEEN 1 AND 240 AND recorded_by_actor_user_id=trim(recorded_by_actor_user_id)),
  recorded_at TEXT NOT NULL CHECK(recorded_at GLOB '????-??-??T??:??:??.?????????Z' AND length(recorded_at)=30 AND julianday(recorded_at) IS NOT NULL),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_supervisor_session_policy_companion'),
  companion_status TEXT NOT NULL CHECK(companion_status='supervisor_session_policy_companion_current_inert'),
  companion_effect TEXT NOT NULL CHECK(companion_effect='supervisor_session_policy_companion_recorded_inert'),
  adapter_effect TEXT NOT NULL CHECK(adapter_effect='none'),
  runtime_effect TEXT NOT NULL CHECK(runtime_effect='none'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  usage_effect TEXT NOT NULL CHECK(usage_effect='none'),
  market_effect TEXT NOT NULL CHECK(market_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  process_spawn_ready INTEGER NOT NULL CHECK(typeof(process_spawn_ready)='integer' AND process_spawn_ready=0),
  ipc_session_ready INTEGER NOT NULL CHECK(typeof(ipc_session_ready)='integer' AND ipc_session_ready=0),
  secret_delivery_ready INTEGER NOT NULL CHECK(typeof(secret_delivery_ready)='integer' AND secret_delivery_ready=0),
  broker_connect_ready INTEGER NOT NULL CHECK(typeof(broker_connect_ready)='integer' AND broker_connect_ready=0),
  upstream_probe_observed INTEGER NOT NULL CHECK(typeof(upstream_probe_observed)='integer' AND upstream_probe_observed=0),
  runtime_launch_ready INTEGER NOT NULL CHECK(typeof(runtime_launch_ready)='integer' AND runtime_launch_ready=0),
  activation_ready INTEGER NOT NULL CHECK(typeof(activation_ready)='integer' AND activation_ready=0),
  CHECK ((predecessor_companion_id IS NULL)=(predecessor_companion_digest IS NULL)),
  UNIQUE (companion_id,companion_digest), UNIQUE (provider_binding_id,sequence),
  UNIQUE (predecessor_companion_id), UNIQUE (idempotency_scope,idempotency_key),
  FOREIGN KEY(profile_id,profile_digest) REFERENCES compute_external_pool_adapter_runtime_launch_profiles(profile_id,profile_digest) ON DELETE RESTRICT,
  FOREIGN KEY(candidate_id,candidate_digest) REFERENCES compute_external_pool_provider_activation_candidates(candidate_id,candidate_digest) ON DELETE RESTRICT,
  FOREIGN KEY(delegation_id,delegation_digest) REFERENCES compute_external_pool_provider_activation_delegations(delegation_id,delegation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(installation_receipt_id) REFERENCES compute_external_pool_adapter_installation_receipts(installation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT,
  FOREIGN KEY(target_id,target_digest) REFERENCES compute_external_pool_adapter_upstream_transport_targets(target_id,target_digest) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_companion_id,predecessor_companion_digest) REFERENCES compute_external_pool_adapter_supervisor_session_policy_companions(companion_id,companion_digest) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_supervisor_session_policy_companion_revocations (
  revocation_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(revocation_id)) BETWEEN 1 AND 240 AND revocation_id=trim(revocation_id)),
  revocation_schema TEXT NOT NULL CHECK(revocation_schema='compute_federation.external_pool_adapter_supervisor_session_policy_companion_revocation.v1'),
  revocation_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_digest)=64 AND revocation_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_material_digest TEXT NOT NULL CHECK(length(revocation_material_digest)=64 AND revocation_material_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_json TEXT NOT NULL CHECK(json_valid(revocation_json) AND json_type(revocation_json)='object' AND length(CAST(revocation_json AS BLOB))<=1048576),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  companion_id TEXT NOT NULL UNIQUE CHECK(length(trim(companion_id)) BETWEEN 1 AND 240 AND companion_id=trim(companion_id)),
  companion_digest TEXT NOT NULL CHECK(length(companion_digest)=64 AND companion_digest NOT GLOB '*[^0-9a-f]*'),
  target_id TEXT NOT NULL CHECK(length(trim(target_id)) BETWEEN 1 AND 240 AND target_id=trim(target_id)),
  target_digest TEXT NOT NULL CHECK(length(target_digest)=64 AND target_digest NOT GLOB '*[^0-9a-f]*'),
  profile_id TEXT NOT NULL CHECK(length(trim(profile_id)) BETWEEN 1 AND 240 AND profile_id=trim(profile_id)),
  profile_digest TEXT NOT NULL CHECK(length(profile_digest)=64 AND profile_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 240 AND provider_id=trim(provider_id)),
  revoked_by_actor_kind TEXT NOT NULL CHECK(revoked_by_actor_kind IN ('provider_owner','platform_admin')),
  revoked_by_actor_user_id TEXT NOT NULL CHECK(length(trim(revoked_by_actor_user_id)) BETWEEN 1 AND 240 AND revoked_by_actor_user_id=trim(revoked_by_actor_user_id)),
  reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 12 AND 500 AND reason=trim(reason)),
  revoked_at TEXT NOT NULL CHECK(revoked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=revoked_at),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240 AND idempotency_scope=trim(idempotency_scope)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_supervisor_session_policy_companion_revocation'),
  revocation_effect TEXT NOT NULL CHECK(revocation_effect='supervisor_session_policy_companion_revoked'),
  adapter_effect TEXT NOT NULL CHECK(adapter_effect='none'),
  runtime_effect TEXT NOT NULL CHECK(runtime_effect='none'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  usage_effect TEXT NOT NULL CHECK(usage_effect='none'),
  market_effect TEXT NOT NULL CHECK(market_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  process_spawn_ready INTEGER NOT NULL CHECK(typeof(process_spawn_ready)='integer' AND process_spawn_ready=0),
  ipc_session_ready INTEGER NOT NULL CHECK(typeof(ipc_session_ready)='integer' AND ipc_session_ready=0),
  secret_delivery_ready INTEGER NOT NULL CHECK(typeof(secret_delivery_ready)='integer' AND secret_delivery_ready=0),
  broker_connect_ready INTEGER NOT NULL CHECK(typeof(broker_connect_ready)='integer' AND broker_connect_ready=0),
  upstream_probe_observed INTEGER NOT NULL CHECK(typeof(upstream_probe_observed)='integer' AND upstream_probe_observed=0),
  runtime_launch_ready INTEGER NOT NULL CHECK(typeof(runtime_launch_ready)='integer' AND runtime_launch_ready=0),
  activation_ready INTEGER NOT NULL CHECK(typeof(activation_ready)='integer' AND activation_ready=0),
  UNIQUE (idempotency_scope,idempotency_key),
  FOREIGN KEY(companion_id,companion_digest) REFERENCES compute_external_pool_adapter_supervisor_session_policy_companions(companion_id,companion_digest) ON DELETE RESTRICT,
  FOREIGN KEY(target_id,target_digest) REFERENCES compute_external_pool_adapter_upstream_transport_targets(target_id,target_digest) ON DELETE RESTRICT,
  FOREIGN KEY(profile_id,profile_digest) REFERENCES compute_external_pool_adapter_runtime_launch_profiles(profile_id,profile_digest) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_id) REFERENCES compute_providers(provider_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_external_pool_adapter_supervisor_session_policy_companion_genesis
  ON compute_external_pool_adapter_supervisor_session_policy_companions(provider_binding_id)
  WHERE predecessor_companion_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_supervisor_session_policy_companion_head
  ON compute_external_pool_adapter_supervisor_session_policy_companions(provider_binding_id,sequence DESC,companion_id);
CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_supervisor_session_policy_companion_target
  ON compute_external_pool_adapter_supervisor_session_policy_companions(target_id,recorded_at DESC,companion_id);
