CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_credential_reattestation_challenges (
  challenge_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(challenge_id)) BETWEEN 1 AND 200),
  challenge_nonce_base64 TEXT NOT NULL CHECK(length(challenge_nonce_base64)=44 AND substr(challenge_nonce_base64,44)='=' AND substr(challenge_nonce_base64,1,43) NOT GLOB '*[^A-Za-z0-9+/]*'),
  challenge_nonce_digest TEXT NOT NULL UNIQUE CHECK(length(challenge_nonce_digest)=64 AND challenge_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  signature_message_base64 TEXT NOT NULL CHECK(length(signature_message_base64) BETWEEN 4 AND 1048576 AND length(signature_message_base64)%4=0 AND rtrim(signature_message_base64,'=') NOT GLOB '*[^A-Za-z0-9+/]*' AND length(signature_message_base64)-length(rtrim(signature_message_base64,'=')) BETWEEN 0 AND 2),
  signature_message_digest TEXT NOT NULL CHECK(length(signature_message_digest)=64 AND signature_message_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 200),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_material_digest TEXT NOT NULL CHECK(length(provider_binding_material_digest)=64 AND provider_binding_material_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 200),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_material_digest TEXT NOT NULL CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_key_record_id TEXT NOT NULL CHECK(length(trim(credential_verifier_key_record_id)) BETWEEN 1 AND 200),
  credential_verifier_key_record_digest TEXT NOT NULL CHECK(length(credential_verifier_key_record_digest)=64 AND credential_verifier_key_record_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_key_id TEXT NOT NULL CHECK(length(credential_verifier_key_id)=64 AND credential_verifier_key_id NOT GLOB '*[^0-9a-f]*'),
  observed_provider_policy_revision INTEGER NOT NULL CHECK(typeof(observed_provider_policy_revision)='integer' AND observed_provider_policy_revision>0),
  observed_provider_digest TEXT NOT NULL CHECK(length(observed_provider_digest)=64 AND observed_provider_digest NOT GLOB '*[^0-9a-f]*'),
  observed_provider_status TEXT NOT NULL CHECK(observed_provider_status IN ('registering','active')),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>0),
  predecessor_receipt_id TEXT CHECK(predecessor_receipt_id IS NULL OR length(trim(predecessor_receipt_id)) BETWEEN 1 AND 200),
  predecessor_receipt_digest TEXT CHECK(predecessor_receipt_digest IS NULL OR (length(predecessor_receipt_digest)=64 AND predecessor_receipt_digest NOT GLOB '*[^0-9a-f]*')),
  challenge_json TEXT NOT NULL CHECK(json_valid(challenge_json) AND json_type(challenge_json)='object' AND length(CAST(challenge_json AS BLOB))<=1048576),
  issued_at TEXT NOT NULL CHECK(issued_at GLOB '????-??-??T??:??:??.?????????Z' AND length(issued_at)=30 AND julianday(issued_at) IS NOT NULL),
  expires_at TEXT NOT NULL CHECK(expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(expires_at)=30 AND julianday(expires_at) IS NOT NULL),
  CHECK((predecessor_receipt_id IS NULL)=(predecessor_receipt_digest IS NULL)),
  CHECK(expires_at=(strftime('%Y-%m-%dT%H:%M:%S',issued_at,'+5 minutes')||substr(issued_at,20))),
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(credential_verifier_key_record_id) REFERENCES compute_external_pool_adapter_credential_verifier_keys(key_record_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_receipt_id) REFERENCES compute_external_pool_adapter_credential_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_credential_reattestation_receipts (
  reattestation_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(reattestation_receipt_id)) BETWEEN 1 AND 200),
  reattestation_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(reattestation_receipt_digest)=64 AND reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json) AND json_type(receipt_json)='object' AND length(CAST(receipt_json AS BLOB))<=1048576),
  reattestation_material_digest TEXT NOT NULL CHECK(length(reattestation_material_digest)=64 AND reattestation_material_digest NOT GLOB '*[^0-9a-f]*'),
  challenge_id TEXT NOT NULL UNIQUE CHECK(length(trim(challenge_id)) BETWEEN 1 AND 200),
  challenge_nonce_digest TEXT NOT NULL CHECK(length(challenge_nonce_digest)=64 AND challenge_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 200),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_material_digest TEXT NOT NULL CHECK(length(provider_binding_material_digest)=64 AND provider_binding_material_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 200),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_material_digest TEXT NOT NULL CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 200),
  installation_receipt_id TEXT NOT NULL CHECK(length(trim(installation_receipt_id)) BETWEEN 1 AND 200),
  installation_receipt_digest TEXT NOT NULL CHECK(length(installation_receipt_digest)=64 AND installation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  application_id TEXT NOT NULL CHECK(length(trim(application_id)) BETWEEN 1 AND 200),
  application_digest TEXT NOT NULL CHECK(length(application_digest)=64 AND application_digest NOT GLOB '*[^0-9a-f]*'),
  adoption_receipt_id TEXT NOT NULL CHECK(length(trim(adoption_receipt_id)) BETWEEN 1 AND 200),
  adoption_receipt_digest TEXT NOT NULL CHECK(length(adoption_receipt_digest)=64 AND adoption_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  provider_id TEXT NOT NULL CHECK(length(trim(provider_id)) BETWEEN 1 AND 160),
  provider_kind TEXT NOT NULL CHECK(provider_kind='external_pool'),
  provider_owner_account_id TEXT NOT NULL CHECK(length(trim(provider_owner_account_id)) BETWEEN 1 AND 160),
  observed_settlement_account_id TEXT NOT NULL CHECK(length(trim(observed_settlement_account_id)) BETWEEN 1 AND 160),
  observed_provider_policy_revision INTEGER NOT NULL CHECK(typeof(observed_provider_policy_revision)='integer' AND observed_provider_policy_revision>0),
  observed_provider_digest TEXT NOT NULL CHECK(length(observed_provider_digest)=64 AND observed_provider_digest NOT GLOB '*[^0-9a-f]*'),
  observed_provider_status TEXT NOT NULL CHECK(observed_provider_status IN ('registering','active')),
  adapter_id TEXT NOT NULL CHECK(length(trim(adapter_id)) BETWEEN 1 AND 160),
  release_version TEXT NOT NULL CHECK(length(trim(release_version)) BETWEEN 1 AND 80),
  adapter_config_revision INTEGER NOT NULL CHECK(typeof(adapter_config_revision)='integer' AND adapter_config_revision>0),
  adapter_config_digest TEXT NOT NULL CHECK(length(trim(adapter_config_digest)) BETWEEN 1 AND 512),
  admission_id TEXT NOT NULL CHECK(length(trim(admission_id)) BETWEEN 1 AND 200),
  admission_digest TEXT NOT NULL CHECK(length(admission_digest)=64 AND admission_digest NOT GLOB '*[^0-9a-f]*'),
  legacy_credential_verification_receipt_id TEXT NOT NULL CHECK(length(trim(legacy_credential_verification_receipt_id)) BETWEEN 1 AND 200),
  legacy_credential_verification_receipt_digest TEXT NOT NULL CHECK(length(legacy_credential_verification_receipt_digest)=64 AND legacy_credential_verification_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  credential_ref_scheme TEXT NOT NULL CHECK(credential_ref_scheme IN ('vault_ref','gateway_ref')),
  credential_locator_commitment TEXT NOT NULL CHECK(length(credential_locator_commitment)=64 AND credential_locator_commitment NOT GLOB '*[^0-9a-f]*'),
  expected_credential_verifier_json TEXT NOT NULL CHECK(json_valid(expected_credential_verifier_json) AND json_type(expected_credential_verifier_json)='object' AND length(CAST(expected_credential_verifier_json AS BLOB))<=65536),
  credential_verifier_digest TEXT NOT NULL CHECK(length(credential_verifier_digest)=64 AND credential_verifier_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_key_record_id TEXT NOT NULL CHECK(length(trim(credential_verifier_key_record_id)) BETWEEN 1 AND 200),
  credential_verifier_key_record_digest TEXT NOT NULL CHECK(length(credential_verifier_key_record_digest)=64 AND credential_verifier_key_record_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_key_id TEXT NOT NULL CHECK(length(credential_verifier_key_id)=64 AND credential_verifier_key_id NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_record_id TEXT NOT NULL CHECK(length(trim(credential_verifier_record_id)) BETWEEN 1 AND 200),
  credential_verifier_record_digest TEXT NOT NULL CHECK(length(credential_verifier_record_digest)=64 AND credential_verifier_record_digest NOT GLOB '*[^0-9a-f]*'),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>0),
  predecessor_receipt_id TEXT CHECK(predecessor_receipt_id IS NULL OR length(trim(predecessor_receipt_id)) BETWEEN 1 AND 200),
  predecessor_receipt_digest TEXT CHECK(predecessor_receipt_digest IS NULL OR (length(predecessor_receipt_digest)=64 AND predecessor_receipt_digest NOT GLOB '*[^0-9a-f]*')),
  verifier_report_id TEXT NOT NULL UNIQUE CHECK(length(trim(verifier_report_id)) BETWEEN 1 AND 200),
  verification_started_at TEXT NOT NULL CHECK(verification_started_at GLOB '????-??-??T??:??:??.?????????Z' AND length(verification_started_at)=30 AND julianday(verification_started_at) IS NOT NULL),
  verification_completed_at TEXT NOT NULL CHECK(verification_completed_at GLOB '????-??-??T??:??:??.?????????Z' AND length(verification_completed_at)=30 AND julianday(verification_completed_at) IS NOT NULL),
  report_generated_at TEXT NOT NULL CHECK(report_generated_at GLOB '????-??-??T??:??:??.?????????Z' AND length(report_generated_at)=30 AND julianday(report_generated_at) IS NOT NULL),
  report_expires_at TEXT NOT NULL CHECK(report_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(report_expires_at)=30 AND julianday(report_expires_at) IS NOT NULL),
  credential_resolution_outcome TEXT NOT NULL CHECK(credential_resolution_outcome='passed'),
  provider_authentication_outcome TEXT NOT NULL CHECK(provider_authentication_outcome='passed'),
  provider_response_evidence_digest TEXT NOT NULL CHECK(length(provider_response_evidence_digest)=64 AND provider_response_evidence_digest NOT GLOB '*[^0-9a-f]*'),
  signature_message_digest TEXT NOT NULL CHECK(length(signature_message_digest)=64 AND signature_message_digest NOT GLOB '*[^0-9a-f]*'),
  signature_base64 TEXT NOT NULL CHECK(length(signature_base64) BETWEEN 4 AND 2048 AND length(signature_base64)%4=0 AND rtrim(signature_base64,'=') NOT GLOB '*[^A-Za-z0-9+/]*' AND length(signature_base64)-length(rtrim(signature_base64,'=')) BETWEEN 0 AND 2),
  signature_digest TEXT NOT NULL CHECK(length(signature_digest)=64 AND signature_digest NOT GLOB '*[^0-9a-f]*'),
  recorded_by_admin_user_id TEXT NOT NULL CHECK(length(trim(recorded_by_admin_user_id)) BETWEEN 1 AND 200),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_credential_reattestation'),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240),
  verified_at TEXT NOT NULL CHECK(verified_at GLOB '????-??-??T??:??:??.?????????Z' AND length(verified_at)=30 AND julianday(verified_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=verified_at),
  evidence_scope TEXT NOT NULL CHECK(evidence_scope='verifier_signature_over_exact_v249_provider_binding_stable_credential_subject_and_single_use_nonce'),
  credential_reattestation_effect TEXT NOT NULL CHECK(credential_reattestation_effect='signed_provider_credential_reattestation_verified_current'),
  adapter_effect TEXT NOT NULL CHECK(adapter_effect='none'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  usage_effect TEXT NOT NULL CHECK(usage_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  CHECK((predecessor_receipt_id IS NULL)=(predecessor_receipt_digest IS NULL)),
  CHECK(credential_verifier_digest=json_extract(expected_credential_verifier_json,'$.verifier_digest')),
  UNIQUE(provider_binding_id,sequence), UNIQUE(predecessor_receipt_id),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(challenge_id) REFERENCES compute_external_pool_adapter_credential_reattestation_challenges(challenge_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(installation_receipt_id) REFERENCES compute_external_pool_adapter_installation_receipts(installation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(application_id) REFERENCES compute_external_pool_onboarding_applications(application_id) ON DELETE RESTRICT,
  FOREIGN KEY(adoption_receipt_id) REFERENCES compute_external_pool_adapter_adoption_receipts(adoption_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(admission_id) REFERENCES compute_external_pool_adapter_release_admissions(admission_id) ON DELETE RESTRICT,
  FOREIGN KEY(legacy_credential_verification_receipt_id) REFERENCES compute_external_pool_adapter_credential_verification_receipts(credential_verification_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(credential_verifier_key_record_id) REFERENCES compute_external_pool_adapter_credential_verifier_keys(key_record_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_receipt_id) REFERENCES compute_external_pool_adapter_credential_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_credential_reattestation_revocations (
  revocation_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(revocation_receipt_id)) BETWEEN 1 AND 200),
  revocation_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_receipt_digest)=64 AND revocation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json) AND json_type(receipt_json)='object' AND length(CAST(receipt_json AS BLOB))<=524288),
  revocation_material_digest TEXT NOT NULL CHECK(length(revocation_material_digest)=64 AND revocation_material_digest NOT GLOB '*[^0-9a-f]*'),
  reattestation_receipt_id TEXT NOT NULL UNIQUE CHECK(length(trim(reattestation_receipt_id)) BETWEEN 1 AND 200),
  reattestation_receipt_digest TEXT NOT NULL CHECK(length(reattestation_receipt_digest)=64 AND reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 200),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  revoked_by_admin_user_id TEXT NOT NULL CHECK(length(trim(revoked_by_admin_user_id)) BETWEEN 1 AND 200),
  reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 12 AND 500 AND reason=trim(reason)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_credential_reattestation_revocation'),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240),
  revoked_at TEXT NOT NULL CHECK(revoked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=revoked_at),
  revocation_effect TEXT NOT NULL CHECK(revocation_effect='credential_reattestation_revoked'),
  adapter_effect TEXT NOT NULL CHECK(adapter_effect='none'),
  provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'),
  usage_effect TEXT NOT NULL CHECK(usage_effect='none'),
  settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(reattestation_receipt_id) REFERENCES compute_external_pool_adapter_credential_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_external_pool_adapter_credential_reattestation_genesis
  ON compute_external_pool_adapter_credential_reattestation_receipts(provider_binding_id)
  WHERE predecessor_receipt_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_credential_reattestation_head
  ON compute_external_pool_adapter_credential_reattestation_receipts(provider_binding_id,sequence DESC,reattestation_receipt_id);
CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_credential_reattestation_challenge_binding
  ON compute_external_pool_adapter_credential_reattestation_challenges(provider_binding_id,issued_at DESC,challenge_id);
