Import-Module "$PSScriptRoot\RustCache.Portability.psm1" -Force -DisableNameChecking

function Get-RustCacheProjectWrapperContent {
    $lines = @(
        "# Generated by the Elon Rust cache platform. Re-run adopt-project to verify."
        '$ErrorActionPreference = "Stop"'
        ''
        'if ([string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {'
        '    throw "LOCALAPPDATA is required to locate the installed Rust cache platform."'
        '}'
        'foreach ($argument in @($args)) {'
        '    if ([string]$argument -match ''(?i)^-ProjectRoot(?:$|[:=])'') {'
        '        throw "The project wrapper owns -ProjectRoot; do not override it."'
        '    }'
        '}'
        '$projectRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))'
        '$entry = Join-Path $env:LOCALAPPDATA "Elon\bin\rust-cache.ps1"'
        'if (-not (Test-Path -LiteralPath $entry -PathType Leaf)) {'
        '    throw "The Elon Rust cache platform is not installed for this PC. Run install from a trusted platform checkout: $entry"'
        '}'
        '& $entry @args -ProjectRoot $projectRoot'
    )
    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function ConvertTo-RustCacheComparableText {
    param([AllowEmptyString()][string]$Text)

    if ($null -eq $Text) { return "" }
    return $Text.TrimStart([char]0xFEFF).Replace("`r`n", "`n").Replace("`r", "`n")
}

function Get-RustCacheProjectWrapperPlan {
    param([Parameter(Mandatory)][string]$ProjectRoot)

    $root = [System.IO.Path]::GetFullPath($ProjectRoot)
    if (-not (Test-Path -LiteralPath $root -PathType Container)) {
        throw "Project root does not exist: $root"
    }
    $relativePath = "scripts\rust-cache.ps1"
    $path = [System.IO.Path]::GetFullPath((Join-Path $root $relativePath))
    $rootPrefix = $root.TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
    if (-not $path.StartsWith($rootPrefix, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Project cache wrapper must remain inside the project root: $path"
    }

    $content = Get-RustCacheProjectWrapperContent
    if (Test-Path -LiteralPath $path) {
        $item = Get-Item -LiteralPath $path -Force
        if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
            throw "Project cache wrapper path is not a regular file: $path"
        }
        $actual = Get-Content -Raw -LiteralPath $path -Encoding UTF8
        if ((ConvertTo-RustCacheComparableText $actual) -cne (ConvertTo-RustCacheComparableText $content)) {
            throw "Project cache wrapper already exists with different content; review it instead of overwriting: $path"
        }
        return [pscustomobject]@{
            action = "unchanged"
            applied = $false
            path = $path
            relative_path = $relativePath.Replace('\', '/')
            content = $content
        }
    }

    return [pscustomobject]@{
        action = "would-create"
        applied = $false
        path = $path
        relative_path = $relativePath.Replace('\', '/')
        content = $content
    }
}

function New-RustCacheProjectAdoption {
    param(
        [Parameter(Mandatory)][string]$ProjectRoot,
        [Parameter(Mandatory)][string]$ProjectId,
        [string]$DefaultDomain = "dev-windows-msvc",
        [string[]]$AllowedDomains = @(),
        [string]$UnknownDomainFallback = "agent-validation",
        [string[]]$SharedPartitionDomains = @(),
        [switch]$Apply
    )

    $root = [System.IO.Path]::GetFullPath($ProjectRoot)
    $manifestPlan = New-RustCacheProjectManifest -ProjectRoot $root -ProjectId $ProjectId `
        -DefaultDomain $DefaultDomain -AllowedDomains $AllowedDomains `
        -UnknownDomainFallback $UnknownDomainFallback -SharedPartitionDomains $SharedPartitionDomains
    $wrapperPlan = Get-RustCacheProjectWrapperPlan -ProjectRoot $root

    if ($Apply) {
        $manifestPlan = New-RustCacheProjectManifest -ProjectRoot $root -ProjectId $ProjectId `
            -DefaultDomain $DefaultDomain -AllowedDomains $AllowedDomains `
            -UnknownDomainFallback $UnknownDomainFallback -SharedPartitionDomains $SharedPartitionDomains -Apply
        if ($wrapperPlan.action -eq "would-create") {
            $parent = Split-Path $wrapperPlan.path -Parent
            if (Test-Path -LiteralPath $parent) {
                $parentItem = Get-Item -LiteralPath $parent -Force
                if (-not $parentItem.PSIsContainer -or ($parentItem.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
                    throw "Project cache wrapper parent is not a regular directory: $parent"
                }
            } else {
                New-Item -ItemType Directory -Path $parent -Force | Out-Null
            }
            $temporary = "$($wrapperPlan.path).$PID.tmp"
            Set-Content -LiteralPath $temporary -Value $wrapperPlan.content -Encoding UTF8 -NoNewline
            Move-Item -LiteralPath $temporary -Destination $wrapperPlan.path
            $wrapperPlan = Get-RustCacheProjectWrapperPlan -ProjectRoot $root
            $wrapperPlan.action = "created"
            $wrapperPlan.applied = $true
        }
    }

    [pscustomobject]@{
        schema = "elon.rust_cache.project_adoption.v1"
        mode = if ($Apply) { "apply" } else { "preview" }
        project_root = $root
        project_id = [string]$manifestPlan.manifest.project_id
        portable = $true
        files = @(
            [pscustomobject]@{ path = $manifestPlan.path; relative_path = "rust-cache.project.json"; action = $manifestPlan.action }
            [pscustomobject]@{ path = $wrapperPlan.path; relative_path = $wrapperPlan.relative_path; action = $wrapperPlan.action }
        )
        next_steps = @(
            $(if ($Apply) { "Commit rust-cache.project.json and scripts/rust-cache.ps1." } else { "Review both files, then repeat with -Apply." })
            "Install or upgrade the platform and Skill once on each PC."
            "Run scripts/rust-cache.ps1 doctor before a long build."
        )
    }
}

Export-ModuleMember -Function Get-RustCacheProjectWrapperContent, Get-RustCacheProjectWrapperPlan, New-RustCacheProjectAdoption
