Import-Module "$PSScriptRoot\RustCache.Paths.psm1" -Force -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Policy.psm1" -Force -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Sccache.psm1" -DisableNameChecking

function ConvertTo-RustCacheTomlPath {
    param([Parameter(Mandatory)][string]$Path)
    [System.IO.Path]::GetFullPath($Path).Replace('\', '/')
}

function Get-RustCacheCargoIncludeContent {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [AllowNull()][string]$SccachePath
    )

    $quarantine = ConvertTo-RustCacheTomlPath (Join-Path $CacheRoot "quarantine\{workspace-path-hash}")
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by the Elon Rust cache platform. Re-run rust-cache.ps1 install to refresh.")
    $lines.Add("[build]")
    $lines.Add("build-dir = `"$quarantine`"")
    if (-not [string]::IsNullOrWhiteSpace($SccachePath)) {
        $wrapper = ConvertTo-RustCacheTomlPath $SccachePath
        $lines.Add("rustc-wrapper = `"$wrapper`"")
    }
    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function Set-RustCacheParentCargoConfig {
    param(
        [Parameter(Mandatory)][string]$CargoConfigPath,
        [Parameter(Mandatory)][string]$IncludeConfigPath,
        [switch]$Apply
    )

    $fullCargoConfig = [System.IO.Path]::GetFullPath($CargoConfigPath)
    $includeTomlPath = ConvertTo-RustCacheTomlPath $IncludeConfigPath
    $existing = if (Test-Path -LiteralPath $fullCargoConfig) { Get-Content -LiteralPath $fullCargoConfig -Encoding UTF8 } else { @() }
    $result = New-Object System.Collections.Generic.List[string]
    $section = ""
    $foundOtherInclude = $false
    foreach ($line in $existing) {
        if ($line -match '^\s*include\s*=') {
            if ($line -notlike "*$includeTomlPath*") {
                $foundOtherInclude = $true
            }
            continue
        }
        if ($line -match '^\s*\[([^]]+)\]\s*$') {
            $section = $Matches[1].Trim().ToLowerInvariant()
        }
        if ($section -eq "build" -and $line -match '^\s*(target-dir|rustflags)\s*=') {
            continue
        }
        $result.Add($line)
    }
    if ($foundOtherInclude) {
        throw "Cargo config already contains an unrelated include entry; merge it manually before activation: $fullCargoConfig"
    }
    while ($result.Count -gt 0 -and [string]::IsNullOrWhiteSpace($result[0])) {
        $result.RemoveAt(0)
    }
    $result.Insert(0, "")
    $result.Insert(0, "include = [`"$includeTomlPath`"]")
    $content = ($result -join [Environment]::NewLine).TrimEnd() + [Environment]::NewLine

    $backupPath = $null
    if ($Apply) {
        $parent = Split-Path $fullCargoConfig -Parent
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
        if (Test-Path -LiteralPath $fullCargoConfig) {
            $stamp = [DateTime]::UtcNow.ToString("yyyyMMdd-HHmmss")
            $backupPath = "$fullCargoConfig.before-rust-cache-$stamp.bak"
            Copy-Item -LiteralPath $fullCargoConfig -Destination $backupPath -Force
        }
        Set-Content -LiteralPath $fullCargoConfig -Value $content -Encoding UTF8 -NoNewline
    }
    [pscustomobject]@{
        cargo_config_path = $fullCargoConfig
        include_config_path = $includeTomlPath
        applied = [bool]$Apply
        backup_path = $backupPath
        content = $content
    }
}

function Restart-RustCacheSccacheServer {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [Parameter(Mandatory)][string]$MaxCacheSize
    )

    $sccache = Get-Command sccache -ErrorAction SilentlyContinue
    if (-not $sccache) { return $null }
    $result = Sync-RustCacheSccacheConfiguration -CacheRoot $CacheRoot -ConfigureProcessEnvironment -ForceRestart
    if ($result.restart_pending) {
        throw "Refusing to report sccache activation while Cargo/rustc is active. Managed configuration remains pending: $($result.state_path)"
    }
    $normalizedLocation = if ($result.location) { ([string]$result.location).Replace("\\", "\") } else { "" }
    if (-not $result.location -or $normalizedLocation -notlike "*$($result.cache_dir)*") {
        throw "sccache server did not bind the managed cache directory. Reported: $($result.location)"
    }
    return [pscustomobject]@{
        path = $sccache.Source
        cache_dir = $result.cache_dir
        max_cache_size = $MaxCacheSize
        config_path = $result.config_path
        base_directories = $result.base_directories
        base_directory_status = $result.base_directory_status
        configuration_loaded = $result.configuration_loaded
        state_path = $result.state_path
        location = $result.location
        restarted = $result.restarted
    }
}

function Get-RustCacheSccacheWrapperContent {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [Parameter(Mandatory)][string]$SccachePath,
        [Parameter(Mandatory)][string]$MaxCacheSize
    )

    $configPath = Get-RustCacheSccacheConfigPath -CacheRoot $CacheRoot
    $cacheDir = Join-Path ([System.IO.Path]::GetFullPath($CacheRoot)) "sccache"
    @(
        "@echo off"
        "rem Generated by the Elon Rust cache platform."
        "set `"SCCACHE_CONF=$configPath`""
        "set `"SCCACHE_DIR=$cacheDir`""
        "set `"SCCACHE_CACHE_SIZE=$MaxCacheSize`""
        "rem Cargo has already consumed these routing controls. Do not hash them as rustc inputs."
        "set `"CARGO_BUILD_BUILD_DIR=`""
        "set `"CARGO_TARGET_DIR=`""
        "`"$SccachePath`" %*"
    ) -join "`r`n"
}

function Set-RustCacheUserEnvironment {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [Parameter(Mandatory)][string]$MaxCacheSize,
        [switch]$Apply
    )

    $values = [ordered]@{
        ELON_RUST_CACHE_ROOT = [System.IO.Path]::GetFullPath($CacheRoot)
        SCCACHE_DIR = Join-Path ([System.IO.Path]::GetFullPath($CacheRoot)) "sccache"
        SCCACHE_CACHE_SIZE = $MaxCacheSize
        SCCACHE_CONF = Get-RustCacheSccacheConfigPath -CacheRoot $CacheRoot
    }
    if ($Apply -and $env:OS -eq "Windows_NT") {
        foreach ($name in $values.Keys) {
            [Environment]::SetEnvironmentVariable($name, $values[$name], "User")
            [Environment]::SetEnvironmentVariable($name, $values[$name], "Process")
        }
        [Environment]::SetEnvironmentVariable("ELON_DEV_CARGO_TARGET_DIR", $null, "User")
        Remove-Item Env:ELON_DEV_CARGO_TARGET_DIR -ErrorAction SilentlyContinue
    }
    [pscustomobject]@{ applied = [bool]$Apply; values = [pscustomobject]$values; cleared_legacy_target = [bool]$Apply }
}

function Install-RustCachePlatform {
    param(
        [Parameter(Mandatory)][string]$SourceScriptsRoot,
        [string]$CacheRoot,
        [string]$RepoRoot,
        [string]$CargoConfigPath,
        [switch]$ActivateCargoConfig,
        [switch]$ConfigureSccacheServer
    )

    $sourceRoot = [System.IO.Path]::GetFullPath($SourceScriptsRoot)
    $sourceEntry = Join-Path $sourceRoot "rust-cache.ps1"
    $sourceModules = Join-Path $sourceRoot "rust-cache"
    if (-not (Test-Path -LiteralPath $sourceEntry) -or -not (Test-Path -LiteralPath $sourceModules)) {
        throw "Rust cache source files are incomplete under $sourceRoot"
    }
    $root = Resolve-RustCacheRoot -ExplicitRoot $CacheRoot -RepoRoot $RepoRoot
    Initialize-RustCachePolicy -CacheRoot $root | Out-Null
    $platformRoot = Join-Path $root "platform"
    $targetModules = Join-Path $platformRoot "rust-cache"
    New-Item -ItemType Directory -Force -Path $targetModules | Out-Null
    Copy-Item -LiteralPath $sourceEntry -Destination (Join-Path $platformRoot "rust-cache.ps1") -Force
    Get-ChildItem -LiteralPath $sourceModules -File | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $targetModules $_.Name) -Force
    }

    $sccache = Get-Command sccache -ErrorAction SilentlyContinue
    $policy = Get-RustCachePolicy -CacheRoot $root
    $sccacheWrapperPath = $null
    if ($sccache) {
        $sccacheWrapperPath = Get-RustCacheSccacheWrapperPath -CacheRoot $root
        $wrapperContent = Get-RustCacheSccacheWrapperContent -CacheRoot $root -SccachePath $sccache.Source -MaxCacheSize ([string]$policy.sccache_max_size)
        Set-Content -LiteralPath $sccacheWrapperPath -Value $wrapperContent -Encoding ASCII -NoNewline
    }
    $includePath = Join-Path $root "config\cargo-cache.toml"
    $includeContent = Get-RustCacheCargoIncludeContent -CacheRoot $root -SccachePath $sccacheWrapperPath
    Set-Content -LiteralPath $includePath -Value $includeContent -Encoding UTF8 -NoNewline

    $sccacheConfig = Sync-RustCacheSccacheConfiguration -CacheRoot $root

    New-Item -ItemType Directory -Force -Path (Join-Path $root "sccache") | Out-Null
    $sccacheServer = $null
    if ($ConfigureSccacheServer -and $sccache) {
        $sccacheServer = Restart-RustCacheSccacheServer -CacheRoot $root -MaxCacheSize ([string]$policy.sccache_max_size)
    }

    $userEnvironment = Set-RustCacheUserEnvironment -CacheRoot $root -MaxCacheSize ([string](Get-RustCachePolicy -CacheRoot $root).sccache_max_size) -Apply:$ActivateCargoConfig

    $activation = $null
    if ($ActivateCargoConfig) {
        if ([string]::IsNullOrWhiteSpace($CargoConfigPath)) {
            throw "-CargoConfigPath is required with -ActivateCargoConfig."
        }
        $activation = Set-RustCacheParentCargoConfig -CargoConfigPath $CargoConfigPath -IncludeConfigPath $includePath -Apply
    }
    [pscustomobject]@{
        cache_root = $root
        platform_root = $platformRoot
        entry_path = Join-Path $platformRoot "rust-cache.ps1"
        cargo_include_path = $includePath
        sccache_path = if ($sccache) { $sccache.Source } else { $null }
        sccache_wrapper_path = $sccacheWrapperPath
        sccache_config_path = $sccacheConfig.config_path
        sccache_server = $sccacheServer
        user_environment = $userEnvironment
        cargo_activation = $activation
    }
}

Export-ModuleMember -Function ConvertTo-RustCacheTomlPath, Get-RustCacheCargoIncludeContent, Get-RustCacheSccacheWrapperContent, Set-RustCacheParentCargoConfig, Restart-RustCacheSccacheServer, Set-RustCacheUserEnvironment, Install-RustCachePlatform
