Import-Module "$PSScriptRoot\RustCache.Portability.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.NetworkStorage.psm1" -DisableNameChecking

function Read-RustCacheCargoControlSnapshot {
    param([Parameter(Mandatory)][string]$Path, [switch]$AllowMissing)
    $full=[IO.Path]::GetFullPath($Path)
    $cursor=[IO.FileInfo]::new($full)
    while ($null -ne $cursor) {
        if (Test-Path -LiteralPath $cursor.FullName) {
            $item=Get-Item -LiteralPath $cursor.FullName -Force
            if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) { throw 'RUST_CACHE_INCLUDE_REPARSE: Linked control files are not accepted.' }
        }
        $cursor=if($cursor -is [IO.FileInfo]){$cursor.Directory}else{$cursor.Parent}
    }
    if (-not (Test-Path -LiteralPath $full)) {
        if ($AllowMissing) { return [pscustomobject]@{path=$full;exists=$false;sha256=$null;bytes=$null;text=''} }
        throw 'RUST_CACHE_INCLUDE_EVIDENCE_MISSING: Managed installation evidence is missing.'
    }
    $item=Get-Item -LiteralPath $full -Force
    if ($item.PSIsContainer -or $item.Length -gt 1MB) { throw 'RUST_CACHE_INCLUDE_EVIDENCE_INVALID: A small regular control file is required.' }
    $bytes=[IO.File]::ReadAllBytes($full)
    $text=[Text.UTF8Encoding]::new($false,$true).GetString($bytes).TrimStart([char]0xfeff)
    $sha=[Security.Cryptography.SHA256]::Create()
    try {$hash=([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}
    [pscustomobject]@{path=$full;exists=$true;sha256=$hash;bytes=$bytes;text=$text}
}

function Get-RustCacheParentIncludePath {
    param([string[]]$Lines)
    $found=$null;$section=''
    foreach($line in $Lines) {
        if($line -match '^\s*\['){$section='table'}
        if($line -notmatch '^\s*include\s*='){continue}
        if($section -or $null -ne $found -or $line -notmatch '^\s*include\s*=\s*\[\s*(?<quote>["''])(?<path>[^"''\\]+)\k<quote>\s*\]\s*(?:#.*)?$') {
            throw 'RUST_CACHE_INCLUDE_UNRELATED: Only one literal top-level managed include may be migrated.'
        }
        $found=[string]$Matches.path
        if(-not [IO.Path]::IsPathRooted($found)){throw 'RUST_CACHE_INCLUDE_UNRELATED: Relative includes require an explicit manual merge.'}
    }
    if($null -eq $found){return $null}
    return [IO.Path]::GetFullPath($found)
}

function Get-RustCacheManagedIncludeMigration {
    param([Parameter(Mandatory)][string]$CargoConfigPath,[Parameter(Mandatory)][string]$PreviousIncludePath)
    $parent=Read-RustCacheCargoControlSnapshot $CargoConfigPath
    $include=Read-RustCacheCargoControlSnapshot $PreviousIncludePath
    $root=Split-Path (Split-Path $include.path -Parent) -Parent
    if($include.path -ine (Join-Path $root 'config\cargo-cache.toml')){throw 'RUST_CACHE_INCLUDE_UNRELATED: Previous include is not the managed include location.'}
    $owner=Read-RustCacheCargoControlSnapshot (Join-Path $root '.rust-cache-owner.json')
    $ownerData=$owner.text|ConvertFrom-Json -ErrorAction Stop
    if($ownerData.schema -ne 'elon.rust_cache.root_owner.v1' -or $ownerData.machine_id_sha256 -cne (Get-RustCacheMachineIdentity)){
        throw 'RUST_CACHE_INCLUDE_FOREIGN: Previous installation does not belong to this machine.'
    }
    $platform=Join-Path $root 'platform'
    $manifest=Read-RustCacheCargoControlSnapshot (Join-Path $platform 'platform-install.json')
    $record=$manifest.text|ConvertFrom-Json -ErrorAction Stop
    if($record.schema -ne 'elon.rust_cache.platform_install.v1' -or $record.installed_fingerprint_mode -ne 'raw-bytes-v1' -or
        $record.entry_relative_path -ne 'platform/rust-cache.ps1' -or $record.installed_hash -notmatch '^[a-f0-9]{64}$'){
        throw 'RUST_CACHE_INCLUDE_INSTALL_IDENTITY: Previous installation manifest is unsupported.'
    }
    $queue=New-Object 'Collections.Generic.Stack[string]';$queue.Push($platform);$count=0
    while($queue.Count){foreach($item in Get-ChildItem -LiteralPath $queue.Pop() -Force){
        $count++;if($count -gt 4096 -or $item.Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'RUST_CACHE_INCLUDE_INSTALL_TREE: Previous installation is linked or exceeds the inspection bound.'}
        if($item.PSIsContainer){$queue.Push($item.FullName)}
    }}
    $fingerprint=Get-RustCachePlatformFingerprint -SourceScriptsRoot $platform -Installed
    if($fingerprint.hash -cne $record.installed_hash -or $fingerprint.file_count -ne $record.installed_file_count){
        throw 'RUST_CACHE_INCLUDE_INSTALL_DRIFT: Previous installed files no longer match their receipt.'
    }
    $prefix=$root.Replace('\','/')
    $expected="# Generated by the Elon Rust cache platform. Re-run rust-cache.ps1 install to refresh.`n[build]`nbuild-dir = `"$prefix/quarantine/{workspace-path-hash}`"`n"
    $native=$expected + "rustc-wrapper = `"$prefix/platform/rustc-sccache-wrapper.exe`"`n"
    $actual=$include.text.Replace("`r`n","`n").Replace("`r","`n")
    if($actual -cne $expected -and $actual -cne $native){throw 'RUST_CACHE_INCLUDE_CONTENT: Previous include is not the exact generated managed content.'}
    [pscustomobject][ordered]@{schema='elon.rust_cache.include_migration.v1';cargo_config_path=$parent.path;cargo_config_sha256=$parent.sha256
        previous_include_path=$include.path;previous_include_sha256=$include.sha256;previous_root=$root
        owner_sha256=$owner.sha256;install_manifest_sha256=$manifest.sha256;installed_hash=$fingerprint.hash}
}

function Assert-RustCacheIncludeMigrationCurrent {
    param([Parameter(Mandatory)]$Migration)
    $current=Get-RustCacheManagedIncludeMigration -CargoConfigPath $Migration.cargo_config_path -PreviousIncludePath $Migration.previous_include_path
    foreach($name in @('schema','cargo_config_path','cargo_config_sha256','previous_include_path','previous_include_sha256','previous_root','owner_sha256','install_manifest_sha256','installed_hash')){
        if([string]$current.$name -cne [string]$Migration.$name){throw 'RUST_CACHE_INCLUDE_MIGRATION_DRIFT: The reviewed migration evidence changed.'}
    }
}

Export-ModuleMember -Function Read-RustCacheCargoControlSnapshot,Get-RustCacheParentIncludePath,Get-RustCacheManagedIncludeMigration,Assert-RustCacheIncludeMigrationCurrent
