Import-Module "$PSScriptRoot\RustCache.Paths.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Policy.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Registry.psm1" -DisableNameChecking

function ConvertTo-RustCacheSccacheConfigPath {
    param([Parameter(Mandatory)][string]$Path)
    [System.IO.Path]::GetFullPath($Path).Replace('\', '/').Replace('"', '\"')
}

function Get-RustCacheSccacheConfigPath {
    param([Parameter(Mandatory)][string]$CacheRoot)
    Join-Path $CacheRoot "config\sccache-config"
}

function Get-RustCacheSccacheWrapperPath {
    param([Parameter(Mandatory)][string]$CacheRoot)
    Join-Path $CacheRoot "platform\rustc-sccache-wrapper.exe"
}

function Get-RustCacheSccacheBaseDirectories {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [string[]]$AdditionalBaseDirs = @()
    )

    $registry = Read-RustCacheRegistry -CacheRoot $CacheRoot
    $candidates = New-Object System.Collections.Generic.List[string]
    foreach ($item in @($registry.workspaces)) {
        if ($item.build_dir) { $candidates.Add([string]$item.build_dir) }
        if ($item.target_dir) { $candidates.Add([string]$item.target_dir) }
        if ($item.workspace_root) { $candidates.Add([string]$item.workspace_root) }
        if ($item.project_root) { $candidates.Add([string]$item.project_root) }
    }
    foreach ($path in $AdditionalBaseDirs) {
        if (-not [string]::IsNullOrWhiteSpace($path)) { $candidates.Add($path) }
    }

    $unique = New-Object System.Collections.Generic.List[string]
    foreach ($candidate in $candidates) {
        if (-not (Test-RustCacheAbsolutePath $candidate)) { continue }
        $fullPath = [System.IO.Path]::GetFullPath($candidate).TrimEnd('\', '/')
        if (-not (Test-Path -LiteralPath $fullPath)) { continue }
        if (-not ($unique | Where-Object { $_ -ieq $fullPath })) { $unique.Add($fullPath) }
    }
    return @($unique | Sort-Object @{ Expression = { $_.Length }; Descending = $true }, @{ Expression = { $_ }; Descending = $false })
}

function Get-RustCacheSccacheConfigContent {
    param([string[]]$BaseDirs = @())

    $values = @($BaseDirs | ForEach-Object { '"{0}"' -f (ConvertTo-RustCacheSccacheConfigPath $_) })
    return "# Generated by the Elon Rust cache platform. Do not edit.`r`nbasedirs = [{0}]`r`n" -f ($values -join ", ")
}

function Enter-RustCacheSccacheConfigLock {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [int]$TimeoutSeconds = 30
    )

    $lockPath = Join-Path $CacheRoot "config\sccache-config.lock"
    New-Item -ItemType Directory -Force -Path (Split-Path $lockPath -Parent) | Out-Null
    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    while ([DateTime]::UtcNow -lt $deadline) {
        try {
            return [System.IO.File]::Open($lockPath, [System.IO.FileMode]::OpenOrCreate, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None)
        } catch [System.IO.IOException] {
            Start-Sleep -Milliseconds 100
        }
    }
    throw "Timed out waiting for sccache configuration lock: $lockPath"
}

function Get-RustCacheTextSha256 {
    param([Parameter(Mandatory)][string]$Value)

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
    $algorithm = [System.Security.Cryptography.SHA256]::Create()
    try { $hash = $algorithm.ComputeHash($bytes) } finally { $algorithm.Dispose() }
    return ([System.BitConverter]::ToString($hash)).Replace("-", "").ToLowerInvariant()
}

function Sync-RustCacheSccacheConfiguration {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [string[]]$AdditionalBaseDirs = @(),
        [switch]$ConfigureProcessEnvironment,
        [switch]$RestartIfChanged,
        [switch]$ForceRestart
    )

    $root = [System.IO.Path]::GetFullPath($CacheRoot)
    $configLock = Enter-RustCacheSccacheConfigLock -CacheRoot $root
    try {
    $policy = Get-RustCachePolicy -CacheRoot $root
    $configPath = Get-RustCacheSccacheConfigPath -CacheRoot $root
    $baseDirs = @(Get-RustCacheSccacheBaseDirectories -CacheRoot $root -AdditionalBaseDirs $AdditionalBaseDirs)
    $content = Get-RustCacheSccacheConfigContent -BaseDirs $baseDirs
    $configHash = Get-RustCacheTextSha256 -Value $content
    $statePath = Join-Path $root "state\sccache-sync.json"
    $previousState = if (Test-Path -LiteralPath $statePath) {
        try { Get-Content -Raw -LiteralPath $statePath -Encoding UTF8 | ConvertFrom-Json } catch { $null }
    } else { $null }
    $previous = if (Test-Path -LiteralPath $configPath) { Get-Content -Raw -LiteralPath $configPath -Encoding UTF8 } else { $null }
    $changed = $previous -cne $content
    if ($changed) {
        New-Item -ItemType Directory -Force -Path (Split-Path $configPath -Parent) | Out-Null
        Set-Content -LiteralPath $configPath -Value $content -Encoding UTF8 -NoNewline
    }

    $cacheDir = Join-Path $root "sccache"
    New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null
    if ($ConfigureProcessEnvironment -or $RestartIfChanged -or $ForceRestart) {
        $env:SCCACHE_CONF = $configPath
        $env:SCCACHE_DIR = $cacheDir
        $env:SCCACHE_CACHE_SIZE = [string]$policy.sccache_max_size
    }
    $sccache = if ($ConfigureProcessEnvironment -or $RestartIfChanged -or $ForceRestart) { Get-Command sccache -ErrorAction SilentlyContinue } else { $null }
    $pendingBefore = $previousState -and ([bool]$previousState.restart_pending -or [string]$previousState.loaded_config_sha256 -ne $configHash)
    $shouldRestart = $sccache -and ($ForceRestart -or ($RestartIfChanged -and ($changed -or $pendingBefore)))
    $pending = $false
    $restarted = $false
    if ($shouldRestart) {
        $activeBuilds = @(Get-Process -Name cargo, rustc -ErrorAction SilentlyContinue)
        if ($activeBuilds.Count -gt 0) {
            $pending = $true
        } else {
            try {
                & $sccache.Source --stop-server 2>$null | Out-Null
            } catch {
                # A first-time install has no server to stop.
            }
            & $sccache.Source --start-server | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "sccache failed to start with managed config: $configPath" }
            $restarted = $true
        }
    }

    $stats = if ($sccache) { @(& $sccache.Source --show-stats 2>&1) } else { @() }
    $location = $stats | Where-Object { $_ -match '^Cache location\s+' } | Select-Object -First 1
    $baseDirStatus = $stats | Where-Object { $_ -match '^Base directories\s+' } | Select-Object -First 1
    $loadedHash = if ($restarted) { $configHash } elseif ($previousState) { [string]$previousState.loaded_config_sha256 } else { $null }
    if ($changed -and -not $restarted) { $pending = $true }
    if ($RestartIfChanged -or $ForceRestart -or $changed) {
        $state = [ordered]@{
            schema_version = 1
            updated_utc = [DateTime]::UtcNow.ToString("o")
            config_sha256 = $configHash
            loaded_config_sha256 = $loadedHash
            restart_pending = [bool]$pending
            base_directory_count = $baseDirs.Count
            base_directory_status = $baseDirStatus
        }
        New-Item -ItemType Directory -Force -Path (Split-Path $statePath -Parent) | Out-Null
        $state | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $statePath -Encoding UTF8
    }
    return [pscustomobject]@{
        config_path = $configPath
        cache_dir = $cacheDir
        max_cache_size = [string]$policy.sccache_max_size
        base_directories = $baseDirs
        changed = $changed
        restarted = $restarted
        restart_pending = $pending
        configuration_loaded = (-not $pending -and $loadedHash -eq $configHash)
        config_sha256 = $configHash
        loaded_config_sha256 = $loadedHash
        state_path = $statePath
        location = $location
        base_directory_status = $baseDirStatus
    }
    } finally {
        if ($configLock) { $configLock.Dispose() }
    }
}

Export-ModuleMember -Function ConvertTo-RustCacheSccacheConfigPath, Get-RustCacheSccacheConfigPath, Get-RustCacheSccacheWrapperPath, Get-RustCacheSccacheBaseDirectories, Get-RustCacheSccacheConfigContent, Enter-RustCacheSccacheConfigLock, Get-RustCacheTextSha256, Sync-RustCacheSccacheConfiguration
