function Get-RustCacheDefaultUserLauncherPath {
    param([string]$ExplicitPath)

    if (-not [string]::IsNullOrWhiteSpace($ExplicitPath)) {
        return [System.IO.Path]::GetFullPath($ExplicitPath)
    }

    $localAppData = [Environment]::GetFolderPath([Environment+SpecialFolder]::LocalApplicationData)
    if ([string]::IsNullOrWhiteSpace($localAppData)) {
        throw "Cannot resolve the per-user Rust cache launcher path. Pass -UserLauncherPath."
    }
    return Join-Path $localAppData "Elon\bin\rust-cache.ps1"
}

function Get-RustCacheUserLauncherContent {
    param([Parameter(Mandatory)][string]$CacheRoot)

    $entryPath = Join-Path ([System.IO.Path]::GetFullPath($CacheRoot)) "platform\rust-cache.ps1"
    $escapedEntry = $entryPath.Replace("'", "''")
    $lines = @(
        "# Generated by the Elon Rust cache platform. Re-run install to refresh."
        '$ErrorActionPreference = "Stop"'
        ('$entry = ''{0}''' -f $escapedEntry)
        'if (-not (Test-Path -LiteralPath $entry -PathType Leaf)) {'
        '    throw "The installed Rust cache platform is missing: $entry"'
        '}'
        '& $entry @args'
    )
    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function Get-RustCacheLauncherHash {
    param([Parameter(Mandatory)][string]$Content)

    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Content)
        return ([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace("-", "").ToLowerInvariant()
    } finally {
        $sha.Dispose()
    }
}

function Install-RustCacheUserLauncher {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [string]$UserLauncherPath
    )

    $root = [System.IO.Path]::GetFullPath($CacheRoot)
    $entryPath = Join-Path $root "platform\rust-cache.ps1"
    if (-not (Test-Path -LiteralPath $entryPath -PathType Leaf)) {
        throw "Cannot install the user launcher before the platform entry exists: $entryPath"
    }

    $launcherPath = Get-RustCacheDefaultUserLauncherPath -ExplicitPath $UserLauncherPath
    $launcherDirectory = Split-Path $launcherPath -Parent
    New-Item -ItemType Directory -Force -Path $launcherDirectory | Out-Null
    $content = Get-RustCacheUserLauncherContent -CacheRoot $root
    $temporary = "$launcherPath.$PID.tmp"
    Set-Content -LiteralPath $temporary -Value $content -Encoding UTF8 -NoNewline
    Move-Item -LiteralPath $temporary -Destination $launcherPath -Force

    [pscustomobject]@{
        schema = "elon.rust_cache.user_launcher.v1"
        path = $launcherPath
        entry_path = $entryPath
        content_hash = Get-RustCacheLauncherHash -Content $content
    }
}

function Test-RustCacheUserLauncher {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [string]$UserLauncherPath
    )

    $launcherPath = Get-RustCacheDefaultUserLauncherPath -ExplicitPath $UserLauncherPath
    $expected = Get-RustCacheUserLauncherContent -CacheRoot $CacheRoot
    if (-not (Test-Path -LiteralPath $launcherPath -PathType Leaf)) {
        return [pscustomobject]@{
            status = "missing"
            healthy = $false
            path = $launcherPath
            expected_hash = Get-RustCacheLauncherHash -Content $expected
            actual_hash = $null
        }
    }

    $actual = Get-Content -Raw -LiteralPath $launcherPath -Encoding UTF8
    [pscustomobject]@{
        status = if ($actual -ceq $expected) { "healthy" } else { "stale" }
        healthy = $actual -ceq $expected
        path = $launcherPath
        expected_hash = Get-RustCacheLauncherHash -Content $expected
        actual_hash = Get-RustCacheLauncherHash -Content $actual
    }
}

Export-ModuleMember -Function Get-RustCacheDefaultUserLauncherPath, Get-RustCacheUserLauncherContent, Install-RustCacheUserLauncher, Test-RustCacheUserLauncher
