Import-Module "$PSScriptRoot\RustCache.Paths.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Policy.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Registry.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.SccacheTiers.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Studio.psm1" -DisableNameChecking

function ConvertTo-RustCacheSccacheConfigPath {
    param([Parameter(Mandatory)][string]$Path)
    [System.IO.Path]::GetFullPath($Path).Replace('\', '/').Replace('"', '\"')
}

function Get-RustCacheSccacheConfigPath {
    param([Parameter(Mandatory)][string]$CacheRoot)
    (Get-RustCacheSccacheTierLayout -CacheRoot $CacheRoot).config_path
}

function Get-RustCacheSccacheWrapperPath {
    param([Parameter(Mandatory)][string]$CacheRoot)
    Join-Path (Resolve-RustCacheManagementRoot -CacheRoot $CacheRoot) "platform\rustc-sccache-wrapper.exe"
}

function Get-RustCacheSccacheBaseDirectories {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [string[]]$AdditionalBaseDirs = @()
    )

    $registry = Read-RustCacheRegistry -CacheRoot $CacheRoot
    $candidates = New-Object System.Collections.Generic.List[string]
    foreach ($item in @($registry.workspaces)) {
        if ($item.build_dir) { $candidates.Add([string]$item.build_dir) }
        if ($item.target_dir) { $candidates.Add([string]$item.target_dir) }
        if ($item.workspace_root) { $candidates.Add([string]$item.workspace_root) }
        if ($item.project_root) { $candidates.Add([string]$item.project_root) }
    }
    foreach ($path in $AdditionalBaseDirs) {
        if (-not [string]::IsNullOrWhiteSpace($path)) { $candidates.Add($path) }
    }

    $unique = New-Object System.Collections.Generic.List[string]
    foreach ($candidate in $candidates) {
        if (-not (Test-RustCacheAbsolutePath $candidate)) { continue }
        $fullPath = [System.IO.Path]::GetFullPath($candidate).TrimEnd('\', '/')
        if (-not (Test-Path -LiteralPath $fullPath)) { continue }
        if (-not ($unique | Where-Object { $_ -ieq $fullPath })) { $unique.Add($fullPath) }
    }
    return @($unique | Sort-Object @{ Expression = { $_.Length }; Descending = $true }, @{ Expression = { $_ }; Descending = $false })
}

function Get-RustCacheSccacheConfigContent {
    param([string[]]$BaseDirs = @(), $Layout = $null)

    $values = @($BaseDirs | ForEach-Object { '"{0}"' -f (ConvertTo-RustCacheSccacheConfigPath $_) })
    $content = "# Generated by the Elon Rust cache platform. Do not edit.`r`nbasedirs = [{0}]`r`n" -f ($values -join ", ")
    if ($null -ne $Layout) { $content += Get-RustCacheSccacheTierToml $Layout }
    return $content
}

function Enter-RustCacheSccacheConfigLock {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [int]$TimeoutSeconds = 30,
        $Layout = $null
    )

    $lockPath = if ($null -ne $Layout) { $Layout.lock_path } else { Join-Path $CacheRoot "config\sccache-config.lock" }
    New-Item -ItemType Directory -Force -Path (Split-Path $lockPath -Parent) | Out-Null
    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    while ([DateTime]::UtcNow -lt $deadline) {
        try {
            return [System.IO.File]::Open($lockPath, [System.IO.FileMode]::OpenOrCreate, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None)
        } catch [System.IO.IOException] {
            Start-Sleep -Milliseconds 100
        }
    }
    throw "Timed out waiting for sccache configuration lock: $lockPath"
}

function Get-RustCacheTextSha256 {
    param([Parameter(Mandatory)][string]$Value)

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
    $algorithm = [System.Security.Cryptography.SHA256]::Create()
    try { $hash = $algorithm.ComputeHash($bytes) } finally { $algorithm.Dispose() }
    return ([System.BitConverter]::ToString($hash)).Replace("-", "").ToLowerInvariant()
}

function Sync-RustCacheSccacheConfiguration {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [string[]]$AdditionalBaseDirs = @(),
        [switch]$ConfigureProcessEnvironment,
        [switch]$RestartIfChanged,
        [switch]$ForceRestart
    )

    $root = [System.IO.Path]::GetFullPath($CacheRoot)
    $layout = Get-RustCacheSccacheTierLayout -CacheRoot $root
    if ($layout.tiered) {
        return Sync-RustCacheTieredSccacheConfiguration -CacheRoot $root -Layout $layout -AdditionalBaseDirs $AdditionalBaseDirs `
            -ConfigureProcessEnvironment:$ConfigureProcessEnvironment -RestartIfChanged:$RestartIfChanged -ForceRestart:$ForceRestart
    }
    $configLock = Enter-RustCacheSccacheConfigLock -CacheRoot $root
    try {
    $policy = Get-RustCachePolicy -CacheRoot $root
    $configPath = Get-RustCacheSccacheConfigPath -CacheRoot $root
    $baseDirs = @(Get-RustCacheSccacheBaseDirectories -CacheRoot $root -AdditionalBaseDirs $AdditionalBaseDirs)
    $content = Get-RustCacheSccacheConfigContent -BaseDirs $baseDirs
    $configHash = Get-RustCacheTextSha256 -Value $content
    $statePath = Join-Path $root "state\sccache-sync.json"
    $previousState = if (Test-Path -LiteralPath $statePath) {
        try { Get-Content -Raw -LiteralPath $statePath -Encoding UTF8 | ConvertFrom-Json } catch { $null }
    } else { $null }
    $previous = if (Test-Path -LiteralPath $configPath) { Get-Content -Raw -LiteralPath $configPath -Encoding UTF8 } else { $null }
    $changed = $previous -cne $content
    if ($changed) {
        New-Item -ItemType Directory -Force -Path (Split-Path $configPath -Parent) | Out-Null
        Set-Content -LiteralPath $configPath -Value $content -Encoding UTF8 -NoNewline
    }

    $cacheDir = Join-Path $root "sccache"
    New-Item -ItemType Directory -Force -Path $cacheDir | Out-Null
    if ($ConfigureProcessEnvironment -or $RestartIfChanged -or $ForceRestart) {
        $env:SCCACHE_CONF = $configPath
        $env:SCCACHE_DIR = $cacheDir
        $env:SCCACHE_CACHE_SIZE = [string]$policy.sccache_max_size
    }
    $sccache = if ($ConfigureProcessEnvironment -or $RestartIfChanged -or $ForceRestart) { Get-Command sccache -ErrorAction SilentlyContinue } else { $null }
    $pendingBefore = $previousState -and ([bool]$previousState.restart_pending -or [string]$previousState.loaded_config_sha256 -ne $configHash)
    $shouldRestart = $sccache -and ($ForceRestart -or ($RestartIfChanged -and ($changed -or $pendingBefore)))
    $pending = $false
    $restarted = $false
    if ($shouldRestart) {
        $activeBuilds = @(Get-Process -Name cargo, rustc -ErrorAction SilentlyContinue)
        if ($activeBuilds.Count -gt 0) {
            $pending = $true
        } else {
            try {
                & $sccache.Source --stop-server 2>$null | Out-Null
            } catch {
                # A first-time install has no server to stop.
            }
            & $sccache.Source --start-server | Out-Null
            if ($LASTEXITCODE -ne 0) { throw "sccache failed to start with managed config: $configPath" }
            $restarted = $true
        }
    }

    $stats = if ($sccache) { @(& $sccache.Source --show-stats 2>&1) } else { @() }
    $location = $stats | Where-Object { $_ -match '^Cache location\s+' } | Select-Object -First 1
    $baseDirStatus = $stats | Where-Object { $_ -match '^Base directories\s+' } | Select-Object -First 1
    $loadedHash = if ($restarted) { $configHash } elseif ($previousState) { [string]$previousState.loaded_config_sha256 } else { $null }
    if ($changed -and -not $restarted) { $pending = $true }
    if ($RestartIfChanged -or $ForceRestart -or $changed) {
        $state = [ordered]@{
            schema_version = 1
            updated_utc = [DateTime]::UtcNow.ToString("o")
            config_sha256 = $configHash
            loaded_config_sha256 = $loadedHash
            restart_pending = [bool]$pending
            base_directory_count = $baseDirs.Count
            base_directory_status = $baseDirStatus
        }
        New-Item -ItemType Directory -Force -Path (Split-Path $statePath -Parent) | Out-Null
        $state | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $statePath -Encoding UTF8
    }
    return [pscustomobject]@{
        config_path = $configPath
        cache_dir = $cacheDir
        max_cache_size = [string]$policy.sccache_max_size
        base_directories = $baseDirs
        changed = $changed
        restarted = $restarted
        restart_pending = $pending
        configuration_loaded = (-not $pending -and $loadedHash -eq $configHash)
        config_sha256 = $configHash
        loaded_config_sha256 = $loadedHash
        state_path = $statePath
        location = $location
        base_directory_status = $baseDirStatus
    }
    } finally {
        if ($configLock) { $configLock.Dispose() }
    }
}

function Write-RustCacheSccacheAtomic {
    param([string]$Path, [string]$Content)
    $temporary = $Path + '.' + [Guid]::NewGuid().ToString('N') + '.tmp'
    $backup = $temporary + '.bak'
    try {
        [IO.File]::WriteAllText($temporary,$Content,(New-Object Text.UTF8Encoding($false)))
        if (Test-Path -LiteralPath $Path) { [IO.File]::Replace($temporary,$Path,$backup) } else { [IO.File]::Move($temporary,$Path) }
    } finally { foreach($item in @($temporary,$backup)){if (Test-Path -LiteralPath $item) { Remove-Item -LiteralPath $item -Force }} }
}

function Get-RustCacheTierDaemon {
    param($Layout, $State, [string]$SccachePath)
    $listeners = @(Get-NetTCPConnection -State Listen -ErrorAction Stop | Where-Object LocalPort -eq ([int]$Layout.server_port))
    if (-not $listeners.Count) { return [pscustomobject]@{ present=$false; owned=$false; pid_value=$null; started_ticks=$null } }
    $ids = @($listeners | Select-Object -ExpandProperty OwningProcess -Unique)
    $owned=$false; $ticks=$null
    if ($ids.Count -eq 1 -and $null -ne $State -and $State.PSObject.Properties.Name -contains 'server_pid') {
        try {
            $process=Get-Process -Id $ids[0] -ErrorAction Stop
            $ticks=$process.StartTime.ToUniversalTime().Ticks
            $owned=[int]$State.server_pid -eq [int]$ids[0] -and [string]$State.server_started_ticks -eq [string]$ticks -and
                [string]$State.server_port -eq $Layout.server_port -and [string]$process.Path -ieq $SccachePath -and
                [string]$State.executable_path -ieq $SccachePath -and @($listeners | Where-Object { $_.LocalAddress -notin @('127.0.0.1','::1') }).Count -eq 0
        } catch { $owned=$false }
    }
    [pscustomobject]@{ present=$true; owned=$owned; pid_value=if($ids.Count -eq 1){$ids[0]}else{$null}; started_ticks=$ticks }
}

function Sync-RustCacheTieredSccacheConfiguration {
    param([string]$CacheRoot, $Layout, [string[]]$AdditionalBaseDirs=@(), [switch]$ConfigureProcessEnvironment, [switch]$RestartIfChanged, [switch]$ForceRestart)
    $sccache=Get-Command sccache -ErrorAction SilentlyContinue
    if ($Layout.tier.remote -and -not $sccache) { throw 'Sccache is required to validate a remote tier.' }
    if ($sccache) { Assert-RustCacheSccacheCapabilities $Layout $sccache.Source }
    Initialize-RustCacheSccacheTierStorage $Layout
    foreach($path in @($Layout.lock_path,$Layout.config_path,$Layout.state_path,$Layout.binding_path,$Layout.cached_config_path)) { Assert-RustCacheTierLocalPath $path | Out-Null }
    $lease=Enter-RustCacheSccacheConfigLock -CacheRoot $CacheRoot -Layout $Layout
    try {
        if (Test-Path -LiteralPath $Layout.binding_path) {
            $binding=[IO.File]::ReadAllText($Layout.binding_path,[Text.Encoding]::UTF8)|ConvertFrom-Json
            $expected=Get-RustCacheTierTextHash ((Get-RustCacheSccacheBinding $Layout)|ConvertTo-Json -Compress)
            if ($binding.binding_sha256 -ne $expected) { throw 'Sccache layout changed; reinstall the native wrapper before activating it.' }
        }
        $state=if(Test-Path -LiteralPath $Layout.state_path){[IO.File]::ReadAllText($Layout.state_path,[Text.Encoding]::UTF8)|ConvertFrom-Json}else{$null}
        # The machine's registered prefixes remain stable when task/build roots change.
        $baseDirs=@($Layout.tier.base_directories)
        $content=Get-RustCacheSccacheConfigContent -BaseDirs $baseDirs -Layout $Layout
        $hash=Get-RustCacheTextSha256 $content
        $previous=if(Test-Path -LiteralPath $Layout.config_path){[IO.File]::ReadAllText($Layout.config_path,[Text.Encoding]::UTF8)}else{$null}
        $changed=$previous -cne $content
        if ($null -ne $previous -and $changed -and ($null -eq $state -or $state.config_sha256 -ne (Get-RustCacheTextSha256 $previous))) { throw 'Existing sccache configuration is unowned or was edited; preserve it and reconcile explicitly.' }
        if ($changed) { Write-RustCacheSccacheAtomic $Layout.config_path $content }
        $configure=$ConfigureProcessEnvironment -or $RestartIfChanged -or $ForceRestart
        if ($configure) {
            $environment=Get-RustCacheSccacheTierEnvironment $Layout
            Set-RustCacheSccacheProcessEnvironment $environment
        }
        $pending=$changed -or $null -eq $state -or [string]$state.loaded_config_sha256 -ne $hash
        $restarted=$false; $reason=$null; $daemon=$null; $location=$null; $baseStatus=$null
        if ($sccache -and $configure) {
            $daemon=Get-RustCacheTierDaemon $Layout $state $sccache.Source
            $shouldRestart=$ForceRestart -or ($RestartIfChanged -and ($pending -or -not $daemon.present))
            if ($daemon.present -and -not $daemon.owned) { throw 'Dedicated sccache port is owned by an unrecognized process; no daemon was stopped or adopted.' }
            elseif ($shouldRestart) {
                if (@(Get-Process -Name cargo,rustc -ErrorAction SilentlyContinue).Count) { $pending=$true; $reason='cargo-or-rustc-active' }
                else {
                    if ($daemon.present) { & $sccache.Source --stop-server 2>$null | Out-Null; if($LASTEXITCODE -ne 0){throw 'Owned sccache daemon did not stop.'} }
                    & $sccache.Source --start-server | Out-Null
                    if ($LASTEXITCODE -ne 0) { throw 'Dedicated sccache daemon did not start.' }
                    $listeners=@(Get-NetTCPConnection -LocalPort ([int]$Layout.server_port) -State Listen -ErrorAction Stop)
                    $ids=@($listeners|Select-Object -ExpandProperty OwningProcess -Unique)
                    if($ids.Count -ne 1){throw 'Dedicated sccache daemon identity is ambiguous.'}
                    $process=Get-Process -Id $ids[0] -ErrorAction Stop
                    if([string]$process.Path -ine $sccache.Source -or @($listeners|Where-Object{$_.LocalAddress -notin @('127.0.0.1','::1')}).Count){throw 'Dedicated daemon executable or listener identity is invalid.'}
                    $daemon=[pscustomobject]@{present=$true;owned=$true;pid_value=$process.Id;started_ticks=$process.StartTime.ToUniversalTime().Ticks}
                    $pending=$false; $restarted=$true
                }
            }
            if($daemon.present -and $daemon.owned){
                $stats=@(& $sccache.Source --show-stats 2>&1)
                $location=$stats|Where-Object{$_ -match '^Cache location\s+'}|Select-Object -First 1
                $baseStatus=$stats|Where-Object{$_ -match '^Base directories\s+'}|Select-Object -First 1
            }
        }
        $loaded=if($restarted){$hash}elseif($state){[string]$state.loaded_config_sha256}else{$null}
        $next=[ordered]@{schema_version=2;config_sha256=$hash;loaded_config_sha256=$loaded;restart_pending=[bool]$pending
            base_directory_count=$baseDirs.Count;server_port=$Layout.server_port;executable_path=if($sccache){$sccache.Source}else{$null}
            server_pid=if($daemon -and $daemon.owned){$daemon.pid_value}elseif($state -and $state.PSObject.Properties.Name -contains 'server_pid'){$state.server_pid}else{$null}
            server_started_ticks=if($daemon -and $daemon.owned){[string]$daemon.started_ticks}elseif($state -and $state.PSObject.Properties.Name -contains 'server_started_ticks'){$state.server_started_ticks}else{$null}}
        Write-RustCacheSccacheAtomic $Layout.state_path ($next|ConvertTo-Json -Depth 5)
        return [pscustomobject]@{config_path=$Layout.config_path;cache_dir=$Layout.cache_dir;max_cache_size=$Layout.max_cache_size;base_directories=$baseDirs
            changed=$changed;restarted=$restarted;restart_pending=[bool]$pending;configuration_loaded=(-not $pending -and $loaded -eq $hash)
            config_sha256=$hash;loaded_config_sha256=$loaded;state_path=$Layout.state_path;location=$location;base_directory_status=$baseStatus
            tiered=$true;remote_configured=($null -ne $Layout.tier.remote);server_port=$Layout.server_port;reason=$reason}
    } finally { $lease.Dispose() }
}

Export-ModuleMember -Function ConvertTo-RustCacheSccacheConfigPath, Get-RustCacheSccacheConfigPath, Get-RustCacheSccacheWrapperPath, Get-RustCacheSccacheBaseDirectories, Get-RustCacheSccacheConfigContent, Enter-RustCacheSccacheConfigLock, Get-RustCacheTextSha256, Sync-RustCacheSccacheConfiguration, Get-RustCacheSccacheEnvironmentNames, Get-RustCacheSccacheTierLayout
