Import-Module "$PSScriptRoot\RustCache.Paths.psm1" -Force -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Policy.psm1" -Force -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Sccache.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.SccacheTiers.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Studio.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Portability.psm1" -Force -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.Launcher.psm1" -Force -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.CargoIncludeMigration.psm1" -DisableNameChecking
Import-Module "$PSScriptRoot\RustCache.ControlFiles.psm1" -DisableNameChecking

function ConvertTo-RustCacheTomlPath {
    param([Parameter(Mandatory)][string]$Path)
    [System.IO.Path]::GetFullPath($Path).Replace('\', '/')
}

function Get-RustCacheCargoIncludeContent {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [AllowNull()][string]$SccachePath
    )

    $quarantine = ConvertTo-RustCacheTomlPath (Join-Path $CacheRoot "quarantine\{workspace-path-hash}")
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Generated by the Elon Rust cache platform. Re-run rust-cache.ps1 install to refresh.")
    $lines.Add("[build]")
    $lines.Add("build-dir = `"$quarantine`"")
    if (-not [string]::IsNullOrWhiteSpace($SccachePath)) {
        $wrapper = ConvertTo-RustCacheTomlPath $SccachePath
        $lines.Add("rustc-wrapper = `"$wrapper`"")
    }
    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

function Set-RustCacheParentCargoConfig {
    param(
        [Parameter(Mandatory)][string]$CargoConfigPath,
        [Parameter(Mandatory)][string]$IncludeConfigPath,
        [switch]$Apply,
        [switch]$ResetSourceReplacement
    )

    $fullCargoConfig = [System.IO.Path]::GetFullPath($CargoConfigPath)
    $includeTomlPath = ConvertTo-RustCacheTomlPath $IncludeConfigPath
    $before = Read-RustCacheCargoControlSnapshot -Path $fullCargoConfig -AllowMissing
    $existing = if ($before.exists) { [regex]::Split($before.text,'\r?\n') } else { @() }
    $previousInclude = Get-RustCacheParentIncludePath -Lines $existing
    $migration = if ($previousInclude -and $previousInclude -ine [IO.Path]::GetFullPath($IncludeConfigPath)) {
        Get-RustCacheManagedIncludeMigration -CargoConfigPath $fullCargoConfig -PreviousIncludePath $previousInclude
    } else { $null }
    $result = New-Object System.Collections.Generic.List[string]
    $section = ""
    $removedSourceReplacements = New-Object System.Collections.Generic.List[string]
    foreach ($line in $existing) {
        if ($line -match '^\s*include\s*=') {
            continue
        }
        if ($line -match '^\s*\[([^]]+)\]\s*$') {
            $section = $Matches[1].Trim().ToLowerInvariant()
        }
        if ($null -eq $migration -and $section -eq "build" -and $line -match '^\s*(target-dir|rustflags)\s*=') {
            continue
        }
        if ($ResetSourceReplacement -and $section -eq 'source.crates-io' -and $line -match '^\s*replace-with\s*=\s*["'']([^"'']+)["'']') {
            $removedSourceReplacements.Add($Matches[1])
            continue
        }
        $result.Add($line)
    }
    while ($result.Count -gt 0 -and [string]::IsNullOrWhiteSpace($result[0])) {
        $result.RemoveAt(0)
    }
    $result.Insert(0, "")
    $result.Insert(0, "include = [`"$includeTomlPath`"]")
    $content = ($result -join [Environment]::NewLine).TrimEnd() + [Environment]::NewLine

    $backupPath = $null
    if ($Apply) {
        if ($null -ne $migration) { Assert-RustCacheIncludeMigrationCurrent $migration }
        $current = Read-RustCacheCargoControlSnapshot -Path $fullCargoConfig -AllowMissing
        if ($current.exists -ne $before.exists -or $current.sha256 -ne $before.sha256) { throw 'RUST_CACHE_CARGO_CONFIG_DRIFT: Cargo configuration changed during planning.' }
        $parent = Split-Path $fullCargoConfig -Parent
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
        if (Test-Path -LiteralPath $fullCargoConfig) {
            $stamp = [Guid]::NewGuid().ToString('N')
            $backupPath = "$fullCargoConfig.before-rust-cache-$stamp.bak"
            [IO.File]::WriteAllBytes($backupPath,$before.bytes)
        }
        $encoding=[Text.UTF8Encoding]::new($PSVersionTable.PSVersion.Major -lt 6)
        [byte[]]$bytes=@($encoding.GetPreamble()) + @($encoding.GetBytes($content))
        Write-RustCacheBoundControlFile -Path $fullCargoConfig -ExpectedSha256 $before.sha256 -ExpectedMissing:(-not $before.exists) -Bytes $bytes | Out-Null
    }
    [pscustomobject]@{
        cargo_config_path = $fullCargoConfig
        include_config_path = $includeTomlPath
        applied = [bool]$Apply
        backup_path = $backupPath
        include_migration = $migration
        removed_source_replacements = @($removedSourceReplacements)
        content = $content
    }
}

function Restart-RustCacheSccacheServer {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [Parameter(Mandatory)][string]$MaxCacheSize
    )

    $sccache = Get-Command sccache -ErrorAction SilentlyContinue
    if (-not $sccache) { return $null }
    $result = Sync-RustCacheSccacheConfiguration -CacheRoot $CacheRoot -ConfigureProcessEnvironment -ForceRestart
    if ($result.restart_pending) {
        return [pscustomobject]@{
            status = "deferred"
            reason = if ($result.PSObject.Properties.Name -contains 'reason') { $result.reason } else { "cargo-or-rustc-active" }
            path = $sccache.Source
            cache_dir = $result.cache_dir
            max_cache_size = $result.max_cache_size
            config_path = $result.config_path
            base_directories = $result.base_directories
            base_directory_status = $result.base_directory_status
            configuration_loaded = $false
            state_path = $result.state_path
            location = $result.location
            restarted = $false
            restart_pending = $true
        }
    }
    $normalizedLocation = if ($result.location) { ([string]$result.location).Replace("\\", "\") } else { "" }
    $multilevel = $result.PSObject.Properties.Name -contains 'remote_configured' -and $result.remote_configured
    $expectedLocation = if ($multilevel) { $normalizedLocation -match 'Multi-level \(2 levels\)' } else { $normalizedLocation -like "*$($result.cache_dir)*" }
    if (-not $result.configuration_loaded -or -not $expectedLocation) {
        throw "sccache server did not bind the managed cache directory. Reported: $($result.location)"
    }
    return [pscustomobject]@{
        status = "ready"
        reason = $null
        path = $sccache.Source
        cache_dir = $result.cache_dir
        max_cache_size = $result.max_cache_size
        config_path = $result.config_path
        base_directories = $result.base_directories
        base_directory_status = $result.base_directory_status
        configuration_loaded = $result.configuration_loaded
        state_path = $result.state_path
        location = $result.location
        restarted = $result.restarted
        restart_pending = $false
    }
}

function Install-RustCacheSccacheWrapper {
    param(
        [Parameter(Mandatory)][string]$SourceModulesRoot,
        [Parameter(Mandatory)][string]$CacheRoot,
        [Parameter(Mandatory)][string]$SccachePath,
        [Parameter(Mandatory)][string]$MaxCacheSize
    )

    $sourcePath = Join-Path $SourceModulesRoot "native\rustc_sccache_wrapper.rs"
    if (-not (Test-Path -LiteralPath $sourcePath)) {
        throw "Native sccache wrapper source is missing: $sourcePath"
    }
    $rustc = Get-Command rustc -ErrorAction SilentlyContinue
    if (-not $rustc) {
        throw "rustc is required to install the native sccache wrapper."
    }

    $wrapperPath = Get-RustCacheSccacheWrapperPath -CacheRoot $CacheRoot
    $temporaryPath = "$wrapperPath.$PID.tmp.exe"
    New-Item -ItemType Directory -Force -Path (Split-Path $wrapperPath -Parent) | Out-Null
    $layout = Get-RustCacheSccacheTierLayout -CacheRoot $CacheRoot -LegacyMaxSize $MaxCacheSize
    Initialize-RustCacheSccacheTierStorage $layout
    Assert-RustCacheSccacheCapabilities $layout $SccachePath
    $nativeBinding = Get-RustCacheSccacheBinding $layout
    $compileEnvironment = [ordered]@{
        ELON_RUST_CACHE_SCCACHE_PATH = [IO.Path]::GetFullPath($SccachePath)
        ELON_RUST_CACHE_SCCACHE_SIZE = $layout.max_cache_size
        ELON_RUST_CACHE_SCCACHE_CONF = $layout.config_path
        ELON_RUST_CACHE_SCCACHE_DIR = $layout.cache_dir
        ELON_RUST_CACHE_SCCACHE_PORT = $layout.server_port
        ELON_RUST_CACHE_SCCACHE_CACHED_CONF = $layout.cached_config_path
        ELON_RUST_CACHE_SCCACHE_WEBDAV_ENDPOINT = $nativeBinding.webdav_endpoint
        ELON_RUST_CACHE_SCCACHE_WEBDAV_KEY_PREFIX = $nativeBinding.webdav_key_prefix
    }
    $previousEnvironment = @{}
    foreach ($name in $compileEnvironment.Keys) { $previousEnvironment[$name] = [Environment]::GetEnvironmentVariable($name,'Process') }
    try {
        Set-RustCacheSccacheProcessEnvironment $compileEnvironment
        & $rustc.Source --edition 2021 --crate-name rustc_sccache_wrapper $sourcePath -C opt-level=s -C strip=symbols -o $temporaryPath
        if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $temporaryPath)) {
            throw "rustc failed to compile the native sccache wrapper: $sourcePath"
        }
        Move-Item -LiteralPath $temporaryPath -Destination $wrapperPath -Force
        if ($layout.tiered) {
            $binding = [ordered]@{ schema='elon.sccache_wrapper_binding.v1'; binding_sha256=(Get-RustCacheTierTextHash ((Get-RustCacheSccacheBinding $layout)|ConvertTo-Json -Compress)) }
            [IO.File]::WriteAllText($layout.binding_path,($binding|ConvertTo-Json),(New-Object Text.UTF8Encoding($false)))
        }
        $legacyCommandWrapper = Join-Path (Split-Path $wrapperPath -Parent) "rustc-sccache-wrapper.cmd"
        $activeBuilds = @(Get-Process -Name cargo, rustc -ErrorAction SilentlyContinue)
        if ($activeBuilds.Count -eq 0 -and (Test-Path -LiteralPath $legacyCommandWrapper)) {
            Remove-Item -LiteralPath $legacyCommandWrapper -Force
        }
    } finally {
        Set-RustCacheSccacheProcessEnvironment $previousEnvironment
        Remove-Item -LiteralPath $temporaryPath -Force -ErrorAction SilentlyContinue
    }
    return $wrapperPath
}

function Set-RustCacheUserEnvironment {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [Parameter(Mandatory)][string]$MaxCacheSize,
        [switch]$Apply
    )

    $layout = Get-RustCacheSccacheTierLayout -CacheRoot $CacheRoot -LegacyMaxSize $MaxCacheSize
    $values = [ordered]@{
        ELON_RUST_CACHE_ROOT = [System.IO.Path]::GetFullPath($CacheRoot)
        SCCACHE_DIR = $layout.cache_dir
        SCCACHE_CACHE_SIZE = $layout.max_cache_size
        SCCACHE_CONF = $layout.config_path
    }
    if ($layout.tiered) {
        $values.ELON_RUST_CACHE_CONTROL_ROOT = $layout.control_root
        $values.ELON_RUST_CACHE_SCCACHE_TIERS = $layout.tier.config_path
        $values.SCCACHE_SERVER_PORT = $layout.server_port
        $values.SCCACHE_CACHED_CONF = $layout.cached_config_path
    }
    if ($Apply -and $env:OS -eq "Windows_NT") {
        foreach ($name in $values.Keys) {
            [Environment]::SetEnvironmentVariable($name, $values[$name], "User")
            [Environment]::SetEnvironmentVariable($name, $values[$name], "Process")
        }
        [Environment]::SetEnvironmentVariable("ELON_DEV_CARGO_TARGET_DIR", $null, "User")
        Remove-Item Env:ELON_DEV_CARGO_TARGET_DIR -ErrorAction SilentlyContinue
    }
    [pscustomobject]@{ applied = [bool]$Apply; values = [pscustomobject]$values; cleared_legacy_target = [bool]$Apply }
}

function Enter-RustCachePlatformInstallLock {
    param(
        [Parameter(Mandatory)][string]$CacheRoot,
        [int]$TimeoutSeconds = 120
    )

    $stateRoot = Join-Path (Resolve-RustCacheManagementRoot -CacheRoot $CacheRoot) "state"
    New-Item -ItemType Directory -Force -Path $stateRoot | Out-Null
    $lockPath = Join-Path $stateRoot "platform-install.lock"
    $deadline = [DateTime]::UtcNow.AddSeconds([math]::Max(0, $TimeoutSeconds))
    while ($true) {
        try {
            $stream = [System.IO.File]::Open(
                $lockPath,
                [System.IO.FileMode]::OpenOrCreate,
                [System.IO.FileAccess]::ReadWrite,
                [System.IO.FileShare]::None
            )
            $owner = [ordered]@{
                schema = "elon.rust_cache.platform_install_lock.v1"
                pid = $PID
                acquired_at_utc = [DateTime]::UtcNow.ToString("o")
            } | ConvertTo-Json -Compress
            $bytes = [System.Text.Encoding]::UTF8.GetBytes($owner)
            $stream.SetLength(0)
            $stream.Write($bytes, 0, $bytes.Length)
            $stream.Flush($true)
            return $stream
        } catch [System.IO.IOException] {
            if ([DateTime]::UtcNow -ge $deadline) {
                throw "Timed out waiting for Rust cache platform install lock: $lockPath"
            }
            Start-Sleep -Milliseconds 100
        }
    }
}

function Exit-RustCachePlatformInstallLock {
    param([AllowNull()]$Lease)
    if ($null -ne $Lease) {
        $Lease.Dispose()
    }
}

function Install-RustCacheStudioDocuments {
    param([string]$SourceScriptsRoot, [string]$ManagementRoot)
    $entries = @()
    foreach ($relative in @('docs/studio-cache-ai-entry.md','docs/studio-cache-operations.md','docs/design/studio-build-cache-v1.md',
        'docs/rust-cache-platform.md','docs/rust-cache-on-demand-adoption.md','docs/rust-cache-network-storage.md','docs/rust-cache-fleet-operations.md')) {
        $source = Join-Path (Split-Path $SourceScriptsRoot -Parent) $relative
        if (-not (Test-Path -LiteralPath $source -PathType Leaf)) { $source = Join-Path $SourceScriptsRoot $relative }
        if (-not (Test-Path -LiteralPath $source -PathType Leaf)) { continue }
        $destination = Join-Path $ManagementRoot $relative
        New-Item -ItemType Directory -Path (Split-Path $destination -Parent) -Force | Out-Null
        if ([IO.Path]::GetFullPath($source) -ine [IO.Path]::GetFullPath($destination)) { [IO.File]::Copy($source,$destination,$true) }
        $entries += [pscustomobject]@{path=$relative;sha256=(Get-RustCacheFileSha256 -Path $destination)}
    }
    if (-not $entries.Count) { return $null }
    $manifestPath = Join-Path $ManagementRoot 'docs/studio-cache-docs-manifest.json'
    $manifest = [ordered]@{schema='elon.studio_cache.documents.v1';files=$entries}
    [IO.File]::WriteAllText($manifestPath,($manifest|ConvertTo-Json -Depth 5),(New-Object Text.UTF8Encoding($false)))
    return $manifestPath
}

function Install-RustCachePlatform {
    param(
        [Parameter(Mandatory)][string]$SourceScriptsRoot,
        [string]$CacheRoot,
        [string]$RepoRoot,
        [string]$CargoConfigPath,
        [string]$SourceSkillRoot,
        [string]$CodexSkillsRoot,
        [string]$UserLauncherPath,
        [int]$InstallLockTimeoutSeconds = 120,
        [switch]$ActivateCargoConfig,
        [switch]$InstallCodexSkill,
        [switch]$ConfigureSccacheServer,
        [switch]$ResetCargoSourcePolicy
    )

    $sourceRoot = [System.IO.Path]::GetFullPath($SourceScriptsRoot)
    $sourceEntry = Join-Path $sourceRoot "rust-cache.ps1"
    $sourceModules = Join-Path $sourceRoot "rust-cache"
    if (-not (Test-Path -LiteralPath $sourceEntry) -or -not (Test-Path -LiteralPath $sourceModules)) {
        throw "Rust cache source files are incomplete under $sourceRoot"
    }
    $sourceFingerprint = Get-RustCachePlatformFingerprint -SourceScriptsRoot $sourceRoot
    if ($ActivateCargoConfig) {
        $writers = @(Get-Process -Name cargo,rustc -ErrorAction SilentlyContinue)
        if ($writers.Count -gt 0) {
            $summary = ($writers | ForEach-Object { "$($_.ProcessName):$($_.Id)" }) -join ', '
            throw "Refusing Cargo config activation while Cargo/rustc writers are active: $summary"
        }
    }
    $root = Resolve-RustCacheRoot -ExplicitRoot $CacheRoot -RepoRoot $RepoRoot
    $installLease = Enter-RustCachePlatformInstallLock -CacheRoot $root -TimeoutSeconds $InstallLockTimeoutSeconds
    try {
        Initialize-RustCachePolicy -CacheRoot $root | Out-Null
        $managementRoot = Resolve-RustCacheManagementRoot -CacheRoot $root
        $platformRoot = Join-Path $managementRoot "platform"
        $targetModules = Join-Path $platformRoot "rust-cache"
        New-Item -ItemType Directory -Force -Path $targetModules | Out-Null
        Copy-Item -LiteralPath $sourceEntry -Destination (Join-Path $platformRoot "rust-cache.ps1") -Force
        Get-ChildItem -LiteralPath $sourceModules -File | ForEach-Object {
            Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $targetModules $_.Name) -Force
        }
        $userLauncher = Install-RustCacheUserLauncher -CacheRoot $root -UserLauncherPath $UserLauncherPath
        $documentationManifest = Install-RustCacheStudioDocuments -SourceScriptsRoot $sourceRoot -ManagementRoot $managementRoot

    $sccache = Get-Command sccache -ErrorAction SilentlyContinue
    $policy = Get-RustCachePolicy -CacheRoot $root
    $sccacheWrapperPath = $null
    if ($sccache) {
        $sccacheWrapperPath = Install-RustCacheSccacheWrapper -SourceModulesRoot $sourceModules -CacheRoot $root -SccachePath $sccache.Source -MaxCacheSize ([string]$policy.sccache_max_size)
    }
    $includePath = Join-Path $managementRoot "config\cargo-cache.toml"
    New-Item -ItemType Directory -Force -Path (Split-Path $includePath -Parent) | Out-Null
    $includeContent = Get-RustCacheCargoIncludeContent -CacheRoot $root -SccachePath $sccacheWrapperPath
    Set-Content -LiteralPath $includePath -Value $includeContent -Encoding UTF8 -NoNewline

    $sccacheConfig = Sync-RustCacheSccacheConfiguration -CacheRoot $root

    $sccacheServer = $null
    if ($ConfigureSccacheServer -and $sccache) {
        $sccacheServer = Restart-RustCacheSccacheServer -CacheRoot $root -MaxCacheSize ([string]$policy.sccache_max_size)
    }

    $userEnvironment = Set-RustCacheUserEnvironment -CacheRoot $root -MaxCacheSize ([string](Get-RustCachePolicy -CacheRoot $root).sccache_max_size) -Apply:$ActivateCargoConfig

    $activation = $null
    if ($ActivateCargoConfig) {
        if ([string]::IsNullOrWhiteSpace($CargoConfigPath)) {
            throw "-CargoConfigPath is required with -ActivateCargoConfig."
        }
        $activation = Set-RustCacheParentCargoConfig -CargoConfigPath $CargoConfigPath -IncludeConfigPath $includePath -Apply -ResetSourceReplacement:$ResetCargoSourcePolicy
    }
    $codexSkill = $null
    if ($InstallCodexSkill) {
        if ([string]::IsNullOrWhiteSpace($SourceSkillRoot)) {
            throw "-SourceSkillRoot is required with -InstallCodexSkill."
        }
        $codexSkill = Install-RustCacheCodexSkill -SourceSkillRoot $SourceSkillRoot -CodexSkillsRoot $CodexSkillsRoot
    }
    $installedFingerprint = Get-RustCachePlatformFingerprint -SourceScriptsRoot $platformRoot -Installed
    $platformManifestPath = Write-RustCachePlatformInstallManifest -CacheRoot $root -SourceFingerprint $sourceFingerprint -InstalledFingerprint $installedFingerprint
        [pscustomobject]@{
            cache_root = $root
            platform_root = $platformRoot
            entry_path = Join-Path $platformRoot "rust-cache.ps1"
            cargo_include_path = $includePath
            sccache_path = if ($sccache) { $sccache.Source } else { $null }
            sccache_wrapper_path = $sccacheWrapperPath
            sccache_config_path = $sccacheConfig.config_path
            sccache_server = $sccacheServer
            user_environment = $userEnvironment
            cargo_activation = $activation
            platform_manifest_path = $platformManifestPath
            documentation_manifest_path = $documentationManifest
            source_hash = $sourceFingerprint.hash
            installed_hash = $installedFingerprint.hash
            codex_skill = $codexSkill
            user_launcher = $userLauncher
        }
    } finally {
        Exit-RustCachePlatformInstallLock -Lease $installLease
    }
}

Export-ModuleMember -Function ConvertTo-RustCacheTomlPath, Get-RustCacheCargoIncludeContent, Install-RustCacheSccacheWrapper, Set-RustCacheParentCargoConfig, Restart-RustCacheSccacheServer, Set-RustCacheUserEnvironment, Enter-RustCachePlatformInstallLock, Exit-RustCachePlatformInstallLock, Install-RustCachePlatform
