use anyhow::Result;
use rusqlite::{named_params, Transaction};

use crate::compute_federation::external_pool_adapter_task_protocol_conformance::*;

use super::types::{
    TaskProtocolConformanceRevocationPrivateFields, TaskProtocolConformanceRunPrivateFields,
};

pub(super) fn insert_run(
    tx: &Transaction<'_>,
    receipt: &ExternalPoolAdapterTaskProtocolConformanceRunReceipt,
    private: &TaskProtocolConformanceRunPrivateFields<'_>,
) -> Result<()> {
    let r = &receipt.run;
    let release = &r.registry_release;
    let vulnerability = &r.vulnerability_reattestation;
    let sandbox = &r.sandbox_reattestation;
    let key = &r.sandbox_verifier_key;
    let compatibility = &r.runtime_compatibility;
    tx.execute(
        "INSERT INTO compute_external_pool_adapter_task_protocol_conformance_run_receipts(
          run_receipt_id,run_receipt_schema,run_receipt_digest,run_material_digest,
          run_receipt_json,canonicalization,digest_algorithm,registry_release_id,
          registry_release_digest,registry_release_material_digest,admission_id,admission_digest,
          package_receipt_id,package_receipt_digest,package_material_digest,source_receipt_id,
          source_receipt_digest,adapter_id,release_version,route_kind,implementation_digest,
          declared_implementation_sha256,entrypoint_path,entrypoint_sha256,entrypoint_size_bytes,
          installation_content_digest,capability_set_digest,
          vulnerability_reattestation_receipt_id,vulnerability_reattestation_receipt_digest,
          vulnerability_reattestation_material_digest,vulnerability_intelligence_snapshot_digest,
          vulnerability_intelligence_expires_at,sandbox_reattestation_receipt_id,
          sandbox_reattestation_receipt_digest,sandbox_reattestation_material_digest,
          sandbox_policy_id,sandbox_test_plan_digest,sandbox_observation_inventory_digest,
          sandbox_report_expires_at,sandbox_verifier_key_record_id,
          sandbox_verifier_key_record_digest,sandbox_verifier_key_id,sandbox_verifier_operator,
          sandbox_verifier_product,
          runtime_compatibility_verification_receipt_id,
          runtime_compatibility_verification_receipt_digest,
          runtime_compatibility_verification_material_digest,
          runtime_compatibility_run_observation_id,runtime_compatibility_run_observation_digest,
          runtime_compatibility_run_observation_material_digest,
          runtime_compatibility_runner_execution_id,runtime_compatibility_profile_id,
          runtime_compatibility_profile_revision,runtime_compatibility_profile_digest,
          runtime_compatibility_runner_policy_digest,runtime_compatibility_fixture_catalog_digest,
          supervisor_session_policy_digest,source_capsule_sha256,source_capsule_size_bytes,
          launch_image_sha256,launch_image_size_bytes,
          runtime_compatibility_public_fixture_delivery_root,runtime_compatibility_expires_at,
          task_protocol_profile_id,task_protocol_profile_revision,task_protocol_profile_digest,
          fixture_catalog_id,fixture_catalog_revision,fixture_catalog_digest,run_nonce_digest,
          public_fixture_delivery_root,session_root_digests_json,session_roots_digest,
          session_transcript_digest,delivery_inventory_digest,exchange_inventory_digest,
          task_observation_root,synthetic_fixture_lane_id,synthetic_fixture_lane_digest,
          synthetic_fixture_executor_id,synthetic_fixture_executor_digest,exchange_count,
          capability_count,duration_ms,cleanup_json,sequence,predecessor_run_receipt_id,
          predecessor_run_receipt_digest,run_started_at,run_completed_at,
          post_cleanup_checked_at,expires_at,recorded_at,evidence_scope,receipt_status,
          non_production_authority_status,effects_json,readiness_json,recorded_by_admin_user_id,
          idempotency_scope,idempotency_key,confirmation,runtime_custody_epoch_digest,
          process_hmac_seal,receipt_integrity_digest
        ) VALUES (
          :run_id,:schema,:run_digest,:material_digest,:json,:canonicalization,:algorithm,
          :release_id,:release_digest,:release_material,:admission_id,:admission_digest,
          :package_id,:package_digest,:package_material,:source_id,:source_digest,:adapter_id,
          :release_version,:route_kind,:implementation,:declared_implementation,:entrypoint_path,
          :entrypoint_sha,:entrypoint_size,:installation_content,:capability_set,
          :vulnerability_id,:vulnerability_digest,:vulnerability_material,
          :intelligence_snapshot,:intelligence_expires,:sandbox_id,:sandbox_digest,
          :sandbox_material,:sandbox_policy,:sandbox_test_plan,:sandbox_observations,
          :sandbox_expires,:key_record_id,:key_record_digest,:key_id,:key_operator,:key_product,
          :verification_id,
          :verification_digest,:verification_material,:observation_id,:observation_digest,
          :observation_material,:runner_execution_id,:runtime_profile_id,
          :runtime_profile_revision,:runtime_profile_digest,:runner_policy_digest,
          :runtime_fixture_catalog_digest,:session_policy_digest,:source_capsule_sha,
          :source_capsule_size,:launch_image_sha,:launch_image_size,
          :runtime_public_delivery_root,:runtime_expires,:task_profile_id,:task_profile_revision,
          :task_profile_digest,:fixture_catalog_id,:fixture_catalog_revision,
          :fixture_catalog_digest,:run_nonce_digest,:public_delivery_root,:session_roots_json,
          :session_roots_digest,:session_transcript_digest,:delivery_inventory_digest,
          :exchange_inventory_digest,:task_observation_root,:lane_id,:lane_digest,:executor_id,
          :executor_digest,:exchange_count,:capability_count,:duration_ms,:cleanup_json,:sequence,
          :predecessor_id,:predecessor_digest,:run_started_at,:run_completed_at,:checked_at,
          :expires_at,:recorded_at,:evidence_scope,:receipt_status,:authority_status,:effects_json,
          :readiness_json,:admin_id,:idempotency_scope,:idempotency_key,:confirmation,
          :custody_epoch_digest,:process_hmac_seal,:receipt_integrity_digest)",
        named_params! {
            ":run_id": receipt.run_receipt_id,
            ":schema": receipt.schema,
            ":run_digest": receipt.run_receipt_digest,
            ":material_digest": receipt.run_material_digest,
            ":json": canonical_task_protocol_conformance_run_receipt_json_and_digest(receipt)?.0,
            ":canonicalization": receipt.canonicalization,
            ":algorithm": receipt.digest_algorithm,
            ":release_id": release.registry_release_id,
            ":release_digest": release.registry_release_digest,
            ":release_material": release.registry_release_material_digest,
            ":admission_id": release.admission_id,
            ":admission_digest": release.admission_digest,
            ":package_id": release.package_receipt_id,
            ":package_digest": release.package_receipt_digest,
            ":package_material": release.package_material_digest,
            ":source_id": release.source_receipt_id,
            ":source_digest": release.source_receipt_digest,
            ":adapter_id": release.adapter_id,
            ":release_version": release.release_version,
            ":route_kind": release.route_kind,
            ":implementation": release.implementation_digest,
            ":declared_implementation": release.declared_implementation_sha256,
            ":entrypoint_path": release.entrypoint_path,
            ":entrypoint_sha": release.entrypoint_sha256,
            ":entrypoint_size": i64::try_from(release.entrypoint_size_bytes)?,
            ":installation_content": release.installation_content_digest,
            ":capability_set": release.capability_set_digest,
            ":vulnerability_id": vulnerability.reattestation_receipt_id,
            ":vulnerability_digest": vulnerability.reattestation_receipt_digest,
            ":vulnerability_material": vulnerability.reattestation_material_digest,
            ":intelligence_snapshot": vulnerability.intelligence_snapshot_digest,
            ":intelligence_expires": vulnerability.intelligence_expires_at,
            ":sandbox_id": sandbox.reattestation_receipt_id,
            ":sandbox_digest": sandbox.reattestation_receipt_digest,
            ":sandbox_material": sandbox.reattestation_material_digest,
            ":sandbox_policy": sandbox.sandbox_policy_id,
            ":sandbox_test_plan": sandbox.test_plan_digest,
            ":sandbox_observations": sandbox.observation_inventory_digest,
            ":sandbox_expires": sandbox.report_expires_at,
            ":key_record_id": key.key_record_id,
            ":key_record_digest": key.key_record_digest,
            ":key_id": key.key_id,
            ":key_operator": key.verifier_operator,
            ":key_product": key.verifier_product,
            ":verification_id": compatibility.verification_receipt_id,
            ":verification_digest": compatibility.verification_receipt_digest,
            ":verification_material": compatibility.verification_material_digest,
            ":observation_id": compatibility.run_observation_id,
            ":observation_digest": compatibility.run_observation_digest,
            ":observation_material": compatibility.run_observation_material_digest,
            ":runner_execution_id": compatibility.runner_execution_id,
            ":runtime_profile_id": compatibility.profile_id,
            ":runtime_profile_revision": i64::try_from(compatibility.profile_revision)?,
            ":runtime_profile_digest": compatibility.profile_digest,
            ":runner_policy_digest": compatibility.runner_policy_digest,
            ":runtime_fixture_catalog_digest": compatibility.fixture_catalog_digest,
            ":session_policy_digest": compatibility.supervisor_session_policy_digest,
            ":source_capsule_sha": compatibility.source_capsule_sha256,
            ":source_capsule_size": i64::try_from(compatibility.source_capsule_size_bytes)?,
            ":launch_image_sha": compatibility.launch_image_sha256,
            ":launch_image_size": i64::try_from(compatibility.launch_image_size_bytes)?,
            ":runtime_public_delivery_root": compatibility.public_fixture_delivery_root,
            ":runtime_expires": compatibility.expires_at,
            ":task_profile_id": r.task_protocol_profile_id,
            ":task_profile_revision": i64::try_from(r.task_protocol_profile_revision)?,
            ":task_profile_digest": r.task_protocol_profile_digest,
            ":fixture_catalog_id": r.fixture_catalog_id,
            ":fixture_catalog_revision": i64::try_from(r.fixture_catalog_revision)?,
            ":fixture_catalog_digest": r.fixture_catalog_digest,
            ":run_nonce_digest": r.run_nonce_digest,
            ":public_delivery_root": r.public_fixture_delivery_root,
            ":session_roots_json": canonical_json(&r.session_root_digests)?,
            ":session_roots_digest": r.session_roots_digest,
            ":session_transcript_digest": r.session_transcript_digest,
            ":delivery_inventory_digest": r.delivery_inventory_digest,
            ":exchange_inventory_digest": r.exchange_inventory_digest,
            ":task_observation_root": r.task_observation_root,
            ":lane_id": r.synthetic_subjects.fixture_lane.subject_id,
            ":lane_digest": r.synthetic_subjects.fixture_lane.subject_digest,
            ":executor_id": r.synthetic_subjects.fixture_executor.subject_id,
            ":executor_digest": r.synthetic_subjects.fixture_executor.subject_digest,
            ":exchange_count": i64::try_from(r.exchanges.len())?,
            ":capability_count": i64::try_from(r.capabilities.len())?,
            ":duration_ms": i64::try_from(r.duration_ms)?,
            ":cleanup_json": canonical_json(&r.cleanup)?,
            ":sequence": i64::try_from(r.sequence)?,
            ":predecessor_id": r.predecessor_run_receipt_id,
            ":predecessor_digest": r.predecessor_run_receipt_digest,
            ":run_started_at": r.run_started_at,
            ":run_completed_at": r.run_completed_at,
            ":checked_at": r.post_cleanup_checked_at,
            ":expires_at": r.expires_at,
            ":recorded_at": r.recorded_at,
            ":evidence_scope": r.evidence_scope,
            ":receipt_status": r.receipt_status,
            ":authority_status": r.non_production_authority_status,
            ":effects_json": canonical_json(&r.effects)?,
            ":readiness_json": canonical_json(&r.readiness)?,
            ":admin_id": private.recorded_by_admin_user_id,
            ":idempotency_scope": private.idempotency_scope,
            ":idempotency_key": private.idempotency_key,
            ":confirmation": private.confirmation,
            ":custody_epoch_digest": private.runtime_custody_epoch_digest,
            ":process_hmac_seal": private.process_hmac_seal,
            ":receipt_integrity_digest": private.receipt_integrity_digest,
        },
    )?;
    Ok(())
}

pub(super) fn insert_revocation(
    tx: &Transaction<'_>,
    receipt: &ExternalPoolAdapterTaskProtocolConformanceRevocationReceipt,
    private: &TaskProtocolConformanceRevocationPrivateFields<'_>,
) -> Result<()> {
    let r = &receipt.revocation;
    tx.execute(
        "INSERT INTO compute_external_pool_adapter_task_protocol_conformance_revocations(
          revocation_receipt_id,revocation_receipt_schema,revocation_receipt_digest,
          revocation_material_digest,revocation_receipt_json,canonicalization,digest_algorithm,
          run_receipt_id,run_receipt_digest,registry_release_id,registry_release_digest,reason,
          revoked_at,recorded_at,revocation_status,effects_json,readiness_json,
          revoked_by_admin_user_id,idempotency_scope,idempotency_key,confirmation
        ) VALUES (
          :id,:schema,:digest,:material,:json,:canonicalization,:algorithm,:run_id,:run_digest,
          :release_id,:release_digest,:reason,:revoked_at,:recorded_at,:status,:effects,
          :readiness,:admin_id,:scope,:key,:confirmation)",
        named_params! {
            ":id": receipt.revocation_receipt_id,
            ":schema": receipt.schema,
            ":digest": receipt.revocation_receipt_digest,
            ":material": receipt.revocation_material_digest,
            ":json": canonical_task_protocol_conformance_revocation_receipt_json_and_digest(receipt)?.0,
            ":canonicalization": receipt.canonicalization,
            ":algorithm": receipt.digest_algorithm,
            ":run_id": r.run_receipt_id,
            ":run_digest": r.run_receipt_digest,
            ":release_id": r.registry_release_id,
            ":release_digest": r.registry_release_digest,
            ":reason": r.reason,
            ":revoked_at": r.revoked_at,
            ":recorded_at": r.recorded_at,
            ":status": r.revocation_status,
            ":effects": canonical_json(&r.effects)?,
            ":readiness": canonical_json(&r.readiness)?,
            ":admin_id": private.revoked_by_admin_user_id,
            ":scope": private.idempotency_scope,
            ":key": private.idempotency_key,
            ":confirmation": private.confirmation,
        },
    )?;
    Ok(())
}

pub(super) fn canonical_json<T: serde::Serialize + ?Sized>(value: &T) -> Result<String> {
    Ok(
        crate::compute_plugin_sharing_directive::canonical_compute_plugin_ijson_and_sha256(
            value,
            TASK_PROTOCOL_CONFORMANCE_MAX_RECEIPT_JSON_BYTES,
        )?
        .0,
    )
}
