PRAGMA foreign_keys=ON;
CREATE TABLE compute_external_pool_adapter_registry_releases(
 registry_release_id TEXT PRIMARY KEY,registry_release_digest TEXT,registry_release_material_digest TEXT,credential_verifier_json TEXT,credential_verifier_digest TEXT);
CREATE VIEW compute_external_pool_adapter_registry_release_current AS SELECT registry_release_id,registry_release_digest,'release_current' current_status FROM compute_external_pool_adapter_registry_releases;
CREATE TABLE compute_external_pool_adapter_registry_provider_bindings(
 provider_binding_id TEXT PRIMARY KEY,provider_binding_digest TEXT,provider_binding_material_digest TEXT,registry_release_id TEXT,registry_release_digest TEXT,
 route_adapter_projection_id TEXT,installation_receipt_id TEXT,installation_receipt_digest TEXT,installation_content_digest TEXT,application_id TEXT,application_digest TEXT,
 adoption_receipt_id TEXT,adoption_receipt_digest TEXT,provider_id TEXT,provider_owner_account_id TEXT,provider_policy_revision INTEGER,provider_digest TEXT,
 adapter_id TEXT,release_version TEXT,adapter_config_revision INTEGER,adapter_config_digest TEXT,admission_id TEXT,admission_digest TEXT,
 credential_verification_receipt_id TEXT,credential_verification_receipt_digest TEXT,credential_locator_commitment TEXT);
CREATE TABLE compute_external_pool_adapter_credential_verification_receipts(
 credential_verification_receipt_id TEXT PRIMARY KEY,credential_verification_receipt_digest TEXT,application_id TEXT,application_digest TEXT,provider_id TEXT,
 provider_policy_revision INTEGER,provider_digest TEXT,
 adapter_id TEXT,adapter_release_version TEXT,adapter_config_revision INTEGER,adapter_config_digest TEXT,admission_id TEXT,admission_digest TEXT,
 credential_ref_scheme TEXT,credential_locator_commitment TEXT);
CREATE TABLE compute_external_pool_adapter_credential_verifier_keys(key_record_id TEXT PRIMARY KEY,key_record_digest TEXT,key_id TEXT,verifier_record_id TEXT,verifier_record_digest TEXT,verification_kind TEXT,verifier_id TEXT,verifier_revision INTEGER,verifier_digest TEXT);
CREATE VIEW compute_external_pool_adapter_credential_verifier_key_current AS SELECT key_record_id,key_record_digest,key_id,verifier_record_id,verifier_record_digest,verification_kind,verifier_id,verifier_revision,verifier_digest,'active' current_status FROM compute_external_pool_adapter_credential_verifier_keys;
CREATE TABLE compute_external_pool_adapter_installation_receipts(installation_receipt_id TEXT PRIMARY KEY);
CREATE TABLE compute_external_pool_adapter_installation_terminal_receipts(terminal_receipt_id TEXT PRIMARY KEY,installation_receipt_id TEXT,installation_receipt_digest TEXT);
CREATE TABLE compute_external_pool_adapter_adoption_receipts(adoption_receipt_id TEXT PRIMARY KEY);
CREATE TABLE compute_external_pool_adapter_adoption_terminal_receipts(terminal_receipt_id TEXT PRIMARY KEY,adoption_receipt_id TEXT,adoption_receipt_digest TEXT);
CREATE TABLE compute_external_pool_onboarding_applications(application_id TEXT PRIMARY KEY,application_digest TEXT,provider_id TEXT,target_provider_jcs TEXT);
CREATE TABLE compute_external_pool_adapter_release_admissions(admission_id TEXT PRIMARY KEY);
CREATE TABLE compute_providers(provider_id TEXT PRIMARY KEY,provider_kind TEXT,owner_account_id TEXT,settlement_account_id TEXT,status TEXT,current_policy_revision INTEGER,current_provider_digest TEXT);
CREATE TABLE compute_provider_versions(provider_id TEXT,policy_revision INTEGER,provider_digest TEXT,provider_json TEXT,PRIMARY KEY(provider_id,policy_revision));
