CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_atomic_activation_receipts (
  activation_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(activation_receipt_id)) BETWEEN 1 AND 240 AND activation_receipt_id=trim(activation_receipt_id)),
  activation_receipt_schema TEXT NOT NULL CHECK(activation_receipt_schema='compute_federation.external_pool_adapter_atomic_activation_receipt.v1'),
  activation_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(activation_receipt_digest)=64 AND activation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  activation_receipt_json TEXT NOT NULL CHECK(json_valid(activation_receipt_json) AND json_type(activation_receipt_json)='object' AND length(CAST(activation_receipt_json AS BLOB))<=2097152),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  provider_binding_id TEXT NOT NULL CHECK(length(trim(provider_binding_id)) BETWEEN 1 AND 240 AND provider_binding_id=trim(provider_binding_id)),
  provider_binding_digest TEXT NOT NULL CHECK(length(provider_binding_digest)=64 AND provider_binding_digest NOT GLOB '*[^0-9a-f]*'),
  activation_root_digest TEXT NOT NULL CHECK(length(activation_root_digest)=64 AND activation_root_digest NOT GLOB '*[^0-9a-f]*'),
  source_registering_provider_id TEXT NOT NULL CHECK(length(trim(source_registering_provider_id)) BETWEEN 1 AND 240 AND source_registering_provider_id=trim(source_registering_provider_id)),
  source_registering_provider_policy_revision INTEGER NOT NULL CHECK(typeof(source_registering_provider_policy_revision)='integer' AND source_registering_provider_policy_revision BETWEEN 1 AND 9007199254740991),
  source_registering_provider_json TEXT NOT NULL CHECK(json_valid(source_registering_provider_json) AND json_type(source_registering_provider_json)='object' AND length(CAST(source_registering_provider_json AS BLOB))<=1048576),
  source_registering_provider_digest TEXT NOT NULL CHECK(length(source_registering_provider_digest)=64 AND source_registering_provider_digest NOT GLOB '*[^0-9a-f]*'),
  target_active_provider_id TEXT NOT NULL CHECK(length(trim(target_active_provider_id)) BETWEEN 1 AND 240 AND target_active_provider_id=trim(target_active_provider_id)),
  target_active_provider_policy_revision INTEGER NOT NULL CHECK(typeof(target_active_provider_policy_revision)='integer' AND target_active_provider_policy_revision BETWEEN 1 AND 9007199254740991),
  target_active_provider_json TEXT NOT NULL CHECK(json_valid(target_active_provider_json) AND json_type(target_active_provider_json)='object' AND length(CAST(target_active_provider_json AS BLOB))<=1048576),
  target_active_provider_digest TEXT NOT NULL CHECK(length(target_active_provider_digest)=64 AND target_active_provider_digest NOT GLOB '*[^0-9a-f]*'),
  registering_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(registering_reattestation_receipt_id)) BETWEEN 1 AND 240 AND registering_reattestation_receipt_id=trim(registering_reattestation_receipt_id)),
  registering_reattestation_receipt_digest TEXT NOT NULL CHECK(length(registering_reattestation_receipt_digest)=64 AND registering_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  projected_transition_proof_material_json TEXT NOT NULL CHECK(json_valid(projected_transition_proof_material_json) AND json_type(projected_transition_proof_material_json)='object' AND length(CAST(projected_transition_proof_material_json AS BLOB))<=1048576),
  projected_transition_proof_digest TEXT NOT NULL UNIQUE CHECK(length(projected_transition_proof_digest)=64 AND projected_transition_proof_digest NOT GLOB '*[^0-9a-f]*'),
  executor_id TEXT NOT NULL UNIQUE CHECK(length(executor_id)=87 AND executor_id GLOB 'external_pool_executor_[0-9a-f]*' AND substr(executor_id,24) NOT GLOB '*[^0-9a-f]*'),
  executor_id_hash TEXT NOT NULL UNIQUE CHECK(length(executor_id_hash)=64 AND executor_id_hash NOT GLOB '*[^0-9a-f]*'),
  executor_id_material_json TEXT NOT NULL CHECK(json_valid(executor_id_material_json) AND json_type(executor_id_material_json)='object' AND length(CAST(executor_id_material_json AS BLOB))<=1048576),
  executor_binding_material_json TEXT NOT NULL CHECK(json_valid(executor_binding_material_json) AND json_type(executor_binding_material_json)='object' AND length(CAST(executor_binding_material_json AS BLOB))<=1048576),
  stable_executor_binding_digest TEXT NOT NULL UNIQUE CHECK(length(stable_executor_binding_digest)=64 AND stable_executor_binding_digest NOT GLOB '*[^0-9a-f]*'),
  projected_v211_adapter_binding_json TEXT NOT NULL CHECK(json_valid(projected_v211_adapter_binding_json) AND json_type(projected_v211_adapter_binding_json)='object' AND length(CAST(projected_v211_adapter_binding_json AS BLOB))<=1048576),
  projected_v211_adapter_binding_digest TEXT NOT NULL CHECK(length(projected_v211_adapter_binding_digest)=64 AND projected_v211_adapter_binding_digest NOT GLOB '*[^0-9a-f]*'),
  route_adapter_projection_id TEXT NOT NULL CHECK(length(trim(route_adapter_projection_id)) BETWEEN 1 AND 240 AND route_adapter_projection_id=trim(route_adapter_projection_id)),
  route_adapter_revision INTEGER NOT NULL CHECK(typeof(route_adapter_revision)='integer' AND route_adapter_revision BETWEEN 1 AND 9007199254740991),
  route_adapter_digest TEXT NOT NULL CHECK(length(route_adapter_digest)=64 AND route_adapter_digest NOT GLOB '*[^0-9a-f]*'),
  service_actor_id TEXT NOT NULL CHECK(length(trim(service_actor_id)) BETWEEN 1 AND 240 AND service_actor_id=trim(service_actor_id)),
  service_actor_authorization_id TEXT NOT NULL CHECK(length(trim(service_actor_authorization_id)) BETWEEN 1 AND 240 AND service_actor_authorization_id=trim(service_actor_authorization_id)),
  service_actor_authorization_digest TEXT NOT NULL CHECK(length(service_actor_authorization_digest)=64 AND service_actor_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  route_credential_id TEXT NOT NULL CHECK(length(trim(route_credential_id)) BETWEEN 1 AND 240 AND route_credential_id=trim(route_credential_id)),
  route_credential_revision INTEGER NOT NULL CHECK(typeof(route_credential_revision)='integer' AND route_credential_revision BETWEEN 1 AND 9007199254740991),
  route_credential_digest TEXT NOT NULL CHECK(length(route_credential_digest)=64 AND route_credential_digest NOT GLOB '*[^0-9a-f]*'),
  route_authorization_id TEXT NOT NULL UNIQUE CHECK(length(trim(route_authorization_id)) BETWEEN 1 AND 240 AND route_authorization_id=trim(route_authorization_id)),
  route_authorization_revision INTEGER NOT NULL CHECK(typeof(route_authorization_revision)='integer' AND route_authorization_revision BETWEEN 1 AND 9007199254740991),
  route_authorization_digest TEXT NOT NULL UNIQUE CHECK(length(route_authorization_digest)=64 AND route_authorization_digest NOT GLOB '*[^0-9a-f]*'),
  route_capabilities_json TEXT NOT NULL CHECK(json_valid(route_capabilities_json) AND json_type(route_capabilities_json)='array' AND json_array_length(route_capabilities_json)=6 AND length(CAST(route_capabilities_json AS BLOB))<=65536),
  route_capability_count INTEGER NOT NULL CHECK(route_capability_count=6),
  route_capability_set_digest TEXT NOT NULL CHECK(length(route_capability_set_digest)=64 AND route_capability_set_digest NOT GLOB '*[^0-9a-f]*'),
  route_capability_0_id TEXT NOT NULL CHECK(route_capability_0_id='authenticated_ack'),
  route_capability_0_revision INTEGER NOT NULL CHECK(route_capability_0_revision>0),
  route_capability_1_id TEXT NOT NULL CHECK(route_capability_1_id='authenticated_events'),
  route_capability_1_revision INTEGER NOT NULL CHECK(route_capability_1_revision>0),
  route_capability_2_id TEXT NOT NULL CHECK(route_capability_2_id='cancel_no_start'),
  route_capability_2_revision INTEGER NOT NULL CHECK(route_capability_2_revision>0),
  route_capability_3_id TEXT NOT NULL CHECK(route_capability_3_id='idempotent_commit'),
  route_capability_3_revision INTEGER NOT NULL CHECK(route_capability_3_revision>0),
  route_capability_4_id TEXT NOT NULL CHECK(route_capability_4_id='prepare'),
  route_capability_4_revision INTEGER NOT NULL CHECK(route_capability_4_revision>0),
  route_capability_5_id TEXT NOT NULL CHECK(route_capability_5_id='reconcile'),
  route_capability_5_revision INTEGER NOT NULL CHECK(route_capability_5_revision>0),
  route_seal_id TEXT NOT NULL UNIQUE CHECK(length(trim(route_seal_id)) BETWEEN 1 AND 240 AND route_seal_id=trim(route_seal_id)),
  route_seal_digest TEXT NOT NULL UNIQUE CHECK(length(route_seal_digest)=64 AND route_seal_digest NOT GLOB '*[^0-9a-f]*'),
  active_runtime_observation_id TEXT NOT NULL UNIQUE CHECK(length(trim(active_runtime_observation_id)) BETWEEN 1 AND 240 AND active_runtime_observation_id=trim(active_runtime_observation_id)),
  active_runtime_observation_digest TEXT NOT NULL UNIQUE CHECK(length(active_runtime_observation_digest)=64 AND active_runtime_observation_digest NOT GLOB '*[^0-9a-f]*'),
  observation_started_at TEXT NOT NULL CHECK(observation_started_at GLOB '????-??-??T??:??:??.?????????Z' AND length(observation_started_at)=30 AND julianday(observation_started_at) IS NOT NULL),
  observation_completed_at TEXT NOT NULL CHECK(observation_completed_at GLOB '????-??-??T??:??:??.?????????Z' AND length(observation_completed_at)=30 AND julianday(observation_completed_at) IS NOT NULL),
  observation_expires_at TEXT NOT NULL CHECK(observation_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(observation_expires_at)=30 AND julianday(observation_expires_at) IS NOT NULL),
  task_protocol_conformance_run_receipt_id TEXT NOT NULL CHECK(length(trim(task_protocol_conformance_run_receipt_id)) BETWEEN 1 AND 240 AND task_protocol_conformance_run_receipt_id=trim(task_protocol_conformance_run_receipt_id)),
  task_protocol_conformance_run_receipt_digest TEXT NOT NULL CHECK(length(task_protocol_conformance_run_receipt_digest)=64 AND task_protocol_conformance_run_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  task_protocol_conformance_expires_at TEXT NOT NULL CHECK(task_protocol_conformance_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(task_protocol_conformance_expires_at)=30 AND julianday(task_protocol_conformance_expires_at) IS NOT NULL),
  task_protocol_active_carrier_material_json TEXT NOT NULL CHECK(json_valid(task_protocol_active_carrier_material_json) AND json_type(task_protocol_active_carrier_material_json)='object' AND length(CAST(task_protocol_active_carrier_material_json AS BLOB))<=1048576),
  task_protocol_active_carrier_digest TEXT NOT NULL CHECK(length(task_protocol_active_carrier_digest)=64 AND task_protocol_active_carrier_digest NOT GLOB '*[^0-9a-f]*'),
  activated_by_actor_kind TEXT NOT NULL CHECK(activated_by_actor_kind='provider_owner'),
  activated_by_actor_user_id TEXT NOT NULL CHECK(length(trim(activated_by_actor_user_id)) BETWEEN 1 AND 240 AND activated_by_actor_user_id=trim(activated_by_actor_user_id)),
  idempotency_scope TEXT NOT NULL CHECK(idempotency_scope='external_pool_adapter_atomic_activation'),
  idempotency_key TEXT NOT NULL CHECK(idempotency_key=activation_root_digest),
  idempotency_material_json TEXT NOT NULL CHECK(json_valid(idempotency_material_json) AND json_type(idempotency_material_json)='object' AND length(CAST(idempotency_material_json AS BLOB))<=1048576),
  idempotency_digest TEXT NOT NULL UNIQUE CHECK(length(idempotency_digest)=64 AND idempotency_digest NOT GLOB '*[^0-9a-f]*'),
  confirmation TEXT NOT NULL CHECK(confirmation='I_CONFIRM_EXTERNAL_POOL_ADAPTER_ATOMIC_ACTIVATION'),
  confirmation_material_json TEXT NOT NULL CHECK(json_valid(confirmation_material_json) AND json_type(confirmation_material_json)='object' AND length(CAST(confirmation_material_json AS BLOB))<=1048576),
  confirmation_digest TEXT NOT NULL UNIQUE CHECK(length(confirmation_digest)=64 AND confirmation_digest NOT GLOB '*[^0-9a-f]*'),
  activation_target_updated_at TEXT NOT NULL CHECK(activation_target_updated_at GLOB '????-??-??T??:??:??.?????????Z' AND length(activation_target_updated_at)=30 AND julianday(activation_target_updated_at) IS NOT NULL),
  evidence_checked_at TEXT NOT NULL CHECK(evidence_checked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(evidence_checked_at)=30 AND julianday(evidence_checked_at) IS NOT NULL),
  created_at TEXT NOT NULL CHECK(created_at=evidence_checked_at),
  CHECK(source_registering_provider_id=target_active_provider_id),
  CHECK(target_active_provider_policy_revision=source_registering_provider_policy_revision+1),
  CHECK(json_extract(source_registering_provider_json,'$.status')='registering'),
  CHECK(json_extract(target_active_provider_json,'$.status')='active'),
  CHECK(json_extract(target_active_provider_json,'$.updated_at')=activation_target_updated_at),
  CHECK(json_extract(source_registering_provider_json,'$.updated_at')<=activation_target_updated_at),
  CHECK(activation_target_updated_at<=observation_started_at AND observation_started_at<=observation_completed_at AND observation_completed_at<=evidence_checked_at AND evidence_checked_at<observation_expires_at AND observation_expires_at<=task_protocol_conformance_expires_at),
  UNIQUE(provider_binding_id,activation_root_digest),
  UNIQUE(idempotency_scope,idempotency_key),
  UNIQUE(activation_receipt_id,activation_receipt_digest,activation_root_digest),
  FOREIGN KEY(provider_binding_id) REFERENCES compute_external_pool_adapter_registry_provider_bindings(provider_binding_id) ON DELETE RESTRICT,
  FOREIGN KEY(source_registering_provider_id,source_registering_provider_policy_revision) REFERENCES compute_provider_versions(provider_id,policy_revision) ON DELETE RESTRICT,
  FOREIGN KEY(target_active_provider_id,target_active_provider_policy_revision) REFERENCES compute_provider_versions(provider_id,policy_revision) ON DELETE RESTRICT,
  FOREIGN KEY(registering_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_credential_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_adapter_projection_id,route_adapter_revision) REFERENCES compute_route_adapter_versions(adapter_id,adapter_revision) ON DELETE RESTRICT,
  FOREIGN KEY(service_actor_authorization_id) REFERENCES compute_service_actor_authorizations(actor_authorization_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_credential_id,route_credential_revision) REFERENCES compute_route_credential_versions(credential_id,credential_revision) ON DELETE RESTRICT,
  FOREIGN KEY(route_authorization_id) REFERENCES compute_route_authorization_receipts(route_authorization_id) ON DELETE RESTRICT,
  FOREIGN KEY(route_seal_id) REFERENCES compute_route_authorization_seals(seal_id) ON DELETE RESTRICT,
  FOREIGN KEY(task_protocol_conformance_run_receipt_id) REFERENCES compute_external_pool_adapter_task_protocol_conformance_run_receipts(run_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(activated_by_actor_user_id) REFERENCES users(id) ON DELETE RESTRICT
);
