CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_sandbox_reattestation_challenges (
  challenge_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(challenge_id)) BETWEEN 1 AND 200),
  challenge_nonce_base64 TEXT NOT NULL CHECK(length(challenge_nonce_base64)=44 AND substr(challenge_nonce_base64,44)='=' AND substr(challenge_nonce_base64,1,43) NOT GLOB '*[^A-Za-z0-9+/]*'),
  challenge_nonce_digest TEXT NOT NULL UNIQUE CHECK(length(challenge_nonce_digest)=64 AND challenge_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  signature_message_base64 TEXT NOT NULL CHECK(length(signature_message_base64) BETWEEN 4 AND 1048576 AND length(signature_message_base64)%4=0 AND rtrim(signature_message_base64,'=') NOT GLOB '*[^A-Za-z0-9+/]*' AND length(signature_message_base64)-length(rtrim(signature_message_base64,'=')) BETWEEN 0 AND 2),
  signature_message_digest TEXT NOT NULL CHECK(length(signature_message_digest)=64 AND signature_message_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 200),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_material_digest TEXT NOT NULL CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(vulnerability_reattestation_receipt_id)) BETWEEN 1 AND 200),
  vulnerability_reattestation_receipt_digest TEXT NOT NULL CHECK(length(vulnerability_reattestation_receipt_digest)=64 AND vulnerability_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_reattestation_material_digest TEXT NOT NULL CHECK(length(vulnerability_reattestation_material_digest)=64 AND vulnerability_reattestation_material_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_key_record_id TEXT NOT NULL CHECK(length(trim(sandbox_verifier_key_record_id)) BETWEEN 1 AND 200),
  sandbox_verifier_key_record_digest TEXT NOT NULL CHECK(length(sandbox_verifier_key_record_digest)=64 AND sandbox_verifier_key_record_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_key_id TEXT NOT NULL CHECK(length(sandbox_verifier_key_id)=64 AND sandbox_verifier_key_id NOT GLOB '*[^0-9a-f]*'),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>0),
  predecessor_receipt_id TEXT CHECK(predecessor_receipt_id IS NULL OR length(trim(predecessor_receipt_id)) BETWEEN 1 AND 200),
  predecessor_receipt_digest TEXT CHECK(predecessor_receipt_digest IS NULL OR (length(predecessor_receipt_digest)=64 AND predecessor_receipt_digest NOT GLOB '*[^0-9a-f]*')),
  challenge_json TEXT NOT NULL CHECK(json_valid(challenge_json) AND json_type(challenge_json)='object' AND length(CAST(challenge_json AS BLOB))<=1048576),
  issued_at TEXT NOT NULL CHECK(issued_at GLOB '????-??-??T??:??:??.?????????Z' AND length(issued_at)=30 AND julianday(issued_at) IS NOT NULL),
  expires_at TEXT NOT NULL CHECK(expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(expires_at)=30 AND julianday(expires_at) IS NOT NULL),
  CHECK((predecessor_receipt_id IS NULL)=(predecessor_receipt_digest IS NULL)),
  CHECK(expires_at=(strftime('%Y-%m-%dT%H:%M:%S',issued_at,'+5 minutes')||substr(issued_at,20))),
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(vulnerability_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_vulnerability_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(sandbox_verifier_key_record_id,sandbox_verifier_key_record_digest,sandbox_verifier_key_id)
    REFERENCES compute_external_pool_adapter_sandbox_verifier_keys(key_record_id,key_record_digest,key_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_receipt_id) REFERENCES compute_external_pool_adapter_sandbox_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_sandbox_reattestation_receipts (
  reattestation_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(reattestation_receipt_id)) BETWEEN 1 AND 200),
  reattestation_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(reattestation_receipt_digest)=64 AND reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json) AND json_type(receipt_json)='object' AND length(CAST(receipt_json AS BLOB))<=1048576),
  reattestation_material_digest TEXT NOT NULL CHECK(length(reattestation_material_digest)=64 AND reattestation_material_digest NOT GLOB '*[^0-9a-f]*'),
  challenge_id TEXT NOT NULL UNIQUE CHECK(length(trim(challenge_id)) BETWEEN 1 AND 200),
  challenge_nonce_digest TEXT NOT NULL CHECK(length(challenge_nonce_digest)=64 AND challenge_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 200),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_material_digest TEXT NOT NULL CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  admission_id TEXT NOT NULL CHECK(length(trim(admission_id)) BETWEEN 1 AND 200),
  admission_digest TEXT NOT NULL CHECK(length(admission_digest)=64 AND admission_digest NOT GLOB '*[^0-9a-f]*'),
  package_receipt_id TEXT NOT NULL CHECK(length(trim(package_receipt_id)) BETWEEN 1 AND 200),
  package_receipt_digest TEXT NOT NULL CHECK(length(package_receipt_digest)=64 AND package_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  source_receipt_id TEXT NOT NULL CHECK(length(trim(source_receipt_id)) BETWEEN 1 AND 200),
  source_receipt_digest TEXT NOT NULL CHECK(length(source_receipt_digest)=64 AND source_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  adapter_id TEXT NOT NULL CHECK(length(trim(adapter_id)) BETWEEN 1 AND 200),
  release_version TEXT NOT NULL CHECK(length(trim(release_version)) BETWEEN 1 AND 200),
  route_kind TEXT NOT NULL CHECK(route_kind='server_adapter'),
  supported_provider_kinds_json TEXT NOT NULL CHECK(supported_provider_kinds_json='["external_pool"]'),
  implementation_digest TEXT NOT NULL CHECK(length(implementation_digest)=64 AND implementation_digest NOT GLOB '*[^0-9a-f]*'),
  declared_implementation_sha256 TEXT NOT NULL CHECK(length(declared_implementation_sha256)=64 AND declared_implementation_sha256 NOT GLOB '*[^0-9a-f]*'),
  supported_capabilities_json TEXT NOT NULL CHECK(json_valid(supported_capabilities_json) AND json_type(supported_capabilities_json)='array' AND json_array_length(supported_capabilities_json)=6 AND length(CAST(supported_capabilities_json AS BLOB))<=65536),
  capability_set_digest TEXT NOT NULL CHECK(length(capability_set_digest)=64 AND capability_set_digest NOT GLOB '*[^0-9a-f]*'),
  credential_verifier_json TEXT NOT NULL CHECK(json_valid(credential_verifier_json) AND json_type(credential_verifier_json)='object' AND length(CAST(credential_verifier_json AS BLOB))<=65536),
  credential_verifier_digest TEXT NOT NULL CHECK(length(credential_verifier_digest)=64 AND credential_verifier_digest NOT GLOB '*[^0-9a-f]*'),
  archive_sha256 TEXT NOT NULL CHECK(length(archive_sha256)=64 AND archive_sha256 NOT GLOB '*[^0-9a-f]*'),
  archive_size_bytes INTEGER NOT NULL CHECK(typeof(archive_size_bytes)='integer' AND archive_size_bytes BETWEEN 1 AND 33554432),
  manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'),
  entry_inventory_digest TEXT NOT NULL CHECK(length(entry_inventory_digest)=64 AND entry_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  entry_count INTEGER NOT NULL CHECK(typeof(entry_count)='integer' AND entry_count BETWEEN 1 AND 128),
  total_uncompressed_bytes INTEGER NOT NULL CHECK(typeof(total_uncompressed_bytes)='integer' AND total_uncompressed_bytes BETWEEN 1 AND 67108864),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(vulnerability_reattestation_receipt_id)) BETWEEN 1 AND 200),
  vulnerability_reattestation_receipt_digest TEXT NOT NULL CHECK(length(vulnerability_reattestation_receipt_digest)=64 AND vulnerability_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_reattestation_material_digest TEXT NOT NULL CHECK(length(vulnerability_reattestation_material_digest)=64 AND vulnerability_reattestation_material_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_reattestation_sequence INTEGER NOT NULL CHECK(typeof(vulnerability_reattestation_sequence)='integer' AND vulnerability_reattestation_sequence>0),
  vulnerability_reattestation_verified_at TEXT NOT NULL CHECK(vulnerability_reattestation_verified_at GLOB '????-??-??T??:??:??.?????????Z' AND length(vulnerability_reattestation_verified_at)=30 AND julianday(vulnerability_reattestation_verified_at) IS NOT NULL),
  vulnerability_intelligence_snapshot_digest TEXT NOT NULL CHECK(length(vulnerability_intelligence_snapshot_digest)=64 AND vulnerability_intelligence_snapshot_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_intelligence_expires_at TEXT NOT NULL CHECK(vulnerability_intelligence_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(vulnerability_intelligence_expires_at)=30 AND julianday(vulnerability_intelligence_expires_at) IS NOT NULL),
  security_receipt_id TEXT NOT NULL CHECK(length(trim(security_receipt_id)) BETWEEN 1 AND 200),
  security_receipt_digest TEXT NOT NULL CHECK(length(security_receipt_digest)=64 AND security_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  security_material_digest TEXT NOT NULL CHECK(length(security_material_digest)=64 AND security_material_digest NOT GLOB '*[^0-9a-f]*'),
  sbom_digest TEXT NOT NULL CHECK(length(sbom_digest)=64 AND sbom_digest NOT GLOB '*[^0-9a-f]*'),
  component_inventory_digest TEXT NOT NULL CHECK(length(component_inventory_digest)=64 AND component_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  component_count INTEGER NOT NULL CHECK(typeof(component_count)='integer' AND component_count BETWEEN 1 AND 128),
  dependency_inventory_digest TEXT NOT NULL CHECK(length(dependency_inventory_digest)=64 AND dependency_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_key_record_id TEXT NOT NULL CHECK(length(trim(sandbox_verifier_key_record_id)) BETWEEN 1 AND 200),
  sandbox_verifier_key_record_digest TEXT NOT NULL CHECK(length(sandbox_verifier_key_record_digest)=64 AND sandbox_verifier_key_record_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_key_id TEXT NOT NULL CHECK(length(sandbox_verifier_key_id)=64 AND sandbox_verifier_key_id NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_operator TEXT NOT NULL CHECK(length(trim(sandbox_verifier_operator)) BETWEEN 1 AND 160),
  sandbox_verifier_product TEXT NOT NULL CHECK(length(trim(sandbox_verifier_product)) BETWEEN 1 AND 160),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence>0),
  predecessor_receipt_id TEXT CHECK(predecessor_receipt_id IS NULL OR length(trim(predecessor_receipt_id)) BETWEEN 1 AND 200),
  predecessor_receipt_digest TEXT CHECK(predecessor_receipt_digest IS NULL OR (length(predecessor_receipt_digest)=64 AND predecessor_receipt_digest NOT GLOB '*[^0-9a-f]*')),
  verifier_report_id TEXT NOT NULL UNIQUE CHECK(length(trim(verifier_report_id)) BETWEEN 1 AND 200),
  sandbox_runtime_id TEXT NOT NULL CHECK(length(trim(sandbox_runtime_id)) BETWEEN 1 AND 200),
  runtime_image_digest TEXT NOT NULL CHECK(length(runtime_image_digest)=64 AND runtime_image_digest NOT GLOB '*[^0-9a-f]*'),
  isolation_profile_id TEXT NOT NULL CHECK(isolation_profile_id='offline_readonly_ephemeral_no_child_process_v1'),
  run_started_at TEXT NOT NULL CHECK(run_started_at GLOB '????-??-??T??:??:??.?????????Z' AND length(run_started_at)=30 AND julianday(run_started_at) IS NOT NULL),
  run_completed_at TEXT NOT NULL CHECK(run_completed_at GLOB '????-??-??T??:??:??.?????????Z' AND length(run_completed_at)=30 AND julianday(run_completed_at) IS NOT NULL),
  report_generated_at TEXT NOT NULL CHECK(report_generated_at GLOB '????-??-??T??:??:??.?????????Z' AND length(report_generated_at)=30 AND julianday(report_generated_at) IS NOT NULL),
  report_expires_at TEXT NOT NULL CHECK(report_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(report_expires_at)=30 AND julianday(report_expires_at) IS NOT NULL),
  external_network_attempt_count INTEGER NOT NULL CHECK(typeof(external_network_attempt_count)='integer' AND external_network_attempt_count=0),
  write_outside_ephemeral_count INTEGER NOT NULL CHECK(typeof(write_outside_ephemeral_count)='integer' AND write_outside_ephemeral_count=0),
  child_process_attempt_count INTEGER NOT NULL CHECK(typeof(child_process_attempt_count)='integer' AND child_process_attempt_count=0),
  peak_memory_bytes INTEGER NOT NULL CHECK(typeof(peak_memory_bytes)='integer' AND peak_memory_bytes BETWEEN 1 AND 536870912),
  cpu_time_ms INTEGER NOT NULL CHECK(typeof(cpu_time_ms)='integer' AND cpu_time_ms BETWEEN 1 AND 900000),
  test_plan_digest TEXT NOT NULL CHECK(length(test_plan_digest)=64 AND test_plan_digest NOT GLOB '*[^0-9a-f]*'),
  test_plan_json TEXT NOT NULL CHECK(json_valid(test_plan_json) AND json_type(test_plan_json)='array' AND json_array_length(test_plan_json)=6 AND length(CAST(test_plan_json AS BLOB))<=262144),
  observation_inventory_digest TEXT NOT NULL CHECK(length(observation_inventory_digest)=64 AND observation_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  observations_json TEXT NOT NULL CHECK(json_valid(observations_json) AND json_type(observations_json)='array' AND json_array_length(observations_json)=6 AND length(CAST(observations_json AS BLOB))<=262144),
  capability_count INTEGER NOT NULL CHECK(typeof(capability_count)='integer' AND capability_count=6),
  passed_capability_count INTEGER NOT NULL CHECK(typeof(passed_capability_count)='integer' AND passed_capability_count=6),
  policy_violation_count INTEGER NOT NULL CHECK(typeof(policy_violation_count)='integer' AND policy_violation_count=0),
  signature_message_digest TEXT NOT NULL CHECK(length(signature_message_digest)=64 AND signature_message_digest NOT GLOB '*[^0-9a-f]*'),
  signature_base64 TEXT NOT NULL CHECK(length(signature_base64) BETWEEN 4 AND 2048 AND length(signature_base64)%4=0 AND rtrim(signature_base64,'=') NOT GLOB '*[^A-Za-z0-9+/]*' AND length(signature_base64)-length(rtrim(signature_base64,'=')) BETWEEN 0 AND 2),
  signature_digest TEXT NOT NULL CHECK(length(signature_digest)=64 AND signature_digest NOT GLOB '*[^0-9a-f]*'),
  recorded_by_admin_user_id TEXT NOT NULL CHECK(length(trim(recorded_by_admin_user_id)) BETWEEN 1 AND 200),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_sandbox_reattestation'),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240),
  verified_at TEXT NOT NULL CHECK(verified_at GLOB '????-??-??T??:??:??.?????????Z' AND length(verified_at)=30 AND julianday(verified_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=verified_at),
  evidence_scope TEXT NOT NULL CHECK(evidence_scope='verifier_signature_over_exact_v249_registry_release_current_v250_vulnerability_reattestation_server_derived_test_plan_and_single_use_nonce'),
  sandbox_reattestation_effect TEXT NOT NULL CHECK(sandbox_reattestation_effect='signed_sandbox_reattestation_verified_current'),
  adapter_effect TEXT NOT NULL CHECK(adapter_effect='none'), provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'), route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'), settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  CHECK((predecessor_receipt_id IS NULL)=(predecessor_receipt_digest IS NULL)),
  UNIQUE(registry_release_id,sequence), UNIQUE(predecessor_receipt_id), UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(challenge_id) REFERENCES compute_external_pool_adapter_sandbox_reattestation_challenges(challenge_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(vulnerability_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_vulnerability_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(sandbox_verifier_key_record_id,sandbox_verifier_key_record_digest,sandbox_verifier_key_id)
    REFERENCES compute_external_pool_adapter_sandbox_verifier_keys(key_record_id,key_record_digest,key_id) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_receipt_id) REFERENCES compute_external_pool_adapter_sandbox_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_sandbox_reattestation_revocations (
  revocation_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(revocation_receipt_id)) BETWEEN 1 AND 200),
  revocation_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_receipt_digest)=64 AND revocation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  receipt_json TEXT NOT NULL CHECK(json_valid(receipt_json) AND json_type(receipt_json)='object' AND length(CAST(receipt_json AS BLOB))<=524288),
  revocation_material_digest TEXT NOT NULL CHECK(length(revocation_material_digest)=64 AND revocation_material_digest NOT GLOB '*[^0-9a-f]*'),
  reattestation_receipt_id TEXT NOT NULL UNIQUE CHECK(length(trim(reattestation_receipt_id)) BETWEEN 1 AND 200),
  reattestation_receipt_digest TEXT NOT NULL CHECK(length(reattestation_receipt_digest)=64 AND reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 200),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  revoked_by_admin_user_id TEXT NOT NULL CHECK(length(trim(revoked_by_admin_user_id)) BETWEEN 1 AND 200),
  reason TEXT NOT NULL CHECK(length(trim(reason)) BETWEEN 12 AND 500 AND reason=trim(reason)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_sandbox_reattestation_revocation'),
  idempotency_scope TEXT NOT NULL CHECK(length(trim(idempotency_scope)) BETWEEN 1 AND 240),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240),
  revoked_at TEXT NOT NULL CHECK(revoked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=revoked_at),
  revocation_effect TEXT NOT NULL CHECK(revocation_effect='sandbox_reattestation_revoked'),
  adapter_effect TEXT NOT NULL CHECK(adapter_effect='none'), provider_effect TEXT NOT NULL CHECK(provider_effect='none'),
  credential_effect TEXT NOT NULL CHECK(credential_effect='none'), route_effect TEXT NOT NULL CHECK(route_effect='none'),
  execution_effect TEXT NOT NULL CHECK(execution_effect='none'), settlement_effect TEXT NOT NULL CHECK(settlement_effect='none'),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(reattestation_receipt_id) REFERENCES compute_external_pool_adapter_sandbox_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_external_pool_adapter_sandbox_reattestation_release
  ON compute_external_pool_adapter_sandbox_reattestation_receipts(registry_release_id,sequence DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_external_pool_adapter_sandbox_reattestation_genesis
  ON compute_external_pool_adapter_sandbox_reattestation_receipts(registry_release_id) WHERE predecessor_receipt_id IS NULL;
