CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_task_protocol_conformance_revocations (
  revocation_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(revocation_receipt_id)) BETWEEN 1 AND 240 AND revocation_receipt_id=trim(revocation_receipt_id)),
  revocation_receipt_schema TEXT NOT NULL CHECK(revocation_receipt_schema='compute_federation.external_pool_adapter_task_protocol_conformance_revocation_receipt.v1'),
  revocation_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_receipt_digest)=64 AND revocation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_material_digest TEXT NOT NULL UNIQUE CHECK(length(revocation_material_digest)=64 AND revocation_material_digest NOT GLOB '*[^0-9a-f]*'),
  revocation_receipt_json TEXT NOT NULL CHECK(json_valid(revocation_receipt_json) AND json_type(revocation_receipt_json)='object' AND length(CAST(revocation_receipt_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  run_receipt_id TEXT NOT NULL UNIQUE CHECK(length(trim(run_receipt_id)) BETWEEN 1 AND 240 AND run_receipt_id=trim(run_receipt_id)),
  run_receipt_digest TEXT NOT NULL CHECK(length(run_receipt_digest)=64 AND run_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 240 AND registry_release_id=trim(registry_release_id)),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  reason TEXT NOT NULL CHECK(length(reason) BETWEEN 12 AND 500 AND reason=trim(reason)),
  revoked_at TEXT NOT NULL CHECK(revoked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(revoked_at)=30 AND julianday(revoked_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=revoked_at),
  revocation_status TEXT NOT NULL CHECK(revocation_status='task_protocol_conformance_revoked_historical_only'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  revoked_by_admin_user_id TEXT NOT NULL CHECK(length(trim(revoked_by_admin_user_id)) BETWEEN 1 AND 240 AND revoked_by_admin_user_id=trim(revoked_by_admin_user_id)),
  idempotency_scope TEXT NOT NULL CHECK(idempotency_scope=('v272:task-protocol-conformance:revoke:'||revoked_by_admin_user_id)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_task_protocol_conformance_revocation'),
  UNIQUE(idempotency_scope,idempotency_key),
  FOREIGN KEY(run_receipt_id,run_receipt_digest) REFERENCES compute_external_pool_adapter_task_protocol_conformance_run_receipts(run_receipt_id,run_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(revoked_by_admin_user_id) REFERENCES users(id) ON DELETE RESTRICT
);
