CREATE TABLE IF NOT EXISTS compute_external_pool_adapter_task_protocol_conformance_run_receipts (
  run_receipt_id TEXT PRIMARY KEY NOT NULL CHECK(length(trim(run_receipt_id)) BETWEEN 1 AND 240 AND run_receipt_id=trim(run_receipt_id)),
  run_receipt_schema TEXT NOT NULL CHECK(run_receipt_schema='compute_federation.external_pool_adapter_task_protocol_conformance_run_receipt.v1'),
  run_receipt_digest TEXT NOT NULL UNIQUE CHECK(length(run_receipt_digest)=64 AND run_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  run_material_digest TEXT NOT NULL UNIQUE CHECK(length(run_material_digest)=64 AND run_material_digest NOT GLOB '*[^0-9a-f]*'),
  run_receipt_json TEXT NOT NULL CHECK(json_valid(run_receipt_json) AND json_type(run_receipt_json)='object' AND length(CAST(run_receipt_json AS BLOB))<=__MAX_RECEIPT_JSON_BYTES_SQL__),
  canonicalization TEXT NOT NULL CHECK(canonicalization='rfc8785_jcs'),
  digest_algorithm TEXT NOT NULL CHECK(digest_algorithm='sha256'),
  registry_release_id TEXT NOT NULL CHECK(length(trim(registry_release_id)) BETWEEN 1 AND 240 AND registry_release_id=trim(registry_release_id)),
  registry_release_digest TEXT NOT NULL CHECK(length(registry_release_digest)=64 AND registry_release_digest NOT GLOB '*[^0-9a-f]*'),
  registry_release_material_digest TEXT NOT NULL CHECK(length(registry_release_material_digest)=64 AND registry_release_material_digest NOT GLOB '*[^0-9a-f]*'),
  admission_id TEXT NOT NULL CHECK(length(trim(admission_id)) BETWEEN 1 AND 240 AND admission_id=trim(admission_id)),
  admission_digest TEXT NOT NULL CHECK(length(admission_digest)=64 AND admission_digest NOT GLOB '*[^0-9a-f]*'),
  package_receipt_id TEXT NOT NULL CHECK(length(trim(package_receipt_id)) BETWEEN 1 AND 240 AND package_receipt_id=trim(package_receipt_id)),
  package_receipt_digest TEXT NOT NULL CHECK(length(package_receipt_digest)=64 AND package_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  package_material_digest TEXT NOT NULL CHECK(length(package_material_digest)=64 AND package_material_digest NOT GLOB '*[^0-9a-f]*'),
  source_receipt_id TEXT NOT NULL CHECK(length(trim(source_receipt_id)) BETWEEN 1 AND 240 AND source_receipt_id=trim(source_receipt_id)),
  source_receipt_digest TEXT NOT NULL CHECK(length(source_receipt_digest)=64 AND source_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  adapter_id TEXT NOT NULL CHECK(length(trim(adapter_id)) BETWEEN 1 AND 240 AND adapter_id=trim(adapter_id)),
  release_version TEXT NOT NULL CHECK(length(trim(release_version)) BETWEEN 1 AND 240 AND release_version=trim(release_version)),
  route_kind TEXT NOT NULL CHECK(route_kind='server_adapter'),
  implementation_digest TEXT NOT NULL CHECK(length(implementation_digest)=64 AND implementation_digest NOT GLOB '*[^0-9a-f]*'),
  declared_implementation_sha256 TEXT NOT NULL CHECK(length(declared_implementation_sha256)=64 AND declared_implementation_sha256 NOT GLOB '*[^0-9a-f]*'),
  entrypoint_path TEXT NOT NULL CHECK(length(entrypoint_path) BETWEEN 1 AND 500 AND entrypoint_path=trim(entrypoint_path)),
  entrypoint_sha256 TEXT NOT NULL CHECK(length(entrypoint_sha256)=64 AND entrypoint_sha256 NOT GLOB '*[^0-9a-f]*'),
  entrypoint_size_bytes INTEGER NOT NULL CHECK(typeof(entrypoint_size_bytes)='integer' AND entrypoint_size_bytes BETWEEN 1 AND 9007199254740991),
  installation_content_digest TEXT NOT NULL CHECK(length(installation_content_digest)=64 AND installation_content_digest NOT GLOB '*[^0-9a-f]*'),
  capability_set_digest TEXT NOT NULL CHECK(length(capability_set_digest)=64 AND capability_set_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(vulnerability_reattestation_receipt_id)) BETWEEN 1 AND 240 AND vulnerability_reattestation_receipt_id=trim(vulnerability_reattestation_receipt_id)),
  vulnerability_reattestation_receipt_digest TEXT NOT NULL CHECK(length(vulnerability_reattestation_receipt_digest)=64 AND vulnerability_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_reattestation_material_digest TEXT NOT NULL CHECK(length(vulnerability_reattestation_material_digest)=64 AND vulnerability_reattestation_material_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_intelligence_snapshot_digest TEXT NOT NULL CHECK(length(vulnerability_intelligence_snapshot_digest)=64 AND vulnerability_intelligence_snapshot_digest NOT GLOB '*[^0-9a-f]*'),
  vulnerability_intelligence_expires_at TEXT NOT NULL CHECK(vulnerability_intelligence_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(vulnerability_intelligence_expires_at)=30 AND julianday(vulnerability_intelligence_expires_at) IS NOT NULL),
  sandbox_reattestation_receipt_id TEXT NOT NULL CHECK(length(trim(sandbox_reattestation_receipt_id)) BETWEEN 1 AND 240 AND sandbox_reattestation_receipt_id=trim(sandbox_reattestation_receipt_id)),
  sandbox_reattestation_receipt_digest TEXT NOT NULL CHECK(length(sandbox_reattestation_receipt_digest)=64 AND sandbox_reattestation_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_reattestation_material_digest TEXT NOT NULL CHECK(length(sandbox_reattestation_material_digest)=64 AND sandbox_reattestation_material_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_policy_id TEXT NOT NULL CHECK(sandbox_policy_id='external_pool_adapter_six_capability_offline_sandbox_v1'),
  sandbox_test_plan_digest TEXT NOT NULL CHECK(length(sandbox_test_plan_digest)=64 AND sandbox_test_plan_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_observation_inventory_digest TEXT NOT NULL CHECK(length(sandbox_observation_inventory_digest)=64 AND sandbox_observation_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_report_expires_at TEXT NOT NULL CHECK(sandbox_report_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(sandbox_report_expires_at)=30 AND julianday(sandbox_report_expires_at) IS NOT NULL),
  sandbox_verifier_key_record_id TEXT NOT NULL CHECK(length(trim(sandbox_verifier_key_record_id)) BETWEEN 1 AND 240 AND sandbox_verifier_key_record_id=trim(sandbox_verifier_key_record_id)),
  sandbox_verifier_key_record_digest TEXT NOT NULL CHECK(length(sandbox_verifier_key_record_digest)=64 AND sandbox_verifier_key_record_digest NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_key_id TEXT NOT NULL CHECK(length(sandbox_verifier_key_id)=64 AND sandbox_verifier_key_id NOT GLOB '*[^0-9a-f]*'),
  sandbox_verifier_operator TEXT NOT NULL CHECK(length(trim(sandbox_verifier_operator)) BETWEEN 1 AND 240 AND sandbox_verifier_operator=trim(sandbox_verifier_operator)),
  sandbox_verifier_product TEXT NOT NULL CHECK(length(trim(sandbox_verifier_product)) BETWEEN 1 AND 240 AND sandbox_verifier_product=trim(sandbox_verifier_product)),
  runtime_compatibility_verification_receipt_id TEXT NOT NULL CHECK(length(trim(runtime_compatibility_verification_receipt_id)) BETWEEN 1 AND 240 AND runtime_compatibility_verification_receipt_id=trim(runtime_compatibility_verification_receipt_id)),
  runtime_compatibility_verification_receipt_digest TEXT NOT NULL CHECK(length(runtime_compatibility_verification_receipt_digest)=64 AND runtime_compatibility_verification_receipt_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_compatibility_verification_material_digest TEXT NOT NULL CHECK(length(runtime_compatibility_verification_material_digest)=64 AND runtime_compatibility_verification_material_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_compatibility_run_observation_id TEXT NOT NULL CHECK(length(trim(runtime_compatibility_run_observation_id)) BETWEEN 1 AND 240 AND runtime_compatibility_run_observation_id=trim(runtime_compatibility_run_observation_id)),
  runtime_compatibility_run_observation_digest TEXT NOT NULL CHECK(length(runtime_compatibility_run_observation_digest)=64 AND runtime_compatibility_run_observation_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_compatibility_run_observation_material_digest TEXT NOT NULL CHECK(length(runtime_compatibility_run_observation_material_digest)=64 AND runtime_compatibility_run_observation_material_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_compatibility_runner_execution_id TEXT NOT NULL CHECK(length(trim(runtime_compatibility_runner_execution_id)) BETWEEN 1 AND 240 AND runtime_compatibility_runner_execution_id=trim(runtime_compatibility_runner_execution_id)),
  runtime_compatibility_profile_id TEXT NOT NULL CHECK(runtime_compatibility_profile_id='external_pool_adapter_linux_runtime_compatibility_v2'),
  runtime_compatibility_profile_revision INTEGER NOT NULL CHECK(runtime_compatibility_profile_revision=2),
  runtime_compatibility_profile_digest TEXT NOT NULL CHECK(length(runtime_compatibility_profile_digest)=64 AND runtime_compatibility_profile_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_compatibility_runner_policy_digest TEXT NOT NULL CHECK(length(runtime_compatibility_runner_policy_digest)=64 AND runtime_compatibility_runner_policy_digest NOT GLOB '*[^0-9a-f]*'),
  runtime_compatibility_fixture_catalog_digest TEXT NOT NULL CHECK(length(runtime_compatibility_fixture_catalog_digest)=64 AND runtime_compatibility_fixture_catalog_digest NOT GLOB '*[^0-9a-f]*'),
  supervisor_session_policy_digest TEXT NOT NULL CHECK(supervisor_session_policy_digest=__SUPERVISOR_SESSION_POLICY_DIGEST_SQL__),
  source_capsule_sha256 TEXT NOT NULL CHECK(length(source_capsule_sha256)=64 AND source_capsule_sha256 NOT GLOB '*[^0-9a-f]*'),
  source_capsule_size_bytes INTEGER NOT NULL CHECK(typeof(source_capsule_size_bytes)='integer' AND source_capsule_size_bytes BETWEEN 1 AND 9007199254740991),
  launch_image_sha256 TEXT NOT NULL CHECK(length(launch_image_sha256)=64 AND launch_image_sha256 NOT GLOB '*[^0-9a-f]*'),
  launch_image_size_bytes INTEGER NOT NULL CHECK(typeof(launch_image_size_bytes)='integer' AND launch_image_size_bytes BETWEEN 1 AND 9007199254740991),
  runtime_compatibility_public_fixture_delivery_root TEXT NOT NULL CHECK(length(runtime_compatibility_public_fixture_delivery_root)=64 AND runtime_compatibility_public_fixture_delivery_root NOT GLOB '*[^0-9a-f]*'),
  runtime_compatibility_expires_at TEXT NOT NULL CHECK(runtime_compatibility_expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(runtime_compatibility_expires_at)=30 AND julianday(runtime_compatibility_expires_at) IS NOT NULL),
  task_protocol_profile_id TEXT NOT NULL CHECK(task_protocol_profile_id='external_pool_adapter_task_protocol_conformance_profile_v1'),
  task_protocol_profile_revision INTEGER NOT NULL CHECK(task_protocol_profile_revision=1),
  task_protocol_profile_digest TEXT NOT NULL CHECK(task_protocol_profile_digest=__TASK_PROTOCOL_PROFILE_DIGEST_SQL__),
  fixture_catalog_id TEXT NOT NULL CHECK(fixture_catalog_id='external_pool_adapter_task_protocol_conformance_fixture_catalog_v1'),
  fixture_catalog_revision INTEGER NOT NULL CHECK(fixture_catalog_revision=1),
  fixture_catalog_digest TEXT NOT NULL CHECK(fixture_catalog_digest=__FIXTURE_CATALOG_DIGEST_SQL__),
  run_nonce_digest TEXT NOT NULL UNIQUE CHECK(length(run_nonce_digest)=64 AND run_nonce_digest NOT GLOB '*[^0-9a-f]*'),
  public_fixture_delivery_root TEXT NOT NULL UNIQUE CHECK(length(public_fixture_delivery_root)=64 AND public_fixture_delivery_root NOT GLOB '*[^0-9a-f]*'),
  session_root_digests_json TEXT NOT NULL CHECK(json_valid(session_root_digests_json) AND json_type(session_root_digests_json)='array' AND json_array_length(session_root_digests_json)=14 AND length(CAST(session_root_digests_json AS BLOB))<=4096),
  session_roots_digest TEXT NOT NULL UNIQUE CHECK(length(session_roots_digest)=64 AND session_roots_digest NOT GLOB '*[^0-9a-f]*'),
  session_transcript_digest TEXT NOT NULL UNIQUE CHECK(length(session_transcript_digest)=64 AND session_transcript_digest NOT GLOB '*[^0-9a-f]*'),
  delivery_inventory_digest TEXT NOT NULL UNIQUE CHECK(length(delivery_inventory_digest)=64 AND delivery_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  exchange_inventory_digest TEXT NOT NULL UNIQUE CHECK(length(exchange_inventory_digest)=64 AND exchange_inventory_digest NOT GLOB '*[^0-9a-f]*'),
  task_observation_root TEXT NOT NULL UNIQUE CHECK(length(task_observation_root)=64 AND task_observation_root NOT GLOB '*[^0-9a-f]*'),
  synthetic_fixture_lane_id TEXT NOT NULL CHECK(synthetic_fixture_lane_id='external_pool_adapter_task_protocol_conformance_fixture_lane_v1'),
  synthetic_fixture_lane_digest TEXT NOT NULL CHECK(length(synthetic_fixture_lane_digest)=64 AND synthetic_fixture_lane_digest NOT GLOB '*[^0-9a-f]*'),
  synthetic_fixture_executor_id TEXT NOT NULL CHECK(synthetic_fixture_executor_id='external_pool_adapter_task_protocol_conformance_fixture_executor_v1'),
  synthetic_fixture_executor_digest TEXT NOT NULL CHECK(length(synthetic_fixture_executor_digest)=64 AND synthetic_fixture_executor_digest NOT GLOB '*[^0-9a-f]*'),
  exchange_count INTEGER NOT NULL CHECK(exchange_count=8),
  capability_count INTEGER NOT NULL CHECK(capability_count=6),
  duration_ms INTEGER NOT NULL CHECK(typeof(duration_ms)='integer' AND duration_ms BETWEEN 0 AND 9007199254740991),
  cleanup_json TEXT NOT NULL CHECK(cleanup_json='{"authenticated_shutdown_completed":true,"cgroup_cleaned":true,"pidfd_reaped":true,"scratch_cleaned":true}'),
  sequence INTEGER NOT NULL CHECK(typeof(sequence)='integer' AND sequence BETWEEN 1 AND 9007199254740991),
  predecessor_run_receipt_id TEXT CHECK(predecessor_run_receipt_id IS NULL OR (length(trim(predecessor_run_receipt_id)) BETWEEN 1 AND 240 AND predecessor_run_receipt_id=trim(predecessor_run_receipt_id))),
  predecessor_run_receipt_digest TEXT CHECK(predecessor_run_receipt_digest IS NULL OR (length(predecessor_run_receipt_digest)=64 AND predecessor_run_receipt_digest NOT GLOB '*[^0-9a-f]*')),
  run_started_at TEXT NOT NULL CHECK(run_started_at GLOB '????-??-??T??:??:??.?????????Z' AND length(run_started_at)=30 AND julianday(run_started_at) IS NOT NULL),
  run_completed_at TEXT NOT NULL CHECK(run_completed_at GLOB '????-??-??T??:??:??.?????????Z' AND length(run_completed_at)=30 AND julianday(run_completed_at) IS NOT NULL),
  post_cleanup_checked_at TEXT NOT NULL CHECK(post_cleanup_checked_at GLOB '????-??-??T??:??:??.?????????Z' AND length(post_cleanup_checked_at)=30 AND julianday(post_cleanup_checked_at) IS NOT NULL),
  expires_at TEXT NOT NULL CHECK(expires_at GLOB '????-??-??T??:??:??.?????????Z' AND length(expires_at)=30 AND julianday(expires_at) IS NOT NULL),
  recorded_at TEXT NOT NULL CHECK(recorded_at=post_cleanup_checked_at),
  evidence_scope TEXT NOT NULL CHECK(evidence_scope='v272_server_owned_stateful_eight_exchange_six_capability_task_protocol_conformance_v1'),
  receipt_status TEXT NOT NULL CHECK(receipt_status='server_run_completed_no_production_authority'),
  non_production_authority_status TEXT NOT NULL CHECK(non_production_authority_status='non_production_no_v213_authority'),
  effects_json TEXT NOT NULL CHECK(effects_json='{"activation_effect":"none","adapter_effect":"none","credential_effect":"none","execution_effect":"none","market_effect":"none","provider_effect":"none","route_effect":"none","settlement_effect":"none","usage_effect":"none"}'),
  readiness_json TEXT NOT NULL CHECK(readiness_json='{"activation_ready":false,"broker_connect_ready":false,"execution_ready":false,"ipc_session_ready":false,"process_spawn_ready":false,"route_ready":false,"runtime_launch_ready":false,"secret_delivery_ready":false,"upstream_probe_ready":false}'),
  recorded_by_admin_user_id TEXT NOT NULL CHECK(length(trim(recorded_by_admin_user_id)) BETWEEN 1 AND 240 AND recorded_by_admin_user_id=trim(recorded_by_admin_user_id)),
  idempotency_scope TEXT NOT NULL CHECK(idempotency_scope=('v272:task-protocol-conformance:create:'||recorded_by_admin_user_id)),
  idempotency_key TEXT NOT NULL CHECK(length(trim(idempotency_key)) BETWEEN 1 AND 240 AND idempotency_key=trim(idempotency_key)),
  confirmation TEXT NOT NULL CHECK(confirmation='confirm_external_pool_adapter_task_protocol_conformance_run'),
  runtime_custody_epoch_digest TEXT NOT NULL CHECK(length(runtime_custody_epoch_digest)=64 AND runtime_custody_epoch_digest NOT GLOB '*[^0-9a-f]*'),
  process_hmac_seal TEXT NOT NULL UNIQUE CHECK(length(process_hmac_seal)=64 AND process_hmac_seal NOT GLOB '*[^0-9a-f]*'),
  receipt_integrity_digest TEXT NOT NULL UNIQUE CHECK(length(receipt_integrity_digest)=64 AND receipt_integrity_digest NOT GLOB '*[^0-9a-f]*'),
  CHECK(implementation_digest=declared_implementation_sha256),
  CHECK(source_capsule_sha256<>launch_image_sha256),
  CHECK((predecessor_run_receipt_id IS NULL)=(predecessor_run_receipt_digest IS NULL)),
  CHECK((sequence=1)=(predecessor_run_receipt_id IS NULL)),
  CHECK(run_started_at<=run_completed_at AND run_completed_at<=post_cleanup_checked_at AND post_cleanup_checked_at<expires_at),
  CHECK(runtime_custody_epoch_digest<>process_hmac_seal AND runtime_custody_epoch_digest<>receipt_integrity_digest AND process_hmac_seal<>receipt_integrity_digest),
  UNIQUE(registry_release_id,sequence),
  UNIQUE(predecessor_run_receipt_id),
  UNIQUE(idempotency_scope,idempotency_key),
  UNIQUE(run_receipt_id,run_receipt_digest),
  FOREIGN KEY(registry_release_id) REFERENCES compute_external_pool_adapter_registry_releases(registry_release_id) ON DELETE RESTRICT,
  FOREIGN KEY(vulnerability_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_vulnerability_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(sandbox_reattestation_receipt_id) REFERENCES compute_external_pool_adapter_sandbox_reattestation_receipts(reattestation_receipt_id) ON DELETE RESTRICT,
  FOREIGN KEY(sandbox_verifier_key_record_id,sandbox_verifier_key_record_digest,sandbox_verifier_key_id) REFERENCES compute_external_pool_adapter_sandbox_verifier_keys(key_record_id,key_record_digest,key_id) ON DELETE RESTRICT,
  FOREIGN KEY(runtime_compatibility_verification_receipt_id,runtime_compatibility_verification_receipt_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_receipts(verification_receipt_id,verification_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(runtime_compatibility_run_observation_id,runtime_compatibility_run_observation_digest) REFERENCES compute_external_pool_adapter_runtime_compatibility_verification_run_observations(run_observation_id,run_observation_digest) ON DELETE RESTRICT,
  FOREIGN KEY(predecessor_run_receipt_id,predecessor_run_receipt_digest) REFERENCES compute_external_pool_adapter_task_protocol_conformance_run_receipts(run_receipt_id,run_receipt_digest) ON DELETE RESTRICT,
  FOREIGN KEY(recorded_by_admin_user_id) REFERENCES users(id) ON DELETE RESTRICT
);
