//! Transitive source commitment for the exact stored-poison Lock quarantine runner.

macro_rules! source {
    ($name:literal, $path:literal) => {
        (
            $name,
            include_str!(concat!(env!("CARGO_MANIFEST_DIR"), $path)),
        )
    };
}

pub(super) const LOCK_STORED_POISON_SOURCE_SCOPE_V1: &[(&str, &str)] = &[
    source!("dynamic_quotient/runner_admission/lock_program.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/source_program.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/source_program.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison/catalog.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison/catalog.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison/source_scope.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison/source_scope.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison/stored_poison_retention_succeeded_members.v1.tsv", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison/stored_poison_retention_succeeded_members.v1.tsv"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison/stored_poison_retention_route_unknown_members.v1.tsv", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison/stored_poison_retention_route_unknown_members.v1.tsv"),
    source!("dynamic_quotient/lock_stored_poison_source_scope.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/lock_stored_poison_source_scope.rs"),
    source!("managed_vfs/a2_dynamic_evidence.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence.rs"),
    source!("managed_vfs/a2_dynamic_evidence/child.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/child.rs"),
    source!("managed_vfs/a2_dynamic_evidence/child/payload.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/child/payload.rs"),
    source!("managed_vfs/a2_dynamic_evidence/child/lock_stored_poison.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/child/lock_stored_poison.rs"),
    source!("managed_vfs/a2_dynamic_evidence/child/lock_stored_poison/route_unknown.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/child/lock_stored_poison/route_unknown.rs"),
    source!("managed_vfs/a2_dynamic_evidence/capture.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/capture.rs"),
    source!("managed_vfs/a2_dynamic_evidence/environment.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/environment.rs"),
    source!("managed_vfs/a2_dynamic_evidence/cleanup.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/cleanup.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_dispatch.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_dispatch.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_model.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_model.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_route_unknown.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_route_unknown.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_route_unknown/payload.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_route_unknown/payload.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison/fixture.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison/fixture.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison/payload.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison/payload.rs"),
    source!("managed_vfs.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs.rs"),
    source!("managed_vfs/connection.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/connection.rs"),
    source!("managed_vfs/callbacks.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/callbacks.rs"),
    source!("managed_vfs/route_file.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/route_file.rs"),
    source!("managed_vfs/live_registration.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/live_registration.rs"),
    source!("managed_vfs/shared_namespace.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/shared_namespace.rs"),
    source!("registry/file_custody/operations.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody/operations.rs"),
    source!("node_agent_managed_fs/sqlite_namespace.rs", "/src/node_agent_managed_fs/sqlite_namespace.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/coordinator.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/coordinator.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/locking.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/locking.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/failure_custody.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/failure_custody.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_faults.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_faults.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_faults/api.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_faults/api.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_faults/stored_poison.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_faults/stored_poison.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_snapshot.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_snapshot.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_lock_runtime.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_lock_runtime.rs"),
    source!("managed_vfs/connection/unmap.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/connection/unmap.rs"),
    source!("managed_vfs/fault_script.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/fault_script.rs"),
    source!("managed_vfs/fault_script/file.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/fault_script/file.rs"),
    source!("managed_vfs/shm_fault_script.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/shm_fault_script.rs"),
    source!("managed_vfs/multi_connection.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/multi_connection.rs"),
    source!("registry/test_vfs_bridge/file.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/test_vfs_bridge/file.rs"),
    source!("registry/file_custody/abi.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody/abi.rs"),
    source!("sqlite_vfs_abi.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_abi.rs"),
    source!("sqlite_vfs_abi/boundary.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_abi/boundary.rs"),
    source!("sqlite_vfs_abi/io_shm.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_abi/io_shm.rs"),
    source!("sqlite_vfs_abi/result_codes.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_abi/result_codes.rs"),
    source!("sqlite_vfs_abi/file_state.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_abi/file_state.rs"),
    source!("sqlite_vfs_abi/raw_state.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_abi/raw_state.rs"),
    source!("sqlite_vfs_abi/types.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_abi/types.rs"),
    source!("node_agent_managed_fs.rs", "/src/node_agent_managed_fs.rs"),
    source!("node_agent_managed_fs/windows.rs", "/src/node_agent_managed_fs/windows.rs"),
    source!("node_agent_managed_fs/windows_sqlite_locking.rs", "/src/node_agent_managed_fs/windows_sqlite_locking.rs"),
    source!("node_agent_managed_fs/windows_sqlite_shm.rs", "/src/node_agent_managed_fs/windows_sqlite_shm.rs"),
    source!("node_agent_managed_fs/sqlite_api.rs", "/src/node_agent_managed_fs/sqlite_api.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_io.rs", "/src/node_agent_managed_fs/sqlite_namespace_io.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/types.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/types.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/node_initialization.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/node_initialization.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/mapping.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/mapping.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_faults/controller.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_faults/controller.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_faults/operation.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_faults/operation.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_faults/mapping.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_faults/mapping.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_map_runtime.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_map_runtime.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_map_runtime/mapping_sequence.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_map_runtime/mapping_sequence.rs"),
    source!("managed_vfs/connection/registry_lifecycle.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/connection/registry_lifecycle.rs"),
    source!("managed_vfs/shared_namespace/registration_shutdown.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/shared_namespace/registration_shutdown.rs"),
    source!("managed_vfs/shared_namespace/registry_lifecycle.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/shared_namespace/registry_lifecycle.rs"),
    source!("managed_vfs/lifecycle_faults.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults.rs"),
    source!("managed_vfs/lifecycle_faults/native_gate.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults/native_gate.rs"),
    source!("managed_vfs/lifecycle_faults/registry_lifecycle.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults/registry_lifecycle.rs"),
    source!("managed_vfs/lifecycle_faults/registry_lifecycle/binding.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults/registry_lifecycle/binding.rs"),
    source!("managed_vfs/lifecycle_faults/unmap.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults/unmap.rs"),
    source!("managed_vfs/lifecycle_faults/unsafe_shm_preemption.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults/unsafe_shm_preemption.rs"),
    source!("managed_vfs/lifecycle_faults/joint_close.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults/joint_close.rs"),
    source!("managed_vfs/lifecycle_faults/registration_shutdown.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults/registration_shutdown.rs"),
    source!("managed_vfs/registration_shutdown_custody.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/registration_shutdown_custody.rs"),
    source!("registry.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry.rs"),
    source!("registry/test_vfs_bridge.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/test_vfs_bridge.rs"),
    source!("registry/file_custody.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody.rs"),
    source!("registry/file_custody/joint_close_runtime.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody/joint_close_runtime.rs"),
    source!("registry/file_custody/lifecycle_events.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody/lifecycle_events.rs"),
    source!("registry/file_custody/promotion.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody/promotion.rs"),
    source!("registry/file_custody/registry_lifecycle.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody/registry_lifecycle.rs"),
    source!("registry/file_custody/test_faults.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody/test_faults.rs"),
    source!("registry/file_custody/operations/unmap.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/file_custody/operations/unmap.rs"),
    source!("registry/owner.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/owner.rs"),
    source!("registry/owner/lifecycle.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/owner/lifecycle.rs"),
    source!("registry/owner/vfs.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/owner/vfs.rs"),
    source!("registry/process_owner.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/process_owner.rs"),
    source!("registry/process_owner/joint_close_direct_xclose.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/process_owner/joint_close_direct_xclose.rs"),
    source!("registry/process_owner/joint_close_fault.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/process_owner/joint_close_fault.rs"),
    source!("registry/process_owner/lifecycle.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/process_owner/lifecycle.rs"),
    source!("registry/process_owner/vfs.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/process_owner/vfs.rs"),
    source!("registry/state.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/state.rs"),
    source!("registry/state/owner.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/state/owner.rs"),
    source!("registry/state/test_lifecycle.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/state/test_lifecycle.rs"),
    source!("registry/state/test_snapshot.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/state/test_snapshot.rs"),
    source!("registry/types.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/registry/types.rs"),
    source!("node_agent_managed_fs/windows_sqlite.rs", "/src/node_agent_managed_fs/windows_sqlite.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_close.rs", "/src/node_agent_managed_fs/sqlite_namespace_close.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_close/main_close.rs", "/src/node_agent_managed_fs/sqlite_namespace_close/main_close.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_close/main_close_test_native.rs", "/src/node_agent_managed_fs/sqlite_namespace_close/main_close_test_native.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_close/test_faults.rs", "/src/node_agent_managed_fs/sqlite_namespace_close/test_faults.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_main.rs", "/src/node_agent_managed_fs/sqlite_namespace_main.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_types.rs", "/src/node_agent_managed_fs/sqlite_namespace_types.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_validation.rs", "/src/node_agent_managed_fs/sqlite_namespace_validation.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_lock_domain.rs", "/src/node_agent_managed_fs/sqlite_namespace_lock_domain.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_locking.rs", "/src/node_agent_managed_fs/sqlite_namespace_locking.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_locking/test_native.rs", "/src/node_agent_managed_fs/sqlite_namespace_locking/test_native.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/barrier.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/barrier.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/close.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/close.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/unmap.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/unmap.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/teardown.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/teardown.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime/authority.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime/authority.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime/detach.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime/detach.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime/native.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime/native.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime/prestate.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_unmap_runtime/prestate.rs"),
];

/// Only source identities that are not already present in the projector's canonical base or its
/// shared Map runtime scopes. The complete list above remains private to the per-program
/// implementation digest; chaining it globally would duplicate existing source identities.
pub(super) const STORED_POISON_PROJECTOR_DELTA_V1: &[(&str, &str)] = &[
    source!("dynamic_quotient/lock_stored_poison_source_scope.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/lock_stored_poison_source_scope.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison/catalog.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison/catalog.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison/source_scope.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison/source_scope.rs"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison/stored_poison_retention_succeeded_members.v1.tsv", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison/stored_poison_retention_succeeded_members.v1.tsv"),
    source!("dynamic_quotient/runner_admission/lock_program/stored_poison/stored_poison_retention_route_unknown_members.v1.tsv", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2b1_cases/denominator/static_contract/dynamic_quotient/runner_admission/lock_program/stored_poison/stored_poison_retention_route_unknown_members.v1.tsv"),
    source!("managed_vfs/a2_dynamic_evidence/child/lock_stored_poison.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/child/lock_stored_poison.rs"),
    source!("managed_vfs/a2_dynamic_evidence/child/lock_stored_poison/route_unknown.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/child/lock_stored_poison/route_unknown.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_dispatch.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_dispatch.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_model.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_model.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_route_unknown.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_route_unknown.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_route_unknown/payload.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison_route_unknown/payload.rs"),
    source!("managed_vfs/lifecycle_faults/unsafe_shm_preemption.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/lifecycle_faults/unsafe_shm_preemption.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison/fixture.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison/fixture.rs"),
    source!("managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison/payload.rs", "/src/node_agent_compute_plugin_host/local_authority/sqlite_vfs_policy/abi/connection_fixture/managed_vfs/a2_dynamic_evidence/lock_runner/stored_poison/payload.rs"),
    source!("node_agent_managed_fs/sqlite_namespace_shm/test_faults/stored_poison.rs", "/src/node_agent_managed_fs/sqlite_namespace_shm/test_faults/stored_poison.rs"),
];
