use super::super::model::*;

const fn node(
    id: SourceNodeId,
    owner: SourceOwnerId,
    symbol: &'static str,
    role: NodeRole,
    ops: &'static [PathOp],
    epoch: Epoch,
    boundary: Boundary,
) -> SourceNode {
    SourceNode {
        id,
        owner,
        symbol,
        role,
        ops,
        epoch,
        boundary,
        state_witness: None,
    }
}

pub(in super::super) const NODES: &[SourceNode] = &[
    node(
        SourceNodeId::AbiRawRun,
        SourceOwnerId::AbiFileState,
        "unsafe fn run_code",
        NodeRole::RawStateGate,
        ALL_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiRawGate,
        SourceOwnerId::AbiRawState,
        "unsafe fn with_installed_state",
        NodeRole::RawStateGate,
        ALL_OPS,
        Epoch::AbiInput,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::AbiRawAbandon,
        SourceOwnerId::AbiFileState,
        "unsafe fn abandon_without_unwind",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::AbiRawStateAbandon,
        SourceOwnerId::AbiRawState,
        "unsafe fn abandon_installed_state",
        NodeRole::RawStateGate,
        ALL_OPS,
        Epoch::AbiInput,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::FixtureFaultController,
        SourceOwnerId::FixtureFaultController,
        "fn begin_operation",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::AbiInput,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryCallbackBegin,
        SourceOwnerId::RegistryOperations,
        "fn with_shm",
        NodeRole::CallbackOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryProcessBegin,
        SourceOwnerId::RegistryProcessOwner,
        "fn begin_callback",
        NodeRole::CallbackOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryOwnerBegin,
        SourceOwnerId::RegistryOwner,
        "fn begin_callback",
        NodeRole::CallbackOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryStateBegin,
        SourceOwnerId::RegistryState,
        "fn begin_callback",
        NodeRole::CallbackOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryShmCustodyGate,
        SourceOwnerId::RegistryOperations,
        "fn with_shm",
        NodeRole::CustodyAdapter,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryUnsafeRetention,
        SourceOwnerId::RegistryOperations,
        "fn quarantine_unsafe_shm_failure",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryRetainTerminal,
        SourceOwnerId::RegistryProcessLifecycle,
        "fn retain_terminal_custody",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryQuarantineApplyRoute,
        SourceOwnerId::RegistryProcessOwner,
        "fn apply_route<T>",
        NodeRole::CustodyAdapter,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryOwnerQuarantine,
        SourceOwnerId::RegistryOwner,
        "fn quarantine",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryStateQuarantine,
        SourceOwnerId::RegistryState,
        "pub(super) fn quarantine",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryCallbackComplete,
        SourceOwnerId::RegistryOperations,
        "callback.complete()",
        NodeRole::CallbackOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryProcessComplete,
        SourceOwnerId::RegistryProcessOwner,
        "fn complete",
        NodeRole::CallbackOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryOwnerFinish,
        SourceOwnerId::RegistryOwner,
        "fn finish_callback",
        NodeRole::CallbackOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryStateFinish,
        SourceOwnerId::RegistryState,
        "fn finish_callback",
        NodeRole::CallbackOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryCallbackUnwind,
        SourceOwnerId::RegistryProcessOwner,
        "fn drop",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::RegistryPinnedDrop,
        SourceOwnerId::RegistryFileCustody,
        "impl<Custody, NonceSource> Drop",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedEnsureNode,
        SourceOwnerId::ManagedInitialization,
        "fn ensure_node",
        NodeRole::Initialization,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedOpenNode,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        NodeRole::Initialization,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedOpenShm,
        SourceOwnerId::ManagedShmRoot,
        "fn open_shm_for_wal",
        NodeRole::Initialization,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedOpenExact,
        SourceOwnerId::ManagedNamespace,
        "fn open_exact",
        NodeRole::PlatformSeam,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedConsumeOpenFailure,
        SourceOwnerId::ManagedFailureCustody,
        "fn consume_open_failure",
        NodeRole::CleanupOwner,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedRetainFailureHandleCustody,
        SourceOwnerId::ManagedFailureCustody,
        "fn retain_handle_custody",
        NodeRole::CleanupOwner,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedOpenCleanup,
        SourceOwnerId::ManagedInitialization,
        "fn close_failed_open_file",
        NodeRole::CleanupOwner,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedPinnedClose,
        SourceOwnerId::ManagedNamespaceClose,
        "fn close",
        NodeRole::CleanupOwner,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedDmsInitialization,
        SourceOwnerId::ManagedInitialization,
        "fn open_node",
        NodeRole::Initialization,
        INITIALIZING_OPS,
        Epoch::ColdNodeAcquirePrefix,
        Boundary::PendingExpansion,
    ),
    node(
        SourceNodeId::ManagedFaultBegin,
        SourceOwnerId::ManagedFaultOperation,
        "fn begin_test_fault",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultObserve,
        SourceOwnerId::ManagedFaultApi,
        "fn observe_test_fault",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultControllerObserve,
        SourceOwnerId::ManagedFaultController,
        "pub(super) fn observe",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultTriggerBefore,
        SourceOwnerId::ManagedFaultApi,
        "fn trigger_before_test_fault",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultActivateBefore,
        SourceOwnerId::ManagedFaultController,
        "fn activate_before",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultFinish,
        SourceOwnerId::ManagedFaultOperation,
        "fn finish_test_fault",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultActivateAfter,
        SourceOwnerId::ManagedFaultController,
        "fn activate_after",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultTriggerAfter,
        SourceOwnerId::ManagedFaultApi,
        "fn trigger_after_test_fault",
        NodeRole::FaultController,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::ManagedFaultTerminalize,
        SourceOwnerId::ManagedFaultOperation,
        "fn terminalize_test_fault",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
    node(
        SourceNodeId::WindowsByteLock,
        SourceOwnerId::WindowsLocking,
        "fn try_lock_sqlite_byte_range",
        NodeRole::PlatformSeam,
        INITIALIZING_OPS,
        Epoch::PlatformBinding,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::WindowsByteUnlock,
        SourceOwnerId::WindowsLocking,
        "fn unlock_sqlite_byte_range",
        NodeRole::PlatformSeam,
        ALL_OPS,
        Epoch::PlatformBinding,
        Boundary::TypedOutcomeSeam,
    ),
    node(
        SourceNodeId::ManagedPoison,
        SourceOwnerId::ManagedCoordinator,
        "fn mark_poisoned",
        NodeRole::CleanupOwner,
        ALL_OPS,
        Epoch::WalMainSteady,
        Boundary::Expanded,
    ),
];
